name_translation_key: books.text
description_translation_key: books.description.text
icon_image: |
  book.svg
category: personal
last_updated: '2025-11-12'
settings_and_memories:
  - id: |
      favorite_books
    stage: planning
  - id: |
      currently_reading
    stage: planning
skills:
  - id: translate
    name_translation_key: books.translate.text
    description_translation_key: books.translate.description.text
    stage: planning
    class_path: |
      skills.translate.TranslateSkill
focuses:
  - id: book_recommendations
    name_translation_key: books.book_recommendations.text
    description_translation_key: books.book_recommendations.description.text
    stage: planning
  - id: book_discussion
    name_translation_key: books.book_discussion.text
    description_translation_key: books.book_discussion.description.text
    stage: planning
    process:
      - ""
    systemprompt: |
      You are a books expert.
