// frontend/packages/ui/src/legal/trainingPolicies.generated.ts
//
// AUTO-GENERATED from /shared/docs/provider_training_policies.yml by
// frontend/packages/ui/scripts/generate-training-policies.js
// DO NOT EDIT BY HAND — run `npm run generate-training-policies` instead.

export interface ProviderTrainingPolicy {
  readonly id: string;
  readonly status: "no_training" | "no_training_opt_out" | "limited_use";
  readonly provider_group: "ai_models" | "image_generation";
  readonly policy_url: string;
  readonly terms_url: string | null;
  readonly source_document: string;
  readonly quote: string;
  readonly mechanism: string;
  readonly notes: string | null;
  readonly opted_out_date: string | null;
  readonly last_verified: string;
}

export const TRAINING_POLICIES_VERSION: number = 1;
export const TRAINING_POLICIES_LAST_AUDIT: string = "2026-04-16";

export const PROVIDER_TRAINING_POLICIES: readonly ProviderTrainingPolicy[] = [
  {"id":"aws_bedrock","status":"no_training","provider_group":"ai_models","policy_url":"https://aws.amazon.com/bedrock/faqs/","terms_url":"https://aws.amazon.com/service-terms/","source_document":"AWS Bedrock FAQ + AWS Service Terms §50.12","quote":"Your content is not used to improve the base models and is not shared with any model providers. Users' inputs and model outputs are not shared with any model providers.","mechanism":"Unconditional — applies to all customers by default","notes":null,"opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"anthropic_direct","status":"no_training","provider_group":"ai_models","policy_url":"https://www.anthropic.com/legal/commercial-terms","terms_url":null,"source_document":"Anthropic Commercial Terms of Service, Section B","quote":"Anthropic may not train models on Customer Content from Services.","mechanism":"Contractual prohibition for API customers","notes":"This applies to the API (Commercial Terms). Consumer Claude.ai users are under separate terms where training is opt-out. We use the API.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"openai","status":"no_training","provider_group":"ai_models","policy_url":"https://openai.com/enterprise-privacy/","terms_url":null,"source_document":"OpenAI Enterprise Privacy page","quote":"We do not train our models on your data by default.","mechanism":"Opt-in only — training requires explicit consent","notes":"Zero Data Retention (ZDR) is also available for eligible endpoints but requires a qualifying use case arranged with OpenAI.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"mistral","status":"no_training","provider_group":"ai_models","policy_url":"https://legal.mistral.ai/terms/privacy-policy","terms_url":null,"source_document":"Mistral AI Privacy Policy","quote":"We do not use your Input and Output to train our artificial intelligence models when you use Le Chat Enterprise or the paid version of our APIs.","mechanism":"No training for paid API customers by default","notes":"Free/consumer tier does train by default (opt-out available). We use the paid API tier.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"google_gemini","status":"no_training","provider_group":"ai_models","policy_url":"https://ai.google.dev/gemini-api/terms","terms_url":null,"source_document":"Gemini API Additional Terms of Service (effective 2026-03-23)","quote":"When you use Paid Services, including, for example, the paid quota of the Gemini API, Google doesn't use your prompts (including associated system instructions, cached content, and files such as images, videos, or documents) or responses to improve our products.","mechanism":"No training on paid tier; billing account = paid status","notes":"Free tier DOES train by default — no opt-out except upgrading to paid. EEA/Switzerland/UK users get paid-tier protections even on free tier. We use the paid tier (Cloud Billing account attached).","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"google_vertex_maas","status":"no_training","provider_group":"ai_models","policy_url":"https://cloud.google.com/terms/service-terms","terms_url":null,"source_document":"Google Cloud Service Specific Terms, §18 — Training Restriction","quote":"Google will not use Customer Data to train or fine-tune any AI/ML models without Customer's prior permission or instruction.","mechanism":"Contractual prohibition for Google-managed models","notes":"Third-party models accessed via Vertex AI Model Garden (\"Separate Offerings\") are governed by the third-party provider's own terms, not this clause. For our use case (e.g., DeepSeek via Vertex), the model provider's terms apply — verify separately if we add new MaaS models.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"together_ai","status":"no_training","provider_group":"ai_models","policy_url":"https://www.together.ai/privacy","terms_url":null,"source_document":"Together AI Privacy Policy §1/2.2 (updated 2025-12-17)","quote":"We do not use any data collected from you to train our models without your explicit opt-in and consent. You may revoke that consent at any time and request deletion of information we have collected.","mechanism":"Opt-in only — no training by default","notes":"Zero Data Retention (ZDR) mode is also available via Settings > Privacy & Security.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"groq","status":"no_training","provider_group":"ai_models","policy_url":"https://console.groq.com/docs/legal/services-agreement","terms_url":null,"source_document":"Groq Services Agreement §4.2 (effective 2025-10-15)","quote":"Groq is not permitted to use Inputs or Outputs for training or fine-tuning any AI Model Services or other models, unless explicitly granted permission or instructed by Customer.","mechanism":"Opt-in only — training prohibited unless customer grants permission","notes":"The public groq.com/privacy-policy does NOT cover API customers — the Services Agreement governs. ZDR setting available at console.groq.com/settings/data-controls.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"cerebras","status":"no_training","provider_group":"ai_models","policy_url":"https://www.cerebras.ai/terms-of-service","terms_url":null,"source_document":"Cerebras ToS, Data Usage and Privacy section (effective 2024-08-27, updated 2025-05-07)","quote":"For clarity, the foregoing does not grant Cerebras the right to use Service Content for the purpose of training or fine-tuning models.","mechanism":"Unconditional — no opt-in path exists","notes":"Privacy Policy §6 additionally confirms: \"We do not retain inputs and outputs associated with our training, inference and chatbot Services.\" We access Cerebras via OpenRouter; Cerebras's own terms apply.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"openrouter","status":"no_training","provider_group":"ai_models","policy_url":"https://openrouter.ai/terms","terms_url":"https://openrouter.ai/privacy","source_document":"OpenRouter Terms of Service §5.1 (updated 2026-04-02)","quote":"Some AI Models may store or train on your Inputs for improving their own large language models and may allow you to opt-out of model training, as described in their AI Model Terms. Where possible, OpenRouter has opted out of model training with the AI Models it uses.","mechanism":"OpenRouter itself does not train — product improvement is opt-in only (§5.2). For downstream providers, OpenRouter has proactively opted out where possible. Our only downstream via OpenRouter is Cerebras, which has its own unconditional no-training policy.","notes":"Private input/output logging is also opt-in (§5.3). If we add new models via OpenRouter, verify the downstream provider's training policy.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"fal","status":"limited_use","provider_group":"image_generation","policy_url":"https://fal.ai/legal/terms-of-service","terms_url":null,"source_document":"fal.ai Terms of Service §6.3 (updated 2026-03-03)","quote":"Customer acknowledges and agrees that Company may generate, collect, store, use, transfer, and/or disclose to third parties Usage Data and use Usage Data to perform data analytics; to monitor, improve, and support the Services; to design, develop, and offer Company products, services, and AI models; and for any other lawful purposes.","mechanism":"\"Usage Data\" is defined as \"anonymized or aggregated data... which may include data based on or derived from Customer Input.\" No opt-out exists for standard API customers. Enterprise contracts are the only path to negotiate this away.","notes":"fal.ai does NOT claim to use raw prompts or images directly — only anonymized/aggregated derivatives. However, \"based on or derived from Customer Input\" is broad enough that we cannot claim zero training use. Enterprise pricing is not viable for us at this time.","opted_out_date":null,"last_verified":"2026-04-16T11:15:00Z"},
  {"id":"recraft","status":"no_training_opt_out","provider_group":"image_generation","policy_url":"https://www.recraft.ai/privacy","terms_url":null,"source_document":"Recraft Privacy Policy, Artificial Intelligence Features section (modified 2026-03-12)","quote":"We may use such information to train Recraft's own proprietary AI models, but you may disallow such use of your information by opting out in your account profile settings.","mechanism":"Training is ON by default. Opt-out available in account profile settings (\"Help improve Recraft\" toggle). Third-party AI providers used by Recraft are contractually prohibited from training.","notes":"We opted out on 2026-04-16 via account settings (disabled \"Help improve Recraft — Allow Recraft to use my content to enhance the quality of our AI models\"). With the opt-out active, Recraft's own terms prohibit training on our data.","opted_out_date":"2026-04-16","last_verified":"2026-04-16T11:15:00Z"},
] as const;
