---
- name: Check Docker installation
  command: docker --version
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Check Docker Compose installation
  command: docker compose version
  register: docker_compose_check
  ignore_errors: true
  changed_when: false

- name: Fail if Docker is not installed
  fail:
    msg: "Docker is not installed. Please ensure the docker role runs first."
  when: docker_check.rc != 0

- name: Fail if Docker Compose is not installed
  fail:
    msg: "Docker Compose is not installed. Please ensure the docker role runs first."
  when: docker_compose_check.rc != 0

- name: Create Plane directory
  file:
    path: "{{ plane_install_dir }}"
    state: directory
    mode: '0755'

- name: Download and run Plane setup
  shell: |
    curl -fsSL https://raw.githubusercontent.com/makeplane/plane/master/deploy/selfhost/install.sh -o setup.sh
    chmod +x setup.sh
    echo "1" | ./setup.sh
  args:
    chdir: "{{ plane_install_dir }}"
    creates: "{{ plane_install_dir }}/plane-app"

- name: Modify specific environment variables in plane.env
  lineinfile:
    path: "{{ plane_install_dir }}/plane-app/plane.env"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: "NGINX_PORT", value: "8080" }
    - { key: "WEB_URL", value: "{{ plane_web_url }}" }
    - { key: "CORS_ALLOWED_ORIGINS", value: "{{ plane_web_url }}" }

- name: Start Plane services
  shell: |
    echo "2" | ./setup.sh
  args:
    chdir: "{{ plane_install_dir }}"