---
- name: Create Docker daemon configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'

- name: Create Docker user group
  group:
    name: docker
    state: present

- name: Add system user for Docker
  user:
    name: dockeruser
    groups: docker
    system: yes
    create_home: no
    shell: /usr/sbin/nologin

- name: Restart Docker service
  service:
    name: docker
    state: restarted