name: |
  Web
description: |
  Browse websites, research topics & more.
icon_image: |
  web.svg
icon_colorgradient:
  start: |
    #DE1E66
  end: |
    #FF763B

skills:

  - id: |
      search
    name: |
      Search
    description: |
      Search the web.
# uses APIs for getting web search results - like DuckDuckGo api, Brave or others. does not get the full page content. Can accept text and image as input. Therefore also searches on reverse image search engines like TinEye.
    stage: |
      planning
    class_path: |
      skills.search.SearchSkill
    providers:
      - Brave

  - id: |
      get_legal_pages
    name: |
      Get legal pages
    description: |
      Get the legal pages of a website: terms of service, privacy policy, cookie policy, etc.
    stage: |
      planning

# additional skills: 
# use firecrawl self hosted or via their api
# - read_website (checks first if website content via reader view or print view is over 20.000 tokens long, if so, ask first if the user wants to read the full page or instead search in content and interpret search results paragraphs.)
# - view_website (makes one or multiple screenshots of the rendered page and returns them)
# - search_in_website (searches in text content of website for results - useful for example for long api documentation)

focuses:

  - id: |
      check_reputation
    name: |
      Check reputation
    description: |
      Check if a business is legit and reliable.
    stage: |
      planning
    process:
      - "check if a business exist on trustpilot and what its rating is"
      - "check on whois.com if the website is nearky registered"
      - "use trustpilot, whois.com and othet sites ro identify scams and business with bad customer ratings"
    # systemprompt just an early placeholder. Nowhere near complete.
    systemprompt: |
      You are an expert on identifying scams vs legit businesses.

  - id: |
      analyze_privacy
    name: |
      Analyze privacy
    description: |
      Analyze the privacy implications of a website or service based on its legal pages.
    stage: |
      planning
    process:
      - "gets the legal pages of a website"
      - "analyzes the legal pages for privacy implications"
      - "creates a report based on the findings"
      - "asks the user if they want to proceed with the service based on the privacy implications or if they have additional questions"

  - id:
      research
    name: |
      Research
    description: |
      Make multiple web searches to get a bigger picture of a topic and its causes and effects.


  - id: |
      deep_web_research
    name: |
      Deep web research
    description: |
      Create a plan what to research and then start in in depth web research to gather a report based on the findings.
    stage: |
      planning
    process:
      - "asks user multiple clearifying questions, then creates a list of requirements / priorities / search terms"
      - "then starts in depth web searches for the search terms and creates a report based on the findings"
    # systemprompt just an early placeholder. Nowhere near complete.
    systemprompt: |
      You are an expert for deep web research.