name_translation_key: web.text
description_translation_key: web.description.text
icon_image: |
  web.svg
category: work
last_updated: '2025-11-12'
settings_and_memories:
  - id: bookmarks
    name_translation_key: web.bookmarks.text
    description_translation_key: web.bookmarks.description.text
    type: list
    stage: development
    schema:
      type: object
      properties:
        title:
          type: string
          description: Page title
        url:
          type: string
          description: Website URL
        category:
          type: string
          description: Bookmark category (e.g., reference, news, tools)
        added_date:
          type: integer
          description: Unix timestamp when bookmarked
      required:
      - url
  - id: favorite_websites
    name_translation_key: web.favorite_websites.text
    description_translation_key: web.favorite_websites.description.text
    type: list
    stage: development
    schema:
      type: object
      properties:
        title:
          type: string
          description: Page title
        url:
          type: string
          description: Website URL
        category:
          type: string
          description: Favorite category (e.g., reference, news, tools)
        added_date:
          type: integer
          description: Unix timestamp when added to favorites
      required:
      - url
  - id: read_later
    name_translation_key: web.read_later.text
    description_translation_key: web.read_later.description.text
    type: list
    stage: development
    schema:
      type: object
      properties:
        title:
          type: string
          description: Page title
        url:
          type: string
          description: Website URL
        category:
          type: string
          description: Read later category (e.g., article, tutorial, documentation)
        added_date:
          type: integer
          description: Unix timestamp when saved for later
        notes:
          type: string
          description: Optional notes about why this was saved
      required:
      - url
instructions:
  - instruction: |
      For questions which can likely be answered better with up to date
      documentation (about APIs for example), always first do web search before answering
      the question.
    categories:
    - software_development
skills:
  - id: search
    name_translation_key: web.search.text
    description_translation_key: web.search.description.text
    stage: development
    class_path: |
      backend.apps.web.skills.search_skill.SearchSkill
    providers:
      - Brave
    # Follow-up suggestions shown to users after search results
    suggestions_follow_up_requests:
      - "Search more in depth"
      - "Create a PDF report"
      - "Get more recent results"
    # Fields to exclude from LLM inference (but keep in full results for UI rendering)
    # These fields are removed before adding to message history for LLM processing
    # but remain in the full response stored in chat history for proper UI rendering
    exclude_fields_for_llm:
      - "type"
      - "hash"
      - "meta_url.favicon"
      - "thumbnail.original"
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: Array of search request objects for parallel processing (up to 9 requests). Each object must contain 'query' and can include optional parameters (count, country, search_lang, safesearch).
          items:
            type: object
            properties:
              query:
                type: string
                description: Search query string
              count:
                type: integer
                description: Number of results for this request (max 20)
                minimum: 1
                maximum: 20
                default: 10
              country:
                type: string
                description: Country code for localized results (ISO 3166-1 alpha-2, e.g., 'us', 'gb', 'de')
                default: "us"
              search_lang:
                type: string
                description: Language code for search (ISO 639-1, e.g., 'en', 'es', 'fr')
                default: "en"
              safesearch:
                type: string
                description: Safe search level
                enum: ["off", "moderate", "strict"]
                default: "moderate"
            required:
              - query
      required:
        - requests
focuses:
  - id: check_reputation
    name_translation_key: web.check_reputation.text
    description_translation_key: web.check_reputation.description.text
    stage: planning
    process:
      - check if a business exist on trustpilot and what its rating is
      - check on whois.com if the website is nearky registered
      - use trustpilot, whois.com and othet sites ro identify scams and business with bad customer ratings
    systemprompt: |
      You are an expert on identifying scams vs legit businesses.
  - id: analyze_privacy
    name_translation_key: web.analyze_privacy.text
    description_translation_key: web.analyze_privacy.description.text
    stage: planning
    process:
      - gets the legal pages of a website
      - analyzes the legal pages for privacy implications
      - creates a report based on the findings
      - asks the user if they want to proceed with the service based on the privacy implications or if they have additional questions
    systemprompt: |
      You are an expert on privacy analysis and data protection. Your role is to analyze legal pages (terms of service, privacy policy, cookie policy) and identify privacy implications, data collection practices, and potential risks for users.
  - id: research
    name_translation_key: web.research.text
    description_translation_key: web.research.description.text
    stage: planning
    systemprompt: |
      You are an expert researcher. Your role is to conduct thorough web research by making multiple searches to understand a topic comprehensively, including its causes, effects, and broader context.
  - id: deep_web_research
    name_translation_key: web.deep_web_research.text
    description_translation_key: web.deep_web_research.description.text
    stage: planning
    process:
      - asks user multiple clearifying questions, then creates a list of requirements / priorities / search terms
      - then starts in depth web searches for the search terms and creates a report based on the findings
    systemprompt: |
      You are an expert for deep web research.
