name: |
  Web
description: |
  Browse websites, research topics & more.
icon_image: |
  web.svg
icon_colorgradient:
  start: |
    #DE1E66
  end: |
    #FF763B

skills:

  - id: |
      search
    name: |
      Search
    description: |
      Search the web.
    stage: |
      planning
    class_path: |
      skills.search.SearchSkill
    providers:
      - Brave

focuses:

  - id: |
      check_reputation
    name: |
      Check reputation
    description: |
      Check if a business is legit and reliable.
    stage: |
      planning
    process:
      - "check if a business exist on trustpilot and what its rating is"
      - "check on whois.com if the website is nearky registered"
      - "use trustpilot, whois.com and othet sites ro identify scams and business with bad customer ratings"
    # systemprompt just an early placeholder. Nowhere near complete.
    systemprompt: |
      You are an expert on identifying scams vs legit businesses.

  - id: |
      deep_web_research
    name: |
      Deep web research
    description: |
      Create a plan what to research and then start in in depth web research to gather a report based on the findings.
    stage: |
      planning
    process:
      - "asks user multiple clearifying questions, then creates a list of requirements / priorities / search terms"
      - "then starts in depth web searches for the search terms and creates a report based on the findings"
    # systemprompt just an early placeholder. Nowhere near complete.
    systemprompt: |
      You are an expert for deep web research.