# These are supported funding model platforms

# GitHub Sponsors: Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: [glowingkitty]

# Custom URLs: Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: ['https://openmates.org/#settings/support']
