---
# roles/nginx/tasks/main.yml

# Install required packages
- name: Install Nginx and Certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

# Setup main Nginx configuration with rate limiting in http context
- name: Setup main Nginx configuration
  template:
    src: nginx_main.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'

# Setup Nginx server blocks for each application
- name: Setup Nginx server blocks for applications
  template:
    src: app.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.key }}.conf"
    mode: '0644'
  loop: "{{ applications | dict2items }}"
  vars:
    app_subdomain: "{{ item.value.subdomain }}"
    app_port: "{{ item.value.port }}"

# Enable application configurations
- name: Enable application configurations
  file:
    src: "/etc/nginx/sites-available/{{ item.key }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.key }}.conf"
    state: link
  loop: "{{ applications | dict2items }}"

# Remove default nginx site
- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

# Generate SSL certificates for all enabled applications
- name: Generate SSL certificates for applications
  shell: |
    certbot certonly --nginx --{{ env if env == 'production' else 'staging' }} --non-interactive --agree-tos \
    --email {{ admin_email }} \
    -d {{ item.value.subdomain }}
  args:
    creates: "/etc/letsencrypt/live/{{ item.value.subdomain }}/fullchain.pem"
  loop: "{{ applications | dict2items }}"
  when: item.value.subdomain is defined

# Test Nginx configuration
- name: Test Nginx configuration
  command: nginx -t
  changed_when: false
  register: nginx_test

# Restart Nginx if configuration is valid
- name: Restart Nginx if configuration is valid
  service:
    name: nginx
    state: restarted
  when: nginx_test.rc == 0

# Enable automatic renewal for SSL certificates
- name: Enable automatic certificate renewal
  cron:
    name: "Certbot Renewal"
    job: "certbot renew --quiet --no-self-upgrade"
    minute: "0"
    hour: "3"
    weekday: "1"