/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * Default model settings E2E test.
 *
 * Tests the AI default model settings flow:
 *
 * 1. Login with test account + 2FA
 * 2. Navigate to Settings → AI
 * 3. Toggle auto-select OFF → select "Mistral Small 3.2 3.2" for Simple requests
 * 4. Close settings, send "Capital of Germany?" and verify Mistral Small 3.2 3.2 is used
 * 5. Re-open settings, toggle auto-select back ON
 * 6. Start new chat, send same question, verify a different model is used (not Mistral Small 3.2 3.2)
 * 7. Cleanup: reset to auto-select, delete test chats
 *
 * This test validates:
 * - The auto-select toggle saves immediately when switched on/off
 * - Selecting a specific model in the dropdown persists and is used for the next message
 * - Switching back to auto-select uses a different (auto-selected) model
 * - Notifications appear only for real value changes and include descriptive change text
 *
 * Architecture context: docs/architecture/ai_model_selection.md
 * Component: frontend/packages/ui/src/components/settings/SettingsAI.svelte
 *
 * REQUIRED ENV VARS:
 * - OPENMATES_TEST_ACCOUNT_EMAIL
 * - OPENMATES_TEST_ACCOUNT_PASSWORD
 * - OPENMATES_TEST_ACCOUNT_OTP_KEY
 * - PLAYWRIGHT_TEST_BASE_URL
 */
export {};

const {
	test,
	expect,
	attachConsoleListeners,
	attachNetworkListeners
} = require('./console-monitor');

const {
	createSignupLogger,
	archiveExistingScreenshots,
	createStepScreenshotter,
	generateTotp,
	getTestAccount,
	getE2EDebugUrl,
	withMockMarker
} = require('./signup-flow-helpers');

const { loginToTestAccount, startNewChat, deleteActiveChat, waitForAssistantMessage } = require('./helpers/chat-test-helpers');
const { skipWithoutCredentials } = require('./helpers/env-guard');

const { email: TEST_EMAIL, password: TEST_PASSWORD, otpKey: TEST_OTP_KEY } = getTestAccount();

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Navigate to AI settings via the settings menu.
 * Path: Settings → AI (top-level)
 */
async function navigateToAiSettings(
	page: any,
	logCheckpoint: (message: string, metadata?: Record<string, unknown>) => void,
	takeStepScreenshot: (page: any, label: string) => Promise<void>,
	stepLabel: string
): Promise<void> {
	// 1. Open settings menu
	const settingsToggle = page.locator('#settings-menu-toggle');
	await expect(settingsToggle).toBeVisible({ timeout: 10000 });
	await settingsToggle.click();
	logCheckpoint('Opened settings menu.');

	const settingsMenu = page.locator('[data-testid="settings-menu"].visible');
	await expect(settingsMenu).toBeVisible({ timeout: 10000 });
	await page.waitForTimeout(800);
	await takeStepScreenshot(page, `${stepLabel}-settings-open`);

	// 2. Click "AI" top-level menu item
	const aiMenuItem = settingsMenu.getByRole('menuitem', { name: /^AI$/i }).first();
	await expect(aiMenuItem).toBeVisible({ timeout: 5000 });
	await aiMenuItem.click();
	logCheckpoint('Clicked AI menu item.');
	await page.waitForTimeout(800);

	// 3. Verify AI Settings page loaded
	const aiSettings = page.getByTestId('ai-settings');
	await expect(aiSettings).toBeVisible({ timeout: 8000 });
	logCheckpoint('AI Settings page loaded.');
	await takeStepScreenshot(page, `${stepLabel}-ai-settings`);
}

/**
 * Close the settings panel by clicking the settings toggle again.
 */
async function closeSettings(
	page: any,
	logCheckpoint: (message: string, metadata?: Record<string, unknown>) => void
): Promise<void> {
	const settingsMenu = page.getByTestId('settings-menu');
	const isSettingsOpen = await settingsMenu.isVisible().catch(() => false);

	if (isSettingsOpen) {
		// Click the close button (data-testid="icon-button-close") inside the settings toggle.
		// Clicking #settings-menu-toggle directly fails because the close-icon-container
		// intercepts pointer events when settings are open.
		const closeButton = page.getByTestId('icon-button-close');
		await closeButton.click({ timeout: 5000 });
		logCheckpoint('Closed settings.');
		await page.waitForTimeout(500);
	} else {
		logCheckpoint('Settings already closed.');
	}
}

/**
 * Send a message and wait for the assistant response to complete.
 * Returns the "generated by" text which contains the model name.
 */
async function sendMessageAndGetModel(
	page: any,
	question: string,
	logCheckpoint: (message: string, metadata?: Record<string, unknown>) => void,
	takeStepScreenshot: (page: any, label: string) => Promise<void>,
	stepLabel: string,
	fixtureId: string
): Promise<string> {
	// Type the question
	const messageEditor = page.getByTestId('message-editor');
	await expect(messageEditor).toBeVisible();
	await messageEditor.click();
	await page.keyboard.type(withMockMarker(question, fixtureId));
	logCheckpoint(`Typed question: "${question}"`);
	await takeStepScreenshot(page, `${stepLabel}-question-typed`);

	// Click send button
	const sendButton = page.locator('[data-action="send-message"]');
	await expect(sendButton).toBeVisible({ timeout: 15000 });
	await expect(sendButton).toBeEnabled({ timeout: 5000 });
	await sendButton.click();
	logCheckpoint('Clicked send button.');
	await takeStepScreenshot(page, `${stepLabel}-message-sent`);

	// Wait for URL to update to new chat ID
	logCheckpoint('Waiting for URL to update to new chat ID...');
	await expect(page).toHaveURL(/chat-id=[a-zA-Z0-9-]+/, { timeout: 15000 });
	const chatUrl = page.url();
	const chatIdMatch = chatUrl.match(/chat-id=([a-zA-Z0-9-]+)/);
	const chatId = chatIdMatch ? chatIdMatch[1] : 'unknown';
	logCheckpoint(`Navigated to chat: ${chatId}`);

	// Wait for the assistant response to complete (generated-by element appears after streaming ends)
	logCheckpoint('Waiting for assistant response...');
	const assistantMessage = await waitForAssistantMessage(page, {
		which: 'last',
		logCheckpoint
	});

	// Wait for substantive content before checking for generated-by
	await expect(async () => {
		const msgText = await assistantMessage.textContent();
		expect((msgText || '').trim().length).toBeGreaterThan(5);
	}).toPass({ timeout: 60000, intervals: [2000, 3000, 5000] });

	const generatedByElement = assistantMessage.getByTestId('generated-by');
	await expect(generatedByElement).toBeVisible({ timeout: 90000 });
	logCheckpoint('Response complete - generated-by element visible.');
	await takeStepScreenshot(page, `${stepLabel}-response-complete`);

	const generatedByText = await generatedByElement.textContent();
	logCheckpoint(`Generated by text: "${generatedByText}"`);

	return generatedByText || '';
}

// ─── Test ────────────────────────────────────────────────────────────────────

test('change default model to Mistral Small 3.2, verify it is used, then switch back to auto', async ({
	page
}: {
	page: any;
}) => {
	attachConsoleListeners(page);
	attachNetworkListeners(page);

	test.slow();
	test.setTimeout(300000); // 5 minutes: covers settings navigation + two chat rounds + cleanup

	const logCheckpoint = createSignupLogger('DEFAULT_MODEL_SETTINGS');
	const takeStepScreenshot = createStepScreenshotter(logCheckpoint, {
		filenamePrefix: 'default-model'
	});

	skipWithoutCredentials(test, TEST_EMAIL, TEST_PASSWORD, TEST_OTP_KEY);

	await archiveExistingScreenshots(logCheckpoint);
	logCheckpoint('Starting default model settings test.', { email: TEST_EMAIL });

	// =========================================================================
	// PHASE 1: Login
	// =========================================================================
	await loginToTestAccount(page, logCheckpoint, takeStepScreenshot);

	// =========================================================================
	// PHASE 2: Navigate to AI Ask settings and set Mistral Small 3.2 as default
	// =========================================================================
	logCheckpoint('Phase 2: Navigating to AI settings...');
	await navigateToAiSettings(page, logCheckpoint, takeStepScreenshot, '02');

	// Find the auto-select toggle in the AI settings page.
	// The toggle wrapper is inside the settings-content of the Default Models section.
	const settingsMenu = page.locator('[data-testid="settings-menu"].visible');
	const aiSettings = settingsMenu.getByTestId('ai-settings');

	// The auto-select toggle is a Toggle component wrapped in a clickable div.
	// The toggle's aria-label is the i18n text for "Auto-select model".
	// We target the outer clickable wrapper div (parent of the pointer-events:none div).
	const autoSelectRow = aiSettings.getByTestId('setting-row').first();
	await expect(autoSelectRow).toBeVisible({ timeout: 5000 });

	// Check if auto-select is currently ON (toggle is checked)
	const toggleInput = autoSelectRow.locator('input[type="checkbox"]');
	const isAutoOn = await toggleInput.evaluate((el: HTMLInputElement) => el.checked);
	logCheckpoint(`Auto-select toggle is currently: ${isAutoOn ? 'ON' : 'OFF'}`);

	if (isAutoOn) {
		// Click the toggle wrapper to turn auto-select OFF
		const toggleWrapper = autoSelectRow.locator('[role="button"]').first();
		await toggleWrapper.click();
		logCheckpoint('Toggled auto-select OFF.');
		await page.waitForTimeout(1000);

		// Verify the toggle actually changed state (checkbox should now be unchecked)
		const isNowOff = await toggleInput.evaluate((el: HTMLInputElement) => !el.checked);
		logCheckpoint(`Toggle state after click: ${isNowOff ? 'OFF (expected)' : 'still ON (unexpected)'}`);
		expect(isNowOff).toBe(true);
	}

	await takeStepScreenshot(page, '02-auto-select-off');

	// Toggling OFF auto-select without changing any values should NOT trigger save/notification
	const noChangeNotification = page.getByTestId('notification');
	await page.waitForTimeout(1200);
	await expect(noChangeNotification).toHaveCount(0);
	logCheckpoint('No notification after toggling auto-select OFF with unchanged values (expected).');

	// The model dropdowns should now be visible.
	// Use page-level locator (not scoped through settingsMenu chain) to avoid issues
	// if the .visible class on the settings menu flickers during Svelte re-render.
	// Also scroll into view since the dropdowns render below the toggle and may be
	// below the settings panel fold.
	const simpleDropdown = page.locator('#default-simple-select');
	// Wait for the {#if} block to render the select element
	await expect(simpleDropdown).toBeAttached({ timeout: 10000 });
	await simpleDropdown.scrollIntoViewIfNeeded();
	await expect(simpleDropdown).toBeVisible({ timeout: 10000 });
	logCheckpoint('Simple requests dropdown is visible.');

	// Select "Mistral Small 3.2" in the Simple requests dropdown.
	// The value format is "provider_id/model_id" = "mistral/mistral-small-2506"
	await simpleDropdown.selectOption({ label: 'Mistral Small 3.2' });
	logCheckpoint('Selected "Mistral Small 3.2" in Simple requests dropdown.');
	await page.waitForTimeout(1000);

	await takeStepScreenshot(page, '02-mistral-small-selected');

	// Verify success notification appears with descriptive change text
	const notification2 = page.getByTestId('notification');
	await expect(notification2).toBeVisible({ timeout: 5000 });
	await expect(notification2).toContainText(
		"Changed model for Simple requests from 'Auto' to 'Mistral Small 3.2'"
	);
	logCheckpoint('Descriptive success notification appeared after selecting Mistral Small 3.2.');

	// Wait for notification to disappear
	await page.waitForTimeout(3000);

	// Close settings
	await closeSettings(page, logCheckpoint);
	await page.waitForTimeout(500);

	// =========================================================================
	// PHASE 3: Send a message and verify Mistral Small 3.2 is used
	// =========================================================================
	logCheckpoint('Phase 3: Sending message to verify Mistral Small 3.2 is used...');

	// Start a new chat for a clean state
	await startNewChat(page, logCheckpoint);

	const generatedByText1 = await sendMessageAndGetModel(
		page,
		'Capital of Germany?',
		logCheckpoint,
		takeStepScreenshot,
		'03',
		'default_model_mistral'
	);

	// Verify the response was generated by Mistral Small 3.2
	expect(generatedByText1.toLowerCase()).toContain('mistral small 3.2');
	logCheckpoint(`Verified: response was generated by Mistral Small 3.2. Text: "${generatedByText1}"`);

	// Verify the response contains the expected answer
	const assistantMessage1 = page.getByTestId('message-assistant').last();
	await expect(assistantMessage1).toContainText('Berlin', { timeout: 15000 });
	logCheckpoint('Verified response contains "Berlin".');

	// Remember this chat for later cleanup
	const chatUrl1 = page.url();
	const chatId1Match = chatUrl1.match(/chat-id=([a-zA-Z0-9-]+)/);
	const chatId1 = chatId1Match ? chatId1Match[1] : 'unknown';
	logCheckpoint(`Chat 1 ID: ${chatId1}`);

	// =========================================================================
	// PHASE 4: Switch back to auto-select
	// =========================================================================
	logCheckpoint('Phase 4: Switching back to auto-select...');
	await navigateToAiSettings(page, logCheckpoint, takeStepScreenshot, '04');

	// The auto-select toggle should be OFF now. Toggle it back ON.
	const autoSelectRow2 = aiSettings.getByTestId('setting-row').first();
	await expect(autoSelectRow2).toBeVisible({ timeout: 5000 });

	const toggleInput2 = autoSelectRow2.locator('input[type="checkbox"]');
	const isAutoOn2 = await toggleInput2.evaluate((el: HTMLInputElement) => el.checked);
	logCheckpoint(`Auto-select toggle is currently: ${isAutoOn2 ? 'ON' : 'OFF'}`);

	if (!isAutoOn2) {
		const toggleWrapper2 = autoSelectRow2.locator('[role="button"]').first();
		await toggleWrapper2.click();
		logCheckpoint('Toggled auto-select back ON.');
		await page.waitForTimeout(1000);
	}

	await takeStepScreenshot(page, '04-auto-select-on');

	// Wait for the success notification with descriptive change text
	const notification3 = page.getByTestId('notification');
	await expect(notification3).toBeVisible({ timeout: 5000 });
	await expect(notification3).toContainText(
		"Changed model for Simple requests from 'Mistral Small 3.2' to 'Auto'"
	);
	logCheckpoint('Descriptive success notification appeared after toggling auto-select ON.');

	// Wait for notification to dismiss
	await page.waitForTimeout(3000);

	// Verify the dropdowns are no longer visible (auto-select is ON)
	const simpleDropdown2 = aiSettings.locator('#default-simple-select');
	await expect(simpleDropdown2).not.toBeVisible({ timeout: 3000 });
	logCheckpoint('Dropdowns hidden - auto-select is ON.');

	// Close settings
	await closeSettings(page, logCheckpoint);
	await page.waitForTimeout(500);

	// =========================================================================
	// PHASE 5: Send another message and verify auto-select uses a DIFFERENT model
	// =========================================================================
	logCheckpoint('Phase 5: Sending message to verify auto-select uses a different model...');

	// Start a new chat
	await startNewChat(page, logCheckpoint);

	const generatedByText2 = await sendMessageAndGetModel(
		page,
		'Capital of Germany?',
		logCheckpoint,
		takeStepScreenshot,
		'05',
		'default_model_auto'
	);

	// Verify the model used is NOT Mistral Small 3.2 (auto-select should pick a different model)
	// Auto-select typically picks premium/standard models for simple requests, not economy tier Mistral Small 3.2.
	expect(generatedByText2.toLowerCase()).not.toContain('mistral small 3.2');
	logCheckpoint(
		`Verified: auto-select used a different model (not Mistral Small 3.2). Text: "${generatedByText2}"`
	);

	// Verify the response still contains the expected answer
	const assistantMessage2 = page.getByTestId('message-assistant').last();
	await expect(assistantMessage2).toContainText('Berlin', { timeout: 15000 });
	logCheckpoint('Verified response contains "Berlin".');

	// =========================================================================
	// PHASE 6: Cleanup - delete both test chats
	// =========================================================================
	logCheckpoint('Phase 6: Cleaning up test chats...');

	// Delete the second chat (currently active)
	await deleteActiveChat(page, logCheckpoint, takeStepScreenshot, 'cleanup');

	// Navigate back to the first chat and delete it
	if (chatId1 !== 'unknown') {
		const baseUrl = process.env.PLAYWRIGHT_TEST_BASE_URL ?? 'https://app.dev.openmates.org';
		await page.goto(`${baseUrl}/#chat-id=${chatId1}`);
		await page.waitForTimeout(3000);
		await deleteActiveChat(page, logCheckpoint, takeStepScreenshot, 'cleanup');
	}

	logCheckpoint('Default model settings test completed successfully.');
});
