/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-require-imports */
export {};

const { test, expect } = require('./helpers/cookie-audit');
const consoleLogs: string[] = [];
const networkActivities: string[] = [];

test.beforeEach(async () => {
	consoleLogs.length = 0;
	networkActivities.length = 0;
});

// eslint-disable-next-line no-empty-pattern
test.afterEach(async ({}, testInfo: any) => {
	if (testInfo.status !== 'passed') {
		console.log('\n--- DEBUG INFO ON FAILURE ---');
		console.log('\n[RECENT CONSOLE LOGS]');
		consoleLogs.slice(-30).forEach((log) => console.log(log));

		console.log('\n[RECENT NETWORK ACTIVITIES]');
		networkActivities.slice(-30).forEach((activity) => console.log(activity));
		console.log('\n--- END DEBUG INFO ---\n');
	}
});

const {
	createSignupLogger,
	archiveExistingScreenshots,
	createStepScreenshotter,
	generateTotp,
	assertNoMissingTranslations,
	getTestAccount,
	getE2EDebugUrl,
	withMockMarker
} = require('./signup-flow-helpers');

const { loginToTestAccount, startNewChat, deleteActiveChat } = require('./helpers/chat-test-helpers');
const { skipWithoutCredentials } = require('./helpers/env-guard');

/**
 * Model override test via MentionDropdown autocomplete.
 *
 * Tests the @mention autocomplete flow for selecting AI models:
 * 1. Type "@" in message input to trigger MentionDropdown
 * 2. Type partial model name to filter results
 * 3. Verify model appears in dropdown
 * 4. Press Tab to autocomplete selection
 * 5. Type question and send message
 * 6. Verify response shows correct model in "generated by" text
 *
 * Based on: docs/architecture/ai_model_selection.md
 * Component: frontend/packages/ui/src/components/enter_message/MentionDropdown.svelte
 *
 * REQUIRED ENV VARS:
 * - OPENMATES_TEST_ACCOUNT_EMAIL: Email of an existing test account.
 * - OPENMATES_TEST_ACCOUNT_PASSWORD: Password for the test account.
 * - OPENMATES_TEST_ACCOUNT_OTP_KEY: 2FA OTP secret (base32) for the test account.
 * - PLAYWRIGHT_TEST_BASE_URL: Base URL for the deployed web app under test.
 */

const { email: TEST_EMAIL, password: TEST_PASSWORD, otpKey: TEST_OTP_KEY } = getTestAccount();

/**
 * Helper function to select a model via @ mention autocomplete.
 * Types "@" followed by the model search term, waits for dropdown,
 * verifies the model appears, and presses Tab to autocomplete.
 *
 * @param page - Playwright page object
 * @param modelSearchTerm - Partial model name to search (e.g., "qwen3" or "gpt-5.4")
 * @param expectedModelDisplayName - Expected model name in dropdown (for verification)
 * @param logCheckpoint - Logging function
 * @param takeStepScreenshot - Screenshot function
 * @param stepLabel - Label for screenshots
 */
async function selectModelViaMentionDropdown(
	page: any,
	modelSearchTerm: string,
	expectedModelDisplayName: string,
	logCheckpoint: (message: string, metadata?: Record<string, unknown>) => void,
	takeStepScreenshot: (page: any, label: string) => Promise<void>,
	stepLabel: string
): Promise<void> {
	const messageEditor = page.getByTestId('message-editor');
	await expect(messageEditor).toBeVisible();
	await messageEditor.click();
	logCheckpoint('Clicked on message editor.');

	// Type "@" to trigger the mention dropdown
	await page.keyboard.type('@');
	logCheckpoint('Typed "@" to trigger mention dropdown.');
	await page.waitForTimeout(500);

	// Type the model search term to filter
	await page.keyboard.type(modelSearchTerm);
	logCheckpoint(`Typed model search term: "${modelSearchTerm}"`);
	await page.waitForTimeout(500);

	// Wait for the mention dropdown to appear with increased timeout
	const mentionDropdown = page.getByTestId('mention-dropdown');
	await expect(mentionDropdown).toBeVisible({ timeout: 10000 });
	logCheckpoint('Mention dropdown is visible.');
	await takeStepScreenshot(page, `${stepLabel}-dropdown-visible`);

	// Verify the expected model appears in the dropdown results
	// The model name is shown in .result-name within .mention-result
	const modelResult = mentionDropdown.getByTestId('mention-result-name').filter({
		hasText: new RegExp(expectedModelDisplayName, 'i')
	});

	await expect(modelResult).toBeVisible({ timeout: 10000 });
	logCheckpoint(`Model "${expectedModelDisplayName}" found in dropdown.`);
	await takeStepScreenshot(page, `${stepLabel}-model-in-dropdown`);

	// Press Tab to autocomplete the selection
	// According to MentionDropdown.svelte, Tab key selects the current result
	await page.keyboard.press('Tab');
	logCheckpoint('Pressed Tab to autocomplete model selection.');
	await page.waitForTimeout(500);

	// Verify dropdown is closed after selection
	await expect(mentionDropdown).not.toBeVisible({ timeout: 3000 });
	logCheckpoint('Mention dropdown closed after selection.');
	await takeStepScreenshot(page, `${stepLabel}-model-selected`);

	// Debug: Log what was actually typed/inserted into the editor
	const editorAfterSelection = page.getByTestId('message-editor');
	const editorContent = await editorAfterSelection.textContent();
	logCheckpoint(`Editor content after model selection: "${editorContent}"`);
}

/**
 * Helper function to type a question and send the message.
 * Assumes the model has already been selected via @ mention.
 *
 * After sending, waits for the URL to update to the new chat ID. This is critical
 * because sending from a demo chat creates a new chat in the background and navigates
 * to it. The WebSocket must be subscribed to the new chat's stream channel before the
 * AI response arrives, otherwise the stream events are lost and the response never
 * renders in the DOM. Waiting for the URL change ensures the frontend has navigated
 * and subscribed before we start polling for assistant messages.
 */
async function typeQuestionAndSend(
	page: any,
	question: string,
	logCheckpoint: (message: string, metadata?: Record<string, unknown>) => void,
	takeStepScreenshot: (page: any, label: string) => Promise<void>,
	stepLabel: string,
	fixtureId: string = 'model_override'
): Promise<void> {
	// Type a space after the autocompleted model, then the question.
	// Each model variant uses a distinct fixture id so the replayer returns the
	// correct cached response per model (otherwise all variants get the same one). (OPE-354)
	await page.keyboard.type(withMockMarker(' ' + question, fixtureId));
	logCheckpoint(`Typed question: "${question}"`);
	await takeStepScreenshot(page, `${stepLabel}-question-typed`);

	// Click send button
	const sendButton = page.locator('[data-action="send-message"]');
	await expect(sendButton).toBeEnabled();
	await sendButton.click();
	logCheckpoint('Clicked send button.');
	await takeStepScreenshot(page, `${stepLabel}-message-sent`);

	// Wait for URL to update to the new chat ID. When sending from demo-for-everyone,
	// the app creates a new chat and navigates to it. We must wait for this navigation
	// so that: (a) the frontend's WebSocket subscribes to the new chat stream before
	// the AI response arrives, and (b) initialCount in waitForResponseAndVerifyModel
	// is captured on the correct (empty) chat rather than a stale one.
	logCheckpoint('Waiting for URL to update to new chat ID...');
	await expect(page).toHaveURL(/chat-id=[a-zA-Z0-9-]+/, { timeout: 15000 });
	const chatUrl = page.url();
	const chatIdMatch = chatUrl.match(/chat-id=([a-zA-Z0-9-]+)/);
	const chatId = chatIdMatch ? chatIdMatch[1] : 'unknown';
	logCheckpoint(`Navigated to chat: ${chatId}`, { chatId });
}

/**
 * Helper function to wait for assistant response and verify the model used.
 * Checks the "generated by" text under the assistant message.
 *
 * Assumes typeQuestionAndSend already waited for URL navigation to the new chat,
 * so the chat is fresh. We wait for at least 1 assistant message with a completed
 * generated-by element rather than comparing against a prior count — this handles
 * the case where the Qwen response arrives before this function is called (fast models).
 *
 * @returns The assistant response text content
 */
async function waitForResponseAndVerifyModel(
	page: any,
	expectedModelPattern: RegExp,
	logCheckpoint: (message: string, metadata?: Record<string, unknown>) => void,
	takeStepScreenshot: (page: any, label: string) => Promise<void>,
	stepLabel: string
): Promise<string> {
	logCheckpoint('Waiting for assistant response...');

	// Log current count for debugging (may already be 1 if the model is very fast)
	const initialCount = await page.getByTestId('message-assistant').count();
	logCheckpoint(`Initial assistant message count: ${initialCount}`);

	// Get the last (newest) assistant message
	const assistantMessage = page.getByTestId('message-assistant').last();
	await expect(assistantMessage).toBeVisible({ timeout: 10000 });

	// Wait for a REAL AI response, not the demo chat welcome text.
	// When startNewChat fails (sidebar closed), the message is sent from the demo chat,
	// creating a new chat. During the transition, getByTestId('message-assistant').last()
	// may initially resolve to the demo welcome text ("OpenMates ✨ Digital team mates...").
	// We must wait for an assistant message that does NOT contain the demo pattern and has
	// substantive content from the actual model.
	await expect(async () => {
		const allAssistant = page.getByTestId('message-assistant');
		const count = await allAssistant.count();
		// Find the last assistant message that isn't demo content
		let found = false;
		for (let i = count - 1; i >= 0; i--) {
			const msg = allAssistant.nth(i);
			const text = (await msg.textContent()) || '';
			if (!text.includes('Digital team mates') && text.trim().length > 10) {
				found = true;
				break;
			}
		}
		logCheckpoint(`Waiting for real AI response... assistant count=${count}, found=${found}`);
		expect(found).toBe(true);
	}).toPass({ timeout: 90000, intervals: [2000, 3000, 5000] });
	logCheckpoint('Real AI response detected.');

	// Re-resolve the assistant message to the real response (skip demo content)
	const allAssistantMsgs = page.getByTestId('message-assistant');
	const msgCount = await allAssistantMsgs.count();
	let realAssistantMessage = allAssistantMsgs.last();
	for (let i = msgCount - 1; i >= 0; i--) {
		const msg = allAssistantMsgs.nth(i);
		const text = (await msg.textContent()) || '';
		if (!text.includes('Digital team mates') && text.trim().length > 10) {
			realAssistantMessage = msg;
			break;
		}
	}
	// Replace the assistantMessage reference for the generated-by check
	const assistantMessageFinal = realAssistantMessage;

	// Wait for streaming to complete - the "generated by" text appears after streaming ends.
	// The generated-by element is INSIDE the message wrapper, so we need to scope it.
	// Use a longer timeout (120s) since some models are slow to finalize the response
	// even after content has started streaming.
	const generatedByElement = assistantMessageFinal.getByTestId('generated-by');
	try {
		await expect(generatedByElement).toBeVisible({ timeout: 120000 });
	} catch {
		// Diagnostic: log message state on failure to help debug model-specific issues
		const msgText = await assistantMessageFinal.textContent();
		logCheckpoint(`generated-by NOT visible after 120s. Message text (first 200 chars): "${(msgText || '').slice(0, 200)}"`);
		await takeStepScreenshot(page, `${stepLabel}-generated-by-timeout`);
		throw new Error(
			`generated-by element not found after 120s. The model may not have completed streaming. ` +
			`Message preview: "${(msgText || '').slice(0, 100)}"`
		);
	}
	logCheckpoint('Response complete - generated-by element visible.');
	await takeStepScreenshot(page, `${stepLabel}-response-complete`);

	// Get the model name from the generated-by text
	const generatedByText = await generatedByElement.textContent();
	logCheckpoint(`Generated by text: "${generatedByText}"`);

	// Verify the model name matches expected pattern
	expect(generatedByText).toMatch(expectedModelPattern);
	logCheckpoint(`Verified model matches pattern: ${expectedModelPattern}`);

	// Get the full response text
	const responseText = await assistantMessageFinal.textContent();
	return responseText || '';
}

/**
 * Test: Select Qwen model via @ mention dropdown and verify it's used.
 *
 * Flow:
 * 1. Type "@qwen" in message input
 * 2. Verify "Qwen 3 256b" appears in MentionDropdown
 * 3. Press Tab to autocomplete
 * 4. Type "Capital city of Germany? short answer please."
 * 5. Send message
 * 6. Verify response shows "Qwen" in generated-by text
 */
test('select qwen model via @ mention dropdown', async ({ page }: { page: any }) => {
	page.on('console', (msg: any) => {
		const timestamp = new Date().toISOString();
		consoleLogs.push(`[${timestamp}] [${msg.type()}] ${msg.text()}`);
	});

	page.on('request', (request: any) => {
		const timestamp = new Date().toISOString();
		networkActivities.push(`[${timestamp}] >> ${request.method()} ${request.url()}`);
	});

	page.on('response', (response: any) => {
		const timestamp = new Date().toISOString();
		networkActivities.push(`[${timestamp}] << ${response.status()} ${response.url()}`);
	});

	test.slow();
	test.setTimeout(180000);

	const logCheckpoint = createSignupLogger('MODEL_MENTION_QWEN');
	const takeStepScreenshot = createStepScreenshotter(logCheckpoint, { filenamePrefix: 'qwen' });

	skipWithoutCredentials(test, TEST_EMAIL, TEST_PASSWORD, TEST_OTP_KEY);

	await archiveExistingScreenshots(logCheckpoint);

	logCheckpoint('Starting Qwen model mention test.', { email: TEST_EMAIL });

	// Login
	await loginToTestAccount(page, logCheckpoint, takeStepScreenshot);

	// Start a new chat
	await startNewChat(page, logCheckpoint);

	// Select Qwen model via @ mention dropdown
	// Search term "qwen" should find "Qwen 3 256b" in the dropdown
	await selectModelViaMentionDropdown(
		page,
		'qwen',
		'Qwen',
		logCheckpoint,
		takeStepScreenshot,
		'qwen'
	);

	// Type the question and send
	await typeQuestionAndSend(
		page,
		'Capital city of Germany? short answer please.',
		logCheckpoint,
		takeStepScreenshot,
		'qwen',
		'model_override_qwen'
	);

	// Wait for response and verify Qwen model was used
	// The generated-by text should contain "Qwen" (case-insensitive)
	const response = await waitForResponseAndVerifyModel(
		page,
		/qwen/i,
		logCheckpoint,
		takeStepScreenshot,
		'qwen'
	);

	// Verify the response contains the expected answer
	expect(response.toLowerCase()).toContain('berlin');
	logCheckpoint('Verified response contains "Berlin".');

	// Verify no missing translations on the chat page
	await assertNoMissingTranslations(page);
	logCheckpoint('No missing translations detected.');

	// Cleanup
	await deleteActiveChat(page, logCheckpoint, takeStepScreenshot, 'qwen-cleanup');

	logCheckpoint('Qwen model mention test completed successfully.');
});

/**
 * Test: Select GPT-5.4 model via @ mention dropdown and verify it's used.
 *
 * Flow:
 * 1. Type "@gpt-5.4" in message input
 * 2. Verify "GPT-5.4" appears in MentionDropdown
 * 3. Press Tab to autocomplete
 * 4. Type "Capital city of Germany? short answer please."
 * 5. Send message
 * 6. Verify response shows "GPT-5.4" in generated-by text
 */
test('select gpt-5.4 model via @ mention dropdown', async ({ page }: { page: any }) => {
	page.on('console', (msg: any) => {
		const timestamp = new Date().toISOString();
		consoleLogs.push(`[${timestamp}] [${msg.type()}] ${msg.text()}`);
	});

	page.on('request', (request: any) => {
		const timestamp = new Date().toISOString();
		networkActivities.push(`[${timestamp}] >> ${request.method()} ${request.url()}`);
	});

	page.on('response', (response: any) => {
		const timestamp = new Date().toISOString();
		networkActivities.push(`[${timestamp}] << ${response.status()} ${response.url()}`);
	});

	test.slow();
	test.setTimeout(180000);

	const logCheckpoint = createSignupLogger('MODEL_MENTION_GPT');
	const takeStepScreenshot = createStepScreenshotter(logCheckpoint, { filenamePrefix: 'gpt' });

	skipWithoutCredentials(test, TEST_EMAIL, TEST_PASSWORD, TEST_OTP_KEY);

	await archiveExistingScreenshots(logCheckpoint);

	logCheckpoint('Starting GPT-5.4 model mention test.', { email: TEST_EMAIL });

	// Login
	await loginToTestAccount(page, logCheckpoint, takeStepScreenshot);

	// Start a new chat
	await startNewChat(page, logCheckpoint);

	// Select GPT-5.4 via @ mention dropdown
	// Search term "gpt-5.4" should find "GPT-5.4" in the dropdown
	await selectModelViaMentionDropdown(
		page,
		'gpt-5.4',
		'GPT-5.4',
		logCheckpoint,
		takeStepScreenshot,
		'gpt'
	);

	// Type the question and send. Math question instead of geography because the
	// gpt-5.4 provider repeatedly errors on the "Capital city of Germany" prompt
	// during recording (chat.an_error_occured). (OPE-354)
	await typeQuestionAndSend(
		page,
		'What is 7 + 7? Answer with just the number.',
		logCheckpoint,
		takeStepScreenshot,
		'gpt',
		'model_override_gpt54'
	);

	// Wait for response and verify GPT-5.4 model was used
	// The generated-by text should contain "GPT-5.4" (case-insensitive)
	const response = await waitForResponseAndVerifyModel(
		page,
		/gpt-?5\.?4/i,
		logCheckpoint,
		takeStepScreenshot,
		'gpt'
	);

	// Verify the response contains the expected answer
	expect(response).toContain('14');
	logCheckpoint('Verified response contains "14".');

	// Cleanup
	await deleteActiveChat(page, logCheckpoint, takeStepScreenshot, 'gpt-cleanup');

	logCheckpoint('GPT-5.4 model mention test completed successfully.');
});

/**
 * Test: Switch between models in the same session using @ mention dropdown.
 *
 * Flow:
 * 1. Login once
 * 2. Test Qwen: Select via @qwen, send question, verify response
 * 3. Delete chat
 * 4. Test GPT-5.4: Select via @gpt-5.4, send question, verify response
 * 5. Delete chat
 */
test('switch between qwen and gpt-5.4 via @ mention dropdown', async ({ page }: { page: any }) => {
	page.on('console', (msg: any) => {
		const timestamp = new Date().toISOString();
		consoleLogs.push(`[${timestamp}] [${msg.type()}] ${msg.text()}`);
	});

	page.on('request', (request: any) => {
		const timestamp = new Date().toISOString();
		networkActivities.push(`[${timestamp}] >> ${request.method()} ${request.url()}`);
	});

	page.on('response', (response: any) => {
		const timestamp = new Date().toISOString();
		networkActivities.push(`[${timestamp}] << ${response.status()} ${response.url()}`);
	});

	test.slow();
	test.setTimeout(300000);

	const logCheckpoint = createSignupLogger('MODEL_MENTION_SWITCH');
	const takeStepScreenshot = createStepScreenshotter(logCheckpoint, { filenamePrefix: 'switch' });

	skipWithoutCredentials(test, TEST_EMAIL, TEST_PASSWORD, TEST_OTP_KEY);

	await archiveExistingScreenshots(logCheckpoint);

	logCheckpoint('Starting model switching test.', { email: TEST_EMAIL });

	// Login once
	await loginToTestAccount(page, logCheckpoint, takeStepScreenshot);

	// --- Test 1: Qwen ---
	logCheckpoint('--- Testing Qwen model via @ mention ---');
	await startNewChat(page, logCheckpoint);

	await selectModelViaMentionDropdown(
		page,
		'qwen',
		'Qwen',
		logCheckpoint,
		takeStepScreenshot,
		'switch-qwen'
	);

	await typeQuestionAndSend(
		page,
		'What is 3 + 3? Answer with just the number.',
		logCheckpoint,
		takeStepScreenshot,
		'switch-qwen',
		'model_override_switch_qwen'
	);

	const qwenResponse = await waitForResponseAndVerifyModel(
		page,
		/qwen/i,
		logCheckpoint,
		takeStepScreenshot,
		'switch-qwen'
	);

	expect(qwenResponse).toContain('6');
	logCheckpoint('Qwen test passed: response contains "6".');

	await deleteActiveChat(page, logCheckpoint, takeStepScreenshot, 'switch-qwen-cleanup');

	// --- Test 2: GPT-5.4 ---
	logCheckpoint('--- Testing GPT-5.4 model via @ mention ---');
	await startNewChat(page, logCheckpoint);

	await selectModelViaMentionDropdown(
		page,
		'gpt-5.4',
		'GPT-5.4',
		logCheckpoint,
		takeStepScreenshot,
		'switch-gpt'
	);

	await typeQuestionAndSend(
		page,
		'What is 5 + 5? Answer with just the number.',
		logCheckpoint,
		takeStepScreenshot,
		'switch-gpt',
		'model_override_switch_gpt54'
	);

	const gptResponse = await waitForResponseAndVerifyModel(
		page,
		/gpt-?5\.?4/i,
		logCheckpoint,
		takeStepScreenshot,
		'switch-gpt'
	);

	expect(gptResponse).toContain('10');
	logCheckpoint('GPT-5.4 test passed: response contains "10".');

	await deleteActiveChat(page, logCheckpoint, takeStepScreenshot, 'switch-gpt-cleanup');

	logCheckpoint('Model switching test completed successfully - both models work via @ mention.');
});

/**
 * Test: Select Kimi K2.5 model via @ mention dropdown and verify it's used.
 *
 * This test specifically targets the Kimi K2.5 model (via Together AI) to verify
 * that tool call parsing works correctly after the fix for function_name=None
 * in ParsedOpenAIToolCall validation.
 *
 * Flow:
 * 1. Type "@kimi" in message input
 * 2. Verify "Kimi K2.5" appears in MentionDropdown
 * 3. Press Tab to autocomplete
 * 4. Type "Capital city of Germany? short answer please."
 * 5. Send message
 * 6. Verify response shows "Kimi" in generated-by text
 */
test('select kimi k2.5 model via @ mention dropdown', async ({ page }: { page: any }) => {
	page.on('console', (msg: any) => {
		const timestamp = new Date().toISOString();
		consoleLogs.push(`[${timestamp}] [${msg.type()}] ${msg.text()}`);
	});

	page.on('request', (request: any) => {
		const timestamp = new Date().toISOString();
		networkActivities.push(`[${timestamp}] >> ${request.method()} ${request.url()}`);
	});

	page.on('response', (response: any) => {
		const timestamp = new Date().toISOString();
		networkActivities.push(`[${timestamp}] << ${response.status()} ${response.url()}`);
	});

	test.slow();
	test.setTimeout(180000);

	const logCheckpoint = createSignupLogger('MODEL_MENTION_KIMI');
	const takeStepScreenshot = createStepScreenshotter(logCheckpoint, { filenamePrefix: 'kimi' });

	skipWithoutCredentials(test, TEST_EMAIL, TEST_PASSWORD, TEST_OTP_KEY);

	await archiveExistingScreenshots(logCheckpoint);

	logCheckpoint('Starting Kimi K2.5 model mention test.', { email: TEST_EMAIL });

	// Login
	await loginToTestAccount(page, logCheckpoint, takeStepScreenshot);

	// Start a new chat
	await startNewChat(page, logCheckpoint);

	// Select Kimi K2.5 model via @ mention dropdown
	// Search term "kimi" should find "Kimi K2.5" in the dropdown
	await selectModelViaMentionDropdown(
		page,
		'kimi',
		'Kimi',
		logCheckpoint,
		takeStepScreenshot,
		'kimi'
	);

	// Type the question and send. Note: model_override.json (the existing fixture
	// from the kimi recording) is reused here so the kimi-only test passes without
	// needing a re-record. (OPE-354)
	await typeQuestionAndSend(
		page,
		'Capital city of Germany? short answer please.',
		logCheckpoint,
		takeStepScreenshot,
		'kimi',
		'model_override'
	);

	// Wait for response and verify Kimi K2.5 model was used
	// The generated-by text should contain "Kimi" (case-insensitive)
	const response = await waitForResponseAndVerifyModel(
		page,
		/kimi/i,
		logCheckpoint,
		takeStepScreenshot,
		'kimi'
	);

	// Verify the response contains the expected answer
	expect(response.toLowerCase()).toContain('berlin');
	logCheckpoint('Verified response contains "Berlin".');

	// Verify no missing translations on the chat page
	await assertNoMissingTranslations(page);
	logCheckpoint('No missing translations detected.');

	// Cleanup
	await deleteActiveChat(page, logCheckpoint, takeStepScreenshot, 'kimi-cleanup');

	logCheckpoint('Kimi K2.5 model mention test completed successfully.');
});
