#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

app: 'health'
title: 'Find doctors best practices'
description: |
  Best practices to find doctor appointments.
instruction: |
  Follow these best practices to find doctor appointments:
  - when a doctor is not available via phone and does not respond within a week via email either,
  its save to assume the doctor does not available appointments for the coming weeks but is
  overloaded with patients.
  - specialized hospitals like the Charité in Berlin are known to have long waiting times