repos:
  - repo: local
    hooks:
      - id: generate-changed-files-md
        name: Generate Changed Files Markdown
        entry: python generate_changed_files_md.py
        language: python
        always_run: true
        files: ''