version: '3.8'

services:
  strapiDB:
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    networks:
      - openmates

  strapi:
    build:
      context: ./server/cms/strapi
      dockerfile: Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./server/cms/strapi/config:/opt/app/config
      - ./server/cms/strapi/src:/opt/app/src
      - ./server/cms/strapi/package.json:/opt/package.json
      - ./server/cms/strapi/yarn.lock:/opt/yarn.lock
      - ./server/cms/strapi/.env:/opt/app/.env
      - ./server/cms/strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "${STRAPI_PORT}:${STRAPI_PORT}"
    networks:
      - openmates
    depends_on:
      - strapiDB

  strapi-setup:
    build:
      context: ./server/cms
      dockerfile: Dockerfile
    env_file: .env
    environment:
      STRAPI_URL: "http://strapi:${STRAPI_PORT}"
      STRAPI_TOKEN: ${STRAPI_TOKEN}
    volumes:
      - ./server/api/models:/usr/src/OpenMates/server/api/models
      - ./server/cms/setup.py:/usr/src/OpenMates/setup.py
    networks:
      - openmates
    depends_on:
      - strapi

  rest-api:
    build:
      context: ./server/api
      dockerfile: Dockerfile
    env_file: .env
    environment:
      STRAPI_URL: "http://strapi:${STRAPI_PORT}"
      STRAPI_TOKEN: ${STRAPI_TOKEN}
      DRAGONFLY_URL: "dragonfly:6379"
    ports:
      - "${REST_API_PORT}:${REST_API_PORT}"
    volumes:
      - .:/usr/src/OpenMates
    networks:
      - openmates
    depends_on:
      - strapi
      - dragonfly

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonfly-data:/data
    networks:
      - openmates

networks:
  openmates:

volumes:
  strapi-data:
  dragonfly-data: