---
# - name: Configure webapp server
#   hosts: webapp
#   roles:
#     - system
#     - security
#     - docker
#     - webapp

- name: Configure apps server
  hosts: apps
  roles:
    - system
    - security
    - docker
    - dns_check
    - { role: plane, when: app_project_management_plane_install }
    - { role: nginx, when: app_project_management_plane_install }