/**
 * App-store examples for the code/search_repos skill.
 *
 * Uses public GitHub repository metadata fetched from api.github.com for known
 * open-source projects. The shape matches the real GitHub provider response.
 */

export interface CodeRepoSearchStoreExample {
  id: string;
  query: string;
  query_translation_key?: string;
  provider: string;
  status: 'finished';
  resultCount: number;
  results: Array<Record<string, unknown>>;
}

const examples: CodeRepoSearchStoreExample[] = [
  {
    "id": "store-example-code-search-repos-1",
    "query": "svelte",
    "query_translation_key": "settings.app_store_examples.code.search_repos.1",
    "provider": "GitHub",
    "status": "finished",
    "resultCount": 6,
    "results": [
      {
        "url": "https://github.com/immich-app/immich",
        "html_url": "https://github.com/immich-app/immich",
        "full_name": "immich-app/immich",
        "owner_login": "immich-app",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/109746326?v=4",
        "name": "immich",
        "description": "High performance self-hosted photo and video management solution.",
        "visibility": "public",
        "private": false,
        "fork": false,
        "archived": false,
        "disabled": false,
        "is_template": false,
        "default_branch": "main",
        "primary_language": "TypeScript",
        "languages": [],
        "topics": ["backup-tool", "flutter", "google-photos", "google-photos-alternative", "javascript", "mobile-app", "nestjs", "nodejs", "photo-gallery", "photos", "photos-management", "self-hosted", "svelte", "sveltekit", "typescript", "videos"],
        "license_name": "GNU Affero General Public License v3.0",
        "license_spdx_id": "AGPL-3.0",
        "stars": 101751,
        "forks": 5701,
        "watchers": 101751,
        "open_issues": 678,
        "created_at": "2022-02-03T15:56:27Z",
        "updated_at": "2026-05-25T08:47:40Z",
        "pushed_at": "2026-05-25T06:12:32Z",
        "latest_release_tag": null,
        "latest_release_name": null,
        "latest_release_published_at": null,
        "latest_commit_sha": null,
        "latest_commit_message": null,
        "latest_commit_date": null,
        "contributors": [],
        "site_name": "GitHub",
        "fetched_at": "2026-05-25T08:55:28.083719Z"
      },
      {
        "url": "https://github.com/storybookjs/storybook",
        "html_url": "https://github.com/storybookjs/storybook",
        "full_name": "storybookjs/storybook",
        "owner_login": "storybookjs",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/22632046?v=4",
        "name": "storybook",
        "description": "Storybook is the industry standard workshop for building, documenting, and testing UI components in isolation",
        "visibility": "public",
        "private": false,
        "fork": false,
        "archived": false,
        "disabled": false,
        "is_template": false,
        "default_branch": "next",
        "primary_language": "TypeScript",
        "languages": [],
        "topics": ["angular", "components", "design-systems", "documentation", "html", "javascript", "react", "react-native", "stories", "storybook", "styleguide", "svelte", "testing", "typescript", "ui", "vite", "vue", "web-components", "webpack", "workshop"],
        "license_name": "MIT License",
        "license_spdx_id": "MIT",
        "stars": 90073,
        "forks": 10084,
        "watchers": 90073,
        "open_issues": 2034,
        "created_at": "2016-03-18T04:23:44Z",
        "updated_at": "2026-05-25T08:15:23Z",
        "pushed_at": "2026-05-23T08:29:09Z",
        "latest_release_tag": null,
        "latest_release_name": null,
        "latest_release_published_at": null,
        "latest_commit_sha": null,
        "latest_commit_message": null,
        "latest_commit_date": null,
        "contributors": [],
        "site_name": "GitHub",
        "fetched_at": "2026-05-25T08:55:28.083773Z"
      },
      {
        "url": "https://github.com/sveltejs/svelte",
        "html_url": "https://github.com/sveltejs/svelte",
        "full_name": "sveltejs/svelte",
        "owner_login": "sveltejs",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/23617963?v=4",
        "name": "svelte",
        "description": "web development for the rest of us",
        "visibility": "public",
        "private": false,
        "fork": false,
        "archived": false,
        "disabled": false,
        "is_template": false,
        "default_branch": "main",
        "primary_language": "JavaScript",
        "languages": [],
        "topics": ["compiler", "template", "ui"],
        "license_name": "MIT License",
        "license_spdx_id": "MIT",
        "stars": 86624,
        "forks": 4921,
        "watchers": 86624,
        "open_issues": 1003,
        "created_at": "2016-11-20T18:13:05Z",
        "updated_at": "2026-05-25T07:20:51Z",
        "pushed_at": "2026-05-24T20:46:37Z",
        "latest_release_tag": null,
        "latest_release_name": null,
        "latest_release_published_at": null,
        "latest_commit_sha": null,
        "latest_commit_message": null,
        "latest_commit_date": null,
        "contributors": [],
        "site_name": "GitHub",
        "fetched_at": "2026-05-25T08:55:28.083820Z"
      },
      {
        "url": "https://github.com/unionlabs/union",
        "html_url": "https://github.com/unionlabs/union",
        "full_name": "unionlabs/union",
        "owner_login": "unionlabs",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/129756567?v=4",
        "name": "union",
        "description": "The trust-minimized, zero-knowledge bridging protocol, designed for censorship resistance, extremely high security, and usage in decentralized finance.",
        "visibility": "public",
        "private": false,
        "fork": false,
        "archived": false,
        "disabled": false,
        "is_template": false,
        "default_branch": "main",
        "primary_language": "Rust",
        "languages": [],
        "topics": ["astro", "blockchain", "cosmos", "cosmwasm", "ethereum", "evm", "golang", "indexer", "interoperability", "move", "nix", "prover", "relayer", "rust", "solidity", "svelte", "typescipt", "typescript", "zero-knowledge"],
        "license_name": "Apache License 2.0",
        "license_spdx_id": "Apache-2.0",
        "stars": 74035,
        "forks": 3891,
        "watchers": 74035,
        "open_issues": 192,
        "created_at": "2023-05-16T22:33:39Z",
        "updated_at": "2026-05-25T05:14:56Z",
        "pushed_at": "2026-05-22T14:55:21Z",
        "latest_release_tag": null,
        "latest_release_name": null,
        "latest_release_published_at": null,
        "latest_commit_sha": null,
        "latest_commit_message": null,
        "latest_commit_date": null,
        "contributors": [],
        "site_name": "GitHub",
        "fetched_at": "2026-05-25T08:55:28.083855Z"
      },
      {
        "url": "https://github.com/coollabsio/coolify",
        "html_url": "https://github.com/coollabsio/coolify",
        "full_name": "coollabsio/coolify",
        "owner_login": "coollabsio",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/60715044?v=4",
        "name": "coolify",
        "description": "An open-source, self-hostable PaaS alternative to Vercel, Heroku & Netlify that lets you easily deploy static sites, databases, full-stack applications and 280+ one-click services on your own servers.",
        "visibility": "public",
        "private": false,
        "fork": false,
        "archived": false,
        "disabled": false,
        "is_template": false,
        "default_branch": "v4.x",
        "primary_language": "PHP",
        "languages": [],
        "topics": ["coolify", "databases", "deployment", "docker", "docker-compose", "inertiajs", "laravel", "mariadb", "mysql", "nextjs", "nodejs", "php", "postgres", "redis", "self-hosted", "self-hosting", "server", "static-site", "svelte", "svelte5"],
        "license_name": "Apache License 2.0",
        "license_spdx_id": "Apache-2.0",
        "stars": 55841,
        "forks": 4636,
        "watchers": 55841,
        "open_issues": 771,
        "created_at": "2021-01-25T20:54:01Z",
        "updated_at": "2026-05-25T08:49:17Z",
        "pushed_at": "2026-05-23T19:06:34Z",
        "latest_release_tag": null,
        "latest_release_name": null,
        "latest_release_published_at": null,
        "latest_commit_sha": null,
        "latest_commit_message": null,
        "latest_commit_date": null,
        "contributors": [],
        "site_name": "GitHub",
        "fetched_at": "2026-05-25T08:55:28.083899Z"
      },
      {
        "url": "https://github.com/TanStack/query",
        "html_url": "https://github.com/TanStack/query",
        "full_name": "TanStack/query",
        "owner_login": "TanStack",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/72518640?v=4",
        "name": "query",
        "description": "\\ud83e\\udd16 Powerful asynchronous state management, server-state utilities and data fetching for the web. TS/JS, React Query, Solid Query, Svelte Query and Vue Query.",
        "visibility": "public",
        "private": false,
        "fork": false,
        "archived": false,
        "disabled": false,
        "is_template": false,
        "default_branch": "main",
        "primary_language": "TypeScript",
        "languages": [],
        "topics": ["async", "cache", "data", "fetch", "graphql", "hooks", "query", "react", "rest", "solid", "stale", "stale-while-revalidate", "svelte", "typescript", "update", "vue"],
        "license_name": "MIT License",
        "license_spdx_id": "MIT",
        "stars": 49506,
        "forks": 3853,
        "watchers": 49506,
        "open_issues": 176,
        "created_at": "2019-09-10T19:23:58Z",
        "updated_at": "2026-05-25T07:50:24Z",
        "pushed_at": "2026-05-25T06:44:03Z",
        "latest_release_tag": null,
        "latest_release_name": null,
        "latest_release_published_at": null,
        "latest_commit_sha": null,
        "latest_commit_message": null,
        "latest_commit_date": null,
        "contributors": [],
        "site_name": "GitHub",
        "fetched_at": "2026-05-25T08:55:28.083935Z"
      }
    ]
  },
  {
    "id": "store-example-code-search-repos-2",
    "query": "SvelteKit framework",
    "query_translation_key": "settings.app_store_examples.code.search_repos.2",
    "provider": "GitHub",
    "status": "finished",
    "resultCount": 1,
    "results": [{
      "url": "https://github.com/sveltejs/kit",
      "html_url": "https://github.com/sveltejs/kit",
      "full_name": "sveltejs/kit",
      "owner_login": "sveltejs",
      "owner_avatar_url": "https://avatars.githubusercontent.com/u/23617963?v=4",
      "name": "kit",
      "description": "web development, streamlined",
      "primary_language": "JavaScript",
      "license_name": "MIT License",
      "license_spdx_id": "MIT",
      "stars": 20529,
      "forks": 2255,
      "open_issues": 1018,
      "updated_at": "2026-05-24T16:35:57Z"
    }]
  },
  {
    "id": "store-example-code-search-repos-3",
    "query": "FastAPI framework",
    "query_translation_key": "settings.app_store_examples.code.search_repos.3",
    "provider": "GitHub",
    "status": "finished",
    "resultCount": 1,
    "results": [{
      "url": "https://github.com/fastapi/fastapi",
      "html_url": "https://github.com/fastapi/fastapi",
      "full_name": "fastapi/fastapi",
      "owner_login": "fastapi",
      "owner_avatar_url": "https://avatars.githubusercontent.com/u/156354296?v=4",
      "name": "fastapi",
      "description": "FastAPI framework, high performance, easy to learn, fast to code, ready for production",
      "primary_language": "Python",
      "license_name": "MIT License",
      "license_spdx_id": "MIT",
      "stars": 98485,
      "forks": 9340,
      "open_issues": 96,
      "updated_at": "2026-05-24T17:29:50Z"
    }]
  }
];

export default examples;
