name_translation_key: ai
description_translation_key: ai.description
icon_image: |
  ai.svg
last_updated: "2025-11-12"
# Providers are auto-discovered from backend/providers/*.yml files
# based on models with for_app_skill matching the skill ID (e.g., "ai.ask")
# See: frontend/packages/ui/scripts/generate-apps-metadata.js

# Optional: Define the display order for provider icons in the App Store.
# Providers listed here will appear first (in this order), followed by any
# remaining auto-discovered providers. This controls the visual presentation
# in the app preview cards, not the actual provider availability.
provider_display_order:
  - Mistral AI
  - Google
  - Anthropic
  - OpenAI
  - Alibaba

settings_and_memories:
  - id: communication_style
    name_translation_key: ai.communication_style
    description_translation_key: ai.communication_style.description
    type: single
    stage: production
    example_translation_keys:
      - "ai.communication_style.example_1"
      - "ai.communication_style.example_2"
    schema:
      type: object
      properties:
        title:
          type: string
          description: A descriptive name for this communication style (e.g., Work Mode, Casual Chat)
          is_title: true
        tone:
          type: string
          enum:
            - formal
            - casual
            - friendly
            - professional
            - conversational
          description: Preferred communication tone
        verbosity:
          type: string
          enum:
            - concise
            - balanced
            - detailed
            - very_detailed
          description: How detailed responses should be
      required:
        - title
        - tone
        - verbosity

  - id: learning_preferences
    name_translation_key: ai.learning_preferences
    description_translation_key: ai.learning_preferences.description
    type: list
    stage: production
    example_translation_keys:
      - "ai.learning_preferences.example_1"
      - "ai.learning_preferences.example_2"
    schema:
      type: object
      properties:
        title:
          type: string
          description: A name for this learning preference (e.g., Hands-on Learner, Visual Thinker)
          is_title: true
        learning_type:
          type: string
          enum:
            - visual
            - auditory
            - reading
            - hands-on
            - video
            - interactive
            - written
            - discussion
          description: Type of learning method
        preference_strength:
          type: string
          enum:
            - strongly_prefer
            - prefer
            - neutral
            - avoid
          description: How strongly you prefer or avoid this learning type
        notes:
          type: string
          description: Additional notes about this learning preference
      required:
        - title
        - learning_type
        - preference_strength

  - id: interaction_preferences
    name_translation_key: ai.interaction_preferences
    description_translation_key: ai.interaction_preferences.description
    type: single
    stage: planning
    schema:
      type: object
      properties:
        ask_clarifying_questions:
          type: string
          enum:
            - always
            - when_ambiguous
            - rarely
            - never
          description: When to ask clarifying questions
        provide_proactive_suggestions:
          type: boolean
          description: Whether to proactively suggest follow-ups and related topics
        confirmation_preference:
          type: string
          enum:
            - always_confirm
            - confirm_important
            - auto_proceed
          description: When to ask for confirmation before taking actions
        reference_past_conversations:
          type: string
          enum:
            - frequently
            - when_relevant
            - rarely
            - never
          description: How often to reference past conversations
      required:
        - ask_clarifying_questions
        - provide_proactive_suggestions

skills:
  - id: ask
    name_translation_key: ai.ask
    description_translation_key: ai.ask.description
    stage: production
    class_path: |
      ai.skills.ask_skill.AskSkill
    # Providers are auto-discovered from backend/providers/*.yml files
    # based on models with for_app_skill: "ai.ask"
    skill_config:
      # Model Selection Configuration
      # When false, uses hardcoded models from default_llms below.
      # When true, uses intelligent auto-selection based on leaderboard rankings.
      enable_auto_model_selection: true
      default_llms:
        preprocessing_model: mistral/mistral-small-latest
        # main_processing_simple: google/gemini-3-flash-preview
        # main_processing_simple_name: Gemini 3 Flash
        main_processing_simple: alibaba/qwen3-235b-a22b-2507
        main_processing_simple_name: Qwen3
        # main_processing_complex: google/gemini-3.1-pro-preview
        # main_processing_complex_name: Gemini 3.1 Pro
        main_processing_complex: alibaba/qwen3-235b-a22b-2507
        main_processing_complex_name: Qwen3
        content_sanitization_model: openai/gpt-oss-safeguard-20b
      preprocessing_thresholds:
        harmful_content_score: 7
        misuse_risk_score: 8
      # ALWAYS-INCLUDE SKILLS:
      # Skills that are ALWAYS available to the main LLM, regardless of
      # whether preprocessing preselected them. Safety net for follow-ups.
      # Note: Keep this list minimal to avoid token waste.
      always_include_skills:
        - web-search
