name: |
  AI
description: |
  Ask questions, brainstorm ideas & more.
icon_image: |
  ai.svg
icon_colorgradient:
  start: |
    #CB7D5D
  end: |
    #CB685D

skills:

  - id: |
      ask
    name: |
      Ask
    description: |
      Ask a question, using text, images, and other media.
    stage: |
      development
    class_path: |
      ai.skills.ask_skill.AskSkill
    # Configuration specific to the 'ask' skill
    skill_config:
      default_llms:
        # Model to be used for the initial preprocessing step (tool calling)
        preprocessing_model: "mistralai/mistral-small-latest"

        # Default model for main processing when complexity is 'simple'
        main_processing_simple: "mistralai/mistral-medium-latest"
        main_processing_simple_name: "Mistral Medium"

        # Default model for main processing when complexity is 'complex'
        main_processing_complex: "google/gemini-2.5-pro-preview-06-05"
        main_processing_complex_name: "Google Gemini 2.5 Pro"

      preprocessing_thresholds:
        harmful_content_score: 7
        misuse_risk_score: 8