name: |
  AI
description: |
  Ask questions, brainstorm ideas & more.
icon_image: |
  ai.svg
icon_colorgradient:
  start: |
    #CB7D5D
  end: |
    #CB685D

skills:

  - id: |
      ask
    name: |
      Ask
    description: |
      Ask a question, using text, images, and other media.
    stage: |
      development
    class_path: |
      ai.skills.ask_skill.AskSkill
    # Configuration specific to the 'ask' skill
    skill_config:
      default_llms:
        # Model to be used for the initial preprocessing step (tool calling)
        preprocessing_model: "mistralai/mistral-small-2506"

        # Default model for main processing when complexity is 'simple'
        main_processing_simple: "openrouter/openai/gpt-oss-120b"
        main_processing_simple_name: "GPT-OSS-120b"
        # main_processing_simple: "mistralai/mistral-medium-latest"
        # main_processing_simple_name: "Mistral Medium"

        # Default model for main processing when complexity is 'complex'
        # main_processing_complex: "anthropic/claude-sonnet-4-20250514"
        # main_processing_complex_name: "Claude Sonnet 4"
        main_processing_complex: "openrouter/openai/gpt-oss-120b"
        main_processing_complex_name: "GPT-OSS-120b"

      preprocessing_thresholds:
        harmful_content_score: 7
        misuse_risk_score: 8