// Watch embed preview and continuation views.
// Renders the small Watch-specific card contract generated by
// WatchEmbedPreviewMapper without importing iOS/macOS embed renderers.
// Tapping a card is handled by the parent shell so the detail screen can offer
// iPhone/Mac continuation instead of rich fullscreen consumption on Watch.

// ─── Web source ─────────────────────────────────────────────────────
// Svelte:  frontend/packages/ui/src/components/embeds/UnifiedEmbedPreview.svelte
//          frontend/packages/ui/src/components/embeds/UnifiedEmbedFullscreen.svelte
// Tokens:  ColorTokens.generated.swift, SpacingTokens.generated.swift
// ────────────────────────────────────────────────────────────────────

import SwiftUI

struct WatchEmbedPreviewCard: View {
    let model: WatchEmbedPreviewModel
    let onOpen: () -> Void

    var body: some View {
        Button(action: onOpen) {
            VStack(alignment: .leading, spacing: .spacing2) {
                HStack(spacing: .spacing2) {
                    Circle()
                        .fill(LinearGradient.primary)
                        .frame(width: .spacing5, height: .spacing5)
                        .accessibilityHidden(true)

                    Text(model.typeLabel)
                        .font(.omMicro)
                        .fontWeight(.semibold)
                        .foregroundStyle(Color.grey30)
                        .lineLimit(1)
                }

                Text(model.title)
                    .font(.omXs)
                    .fontWeight(.semibold)
                    .foregroundStyle(Color.grey0)
                    .lineLimit(2)

                if let subtitle = model.subtitle {
                    Text(subtitle)
                        .font(.omMicro)
                        .foregroundStyle(Color.grey30)
                        .lineLimit(2)
                }

                Spacer(minLength: 0)

                WatchEmbedStatePill(state: model.state)
            }
            .padding(.spacing3)
            .frame(
                width: CGFloat(WatchEmbedPreviewModel.cardWidth),
                height: CGFloat(WatchEmbedPreviewModel.cardHeight),
                alignment: .topLeading
            )
            .background(Color.grey90, in: RoundedRectangle(cornerRadius: .radius6, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: .radius6, style: .continuous)
                    .stroke(borderColor, lineWidth: 1)
            )
        }
        .buttonStyle(.plain)
        .disabled(model.state == .processing)
        .accessibilityIdentifier("watch-embed-preview-\(model.family.rawValue)")
    }

    private var borderColor: Color {
        switch model.state {
        case .ready: return Color.grey70
        case .processing: return Color.buttonPrimary.opacity(0.65)
        case .error: return Color.error.opacity(0.75)
        }
    }
}

private struct WatchEmbedStatePill: View {
    let state: WatchEmbedPreviewState

    var body: some View {
        Text(label)
            .font(.omMicro)
            .foregroundStyle(foreground)
            .padding(.horizontal, .spacing2)
            .padding(.vertical, 1)
            .background(background, in: Capsule())
    }

    private var label: String {
        switch state {
        case .ready: return WatchLocalization.text("common.continue")
        case .processing: return WatchLocalization.text("common.processing")
        case .error: return WatchLocalization.text("embeds.application_preview_failed")
        }
    }

    private var foreground: Color {
        switch state {
        case .ready, .processing: return Color.grey0
        case .error: return Color.error
        }
    }

    private var background: Color {
        switch state {
        case .ready: return Color.buttonPrimary.opacity(0.35)
        case .processing: return Color.grey80
        case .error: return Color.error.opacity(0.16)
        }
    }
}
