name_translation_key: news.text
description_translation_key: news.description.text
icon_image: |
  news.svg
category: personal
last_updated: '2025-11-26'
settings_and_memories: []
instructions: []
skills:
  - id: search
    name_translation_key: news.search.text
    description_translation_key: news.search.description.text
    stage: development
    class_path: |
      backend.apps.news.skills.search_skill.SearchSkill
    providers:
      - Brave
    # Follow-up suggestions shown to users after search results
    suggestions_follow_up_requests:
      - "Get more recent news"
      - "Read full article"
      - "Search related topics"
    # Fields to exclude from LLM inference (but keep in full results for UI rendering)
    # These fields are removed before adding to message history for LLM processing
    # but remain in the full response stored in chat history for proper UI rendering
    exclude_fields_for_llm:
      - "type"
      - "hash"
      - "meta_url.favicon"
      - "thumbnail.original"
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: Array of search request objects for parallel processing (up to 9 requests). Each object must contain 'query' and can include optional parameters (count, country, search_lang, safesearch).
          items:
            type: object
            properties:
              query:
                type: string
                description: Search query string
              count:
                type: integer
                description: Number of results for this request (max 20)
                minimum: 1
                maximum: 20
                default: 10
              country:
                type: string
                description: "Country code for localized results. Must be one of: AR, AU, AT, BE, BR, CA, CL, DK, FI, FR, DE, GR, HK, IN, ID, IT, JP, KR, MY, MX, NL, NZ, NO, CN, PL, PT, PH, RU, SA, ZA, ES, SE, CH, TW, TR, GB, US, or ALL (case-insensitive). Defaults to 'us' if invalid."
                enum: ["AR", "AU", "AT", "BE", "BR", "CA", "CL", "DK", "FI", "FR", "DE", "GR", "HK", "IN", "ID", "IT", "JP", "KR", "MY", "MX", "NL", "NZ", "NO", "CN", "PL", "PT", "PH", "RU", "SA", "ZA", "ES", "SE", "CH", "TW", "TR", "GB", "US", "ALL", "ar", "au", "at", "be", "br", "ca", "cl", "dk", "fi", "fr", "de", "gr", "hk", "in", "id", "it", "jp", "kr", "my", "mx", "nl", "nz", "no", "cn", "pl", "pt", "ph", "ru", "sa", "za", "es", "se", "ch", "tw", "tr", "gb", "us", "all"]
                default: "us"
              search_lang:
                type: string
                description: Language code for search (ISO 639-1, e.g., 'en', 'es', 'fr')
                default: "en"
              safesearch:
                type: string
                description: Safe search level
                enum: ["off", "moderate", "strict"]
                default: "moderate"
              freshness:
                type: string
                description: Filter by freshness - "pd" (past 24 hours), "pw" (past week), "pm" (past month), "py" (past year). Defaults to "pw" (past week) to prioritize recent news content.
                enum: ["pd", "pw", "pm", "py"]
                default: "pw"
            required:
              - query
      required:
        - requests
focuses:
  - id: understand_the_news
    name_translation_key: news.understand_the_news.text
    description_translation_key: news.understand_the_news.description.text
    stage: planning
    process:
      - searches for the latest news
      - asks the users which news they want to learn more about and discuss more
      - triggers the Web Read skill to get the full news article
      - discusses the article and topic with the user
    systemprompt: |
      You are an expert news analyst. Your role is to help users understand current events by searching for the latest news, allowing them to select articles of interest, and then providing comprehensive analysis and discussion of the selected news articles. Your goal is for the user to have a broad understanding of the topic.

