name_translation_key: videos.text
description_translation_key: videos.description.text
icon_image: |
  videos.svg
category: personal
last_updated: '2025-11-12'
settings_and_memories:
  - id: to_watch_list
    name_translation_key: videos.to_watch_list.text
    description_translation_key: videos.to_watch_list.description.text
    type: list
    stage: planning
    schema:
      type: object
      properties:
        title:
          type: string
          description: Video title
        channel:
          type: string
          description: Channel name
        url:
          type: string
          description: Video URL
        added_date:
          type: integer
          description: Unix timestamp when added
      required:
        - url
  - id: subscribed_channels
    name_translation_key: videos.subscribed_channels.text
    description_translation_key: videos.subscribed_channels.description.text
    type: list
    stage: planning
    schema:
      type: object
      properties:
        name:
          type: string
          description: Channel name
        url:
          type: string
          description: YouTube Channel URL
        subscribed_date:
          type: integer
          description: Unix timestamp when subscribed
        category:
          type: string
          description: Content category (e.g., tech, music, education)
      required:
        - url
skills:
  - id: get_transcript
    name_translation_key: videos.get_transcript.text
    description_translation_key: videos.get_transcript.description.text
    stage: planning
