name_translation_key: videos.text
description_translation_key: videos.description.text
icon_image: |
  videos.svg
category: personal
last_updated: '2025-11-12'
settings_and_memories:
  - id: to_watch_list
    name_translation_key: videos.to_watch_list.text
    description_translation_key: videos.to_watch_list.description.text
    type: list
    stage: planning
    schema:
      type: object
      properties:
        title:
          type: string
          description: Video title
        channel:
          type: string
          description: Channel name
        url:
          type: string
          description: Video URL
        added_date:
          type: integer
          description: Unix timestamp when added
      required:
        - url
  - id: subscribed_channels
    name_translation_key: videos.subscribed_channels.text
    description_translation_key: videos.subscribed_channels.description.text
    type: list
    stage: planning
    schema:
      type: object
      properties:
        name:
          type: string
          description: Channel name
        url:
          type: string
          description: YouTube Channel URL
        subscribed_date:
          type: integer
          description: Unix timestamp when subscribed
        category:
          type: string
          description: Content category (e.g., tech, music, education)
      required:
        - url
skills:
  - id: get_transcript
    name_translation_key: videos.get_transcript.text
    description_translation_key: videos.get_transcript.description.text
    stage: development
    class_path: |
      backend.apps.videos.skills.transcript_skill.TranscriptSkill
    providers:
      - YouTube
    # Fields to exclude from LLM inference (but keep in full results for UI rendering)
    # These fields are removed before adding to message history for LLM processing
    # but remain in the full response stored in chat history for proper UI rendering
    exclude_fields_for_llm:
      - "type"
      - "hash"
      - "metadata.thumbnail_url"
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: Array of transcript request objects for parallel processing. Each object must contain 'url' and can include optional parameters (languages).
          items:
            type: object
            properties:
              url:
                type: string
                description: YouTube video URL (supports youtube.com/watch?v= and youtu.be/ formats)
              languages:
                type: array
                description: List of language codes to try for transcript (ISO 639-1, e.g., 'en', 'de', 'es', 'fr'). The API will use the first available language.
                items:
                  type: string
                default: ["en", "de", "es", "fr"]
            required:
              - url
      required:
        - requests
