// Web source: frontend/packages/ui/src/components/settings/AppSettingsMemoriesCreateEntry.svelte,
// AppSettingsMemoriesEntryDetail.svelte; frontend/packages/ui/src/utils/inputValidation.ts.
// Specification: specifications/features/app-memories/specification.yml
// Assertions: app-memories.surface.semantic-parity

import Foundation

struct SettingsMemoryDraft {
    var inputs: [String: String]
    var key: String
    var genericValue: String
    let original: SettingsMemoryEntry?
    let category: SettingsMemoryCategory

    init(category: SettingsMemoryCategory, entry: SettingsMemoryEntry?) {
        self.category = category; original = entry; key = entry?.key ?? ""
        genericValue = entry?.value ?? ""
        inputs = Dictionary(uniqueKeysWithValues: (category.schema?.inputFields ?? []).map { field in
            (field.name, entry?.fields[field.name]?.display ?? field.defaultValue?.display ?? (field.type == "boolean" ? "false" : ""))
        })
    }
    var usesSchema: Bool { !(category.schema?.inputFields.isEmpty ?? true) }
    @MainActor
    func payload(now: Int = Int(Date().timeIntervalSince1970)) throws -> (key: String, fields: [String: SettingsMemoryValue]) {
        guard let schema = category.schema, usesSchema else {
            let cleanKey = key.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !cleanKey.isEmpty else { throw Validation(AppStrings.memoryKeyRequired) }
            guard cleanKey.utf16.count <= 100 else { throw Validation(AppStrings.memoryValidation(.keyLength, limit: "100")) }
            if original == nil, genericValue.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { throw Validation(AppStrings.memoryValueRequired) }
            guard genericValue.utf16.count <= 1000 else { throw Validation(AppStrings.memoryValidation(.valueLength, limit: "1000")) }
            let parsed = try? SettingsMemoryValue.parse(genericValue)
            return (cleanKey, parsed?.object ?? ["value": .string(genericValue.trimmingCharacters(in: .whitespacesAndNewlines))])
        }
        var fields = original?.fields ?? [:]
        for field in schema.inputFields {
            let text = (inputs[field.name] ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            if text.isEmpty {
                if schema.required.contains(field.name) { throw Validation(AppStrings.memoryValidation(.required, field: field.label)) }
                fields.removeValue(forKey: field.name)
                continue
            }
            let value = try Self.convert(text, field: field)
            try Self.validate(value, field: field)
            fields[field.name] = value
        }
        for field in schema.fields where field.autoGenerated {
            if field.name == "title" {
                let parts = schema.fields.filter { !$0.autoGenerated }.compactMap { fields[$0.name]?.display }.filter { !$0.isEmpty }
                fields[field.name] = .string(parts.isEmpty ? "Untitled" : parts.map { $0.contains("_") && !$0.contains(" ") ? $0.replacingOccurrences(of: "_", with: " ").capitalized : $0 }.joined(separator: " - "))
            } else if original == nil {
                if field.name.contains("date") || field.name.contains("_at") || field.name == "timestamp" || ["integer", "number"].contains(field.type) { fields[field.name] = .number(Double(now)) }
                else if ["id", "entry_id"].contains(field.name) { fields[field.name] = .string(UUID().uuidString) }
                else { fields[field.name] = .string("") }
            }
        }
        let url = schema.fields.first { $0.name.lowercased().contains("url") }.flatMap { fields[$0.name]?.display }
        let name = schema.fields.first { ["name", "title"].contains($0.name.lowercased()) }.flatMap { fields[$0.name]?.display }
        let first = schema.required.first { required in schema.inputFields.contains { $0.name == required } } ?? schema.inputFields.first?.name
        let fallback = first.flatMap { fields[$0]?.display }
        let identity = [url, name].compactMap { $0 }.first { !$0.isEmpty }
        let itemKey = identity.map { "\(category.categoryId).\($0)" } ?? original?.key ?? "\(category.categoryId).\(fallback ?? String(now))"
        return (itemKey, fields)
    }
    @MainActor
    private static func convert(_ text: String, field: SettingsMemoryField) throws -> SettingsMemoryValue {
        switch field.type {
        case "string": return .string(text)
        case "integer", "number":
            guard let number = Double(text), number.isFinite, field.type != "integer" || number.rounded() == number else { throw Validation(AppStrings.memoryValidation(field.type == "integer" ? .integer : .number, field: field.label)) }
            return .number(number)
        case "boolean":
            guard text == "true" || text == "false" else { throw Validation(AppStrings.memoryValidation(.boolean, field: field.label)) }
            return .bool(text == "true")
        case "array", "object":
            guard let value = try? SettingsMemoryValue.parse(text) else { throw Validation(AppStrings.memoryValidation(.json, field: field.label)) }
            if field.type == "array", case .array = value { return value }
            if field.type == "object", case .object = value { return value }
            throw Validation(AppStrings.memoryValidation(field.type == "array" ? .jsonArray : .jsonObject, field: field.label))
        default: throw Validation(AppStrings.memoryValidation(.unsupportedType, type: field.type))
        }
    }
    @MainActor
    static func validate(_ value: SettingsMemoryValue, field: SettingsMemoryField) throws {
        if !field.enumValues.isEmpty, !field.enumValues.contains(value.display) { throw Validation(AppStrings.memoryValidation(.allowedValue, field: field.label)) }
        switch value {
        case .string(let string):
            guard string.utf16.count <= field.maxLength else { throw Validation(AppStrings.memoryValidation(.length, field: field.label, limit: String(field.maxLength))) }
        case .number(let number):
            if let min = field.minimum, number < min { throw Validation(AppStrings.memoryValidation(.minimum, field: field.label, limit: String(min))) }
            if let max = field.maximum, number > max { throw Validation(AppStrings.memoryValidation(.maximum, field: field.label, limit: String(max))) }
        case .object(let object): if let schema = field.nested { try validateContainer(.object(object), schema: schema, label: field.label) }
        case .array(let items): if let schema = field.items { for item in items { try validateContainer(item, schema: schema, label: field.label) } }
        default: break
        }
    }
    @MainActor
    private static func validateContainer(_ value: SettingsMemoryValue, schema: SettingsMemorySchema, label: String) throws {
        let matches: Bool
        switch (schema.type, value) {
        case ("object", .object), ("array", .array), ("string", .string), ("boolean", .bool), ("number", .number): matches = true
        case ("integer", .number(let v)): matches = v.rounded() == v
        default: matches = false
        }
        guard matches else { throw Validation(AppStrings.memoryValidation(.invalidType, field: label)) }
        if !schema.enumValues.isEmpty, !schema.enumValues.contains(value.display) { throw Validation(AppStrings.memoryValidation(.allowedValue, field: label)) }
        if case .string(let string) = value, string.utf16.count > schema.maxLength { throw Validation(AppStrings.memoryValidation(.length, field: label, limit: String(schema.maxLength))) }
        if case .number(let number) = value {
            if let min = schema.minimum, number < min { throw Validation(AppStrings.memoryValidation(.minimum, field: label, limit: String(min))) }
            if let max = schema.maximum, number > max { throw Validation(AppStrings.memoryValidation(.maximum, field: label, limit: String(max))) }
        }
        if case .array(let items) = value, let itemSchema = schema.nestedItems.first {
            for item in items { try validateContainer(item, schema: itemSchema, label: label) }
        }
        guard let object = value.object else { return }
        for required in schema.required where object[required] == nil || object[required] == .null || object[required] == .string("") { throw Validation(AppStrings.memoryValidation(.required, field: required)) }
        for field in schema.fields {
            guard let value = object[field.name] else { continue }
            switch (field.type, value) {
            case ("string", .string), ("integer", .number), ("number", .number), ("boolean", .bool), ("object", .object), ("array", .array): break
            default: throw Validation(AppStrings.memoryValidation(.invalidType, field: field.label))
            }
            if case .number(let number) = value, field.type == "integer", number.rounded() != number { throw Validation(AppStrings.memoryValidation(.integer, field: field.label)) }
            try validate(value, field: field)
        }
    }
    struct Validation: LocalizedError { let message: String; init(_ message: String) { self.message = message }; var errorDescription: String? { message } }
}

// Keep localized error rendering on the main actor while draft data stays nonisolated.
extension AppStrings {
    enum MemoryValidationRule: String {
        case keyLength = "validation_key_length", valueLength = "validation_value_length"
        case required = "validation_required", length = "validation_length"
        case integer = "validation_integer", number = "validation_number", boolean = "validation_boolean"
        case json = "validation_json", jsonArray = "validation_json_array", jsonObject = "validation_json_object"
        case unsupportedType = "validation_unsupported_type", allowedValue = "validation_allowed_value"
        case minimum = "validation_minimum", maximum = "validation_maximum", invalidType = "validation_invalid_type"
    }
    static func memoryValidation(_ rule: MemoryValidationRule, field: String = "", limit: String = "", type: String = "") -> String {
        LocalizationManager.shared.text("settings.app_settings_memories.\(rule.rawValue)",
            replacements: ["field": field, "limit": limit, "type": type])
    }
}
