// Web source: settings/SettingsMemoriesHub.svelte, AppSettingsMemoriesCategory.svelte,
// AppSettingsMemoriesEntryDetail.svelte, AppSettingsMemoriesCreateEntry.svelte;
// stores/appSettingsMemoriesStore.ts and utils/inputValidation.ts (frontend/packages/ui/src).
// Specification: specifications/features/app-memories/specification.yml
// Assertions: app-memories.surface.semantic-parity

import Foundation

indirect enum SettingsMemoryValue: Equatable, Codable, Sendable {
    case string(String), number(Double), bool(Bool), object([String: Self]), array([Self]), null

    init(from decoder: any Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null }
        else if let v = try? c.decode(Bool.self) { self = .bool(v) }
        else if let v = try? c.decode(Double.self) { self = .number(v) }
        else if let v = try? c.decode(String.self) { self = .string(v) }
        else if let v = try? c.decode([Self].self) { self = .array(v) }
        else { self = .object(try c.decode([String: Self].self)) }
    }
    func encode(to encoder: any Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .string(let v): try c.encode(v)
        case .number(let v): try c.encode(v)
        case .bool(let v): try c.encode(v)
        case .object(let v): try c.encode(v)
        case .array(let v): try c.encode(v)
        case .null: try c.encodeNil()
        }
    }
    var object: [String: Self]? { if case .object(let v) = self { return v }; return nil }
    var string: String? { if case .string(let v) = self { return v }; return nil }
    var display: String {
        switch self {
        case .string(let v): return v
        case .bool(let v): return v ? "true" : "false"
        case .number(let v): return v.rounded() == v ? String(format: "%.0f", v) : String(v)
        case .null: return "null"
        default: return (try? json()) ?? ""
        }
    }
    func json() throws -> String {
        let encoder = JSONEncoder(); encoder.outputFormatting = [.sortedKeys, .prettyPrinted]
        return String(decoding: try encoder.encode(self), as: UTF8.self)
    }
    static func parse(_ text: String) throws -> Self { try JSONDecoder().decode(Self.self, from: Data(text.utf8)) }
    static func from(_ raw: Any) -> Self? {
        guard let data = try? JSONSerialization.data(withJSONObject: raw, options: [.fragmentsAllowed]) else { return nil }
        return try? JSONDecoder().decode(Self.self, from: data)
    }
}

struct SettingsMemoryField: Equatable {
    let name: String
    let type: String
    let description: String
    let format: String?
    let enumValues: [String]
    let defaultValue: SettingsMemoryValue?
    let minimum: Double?
    let maximum: Double?
    let maxLength: Int
    let multiline: Bool
    let autoGenerated: Bool
    let isTitle: Bool
    let isSubtitle: Bool
    let nested: SettingsMemorySchema?
    let items: SettingsMemorySchema?

    init(name: String, raw: [String: Any], path: [String] = [], order: [String: [String]] = [:]) {
        self.name = name; type = raw["type"] as? String ?? (raw["type"] == nil ? "string" : "unsupported")
        description = raw["description"] as? String ?? ""
        format = raw["format"] as? String
        enumValues = raw["enum"] as? [String] ?? []
        defaultValue = raw["default"].flatMap(SettingsMemoryValue.from)
        minimum = (raw["minimum"] as? NSNumber)?.doubleValue
        maximum = (raw["maximum"] as? NSNumber)?.doubleValue
        multiline = raw["multiline"] as? Bool ?? false
        maxLength = raw["maxLength"] as? Int ?? (multiline ? 500 : (["uri", "url"].contains(format ?? "") ? 300 : 100))
        autoGenerated = raw["auto_generated"] as? Bool ?? false
        isTitle = raw["is_title"] as? Bool ?? false; isSubtitle = raw["is_subtitle"] as? Bool ?? false
        nested = type == "object" ? SettingsMemorySchema(raw: raw, path: path, order: order) : nil
        items = (raw["items"] as? [String: Any]).map { SettingsMemorySchema(raw: $0, path: path + ["items"], order: order) }
    }
    var label: String { name.replacingOccurrences(of: "_", with: " ").prefix(1).uppercased() + String(name.replacingOccurrences(of: "_", with: " ").dropFirst()) }
}

struct SettingsMemorySchema: Equatable {
    let type: String
    let fields: [SettingsMemoryField]
    let required: [String]
    let enumValues: [String]
    let minimum: Double?
    let maximum: Double?
    let maxLength: Int
    let nestedItems: [Self]
    init(raw: [String: Any], path: [String] = [], order: [String: [String]] = [:]) {
        type = raw["type"] as? String ?? (raw["type"] == nil ? "object" : "unsupported")
        minimum = (raw["minimum"] as? NSNumber)?.doubleValue
        maximum = (raw["maximum"] as? NSNumber)?.doubleValue
        maxLength = raw["maxLength"] as? Int ?? (raw["multiline"] as? Bool == true ? 500 : (["uri", "url"].contains(raw["format"] as? String ?? "") ? 300 : 100))
        nestedItems = (raw["items"] as? [String: Any]).map { [SettingsMemorySchema(raw: $0, path: path + ["items"], order: order)] } ?? []
        required = raw["required"] as? [String] ?? []
        enumValues = raw["enum"] as? [String] ?? []
        let properties = raw["properties"] as? [String: [String: Any]] ?? [:]
        let names = order[(path + ["properties"]).joined(separator: "/")] ?? properties.keys.sorted()
        fields = names.compactMap { name in properties[name].map { SettingsMemoryField(name: name, raw: $0, path: path + ["properties", name], order: order) } }
    }
    var inputFields: [SettingsMemoryField] { fields.filter { !$0.autoGenerated && !Self.internalFields.contains($0.name) } }
    static let internalFields: Set<String> = ["embed_id", "settings_group", "_original_item_key"]
    var titleField: String? { fields.first(where: \.isTitle)?.name ?? ["name", "title", "label"].first { name in fields.contains { $0.name == name } } }
    var subtitleField: String? { fields.first(where: \.isSubtitle)?.name ?? ["proficiency", "description", "status", "type"].first { name in fields.contains { $0.name == name } } }
}

struct SettingsMemoryCategory: Identifiable, Equatable {
    let appId: String
    let appName: String
    let categoryId: String
    let categoryName: String
    let iconName: String
    let examples: [SettingsMemoryEntry]
    var description = ""
    var appIconName = ""
    var schema: SettingsMemorySchema? = nil
    var id: String { "\(appId):\(categoryId)" }
}

struct SettingsMemoryEntry: Identifiable, Equatable {
    let id: String
    let appId: String
    let categoryId: String
    var key: String
    var value: String
    let createdAt: Int
    var updatedAt: Int
    var version: Int
    let isExample: Bool
    var fields: [String: SettingsMemoryValue] = [:]
    var mentionSyntax: String { "@memory-entry:\(appId):\(categoryId):\(id)" }
    func title(in category: SettingsMemoryCategory) -> String {
        if let field = category.schema?.titleField, let v = fields[field], v != .null, !v.display.isEmpty { return v.display }
        return key.contains(".") ? key.split(separator: ".").dropFirst().joined(separator: ".") : key
    }
    func subtitle(in category: SettingsMemoryCategory) -> String? {
        category.schema?.subtitleField.flatMap { fields[$0]?.display }
    }
}

struct SettingsMemoryAppSection: Identifiable, Equatable {
    let appId: String
    let name: String
    let iconName: String
    var categories: [SettingsMemoryCategory]
    var id: String { appId }
}

enum SettingsMemoryCatalog {
    static func categoryID(appID: String, itemType: String) -> String {
        appID == "travel" && itemType == "interests" ? "preferred_activities" : itemType
    }
    static func icon(_ image: String?, fallback: String) -> String {
        let name = image?.replacingOccurrences(of: ".svg", with: "") ?? fallback
        return name == "coding" ? "code" : name == "heart" ? "health" : name
    }
    static func siblings(categories: [SettingsMemoryCategory], selected: SettingsMemoryCategory) -> (previous: SettingsMemoryCategory?, next: SettingsMemoryCategory?) {
        let siblings = categories.filter { $0.appId == selected.appId }
        guard let index = siblings.firstIndex(where: { $0.id == selected.id }) else { return (nil, nil) }
        return (index > 0 ? siblings[index - 1] : nil, index + 1 < siblings.count ? siblings[index + 1] : nil)
    }
    static func sections(categories: [SettingsMemoryCategory], entries: [SettingsMemoryEntry], authenticated: Bool) -> [SettingsMemoryAppSection] {
        var visible = categories.filter { category in
            authenticated ? entries.contains { $0.appId == category.appId && $0.categoryId == category.categoryId && !$0.isExample } : !category.examples.isEmpty
        }
        if authenticated {
            func updated(_ category: SettingsMemoryCategory) -> Int {
                entries.filter { $0.appId == category.appId && $0.categoryId == category.categoryId }.map(\.updatedAt).max() ?? 0
            }
            visible = visible.enumerated().sorted { a, b in
                let au = updated(a.element), bu = updated(b.element)
                return au == bu ? a.offset < b.offset : au > bu
            }.map(\.element)
        }
        var sections: [SettingsMemoryAppSection] = []
        for category in visible {
            if let i = sections.firstIndex(where: { $0.appId == category.appId }) { sections[i].categories.append(category) }
            else { sections.append(.init(appId: category.appId, name: category.appName, iconName: category.appIconName, categories: [category])) }
        }
        return sections
    }
}

enum SettingsMemoryRoute: Equatable {
    case hub
    case category(String, String)
    case entry(String, String, String)
    case editor(String, String, String?)
    init(path: String?) {
        let parts = (path ?? "").split(separator: "/").map(String.init)
        if let index = parts.firstIndex(of: "settings_memories"), index >= 2, parts[index - 2] == "apps", parts.count > index + 1 {
            let app = parts[index - 1], category = SettingsMemoryCatalog.categoryID(appID: app, itemType: parts[index + 1])
            if parts.count > index + 2, parts[index + 2] == "create" { self = .editor(app, category, nil) }
            else if parts.count > index + 3, parts[index + 2] == "entry" {
                self = parts.last == "edit" ? .editor(app, category, parts[index + 3]) : .entry(app, category, parts[index + 3])
            } else { self = .category(app, category) }
        } else { self = .hub }
    }
    var parent: Self {
        switch self {
        case .hub: return .hub
        case .category: return .hub
        case .entry(let app, let category, _): return .category(app, category)
        case .editor(let app, let category, let id): return id.map { .entry(app, category, $0) } ?? .category(app, category)
        }
    }
    var categoryIdentity: String? {
        switch self {
        case .hub: return nil
        case .category(let app, let category), .entry(let app, let category, _), .editor(let app, let category, _): return "\(app):\(category)"
        }
    }
}

// JSONDecoder dictionaries do not retain metadata order. Record object key order
// alongside Foundation decoding so guest apps and form fields follow the web.
struct SettingsMemoryMetadataOrder {
    private var bytes: [UInt8]
    private var cursor = 0
    private var result: [String: [String]] = [:]
    init(data: Data) { bytes = Array(data) }
    mutating func read() -> [String: [String]] { parse(path: []); return result }
    private mutating func whitespace() { while cursor < bytes.count && [9, 10, 13, 32].contains(bytes[cursor]) { cursor += 1 } }
    private mutating func quoted() -> String {
        let start = cursor; cursor += 1
        while cursor < bytes.count {
            if bytes[cursor] == 92 { cursor += 2; continue }
            if bytes[cursor] == 34 { cursor += 1; break }
            cursor += 1
        }
        return (try? JSONDecoder().decode(String.self, from: Data(bytes[start..<min(cursor, bytes.count)]))) ?? ""
    }
    private mutating func parse(path: [String]) {
        whitespace(); guard cursor < bytes.count else { return }
        switch bytes[cursor] {
        case 123:
            cursor += 1; whitespace(); var names: [String] = []
            while cursor < bytes.count && bytes[cursor] != 125 {
                guard bytes[cursor] == 34 else { return }
                let name = quoted(); names.append(name); whitespace()
                guard cursor < bytes.count && bytes[cursor] == 58 else { return }
                cursor += 1; parse(path: path + [name]); whitespace()
                if cursor < bytes.count && bytes[cursor] == 44 { cursor += 1; whitespace() } else { break }
            }
            result[path.joined(separator: "/")] = names
            if cursor < bytes.count { cursor += 1 }
        case 91:
            cursor += 1; whitespace(); var index = 0
            while cursor < bytes.count && bytes[cursor] != 93 {
                parse(path: path + [String(index)]); index += 1; whitespace()
                if cursor < bytes.count && bytes[cursor] == 44 { cursor += 1; whitespace() } else { break }
            }
            if cursor < bytes.count { cursor += 1 }
        case 34: _ = quoted()
        default:
            while cursor < bytes.count && ![9, 10, 13, 32, 44, 93, 125].contains(bytes[cursor]) { cursor += 1 }
        }
    }
}
