# todo
# - add genius for getting song lyrics https://melaniewalsh.github.io/Intro-Cultural-Analytics/04-Data-Collection/07-Genius-API.html 
# - add Musicbrainz.org for getting album, songs, artists details https://musicbrainz.org/doc/MusicBrainz_API