server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # API application logs
  - job_name: api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-logs
          __path__: /var/log/api/*.log
          # Exclude compliance log from being processed by this job
          __path_exclude__: /var/log/api/compliance.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            name: name
            request_id: request_id
            event_type: event_type
            status: status
      - labels:
          level:
          name:
          request_id:
          event_type:
          status:

  # Compliance logs - special handling for GDPR-related logs
  - job_name: compliance-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: compliance-logs
          __path__: /var/log/api/compliance.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event_type: event_type
            user_id: user_id
            status: status
      - labels:
          event_type:
          status:
