/**
 * App-store examples for the images/generate and images/generate_draft skills.
 *
 * Both skills share the same preview component (ImageGenerateEmbedPreview),
 * so examples live in one file. The `skillId` field lets the resolver filter
 * to the correct skill when rendering the app store page.
 *
 * Uses real images generated by Google Gemini 3 Pro (generate) and
 * fal.ai Flux 2 Klein (generate_draft), saved as static WebP files in
 * frontend/apps/web_app/static/store-examples/. The preview component
 * loads them via the `previewImageUrl` prop, bypassing the normal S3 +
 * AES decrypt pipeline used for real chat embeds.
 *
 * A "Sample data" banner is shown at the top of the fullscreen via the
 * is_store_example flag set by SkillExamplesSection.
 */

export interface ImageGenerateStoreExample {
  id: string;
  query: string;
  query_translation_key?: string;
  skillId: 'generate' | 'generate_draft';
  prompt: string;
  model: string;
  status: 'finished';
  previewImageUrl: string;
  results: Array<Record<string, unknown>>;
}

const examples: ImageGenerateStoreExample[] = [
  // ── images/generate (Gemini 3 Pro) ──────────────────────────────────────
  {
    "id": "store-example-images-generate-1",
    "query": "Ceramic bowls with berries",
    "query_translation_key": "settings.app_store_examples.images.generate.1",
    "skillId": "generate",
    "prompt": "Product photography of handmade ceramic bowls on a linen tablecloth, one bowl filled with fresh berries, soft natural side lighting, shallow depth of field, muted earth tones, 85mm lens look",
    "model": "google/gemini-3-pro-image-preview",
    "status": "finished",
    "previewImageUrl": "/store-examples/generate-1.webp",
    "results": []
  },
  {
    "id": "store-example-images-generate-2",
    "query": "Concrete house with mountain view",
    "query_translation_key": "settings.app_store_examples.images.generate.2",
    "skillId": "generate",
    "prompt": "Architectural photograph of a modern minimal concrete house with large glass windows reflecting a mountain landscape, golden hour lighting, clean composition, no people",
    "model": "google/gemini-3-pro-image-preview",
    "status": "finished",
    "previewImageUrl": "/store-examples/generate-2.webp",
    "results": []
  },
  {
    "id": "store-example-images-generate-3",
    "query": "Morning dew on spider web",
    "query_translation_key": "settings.app_store_examples.images.generate.3",
    "skillId": "generate",
    "prompt": "Close-up macro photograph of morning dew drops on a spider web between grass blades, bokeh background of green meadow, sunrise backlight creating rainbow refractions in each droplet",
    "model": "google/gemini-3-pro-image-preview",
    "status": "finished",
    "previewImageUrl": "/store-examples/generate-3.webp",
    "results": []
  },

  // ── images/generate_draft (Flux 2 Klein) ────────────────────────────────
  {
    "id": "store-example-images-generate-draft-1",
    "query": "Weekly meal planner illustration",
    "query_translation_key": "settings.app_store_examples.images.generate_draft.1",
    "skillId": "generate_draft",
    "prompt": "A clean flat vector illustration of a weekly meal planner pinned to a refrigerator door, with colorful sticky notes for each day showing simple food icons, warm kitchen background, soft shadows",
    "model": "bfl/flux-2-klein",
    "status": "finished",
    "previewImageUrl": "/store-examples/generate-draft-1.webp",
    "results": []
  },
  {
    "id": "store-example-images-generate-draft-2",
    "query": "Organized desk workspace",
    "query_translation_key": "settings.app_store_examples.images.generate_draft.2",
    "skillId": "generate_draft",
    "prompt": "Overhead photo of a well-organized wooden desk workspace with a laptop, a ceramic coffee mug, a small succulent plant, scattered sketches on graph paper, natural window light, shallow depth of field",
    "model": "bfl/flux-2-klein",
    "status": "finished",
    "previewImageUrl": "/store-examples/generate-draft-2.webp",
    "results": []
  },
  {
    "id": "store-example-images-generate-draft-3",
    "query": "European cobblestone street at dusk",
    "query_translation_key": "settings.app_store_examples.images.generate_draft.3",
    "skillId": "generate_draft",
    "prompt": "Watercolor painting of a small European cobblestone street at dusk, string lights between buildings, a bicycle leaning against a wall, warm amber and blue tones, loose brushstrokes",
    "model": "bfl/flux-2-klein",
    "status": "finished",
    "previewImageUrl": "/store-examples/generate-draft-3.webp",
    "results": []
  }
];

export default examples;
