import { webcrypto } from "node:crypto";
import { beforeAll, beforeEach, describe, expect, it, vi } from "vitest";

import { decryptWithEmbedKey, encryptWithEmbedKey } from "../cryptoService";
import {
  canonicalPortableRemoteCommandRequest,
  createBrowserRemoteCommandClient,
  prepareRemoteCommandApproval,
  validateRemoteCommandReview,
} from "../browserRemoteCommandClient";

const projectKey = new Uint8Array(32).fill(7);
const review = {
  protocol_version: 1 as const,
  execution_id: "execution-1",
  chat_id: "chat-1",
  project_id: "project-1",
  source_id: "source-1",
  state: "REVIEW_REQUIRED" as const,
  created_at: 100,
  review_expires_at: 700,
  review_token: "r".repeat(32),
  approval_requirement: "one_run_or_preset" as const,
  command: {
    argv: ["pnpm", "test"],
    cwd: "frontend",
    mode: "foreground" as const,
    source_access: "read_only" as const,
    deadline_ms: 60_000,
    writable_profiles: [],
    network_profile: null,
    credential_profiles: [],
  },
  explanation: {
    summary: "Run the focused tests.",
    effects: ["Reads source files."],
    risks: [],
    uncertainty: [],
  },
};

vi.mock("../projectService", () => ({
  getActiveProjectFocus: vi.fn(async () => ({
    active: true,
    project_id: "project-1",
    team_id: null,
  })),
  getProject: vi.fn(async () => ({
    project_id: "project-1",
    name: "Website",
    projectKey,
  })),
  listProjectSources: vi.fn(async () => [
    { source_id: "source-1", displayName: "Development laptop" },
  ]),
}));

beforeAll(() => {
  Object.defineProperty(globalThis, "crypto", {
    value: webcrypto,
    writable: true,
    configurable: true,
  });
});

describe("browser remote command origin client", () => {
  beforeEach(() => vi.clearAllMocks());

  // contract-test: direct surface=gui.web assertions=code-run.remote.explicit-approval,projects.files.no-server-decryption-authority
  it("encrypts the exact approved command and binds its HMAC commitment", async () => {
    const prepared = await prepareRemoteCommandApproval(review, projectKey);
    const plaintext = await decryptWithEmbedKey(
      prepared.encrypted_request as string,
      projectKey,
    );
    expect(plaintext).toBe(
      canonicalPortableRemoteCommandRequest({
        protocol_version: 1,
        execution_id: review.execution_id,
        chat_id: review.chat_id,
        project_id: review.project_id,
        source_id: review.source_id,
        policy: review.command,
        approval: { kind: "one_run" },
      }),
    );
    // Golden vector generated by the CLI portable-request implementation.
    expect(prepared.request_digest).toBe(
      "--r9K6w9j-m0Nei-o_GypSO13pORI-MfpcwoPFAottE",
    );
    expect(prepared.approval).toEqual({ kind: "one_run" });
  });

  // contract-test: direct surface=gui.web assertions=code-run.remote.explicit-approval,code-run.execution.wait-or-continue
  it("keeps a scoped terminal completion after the user switches chats", async () => {
    const sent: Array<{ event: string; payload: Record<string, unknown> }> = [];
    let activeChatId: string | null = "chat-1";
    const requestApproval = vi.fn(async (_review, labels) => {
      expect(labels).toEqual({
        projectName: "Website",
        sourceName: "Development laptop",
      });
      return true;
    });
    const client = createBrowserRemoteCommandClient({
      transport: {
        send: async (event, payload) => {
          sent.push({ event, payload });
        },
      },
      isActiveChat: (chatId) => chatId === activeChatId,
      requestApproval,
    });

    await client.review(review);
    expect(sent[0]?.event).toBe("remote_command_prepare");
    activeChatId = "chat-2";

    const encryptedEvent = await encryptWithEmbedKey(
      JSON.stringify({
        execution_id: review.execution_id,
        sequence: 0,
        event_kind: "terminal",
        status: "succeeded",
        job: { output_truncated: false },
      }),
      projectKey,
    );
    await client.event({
      ...review,
      state: "AWAITING_ORIGIN_COMPLETION",
      sequence: 0,
      event_kind: "terminal",
      status: "succeeded",
      encrypted_event: encryptedEvent,
    });

    expect(sent.at(-1)).toEqual({
      event: "remote_command_origin_completion",
      payload: {
        protocol_version: 1,
        execution_id: "execution-1",
        chat_id: "chat-1",
        project_id: "project-1",
        result_status: "succeeded",
        model_text: "",
        upstream_truncated: false,
      },
    });
    client.stop();
  });

  // contract-test: supporting surface=gui.web assertions=code-run.remote.explicit-approval
  it("rejects shell-like or parent-relative policy input before it reaches approval", () => {
    expect(() =>
      validateRemoteCommandReview({
        ...review,
        command: { ...review.command, cwd: "../private" },
      }),
    ).toThrow("invalid remote command cwd");
  });
});
