#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Travel' app          ####################
#########################################################################

name: 'Travel'
slug: 'travel'
description: |
  Plan your next trip with ease.
icon: /images/icons/apps/travel.svg
allowed: ${APP_TRAVEL_ALLOWED}
providers:
  google_maps:
    name: 'Google Maps'
    slug: 'google_maps'
    description: |
      Google Maps is a platform for finding connections between places.
    icon: /images/icons/providers/google_maps.svg
    allowed: ${APP_TRAVEL_PROVIDER_GOOGLE_MAPS_ALLOWED}
  open_trip_planner:
    name: 'Open Trip Planner'
    slug: 'open_trip_planner'
    description: |
      Open Trip Planner is a platform for finding connections between places.
    icon: /images/icons/providers/open_trip_planner.svg
    allowed: ${APP_TRAVEL_PROVIDER_OPEN_TRIP_PLANNER_ALLOWED}
skills:
  search_connections:
    name: 'Search connections'
    slug: 'search_connections'
    description: |
      Search for the best connections via train, plane and bus.
      Also considers events like extreme weather and other unexpected events.
    icon: /images/icons/skills/search.svg
    allowed: ${APP_TRAVEL_SKILL_SEARCH_CONNECTIONS_ALLOWED}
# focuses: