name_translation_key: pcb_design
description_translation_key: pcb_design.description
icon_image: |
  pcbdesign.svg
# Icon colors are defined in theme.css instead of here
category: work
last_updated: "2025-11-12"

focuses:
  - id: create_schematic
    name_translation_key: focus_modes.pcb_design_create_schematic.text
    description_translation_key: focus_modes.pcb_design_create_schematic.description
    stage: planning
      You are a PCB design expert.
  - id: create_layout
    name_translation_key: focus_modes.pcb_design_create_layout.text
    description_translation_key: focus_modes.pcb_design_create_layout.description
    stage: planning
      You are a PCB design expert.