#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Health' app          ####################
#########################################################################

name: 'Health'
slug: 'health'
description: |
  Everything to improve your health and well being.
icon: ./images/icons/apps/health.svg
allowed: ${APP_HEALTH_ALLOWED}
providers:
  doctolib:
    name: 'Doctolib'
    slug: 'doctolib'
    description: |
      Doctolib is a platform for finding doctors and booking appointments.
    icon: ./images/icons/providers/doctolib.svg
    allowed: ${APP_HEALTH_PROVIDER_DOCTOLIB_ALLOWED}
skills:
  search_doctors:
    name: 'Search doctors'
    slug: 'search_doctors'
    description: |
      Searches for doctors based on your requirements.
    icon: ./images/icons/skills/search.svg
    allowed: ${APP_HEALTH_SKILL_SEARCH_DOCTORS_ALLOWED}
  search_appointments:
    name: 'Search appointments'
    slug: 'search_appointments'
    description: |
      Searches for available appointments based on your requirements.
    icon: ./images/icons/skills/search.svg
    allowed: ${APP_HEALTH_SKILL_SEARCH_APPOINTMENTS_ALLOWED}
# focuses: