FROM python:3.13-slim

WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY setup /usr/src/app
COPY schemas /usr/src/app/schemas

RUN pip install --no-cache-dir requests pyyaml python-dotenv \
    && chmod +x setup_schemas.py

CMD ["python", "setup_schemas.py"]
