#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Photos' app          #####################
#########################################################################

name: 'Photos'
slug: 'photos'
description: |
  Generate images, modify and resize them and more.
icon: /images/icons/apps/photos.svg
allowed: ${APP_PHOTOS_ALLOWED}
providers:
  black_forest_labs:
    name: 'Black Forest Labs'
    slug: 'black_forest_labs'
    description: |
      Black Forest Labs is an AI company that models for image and video generation - some of them open source.
    icon: /images/icons/providers/black_forest_labs.svg
    allowed: ${APP_FINANCE_PROVIDER_AKAUNTING_ALLOWED}
    install_server: ${APP_FINANCE_PROVIDER_AKAUNTING_INSTALL_SERVER}
    api_url: ${APP_FINANCE_PROVIDER_AKAUNTING_API_URL}
skills:
  generate:
    name: 'Generate'
    slug: 'generate'
    description: |
      Generate an image using AI.
    icon: /images/icons/skills/generate_image_ai.svg
    allowed: ${APP_PHOTOS_SKILL_GENERATE_ALLOWED}
    default_provider_slug: ${APP_PHOTOS_SKILL_GENERATE_DEFAULT_PROVIDER_SLUG}
  resize:
    name: 'Resize'
    slug: 'resize'
    description: |
      Scale or crop an existing image to a higher or lower resolution.
      Can also use AI upscaling for even better results.
    icon: /images/icons/skills/resize.svg
    allowed: ${APP_PHOTOS_SKILL_RESIZE_ALLOWED}
# focuses: