// Auth-free DEBUG recipient proof for the real short-link resolver and import
// panel. It decrypts synthetic opaque bytes locally and never calls the API.

#if DEBUG
import CryptoKit
import SwiftUI

private enum WorkflowShortTemplateFixtureError: Error { case invalidFixture }

@MainActor
private final class WorkflowShortTemplatePreviewModel: ObservableObject {
    @Published private(set) var link: WorkflowTemplateLink?
    @Published private(set) var payload: WorkflowTemplatePayload?
    @Published private(set) var failed = false

    private final class EncryptedFixture {
        var token = ""
        var ciphertext = ""
    }

    private static let devToken = "a8f3kLmN"
    private static let devShortKey = String(repeating: "A", count: 22)
    // Independently generated by web WebCrypto with a synthetic URL and key.
    private static let devCiphertext = "AAECAwQFBgcICQoLXoveq1_KbaiLstq8NZe9eCWpW_sCsm-6v0Se1GfAjVT05g4bISj1S6DU_8WvOexTo7B3kJWtr-zMkesbJ3kVRwH9gl3QS3m-mNFiRfsAcpS29naCwZPBV_CeMURKac4iNmQVETSayeFrYLfTU6bGDHlevXUUZlcuDQy60bStHhs"
    private static let projectionKey = String(repeating: "A", count: 43)

    private let fixture: EncryptedFixture
    private let handler: DeepLinkHandler
    private var started = false

    init() {
        let fixture = EncryptedFixture()
        self.fixture = fixture
        handler = DeepLinkHandler(shortLinkResolver: { link, _ in
            guard link.token == fixture.token else { throw WorkflowShortTemplateFixtureError.invalidFixture }
            return try await ShareLinkCrypto.decryptShortURL(
                fixture.ciphertext, token: link.token, shortKey: link.fragmentKey
            )
        })
    }

    func start() async {
        guard !started else { return }
        started = true
        do {
            let profile = ServerProfile.current()
            let token: String
            let shortKey: String
            if profile.displayDomain == "app.dev.openmates.org" {
                token = Self.devToken
                shortKey = Self.devShortKey
                fixture.ciphertext = Self.devCiphertext
            } else {
                let target = try ShareLinkCrypto.urlWithFragment(
                    profile.webBaseURL.appendingPathComponent("share/workflow-template/wt_fixture"),
                    fragment: "key=\(Self.projectionKey)"
                )
                let encrypted = try await ShareLinkCrypto.encryptedShortURL(target)
                token = encrypted.token
                shortKey = encrypted.shortKey
                fixture.ciphertext = encrypted.encryptedURL
            }
            fixture.token = token
            let shortURL = try ShareLinkCrypto.shortURL(
                webURL: profile.webBaseURL, token: token, shortKey: shortKey
            )
            handler.handle(url: shortURL)
            await handler.shortLinkResolutionTask?.value
            guard !handler.pendingShortLinkError,
                  let link = handler.pendingWorkflowTemplate,
                  link.templateID == "wt_fixture",
                  let key = Data(base64URLEncoded: link.fragmentKey), key.count == 32 else {
                throw WorkflowShortTemplateFixtureError.invalidFixture
            }
            let encryptedProjection = try WorkflowTemplateProjection.encrypt(
                Self.projection, key: SymmetricKey(data: key)
            )
            let opened = try WorkflowTemplateProjection.decrypt(
                ciphertext: encryptedProjection.ciphertext,
                checksum: encryptedProjection.checksum,
                fragmentKey: link.fragmentKey
            )
            self.link = link
            payload = opened
        } catch {
            failed = true
        }
    }

    private static var projection: WorkflowTemplatePayload {
        let schedule = WorkflowTemplateNode(
            id: "schedule", type: .scheduleTrigger, title: "Every morning",
            config: ["schedule": AnyCodable(["type": "daily", "time": "09:00", "timezone": "Europe/Berlin"])]
        )
        let forecast = WorkflowTemplateNode(
            id: "forecast", type: .appSkillAction, title: "Get forecast",
            config: ["app_id": AnyCodable("weather"), "skill_id": AnyCodable("forecast"),
                     "input": AnyCodable(["location": "Berlin"])]
        )
        let message = WorkflowTemplateNode(
            id: "message", type: .sendChatMessage, title: "Morning update",
            config: ["title": AnyCodable("Morning update"),
                     "message": AnyCodable("Today's forecast is ready.")]
        )
        return WorkflowTemplatePayload(
            templateVersion: 2,
            title: "Weekly AI events",
            description: "A portable sample workflow.",
            triggerTemplate: schedule,
            nodeTemplates: [forecast, message],
            edgeTemplates: [WorkflowEdge(from: "schedule", to: "forecast", branch: nil),
                            WorkflowEdge(from: "forecast", to: "message", branch: nil)],
            variablesSchema: [:],
            requiredCapabilities: ["weather", "weather.forecast"],
            bindingRequirements: [
                WorkflowTemplateBindingRequirement(type: "schedule", nodeId: "schedule", appId: nil, skillId: nil),
                WorkflowTemplateBindingRequirement(type: "app_skill", nodeId: "forecast", appId: "weather", skillId: "forecast")
            ]
        )
    }
}

struct WorkflowShortTemplatePreviewHost: View {
    @StateObject private var model = WorkflowShortTemplatePreviewModel()

    var body: some View {
        ScrollView {
            if let link = model.link, let payload = model.payload {
                WorkflowTemplateImportPanel(
                    templateId: link.templateID, fragmentKey: link.fragmentKey,
                    accountId: "workflow-preview", previewPayload: payload
                )
                .frame(maxWidth: 680)
                .padding(.spacing5)
            } else if model.failed {
                Text(AppStrings.error)
                    .foregroundStyle(Color.error)
                    .accessibilityIdentifier("workflow-short-template-error")
            } else {
                ProgressView()
                    .accessibilityIdentifier("workflow-short-template-loading")
            }
        }
        .task { await model.start() }
    }
}
#endif
