#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
#################          'Messages' app          ######################
#########################################################################


name: 'Messages'
slug: 'messages'
description: 'Send messages, create threads and more.'
icon: /images/icons/apps/messages.svg
allowed: ${APP_MESSAGES_ALLOWED}
providers:
  discord:
    name: 'Discord'
    slug: 'discord'
    description: 'Discord is a communication platform that runs in the web browser.'
    icon: /images/icons/providers/discord.svg
    allowed: ${APP_MESSAGES_PROVIDER_DISCORD_ALLOWED}
    bots:
      burton:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_BURTON_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_BURTON_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_BURTON_TOKEN}
      sophia:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_SOPHIA_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_SOPHIA_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_SOPHIA_TOKEN}
      mark:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MARK_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MARK_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MARK_TOKEN}
      elton:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_ELTON_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_ELTON_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_ELTON_TOKEN}
      finn:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_FINN_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_FINN_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_FINN_TOKEN}
      grace:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_GRACE_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_GRACE_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_GRACE_TOKEN}
      leon:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_LEON_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_LEON_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_LEON_TOKEN}
      priscilla:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_PRISCILLA_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_PRISCILLA_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_PRISCILLA_TOKEN}
      selma:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_SELMA_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_SELMA_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_SELMA_TOKEN}
      makani:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MAKANI_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MAKANI_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MAKANI_TOKEN}
      monika:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MONIKA_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MONIKA_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MONIKA_TOKEN}
      melvin:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MELVIN_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MELVIN_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_MELVIN_TOKEN}
      lisa:
        client_id: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_LISA_CLIENT_ID}
        oauth_url: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_LISA_OAUTH_URL}
        token: ${APP_MESSAGES_PROVIDER_DISCORD_BOTS_LISA_TOKEN}
  slack:
    name: 'Slack'
    slug: 'slack'
    description: 'Slack is a communication platform that runs in the web browser.'
    icon: /images/icons/providers/slack.svg
    allowed: ${APP_MESSAGES_PROVIDER_SLACK_ALLOWED}
    bots:
      sophia:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_SOPHIA_TOKEN}
      mark:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_MARK_TOKEN}
      elton:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_ELTON_TOKEN}
      finn:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_FINN_TOKEN}
      grace:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_GRACE_TOKEN}
      leon:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_LEON_TOKEN}
      priscilla:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_PRISCILLA_TOKEN}
      selma:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_SELMA_TOKEN}
      makani:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_MAKANI_TOKEN}
      monika:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_MONIKA_TOKEN}
      melvin:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_MELVIN_TOKEN}
      lisa:
        token: ${APP_MESSAGES_PROVIDER_SLACK_BOTS_LISA_TOKEN}
skills:
  send:
    name: 'Send'
    slug: 'send'
    description: 'Send a new message to a channel or thread.'
    icon: /images/icons/skills/create.svg
    allowed: ${APP_MESSAGES_SKILL_SEND_ALLOWED}
  connect:
    name: 'Connect'
    slug: 'connect'
    description: 'Connect a third party messenger. Allows you to chat with your AI team mates in that messenger.'
    icon: /images/icons/skills/connect.svg
    allowed: ${APP_MESSAGES_SKILL_CONNECT_ALLOWED}
# focuses: