name: |
  Health
description: |
  Everything to improve your health and well being.
icon_image: |
  heart.svg
icon_colorgradient:
  start: |
    #FD50A0
  end: |
    #F42C2D

# IMPORTANT NOTE: only start implementing app user settings & memories for health app once end to end encryption is implemented for storing
# settings_and_memories:
#   - id: |
#       recent_doctor_visits
#     name: |
#       Recent doctor visits
#     description: |
#       Details about your recent doctor visits.
#     type: list
#     schema:
#       type: object
#       properties:
#         doctor_name: { type: string, description: "Name of the doctor" }
#         visit_date: { type: string, format: date, description: "YYYY-MM-DD" }
#         notes: { type: string, description: "Additional notes from the visit" }
#       required: [doctor_name, visit_date]
#   - id: |
#      upcoming_appointments
#   - id: |
#      syptoms_history

skills:

  - id: |
      search_appointments
    name: |
      Search appointments
    description: |
      Searches for available doctor appointments based on your requirements.
    stage: |
      planning
    class_path: |
      skills.search_appointments.SearchAppointmentsSkill
    providers:
      - Jameda
      - Doctolib

  - id: |
      create_report
    name: |
      Create report
    description: |
      Create a report for the next doctor visit.

focuses:

  - id: |
      prepare_doctor_report
    name: |
      Prepare doctor report
    description: |
      Asks clearifying questions to then create a report for the next doctor appointment.
      Including symptoms overview, previous doctor visits, previous tests and results 
      (including links or QR codes and access instructions to access them) and data 
      from health tracking / fitness tracking devices (Apple Watch for example).

  - id: |
      health_insights
    name: |
      Health insights
    description: |
      Get general health insights tailored to your questions, using multiple rounds
      of questions. Will also help you to find out which doctor to consult for advice
    stage: |
      planning
    process:
      - ""
    # systemprompt just an early placeholder. Nowhere near complete.
    systemprompt: |
      You are a health expert.

  - id: |
      prepare_doctor_appointment
    name: |
      Prepare doctor appointment
    description: |
      Prepare your next appointment, by discussing what symptoms & tests you should ask your doctor about and what previous test results to bring.
    stage: |
      planning
    process:
      - "discusses what symptoms one had in recent weeks and months, even if one doesn’t see connections between them"
      - "discusses what test results / documents one should collect before the next appointment"
    # systemprompt just an early placeholder. Nowhere near complete.
    systemprompt: |
      You are a health expert.