---
- name: Get server's public IP
  set_fact:
    server_ip: "{{ ansible_default_ipv4.address }}"

- name: Debug server_ip
  debug:
    msg: "Server IP is set to: {{ server_ip }}"

- name: Get domain IP from DNS
  command: "dig +short {{ domain_name }} A"
  register: domain_ip
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  become: false

- name: Extract IP from dig output
  set_fact:
    resolved_ip: "{{ domain_ip.stdout_lines[0] | default('') }}"

- name: Log successful DNS configuration
  debug:
    msg: "DNS check successful: {{ domain_name }} is correctly pointing to {{ server_ip }}"
  when: resolved_ip == server_ip

- name: Handle incorrect DNS configuration
  block:
    - name: Log DNS update requirement
      debug:
        msg: |
          ACTION REQUIRED: Please update your DNS records
          Add an A record for {{ domain_name }} pointing to {{ server_ip }}
          Current DNS resolves to: {{ resolved_ip if resolved_ip else 'no IP' }}
    
    - name: Wait for DNS propagation
      command: "dig +short {{ domain_name }} A"
      register: dns_check
      until: dns_check.stdout_lines[0] | default('') == server_ip
      retries: "{{ dns_check_retries | default(40) }}"
      delay: "{{ dns_check_delay | default(15) }}"
      changed_when: false
      delegate_to: "{{ inventory_hostname }}"
      become: false
  when: resolved_ip != server_ip

- name: Set default DNS check retries and delay
  set_fact:
    dns_check_retries: 40
    dns_check_delay: 15
  when: dns_check_retries is not defined or dns_check_delay is not defined