---
# server/deployment/ansible/roles/dns_check/tasks/main.yml

- name: Get server's public IP
  set_fact:
    server_ip: "{{ ansible_host }}"

- name: Retrieve all application subdomains
  set_fact:
    app_subdomains: "{{ applications | dict2items | map(attribute='value.subdomain') | list }}"

- name: Check DNS records for each subdomain
  block:
    - name: Get subdomain IP from DNS
      command: "dig +short {{ item }} A"
      register: subdomain_ip
      changed_when: false
      delegate_to: localhost
      become: false

    - name: Log DNS configuration status
      debug:
        msg: "DNS check for {{ item }}: {{ subdomain_ip.stdout_lines[0] if subdomain_ip.stdout_lines[0] else 'no IP' }}"

    - name: Log DNS configuration requirement if incorrect
      debug:
        msg: |
          ACTION REQUIRED: Please update your DNS records
          Add an A record for {{ item }} pointing to {{ server_ip }}
          Current DNS resolves to: {{ subdomain_ip.stdout_lines[0] if subdomain_ip.stdout_lines[0] else 'no IP' }}
      when: subdomain_ip.stdout_lines[0] != server_ip

    - name: Wait for DNS propagation
      command: "dig +short {{ item }} A"
      register: dns_check
      until: dns_check.stdout_lines[0] == server_ip
      retries: "{{ dns_check_retries }}"
      delay: "{{ dns_check_delay }}"
      changed_when: false
      delegate_to: localhost
      become: false
      when: subdomain_ip.stdout_lines[0] != server_ip

  loop: "{{ app_subdomains }}"