import type { DemoChat } from "../types";

/**
 * Newsletter demo chat — april-2026-first-update
 * Kind: announcements (derived from meta.yml category "updates_and_announcements")
 * Generated by backend/scripts/publish_newsletter.py — edits will be
 * overwritten next time the publisher runs on this slug.
 */
export const announcementsApril2026FirstUpdateChat: DemoChat = {
  chat_id: "announcements-april-2026-first-update",
  slug: "april-2026-first-update",
  title: "demo_chats.announcements_april_2026_first_update.title",
  description: "demo_chats.announcements_april_2026_first_update.description",
  keywords: [
    "OpenMates",
    "newsletter",
    "announcements",
  ],
  messages: [
    {
      id: "announcements-april-2026-first-update-1",
      role: "assistant",
      content: "demo_chats.announcements_april_2026_first_update.message",
      timestamp: new Date().toISOString(),
    },
  ],
  metadata: {
    category: "openmates_official",
    icon_names: ['megaphone', 'sparkles'],
    featured: false,
    order: 100,
    lastUpdated: new Date().toISOString(),

  },
};
