import type { DemoChat } from "../types";

/**
 * Newsletter demo chat — referral-feature-launch
 * Kind: announcements (derived from meta.yml category "updates_and_announcements")
 * Generated by backend/scripts/publish_newsletter.py — edits will be
 * overwritten next time the publisher runs on this slug.
 */

export const announcementsReferralFeatureLaunchChat: DemoChat = {
  chat_id: "announcements-referral-feature-launch",
  slug: "referral-feature-launch",
  title: "demo_chats.announcements_referral_feature_launch.title",
  description: "demo_chats.announcements_referral_feature_launch.description",
  keywords: [
    "OpenMates",
    "newsletter",
    "announcements",
  ],
  messages: [
    {
      id: "announcements-referral-feature-launch-1",
      role: "assistant",
      content: "demo_chats.announcements_referral_feature_launch.message",
      timestamp: new Date().toISOString(),
    },
  ],
  metadata: {
    category: "openmates_official",
    icon_names: ['megaphone', 'sparkles'],
    featured: false,
    order: 100,
    lastUpdated: new Date().toISOString(),
    publishedAt: "2026-05-28T12:28:19+00:00",

  },
};
