import type { DemoChat } from "../types";

/**
 * Newsletter demo chat — introducing-openmates-v010
 * Kind: announcements (derived from meta.yml category "updates_and_announcements")
 * Generated by backend/scripts/publish_newsletter.py — edits will be
 * overwritten next time the publisher runs on this slug.
 */

export const announcementsIntroducingOpenmatesV010Chat: DemoChat = {
  chat_id: "announcements-introducing-openmates-v010",
  slug: "introducing-openmates-v010",
  title: "demo_chats.announcements_introducing_openmates_v010.title",
  description: "demo_chats.announcements_introducing_openmates_v010.description",
  keywords: [
    "OpenMates",
    "newsletter",
    "announcements",
  ],
  messages: [
    {
      id: "announcements-introducing-openmates-v010-1",
      role: "assistant",
      content: "demo_chats.announcements_introducing_openmates_v010.message",
      timestamp: new Date().toISOString(),
    },
  ],
  metadata: {
    category: "openmates_official",
    icon_names: ['megaphone', 'sparkles'],
    featured: false,
    order: 100,
    lastUpdated: new Date().toISOString(),
    publishedAt: "2026-05-04T17:35:46+00:00",

  },
};
