import type { DemoChat } from "../types";
import { OPENMATES_VIDEOS } from "./videos";

/**
 * Newsletter demo chat — introducing-openmates-v09
 * Kind: announcements (derived from meta.yml category "updates_and_announcements")
 * Generated by backend/scripts/publish_newsletter.py — edits will be
 * overwritten next time the publisher runs on this slug.
 */

// Uses the intro video until a dedicated announcement video is uploaded
const video = OPENMATES_VIDEOS["intro-en"];

export const announcementsIntroducingOpenmatesV09Chat: DemoChat = {
  chat_id: "announcements-introducing-openmates-v09",
  slug: "introducing-openmates-v09",
  title: "demo_chats.announcements_introducing_openmates_v09.title",
  description: "demo_chats.announcements_introducing_openmates_v09.description",
  keywords: [
    "OpenMates",
    "newsletter",
    "announcements",
  ],
  messages: [
    {
      id: "announcements-introducing-openmates-v09-1",
      role: "assistant",
      content: "demo_chats.announcements_introducing_openmates_v09.message",
      timestamp: new Date().toISOString(),
    },
  ],
  metadata: {
    category: "openmates_official",
    icon_names: ['megaphone', 'sparkles'],
    featured: false,
    order: 100,
    lastUpdated: new Date().toISOString(),
    video_key: "intro",
    video_hls_url: video.hls_url,
    video_mp4_url: video.mp4_url,
    video_thumbnail_url: video.thumbnail_url,
    video_start_time: video.start_time,
    background_frames: video.background_frames,
  },
};
