name_translation_key: social_media.text
description_translation_key: social_media.description.text
icon_image: |
  social_media.svg
category: work
last_updated: '2025-11-17'


focuses:
  - id: content_calendar_strategist
    name_translation_key: social_media.content_calendar_strategist.text
    description_translation_key: social_media.content_calendar_strategist.description.text
    stage: planning
    systemprompt_translation_key: social_media.content_calendar_strategist.systemprompt.text
