# backend/apps/pdf/app.yml
#
# App configuration for the PDF processor.
#
# Architecture:
#   PDFs uploaded by the user are processed in background by app-pdf-worker:
#     - Mistral OCR extracts markdown text + embedded images per page
#     - pymupdf renders page screenshots at 150 DPI
#     - Groq gpt-oss-20b detects table of contents and legends via tool use
#
#   Three skills let the LLM interact with processed PDFs:
#     - pdf.read  : load raw page markdown (up to 50K tokens)
#     - pdf.search: text search across all page markdowns
#     - pdf.view  : vision analysis of page screenshots via Gemini Flash

name_translation_key: pdf
description_translation_key: pdf.description
icon_image: |
  pdf.svg
category: work
last_updated: "2026-02-20"

skills:
  - id: read
    name_translation_key: pdf.read
    description_translation_key: pdf.read.description
    preprocessor_hint: >
      Load and read the raw text content (markdown) of specific pages from an uploaded
      PDF document. Use when the user asks what a PDF says, wants you to summarise
      sections, or requests information that is likely textual (paragraphs, tables,
      headings). The embed TOON content includes a TOC and per-page token estimates —
      use them to select the most relevant pages. Limits output to 50 000 tokens; call
      again for remaining pages if needed.
    stage: development
    class_path: |
      backend.apps.pdf.skills.read_skill.ReadSkill
    api_config:
      expose_get: false
    tool_schema:
      type: object
      properties:
        embed_id:
          type: string
          description: "The embed_id of the uploaded PDF."
        vault_wrapped_aes_key:
          type: string
          description: "Vault Transit-wrapped AES key from the embed metadata."
        ocr_data_s3_key:
          type: string
          description: "S3 key for the encrypted OCR JSON blob produced during background processing."
        s3_base_url:
          type: string
          description: "S3 base URL for the file storage bucket."
        aes_nonce:
          type: string
          description: "Base64 AES-GCM nonce."
        pages:
          type: array
          description: "1-indexed page numbers to read (e.g. [1, 2, 3]). If omitted, reads from page 1."
          items:
            type: integer
        vault_key_id:
          type: string
          description: "The user's Vault Transit key ID (optional, resolved from context)."
      required:
        - embed_id
        - vault_wrapped_aes_key
        - ocr_data_s3_key
        - s3_base_url
        - aes_nonce

  - id: search
    name_translation_key: pdf.search
    description_translation_key: pdf.search.description
    preprocessor_hint: >
      Search for specific text, keywords, or phrases across all pages of an uploaded PDF.
      Returns matching text blocks with surrounding context and page numbers.
      Use when the user asks to find where something is mentioned in the document,
      or when a targeted keyword search is faster than reading entire sections.
      No LLM call required — pure text search over the OCR data.
    stage: development
    class_path: |
      backend.apps.pdf.skills.search_skill.SearchSkill
    api_config:
      expose_get: false
    tool_schema:
      type: object
      properties:
        embed_id:
          type: string
          description: "The embed_id of the uploaded PDF."
        vault_wrapped_aes_key:
          type: string
          description: "Vault Transit-wrapped AES key from the embed metadata."
        ocr_data_s3_key:
          type: string
          description: "S3 key for the encrypted OCR JSON blob."
        s3_base_url:
          type: string
          description: "S3 base URL for the file storage bucket."
        aes_nonce:
          type: string
          description: "Base64 AES-GCM nonce."
        query:
          type: string
          description: "The search query string (case-insensitive substring match)."
        context_chars:
          type: integer
          description: "Number of characters of surrounding context to include per match (default: 200)."
        vault_key_id:
          type: string
          description: "The user's Vault Transit key ID (optional, resolved from context)."
      required:
        - embed_id
        - vault_wrapped_aes_key
        - ocr_data_s3_key
        - s3_base_url
        - aes_nonce
        - query

  - id: view
    name_translation_key: pdf.view.skill_name
    description_translation_key: pdf.view.skill_description
    preprocessor_hint: >
      View one or more page screenshots from an uploaded PDF using vision AI (Gemini Flash).
      Use when the user asks about the visual layout, diagrams, charts, figures, or images
      on specific pages. Also useful when text OCR may have been imperfect (e.g. complex
      tables, mathematical notation, handwriting). Up to 5 pages can be viewed per call.
    stage: development # Hidden from app store; LLM uses this for visual page analysis
    class_path: |
      backend.apps.pdf.skills.view_skill.ViewSkill
    api_config:
      expose_get: false
    tool_schema:
      type: object
      properties:
        embed_id:
          type: string
          description: "The embed_id of the uploaded PDF."
        vault_wrapped_aes_key:
          type: string
          description: "Vault Transit-wrapped AES key from the embed metadata."
        screenshot_s3_keys:
          type: object
          description: >
            Map of 1-indexed page numbers (as strings) to S3 keys for encrypted page screenshots.
            From the embed TOON content. Example: {\"1\": \"chatfiles/.../page_1.bin\"}.
        s3_base_url:
          type: string
          description: "S3 base URL for the file storage bucket."
        aes_nonce:
          type: string
          description: "Base64 AES-GCM nonce."
        pages:
          type: array
          description: "1-indexed page numbers to view (max 5). Example: [1, 2]."
          items:
            type: integer
        query:
          type: string
          description: "The user's question or instruction about the page(s)."
        vault_key_id:
          type: string
          description: "The user's Vault Transit key ID (optional, resolved from context)."
      required:
        - embed_id
        - vault_wrapped_aes_key
        - screenshot_s3_keys
        - s3_base_url
        - aes_nonce
        - pages
        - query
