# Dockerfile
FROM mcr.microsoft.com/playwright:v1.47.0-focal

# Install pip
RUN apt-get update && apt-get install -y python3-pip

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Set the working directory
WORKDIR /usr/src/app_web

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Use the entrypoint script to start Uvicorn
ENTRYPOINT ["/entrypoint.sh"]