#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Home' app          ####################
#########################################################################

name: 'Home'
slug: 'home'
description: 'Control your smart home, organize daily tasks and more.'
icon: /images/icons/apps/home.svg
allowed: ${APP_HOME_ALLOWED}
providers:
  mosquitto:
    name: 'Mosquitto'
    slug: 'mosquitto'
    description: 'Mosquitto is an open-source message broker for MQTT - to control your smart home devices.'
    icon: /images/icons/providers/mosquitto.svg
    allowed: ${APP_HOME_PROVIDER_MOSQUITTO_ALLOWED}
    install_server: ${APP_HOME_PROVIDER_MOSQUITTO_INSTALL_SERVER}