// frontend/packages/ui/src/demo_chats/data/example_chats/audio-speak-welcome-message.ts
//
// Example chat: Generate a Spoken Welcome Message
// Extracted from shared chat 3ec7bc42-238c-4a1d-8fc2-b318cb0bff44
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const audioSpeakWelcomeMessageChat: ExampleChat = {
  chat_id: "example-audio-speak-welcome-message",
  slug: "audio-speak-welcome-message",
  title: "example_chats.audio_speak_welcome_message.title",
  summary: "example_chats.audio_speak_welcome_message.summary",
  icon: "volume2",
  category: "design",
  keywords: ["text to speech", "ElevenLabs", "speech generation", "voice narration", "OpenMates apps"],
  follow_up_suggestions: ["example_chats.audio_speak_welcome_message.follow_up_1", "example_chats.audio_speak_welcome_message.follow_up_2", "example_chats.audio_speak_welcome_message.follow_up_3", "example_chats.audio_speak_welcome_message.follow_up_4", "example_chats.audio_speak_welcome_message.follow_up_5", "example_chats.audio_speak_welcome_message.follow_up_6"],
  
  messages: [
    {
        "id": "31b4d8c3-2275-4d4a-9524-afa4db0ce1fa",
        "role": "user",
        "content": "example_chats.audio_speak_welcome_message.message_1",
        "created_at": 1786382241
    },
    {
        "id": "788e47e2-6f0b-5a4b-9230-b906f6da09b3",
        "role": "assistant",
        "content": "example_chats.audio_speak_welcome_message.message_2",
        "created_at": 1786382255,
        "user_message_id": "31b4d8c3-2275-4d4a-9524-afa4db0ce1fa",
        "response_credits": 18,
        "category": "onboarding_support",
        "model_name": "Gemini 3.5 Flash-Lite"
    }
],
  embeds: [
    {
        "embed_id": "96260d6f-9258-4de5-bfcd-f579951e93f5",
        "type": "app_skill_use",
        "content": "app_id: audio\nskill_id: speak\nresults[1]{id,status,text_preview,generation_type,voice,accent,style,provider,model,mime_type,duration_seconds,byte_length,credits_charged,error}:\n  1,finished,Welcome back to OpenMates. Your morning briefing is ready.,speech,warm_neutral,en_us,natural,ElevenLabs,eleven_flash_v2_5,audio/mpeg,3.631,58140,3,null\nresult_count: 1\nstatus: finished\nembed_ref: speak-rNM\ntext: Welcome back to OpenMates. Your morning briefing is ready.",
        "parent_embed_id": null,
        "embed_ids": null
    }
],
  usage_entries: [
    {
        "id": "example-audio-speak-welcome-message-usage-1",
        "type": "skill_execution",
        "source": "chat",
        "app_id": "ai",
        "skill_id": "ask",
        "model_used": "google/gemini-3.5-flash-lite",
        "credits": 18,
        "input_tokens": 19599,
        "output_tokens": 69,
        "user_input_tokens": 181,
        "system_prompt_tokens": 9066,
        "server_provider": "Google AI Studio",
        "server_region": "US",
        "chat_id": "example-audio-speak-welcome-message",
        "message_id": "31b4d8c3-2275-4d4a-9524-afa4db0ce1fa",
        "created_at": 1786382249,
        "updated_at": 1786382249,
        "tool_inference_iterations": 1
    }
],
  metadata: {
    featured: true,
    order: 124,
    app_skill_examples: ["audio.speak"],
  },
};
