// frontend/packages/ui/src/demo_chats/data/example_chats/audio-transcribe-voice-note.ts
//
// Example chat: Transcribe a voice note
// Extracted from shared chat 8c07f077-d93e-40f9-a7bd-f93b54b7667a
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const audioTranscribeVoiceNoteChat: ExampleChat = {
  chat_id: "example-audio-transcribe-voice-note",
  slug: "audio-transcribe-voice-note",
  title: "example_chats.audio_transcribe_voice_note.title",
  summary: "example_chats.audio_transcribe_voice_note.summary",
  icon: "search",
  category: "general_knowledge",
  keywords: ["audio transcription", "voice notes", "command line", "OpenMates"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "869f5db0-7377-44c9-8b6b-38181fd844c3",
        "role": "user",
        "content": "example_chats.audio_transcribe_voice_note.message_1",
        "created_at": 1780930924
    },
    {
        "id": "4a500d37-5207-4e84-9119-2756c886905c",
        "role": "assistant",
        "content": "example_chats.audio_transcribe_voice_note.message_2",
        "created_at": 1780930954,
        "category": "general_knowledge",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [
    {
        "embed_id": "4e7bca90-2a2a-4cf2-b773-ac5b3a4dc40b",
        "type": "audio-recording",
        "content": "app_id: audio\nskill_id: transcribe\ntype: audio-recording\nstatus: finished\nfilename: openmates-audio-transcribe-example.wav\nmime_type: audio/wav\ntranscript: OpenMates can transcribe short voice notes from the command line.\ntranscript_original: OpenMates can transcribe short voice notes from the command line.\ntranscript_corrected: OpenMates can transcribe short voice notes from the command line.\nuse_corrected: true\ncorrection_model: gemini-3.5-flash\nmodel: voxtral-mini-2602\ns3_base_url: \"https://dev-openmates-chatfiles.nbg1.your-objectstorage.com\"\nfiles:\n  original:\n    s3_key: 8881f651-dcaf-4809-8f06-a8e8796f7486/e52654f8ba9eea7c32524208f13198bf45083e1d8a2f75618b7ec798181e40ae/20260608_145944_original.bin\n    width: 0\n    height: 0\n    size_bytes: 132254\n    format: wav\naes_key: wo45Y0LHY4oYnKyiuQG57psEXk8PT5Tnn5eGBvsRFFo=\naes_nonce: pBkYfmWsXTi9FC8y\nvault_wrapped_aes_key: \"vault:v1:dNFQaRdHr76RWBCk7ww01J081afJFDpiEjrKbanHGXHlhLNu1DaUZSKztGgzdciGYtMCTNyXK7c8wyHwDjWyp8gKZJcaTSwC\"",
        "parent_embed_id": null,
        "embed_ids": null
    }
],
  metadata: {
    featured: true,
    order: 46,
    app_skill_examples: ["audio.transcribe"],
  },
};
