// frontend/packages/ui/src/demo_chats/data/example_chats/autumn-basil-balcony-care.ts
//
// Example chat: Autumn Basil Care on a Berlin Balcony
// Extracted from shared chat 2f792162-80a3-4a6d-8a13-a4c40d806833
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const autumnBasilBalconyCareChat: ExampleChat = {
  chat_id: "example-autumn-basil-balcony-care",
  slug: "autumn-basil-balcony-care",
  title: "example_chats.autumn_basil_balcony_care.title",
  summary: "example_chats.autumn_basil_balcony_care.summary",
  icon: "sprout",
  category: "science",
  keywords: ["basil care", "balcony gardening", "Berlin autumn", "plant care guide"],
  follow_up_suggestions: ["example_chats.autumn_basil_balcony_care.follow_up_1", "example_chats.autumn_basil_balcony_care.follow_up_2", "example_chats.autumn_basil_balcony_care.follow_up_3", "example_chats.autumn_basil_balcony_care.follow_up_4", "example_chats.autumn_basil_balcony_care.follow_up_5", "example_chats.autumn_basil_balcony_care.follow_up_6"],

  messages: [
    {
        "id": "f83632d8-a7f7-494a-946c-9c982f8bcb2d",
        "role": "user",
        "content": "example_chats.autumn_basil_balcony_care.message_1",
        "created_at": 1791558993
    },
    {
        "id": "eafd61f7-e9e9-57fc-bdd5-093a294b464e",
        "role": "assistant",
        "content": "example_chats.autumn_basil_balcony_care.message_2",
        "created_at": 1791558994,
        "user_message_id": "f83632d8-a7f7-494a-946c-9c982f8bcb2d",
        "category": "science",
        "model_name": "Gemini 3.8 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 138,
  },
};
