// frontend/packages/ui/src/demo_chats/data/example_chats/berlin-rain-radar-next-10-minutes.ts
//
// Example chat: Berlin Rain Radar for the Next 10 Minutes
// Extracted from shared chat eb198e72-9dde-4b15-8683-288504d7714d
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const berlinRainRadarNext10MinutesChat: ExampleChat = {
  chat_id: "example-berlin-rain-radar-next",
  slug: "berlin-rain-radar-next-10-minutes",
  title: "example_chats.berlin_rain_radar_next_10_minutes.title",
  summary: "example_chats.berlin_rain_radar_next_10_minutes.summary",
  icon: "weather",
  category: "general_knowledge",
  keywords: ["Berlin rain radar", "DWD weather", "short-term rain forecast", "weather app", "rain in 10 minutes"],
  follow_up_suggestions: [],
  messages: [
    {
      id: "4ae4309a-6f6e-420c-a5f4-29af8816f724",
      role: "user",
      content: "example_chats.berlin_rain_radar_next_10_minutes.message_1",
      created_at: 1781458405,
    },
    {
      id: "d4943f88-877d-4201-8d12-335d520cd610",
      role: "assistant",
      content: "example_chats.berlin_rain_radar_next_10_minutes.message_2",
      created_at: 1781458435,
      category: "general_knowledge",
      model_name: "Gemini 3 Flash",
    },
  ],
  embeds: [
    {
      embed_id: "935fef42-7368-4449-9309-f632e8f1343b",
      type: "app_skill_use",
      content: `app_id: weather
skill_id: rain_radar
status: finished
embed_id: 935fef42-7368-4449-9309-f632e8f1343b
query: Berlin rain radar
provider: Deutscher Wetterdienst (DWD) via Bright Sky
location:
  name: Berlin
  country: Germany
  country_code: DE
  admin1: State of Berlin
  latitude: 52.52437
  longitude: 13.41053
  timezone: Europe/Berlin
coverage:
  status: available
  radius_km: 5
summary:
  rain_expected: false
  in_10_min: No rain visible near Berlin.
  next_2_hours: No rain is visible near Berlin in the radar timeline.
  peak_intensity: none
  preview_frame_id: frame-16
timeline[25]{frame_id,timestamp,kind,label,rain_at_location_mm_5min,max_intensity,rain_area_pct}:
  frame-0,"2026-06-14T18:25:00+02:00",past,"-69 min",0,none,0
  frame-1,"2026-06-14T18:30:00+02:00",past,"-64 min",0,none,0
  frame-2,"2026-06-14T18:35:00+02:00",past,"-59 min",0,none,0
  frame-3,"2026-06-14T18:40:00+02:00",past,"-54 min",0,none,0
  frame-4,"2026-06-14T18:45:00+02:00",past,"-49 min",0,none,0
  frame-5,"2026-06-14T18:50:00+02:00",past,"-44 min",0,none,0
  frame-6,"2026-06-14T18:55:00+02:00",past,"-39 min",0,none,0
  frame-7,"2026-06-14T19:00:00+02:00",past,"-34 min",0,none,0
  frame-8,"2026-06-14T19:05:00+02:00",past,"-29 min",0,none,0
  frame-9,"2026-06-14T19:10:00+02:00",past,"-24 min",0,none,0
  frame-10,"2026-06-14T19:15:00+02:00",past,"-19 min",0,none,0
  frame-11,"2026-06-14T19:20:00+02:00",past,"-14 min",0,none,0
  frame-12,"2026-06-14T19:25:00+02:00",past,"-9 min",0,none,0
  frame-13,"2026-06-14T19:30:00+02:00",past,"-4 min",0,none,0
  frame-14,"2026-06-14T19:35:00+02:00",forecast,+1 min,0,none,0
  frame-15,"2026-06-14T19:40:00+02:00",forecast,+6 min,0,none,0
  frame-16,"2026-06-14T19:45:00+02:00",forecast,+11 min,0,none,0
  frame-17,"2026-06-14T19:50:00+02:00",forecast,+16 min,0,none,0
  frame-18,"2026-06-14T19:55:00+02:00",forecast,+21 min,0,none,0
  frame-19,"2026-06-14T20:00:00+02:00",forecast,+26 min,0,none,0
  frame-20,"2026-06-14T20:05:00+02:00",forecast,+31 min,0,none,0
  frame-21,"2026-06-14T20:10:00+02:00",forecast,+36 min,0,none,0
  frame-22,"2026-06-14T20:15:00+02:00",forecast,+41 min,0,none,0
  frame-23,"2026-06-14T20:20:00+02:00",forecast,+46 min,0,none,0
  frame-24,"2026-06-14T20:25:00+02:00",forecast,+51 min,0,none,0`,
      parent_embed_id: null,
      embed_ids: null,
    },
  ],
  metadata: {
    featured: true,
    order: 100,
    app_skill_examples: ["weather.rain_radar"],
  },
};
