// frontend/packages/ui/src/demo_chats/data/example_chats/books-after-left-hand-of-darkness.ts
//
// Example chat: Books to Read After The Left Hand of Darkness
// Extracted from shared chat 447ca147-85cd-4813-a845-06465ddc594e
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const booksAfterLeftHandOfDarknessChat: ExampleChat = {
  chat_id: "example-books-after-left-hand",
  slug: "books-after-left-hand-of-darkness",
  title: "example_chats.books_after_left_hand_of_darkness.title",
  summary: "example_chats.books_after_left_hand_of_darkness.summary",
  icon: "book-open",
  category: "general_knowledge",
  keywords: ["Left Hand of Darkness", "science fiction books", "Ursula Le Guin", "book recommendations"],
  follow_up_suggestions: ["example_chats.books_after_left_hand_of_darkness.follow_up_1", "example_chats.books_after_left_hand_of_darkness.follow_up_2", "example_chats.books_after_left_hand_of_darkness.follow_up_3", "example_chats.books_after_left_hand_of_darkness.follow_up_4", "example_chats.books_after_left_hand_of_darkness.follow_up_5", "example_chats.books_after_left_hand_of_darkness.follow_up_6"],

  messages: [
    {
        "id": "140c0902-e073-4110-b411-1342ead46f8d",
        "role": "user",
        "content": "example_chats.books_after_left_hand_of_darkness.message_1",
        "created_at": 1791554713
    },
    {
        "id": "b263ae73-e35a-4ca0-b3d5-2b8766014d91",
        "role": "assistant",
        "content": "example_chats.books_after_left_hand_of_darkness.message_2",
        "created_at": 1791554761,
        "user_message_id": "140c0902-e073-4110-b411-1342ead46f8d",
        "category": "general_knowledge",
        "model_name": "Gemini 3.8 Flash"
    }
],
  embeds: [
    {
        "embed_id": "87e82e4a-3fba-475d-a77a-585630b39bec",
        "type": "focus-mode-activation",
        "content": "focus_id: books-book_discussion\napp_id: books\nskill_id: book_discussion\nfocus_mode_name: Book discussion\nstatus: finished",
        "parent_embed_id": null,
        "embed_ids": null
    }
],
  metadata: {
    featured: true,
    order: 133,
    app_focus_mode_examples: ["books.book_discussion"],
    active_focus_id: "books-book_discussion",
  },
};
