// frontend/packages/ui/src/demo_chats/data/example_chats/chickpea-spinach-protein-dinners.ts
//
// Example chat: Chickpea Spinach Protein Dinners
// Extracted from shared chat 91e57096-c6fc-45cc-9a1a-bea822ee968a
// Generated by scripts/create-example-chat-from-share.mjs and sanitized for public demo use.

import type { ExampleChat } from "../../types";

const imageEmbeds = [
  {
    embed_id: "ecd4fd0a-75fa-413a-80ee-5be5450ec68f",
    type: "image_result",
    content: `type: image_result
title: Chickpea spinach curry process photo
source_page_url: "https://www.thefieryvegetarian.com/chickpea-spinach-curry/"
image_url: "https://www.thefieryvegetarian.com/wp-content/uploads/2019/03/chickpea-spinach-curry-process-photo-6.jpg"
source: thefieryvegetarian.com
embed_ref: thefieryvegetarian.com-3sr
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
  {
    embed_id: "989fe7f7-6a54-48c3-9494-2cd2a3f9589d",
    type: "image_result",
    content: `type: image_result
title: Chickpea and spinach curry step photo
source_page_url: "https://vegancocotte.com/chickpea-spinach-curry/"
image_url: "https://vegancocotte.com/wp-content/uploads/2022/09/Chickpea-and-Spinach-Curry-Steps-4.jpg"
source: vegancocotte.com
embed_ref: vegancocotte.com-IZt
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
  {
    embed_id: "66de1a75-66ec-48ad-9c33-5628b89a67b4",
    type: "image_result",
    content: `type: image_result
title: Chickpea and spinach curry with naan
source_page_url: "https://vegancocotte.com/chickpea-spinach-curry/"
image_url: "https://vegancocotte.com/wp-content/uploads/2022/09/Chickpea-and-Spinach-Curry-4.jpg"
source: vegancocotte.com
embed_ref: vegancocotte.com-rFn
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
  {
    embed_id: "9e98f553-d055-446b-b274-fcef409e68f3",
    type: "image_result",
    content: `type: image_result
title: Creamy chickpeas with spinach
source_page_url: "https://runningonrealfood.com/spiced-chickpeas/"
image_url: "https://runningonrealfood.com/wp-content/uploads/2026/01/creamy-marry-me-chickpeas-recipe-12-600x896.jpg"
source: runningonrealfood.com
embed_ref: runningonrealfood.com-R8H
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
  {
    embed_id: "42f9a5c7-39d1-4f5d-aa25-64ac842ee11d",
    type: "image_result",
    content: `type: image_result
title: Skillet chickpeas with spinach and tomatoes
source_page_url: "https://americanhomecook.com/skillet-chickpeas-spinach-lemon/"
image_url: "https://americanhomecook.com/wp-content/uploads/2023/01/Skillet-Chickpeas-with-Spinach-Tomatoes10-819x1024.jpg"
source: americanhomecook.com
embed_ref: americanhomecook.com-Alt
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
  {
    embed_id: "28e60f6d-9775-48ff-abc4-e1db59106be9",
    type: "image_result",
    content: `type: image_result
title: Curry with spinach, chickpeas, and tomatoes
source_page_url: "https://shortgirltallorder.com/chickpea-tomato-spinach-curry"
image_url: "https://shortgirltallorder.com/wp-content/uploads/2020/04/making-curry-in-cast-iron-skillet.jpg"
source: shortgirltallorder.com
embed_ref: shortgirltallorder.com-QXv
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
  {
    embed_id: "43008b96-c5f7-433a-89ee-19749a79a231",
    type: "image_result",
    content: `type: image_result
title: Spanish chickpeas and spinach
source_page_url: "https://www.carolinescooking.com/spanish-chickpeas-and-spinach/"
image_url: "https://www.carolinescooking.com/wp-content/uploads/2015/04/Spanish-chickpeas-and-spinach-pin.jpg"
source: carolinescooking.com
embed_ref: carolinescooking.com-Dy7
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
  {
    embed_id: "771fae42-32e9-4e9d-b8ee-9f9c0afbce91",
    type: "image_result",
    content: `type: image_result
title: Spanish spinach with chickpeas
source_page_url: "https://simpleveganblog.com/spanish-spinach-with-chickpeas/"
image_url: "https://simpleveganblog.com/wp-content/uploads/2015/01/Spanish-Spinach-with-chickpeas-simpleveganblog.com-vegan-2.jpg"
source: simpleveganblog.com
embed_ref: simpleveganblog.com-8dt
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
  {
    embed_id: "6434fec2-7336-4318-b41c-7bf2dff7da61",
    type: "image_result",
    content: `type: image_result
title: Plated Spanish sauteed chickpeas with spinach
source_page_url: "https://ourplantbasedworld.com/sauteed-chickpeas-spinach-spanish/"
image_url: "https://ourplantbasedworld.com/wp-content/uploads/2023/03/sauteed-chickpeas-spinach-spanish-7409231.jpg"
source: ourplantbasedworld.com
embed_ref: ourplantbasedworld.com-Krr
app_id: images
skill_id: search`,
    parent_embed_id: null,
    embed_ids: null,
  },
];

const nutritionEmbeds = [
  {
    embed_id: "d7f21a46-8f13-4f14-82c4-d868ba62bb8a",
    type: "app_skill_use",
    content: `app_id: nutrition
skill_id: search_recipes
result_count: 3
embed_ref: nutrition-search-recipes-chickpea-spinach
embed_ids: 0a4679f4-b2eb-43df-ac66-30e99a98c66b|67e396cc-2a88-4b9a-abf2-be225cce0f03|ce64916b-7e17-4e01-a972-78231cb11b8c
status: finished
embed_id: d7f21a46-8f13-4f14-82c4-d868ba62bb8a
query: chickpea and spinach dinner
max_results: 3
time: 1-35
health: vegetarian
provider: Edamam
preview_results[3]{title,source,provider,image_url,calories_per_serving}:
  Spinach and Chickpeas,theharvestkitchen.com,Edamam,https://edamam-product-images.s3.amazonaws.com/web-img/a0a/a0a6a1e734b3db0b2c9d9b66915ead7a-l.jpg,217
  Chickpea and Spinach Curry,hintofhealthy.com,Edamam,https://edamam-product-images.s3.amazonaws.com/web-img/faa/faa98d303d8822dd2af21e9a55732d9f-l.jpg,220
  Spinach and chickpea curry,damntastyvegan.com,Edamam,https://edamam-product-images.s3.amazonaws.com/web-img/d5d/d5d8ac796cc1b5abbd778b2c22a6d63d-l.jpg,477`,
    parent_embed_id: null,
    embed_ids: [
      "0a4679f4-b2eb-43df-ac66-30e99a98c66b",
      "67e396cc-2a88-4b9a-abf2-be225cce0f03",
      "ce64916b-7e17-4e01-a972-78231cb11b8c",
    ],
  },
  {
    embed_id: "0a4679f4-b2eb-43df-ac66-30e99a98c66b",
    type: "recipe",
    content: `type: recipe
uid: recipe_60b831cae4ae4f3dbc7ec0df6b87de0f
title: Spinach and Chickpeas
recipe_url: "https://www.theharvestkitchen.com/spinach-and-chickpeas/"
source: theharvestkitchen.com
provider: Edamam
embed_ref: nutrition-spinach-and-chickpeas
image_url: "https://edamam-product-images.s3.amazonaws.com/web-img/a0a/a0a6a1e734b3db0b2c9d9b66915ead7a-l.jpg"
total_time_minutes: 20
servings: 4
calories_total: 869
calories_per_serving: 217
diet_labels: Balanced|High-Fiber
health_labels: Kidney-Friendly|Vegan|Vegetarian|Pescatarian|Mediterranean|DASH|Dairy-Free|Gluten-Free
cuisine_type: middle eastern
meal_type: lunch/dinner
dish_type: main course
ingredients: 1-1/2 tablespoons extra-virgin olive oil|2/3 cup tomatoes, diced|1/2 large white onion, diced|2 teaspoons garlic, minced|3 cups low-sodium canned garbanzo beans, drained and rinsed|2 cups baby spinach
instructions: Heat olive oil in pan.|Add onion and saute for 2-3 minutes. Stir in garlic and saute another minute. Pour in tomatoes and cook a minute. Add garbanzo beans and cook for 10 minutes with 3-4 tablespoons water or vegetable broth. Fold in baby spinach and taste to adjust for seasoning.
nutrition_calories_kcal: 217
nutrition_protein_g: 8.7
nutrition_fat_g: 8
nutrition_carbs_g: 29.5
nutrition_fiber_g: 7.9
nutrition_sodium_mg: 248`,
    parent_embed_id: "d7f21a46-8f13-4f14-82c4-d868ba62bb8a",
    embed_ids: null,
  },
  {
    embed_id: "67e396cc-2a88-4b9a-abf2-be225cce0f03",
    type: "recipe",
    content: `type: recipe
uid: recipe_2442d3551cf54cf1bce405e62819260c
title: Chickpea and Spinach Curry
recipe_url: "https://www.hintofhealthy.com/chickpea-and-spinach-curry/"
source: hintofhealthy.com
provider: Edamam
embed_ref: nutrition-chickpea-spinach-curry
image_url: "https://edamam-product-images.s3.amazonaws.com/web-img/faa/faa98d303d8822dd2af21e9a55732d9f-l.jpg"
total_time_minutes: 10
servings: 4
calories_total: 879
calories_per_serving: 220
diet_labels: High-Fiber
health_labels: Vegan|Vegetarian|Pescatarian|Dairy-Free|Gluten-Free|Wheat-Free|Egg-Free|Peanut-Free
cuisine_type: indian
meal_type: lunch/dinner
dish_type: main course
ingredients: 1 (15 oz) can chickpeas, drained and rinsed|1 (15 oz) can diced tomatoes|1 onion|4 garlic cloves|1 red chili pepper|3 tablespoons curry paste|2 tablespoons tomato paste|1 tablespoon diced ginger|3 cups spinach|1 teaspoon vegetable oil
instructions: Finely dice the onion, garlic, ginger and red chili.|Add the onion, garlic, ginger and chili to a large pot along with the vegetable oil.|Saute for about 1 minute, or until the onion is soft and fragrant.|Add tomato paste and curry paste to the pot, and saute for another minute.|Add canned diced tomatoes, and drained and rinsed canned chickpeas.|Stir to combine all ingredients, and cover the pot with a lid.|Leave the curry to simmer on medium to high heat for about 3-5 minutes.|Add washed spinach to the curry, and stir until the leaves have wilted, about 1-2 minutes.
nutrition_calories_kcal: 220
nutrition_protein_g: 10.5
nutrition_fat_g: 5.3
nutrition_carbs_g: 36.2
nutrition_fiber_g: 10.8
nutrition_sodium_mg: 368`,
    parent_embed_id: "d7f21a46-8f13-4f14-82c4-d868ba62bb8a",
    embed_ids: null,
  },
  {
    embed_id: "ce64916b-7e17-4e01-a972-78231cb11b8c",
    type: "recipe",
    content: `type: recipe
uid: recipe_db074a7259484379adedc360d8e793b9
title: Spinach and chickpea curry
recipe_url: "https://damntastyvegan.com/spinach-chickpea-curry/"
source: damntastyvegan.com
provider: Edamam
embed_ref: nutrition-skillet-chickpeas-spinach-tomatoes
total_time_minutes: 25
servings: 4
image_url: "https://edamam-product-images.s3.amazonaws.com/web-img/d5d/d5d8ac796cc1b5abbd778b2c22a6d63d-l.jpg"
calories_total: 1907
calories_per_serving: 477
diet_labels: Balanced|High-Fiber
health_labels: Vegan|Vegetarian|Pescatarian|Mediterranean|Dairy-Free|Gluten-Free|Wheat-Free|Egg-Free
cuisine_type: indian
meal_type: lunch/dinner
dish_type: main course
ingredients: 2 tablespoons neutral oil|1 medium onion, diced|4 cloves garlic, minced|1 teaspoon fresh ginger, minced|1 teaspoon cumin powder|2 teaspoons coriander powder|1/2 teaspoon turmeric powder|1 tablespoon curry powder|15 ounce can crushed tomatoes|2 (15 ounce) cans chickpeas
instructions: Heat up oil in a large pan on medium heat.|Once pan is hot, add the onions and saute until golden brown and translucent.|Add the garlic and ginger and saute for five minutes.|Add all of the spices and saute for 30 seconds. Add the canned tomatoes, chickpeas, water, baking powder and salt.|Cover and bring to a simmer.|Simmer for 10 minutes.|After 10 minutes, add the frozen spinach, cover and simmer for another 5-10 minutes, or until the spinach is warmed through.|Smash a few chickpeas with the back of your spoon to thicken the sauce.|Add the lemon juice, cilantro and optional coconut milk.|Serve over basmati rice or with Indian bread.
nutrition_calories_kcal: 477
nutrition_protein_g: 18.5
nutrition_fat_g: 19.8
nutrition_carbs_g: 62.5
nutrition_fiber_g: 17.7
nutrition_sodium_mg: 1277`,
    parent_embed_id: "d7f21a46-8f13-4f14-82c4-d868ba62bb8a",
    embed_ids: null,
  },
];

export const chickpeaSpinachProteinDinnersChat: ExampleChat = {
  chat_id: "example-chickpea-spinach-protein-dinners",
  slug: "chickpea-spinach-protein-dinners",
  title: "example_chats.chickpea_spinach_protein_dinners.title",
  summary: "example_chats.chickpea_spinach_protein_dinners.summary",
  icon: "utensils",
  category: "cooking_food",
  keywords: ["vegetarian recipes", "chickpeas", "spinach", "protein dinner", "Edamam"],
  follow_up_suggestions: [],
  messages: [
    {
      id: "dc8fb03c-e917-4b53-8e01-c131b8ab3bdb",
      role: "user",
      content: "example_chats.chickpea_spinach_protein_dinners.message_1",
      created_at: 1781353445,
    },
    {
      id: "dbacf972-09e4-4a86-a30f-f343598986f7",
      role: "assistant",
      content: "example_chats.chickpea_spinach_protein_dinners.message_2",
      created_at: 1781353503,
      category: "cooking_food",
      model_name: "Gemini 3 Flash",
    },
  ],
  embeds: [...imageEmbeds, ...nutritionEmbeds],
  metadata: {
    featured: true,
    order: 30,
    app_skill_examples: ["nutrition.search_recipes"],
  },
};
