// frontend/packages/ui/src/demo_chats/data/example_chats/family-stays-kyoto.ts
//
// Example chat: Family Stays In Kyoto
// Extracted from shared chat f9abbfe7-a52f-451c-8550-7a1a3cc1ad1d
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const familyStaysKyotoChat: ExampleChat = {
  chat_id: "example-family-stays-kyoto",
  slug: "family-stays-kyoto",
  title: "example_chats.family_stays_kyoto.title",
  summary: "example_chats.family_stays_kyoto.summary",
  icon: "hotel",
  category: "general_knowledge",
  keywords: ["Kyoto", "hotels", "family", "travel", "public transit"],
  follow_up_suggestions: [],
  messages: [
    {
        id: "7f3a5d29-b781-4621-bd9e-8288f6ce1833",
        role: "user",
        content: "example_chats.family_stays_kyoto.message_1",
        created_at: 1780871665
    },
    {
        id: "82b4e8c2-dd81-4710-8604-3485032dd255",
        role: "assistant",
        content: "example_chats.family_stays_kyoto.message_2",
        created_at: 1780871718,
        category: "general_knowledge",
        model_name: "Gemini 3.1 Pro"
    }
],
  embeds: [
    {
        embed_id: "48320665-f5ea-4c75-9b79-8e01f1b602ae",
        type: "app_skill_use",
        content: "app_id: travel\nskill_id: search_stays\nresult_count: 0\nembed_ids[0]:\nstatus: finished\nembed_id: 48320665-f5ea-4c75-9b79-8e01f1b602ae\nquery: Kyoto\ncheck_out_date: 2026-10-17\ncheck_in_date: 2026-10-12\nchildren: 1\ncurrency: USD\nadults: 2\nid: 1\nprovider: Google",
        parent_embed_id: null,
        embed_ids: []
    },
    {
        embed_id: "7a6cfd2a-6000-4686-ae1e-c0360b46c752",
        type: "app_skill_use",
        content: "app_id: travel\nskill_id: search_stays\nresult_count: 0\nembed_ids[0]:\nstatus: finished\nembed_id: 7a6cfd2a-6000-4686-ae1e-c0360b46c752\nquery: Kyoto\ncurrency: USD\nadults: 2\nchildren: 0\ncheck_out_date: 2026-10-17\ncheck_in_date: 2026-10-12\nid: 2\nprovider: Google",
        parent_embed_id: null,
        embed_ids: []
    },
    {
        embed_id: "ab6a375c-d92a-42fb-a6f0-b1c2456f1199",
        type: "app_skill_use",
        content: "app_id: travel\nskill_id: search_stays\nresult_count: 0\nembed_ids[0]:\nstatus: finished\nembed_id: ab6a375c-d92a-42fb-a6f0-b1c2456f1199\nquery: Hotels in Kyoto\ncheck_out_date: 2026-10-17\ncurrency: USD\nchildren: 1\ncheck_in_date: 2026-10-12\nadults: 2\nid: 1\nprovider: Google",
        parent_embed_id: null,
        embed_ids: []
    },
    {
        embed_id: "c90ccab0-0788-4e41-a49f-bc359016aa2e",
        type: "app_skill_use",
        content: "app_id: travel\nskill_id: search_stays\nresult_count: 0\nembed_ids[0]:\nstatus: finished\nembed_id: c90ccab0-0788-4e41-a49f-bc359016aa2e\nchildren: 1\ncheck_in_date: 2026-10-12\ncurrency: USD\nadults: 2\ncheck_out_date: 2026-10-17\nquery: Hotels near Kyoto Station\nid: 2\nprovider: Google",
        parent_embed_id: null,
        embed_ids: []
    },
    {
        embed_id: "c5e222f6-b05e-4c6f-8874-7b595604d7ce",
        type: "app_skill_use",
        content: "app_id: travel\nskill_id: search_stays\nresult_count: 0\nembed_ids[0]:\nstatus: finished\nembed_id: c5e222f6-b05e-4c6f-8874-7b595604d7ce\nchildren: 1\nadults: 2\ncurrency: USD\ncheck_out_date: 2026-10-17\nquery: Family friendly hotels near public transit in Kyoto\ncheck_in_date: 2026-10-12",
        parent_embed_id: null,
        embed_ids: []
    }
],
  metadata: {
    featured: true,
    order: 18,
    app_skill_examples: ["travel.search_stays"],
  },
};
