// frontend/packages/ui/src/demo_chats/data/example_chats/habit-tracker-onboarding-draft.ts
//
// Example chat: Habit Tracker Onboarding Draft
// Extracted from shared chat a1702987-e69c-47f6-a375-10c140ace17b
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const habitTrackerOnboardingDraftChat: ExampleChat = {
  chat_id: "example-habit-tracker-onboarding-draft",
  slug: "habit-tracker-onboarding-draft",
  title: "example_chats.habit_tracker_onboarding_draft.title",
  summary: "example_chats.habit_tracker_onboarding_draft.summary",
  icon: "image",
  category: "design",
  keywords: ["image draft", "app mockup", "habit tracker", "onboarding screen", "design concept"],
  follow_up_suggestions: [],
  messages: [
    {
        id: "635ebcc8-ee57-4b44-b57a-ba9bab4b1380",
        role: "user",
        content: "example_chats.habit_tracker_onboarding_draft.message_1",
        created_at: 1780913221
    },
    {
        id: "3222ec8f-7afc-4570-9490-9006ca0c0a36",
        role: "assistant",
        content: "example_chats.habit_tracker_onboarding_draft.message_2",
        created_at: 1780913242,
        category: "design",
        model_name: "Gemini 3 Flash"
    }
],
  embeds: [
    {
        embed_id: "79e332e8-5d75-4fd0-9e75-2fe0cb8e209b",
        type: "app_skill_use",
        content: "app_id: images\nskill_id: generate_draft\ntype: image\nstatus: finished\nfiles:\n  original:\n    s3_key: 8881f651-dcaf-4809-8f06-a8e8796f7486/20260608_100718_2ccb72c4_original.png\n    width: 1024\n    height: 768\n    size_bytes: 712595\n    format: png\n  full:\n    s3_key: 8881f651-dcaf-4809-8f06-a8e8796f7486/20260608_100718_2ccb72c4_full_webp.webp\n    width: 1024\n    height: 768\n    size_bytes: 186012\n    format: webp\n  preview:\n    s3_key: 8881f651-dcaf-4809-8f06-a8e8796f7486/20260608_100718_2ccb72c4_preview_webp.webp\n    width: 600\n    height: 400\n    size_bytes: 184966\n    format: webp\ns3_base_url: \"https://dev-openmates-chatfiles.nbg1.your-objectstorage.com\"\naes_key: zHlFo/+ZagV9qIW/V8wiYkHtinDJdbuBt1ixhJ8SKmo=\naes_nonce: O6KedQF4fhwdvkNy\nvault_wrapped_aes_key: \"vault:v1:2NECwZI/Nj1EDh0QSR9DJC4KvBzRiVtL4dXwcvFVJg+V5HjczBXXiNZNFAGnDqurRsMmfbVvriq9WIAWFsoCLEqXOwz/sqew\"\nprompt: \"Mobile app onboarding screen for a habit tracker, UI concept. Design elements: friendly organic abstract shapes, stylized circular progress rings, calm sage and mint green palette. Minimalist layout with placeholder UI blocks for cards and buttons. No readable text, using squiggles or boxes instead. Clean, modern, soft shadows, high-quality UI/UX concept art.\"\nmodel: flux-2-klein\naspect_ratio: \"1:1\"\noutput_filetype: png\ngenerated_at: \"2026-06-08T10:07:18.915693+00:00\"\ninput_embed_ids[0]:\nprovenance:\n  ai_generated: true\n  labeling: xmp+c2pa\n  visual_watermark: false\n  provider_watermarking: provider-dependent",
        parent_embed_id: null,
        embed_ids: null
    }
],
  metadata: {
    featured: true,
    order: 29,
    app_skill_examples: ["images.generate_draft"],
  },
};
