// frontend/packages/ui/src/demo_chats/data/example_chats/memory-ai-communication-style.ts
//
// Example chat: Memory Ai Communication Style
// Extracted from shared chat f4a6e984-d5a6-45a3-9178-645c5c720398
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryAiCommunicationStyleChat: ExampleChat = {
  chat_id: "example-memory-ai-communication-style",
  slug: "memory-ai-communication-style",
  title: "example_chats.memory_ai_communication_style.title",
  summary: "example_chats.memory_ai_communication_style.summary",
  icon: "ai",
  category: "general_knowledge",
  keywords: ["memory", "AI preferences", "communication style", "personalization"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "1214b1c9-cc31-4b73-80d5-a66fc3f0805f",
        "role": "user",
        "content": "example_chats.memory_ai_communication_style.message_1",
        "created_at": 1781290377
    },
    {
        "id": "2d2ffd99-517f-44f5-9988-57a2230a7b5a",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_request\",\"user_message_id\":\"1214b1c9-cc31-4b73-80d5-a66fc3f0805f\",\"request_id\":\"2d2ffd99-517f-44f5-9988-57a2230a7b5a\",\"requested_keys\":[\"ai-communication_style\"],\"categories\":[{\"appId\":\"ai\",\"itemType\":\"communication_style\",\"entryCount\":0}]}",
        "created_at": 1781290379
    },
    {
        "id": "1214b1c9-cc31-4b73-80d5-a66fc3f0805f-memory-response",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_response\",\"user_message_id\":\"1214b1c9-cc31-4b73-80d5-a66fc3f0805f\",\"action\":\"included\",\"categories\":[{\"appId\":\"ai\",\"itemType\":\"communication_style\",\"entryCount\":3}]}",
        "created_at": 1781290379
    },
    {
        "id": "d80e86b0-795c-4839-8023-05c8a1829965",
        "role": "assistant",
        "content": "example_chats.memory_ai_communication_style.message_2",
        "created_at": 1781290398,
        "category": "life_coach_psychology",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 50,
    app_settings_memory_examples: ["ai.communication_style"],
  },
};
