// frontend/packages/ui/src/demo_chats/data/example_chats/memory-travel-saved-connections.ts
//
// Example chat: Memory Travel Saved Connections
// Extracted from shared chat 15aeb908-da5f-431b-b802-d6ce2de15ec3
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryTravelSavedConnectionsChat: ExampleChat = {
  chat_id: "example-memory-travel-saved-connections",
  slug: "memory-travel-saved-connections",
  title: "example_chats.memory_travel_saved_connections.title",
  summary: "example_chats.memory_travel_saved_connections.summary",
  icon: "travel",
  category: "general_knowledge",
  keywords: ["memory", "travel connection", "train", "trip preparation"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "10cb03c7-53d1-4774-bf68-ffeeaaae7814",
        "role": "user",
        "content": "example_chats.memory_travel_saved_connections.message_1",
        "created_at": 1781291080
    },
    {
        "id": "403979dc-8bf4-4a00-a036-e2c46fedd52a",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_request\",\"user_message_id\":\"10cb03c7-53d1-4774-bf68-ffeeaaae7814\",\"request_id\":\"403979dc-8bf4-4a00-a036-e2c46fedd52a\",\"requested_keys\":[\"travel-saved_connections\"],\"categories\":[{\"appId\":\"travel\",\"itemType\":\"saved_connections\",\"entryCount\":0}]}",
        "created_at": 1781291083
    },
    {
        "id": "10cb03c7-53d1-4774-bf68-ffeeaaae7814-memory-response",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_response\",\"user_message_id\":\"10cb03c7-53d1-4774-bf68-ffeeaaae7814\",\"action\":\"included\",\"categories\":[{\"appId\":\"travel\",\"itemType\":\"saved_connections\",\"entryCount\":2}]}",
        "created_at": 1781291083
    },
    {
        "id": "63cf44bf-275a-41e4-a467-f9a8d4ddd8c1",
        "role": "assistant",
        "content": "example_chats.memory_travel_saved_connections.message_2",
        "created_at": 1781291106,
        "category": "general_knowledge",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 68,
    app_settings_memory_examples: ["travel.saved_connections"],
  },
};
