// frontend/packages/ui/src/demo_chats/data/example_chats/memory-mail-writing-styles.ts
//
// Example chat: Memory Mail Writing Styles
// Extracted from shared chat 76321598-0bea-4c30-8480-5ab73f260343
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryMailWritingStylesChat: ExampleChat = {
  chat_id: "example-memory-mail-writing-styles",
  slug: "memory-mail-writing-styles",
  title: "example_chats.memory_mail_writing_styles.title",
  summary: "example_chats.memory_mail_writing_styles.summary",
  icon: "mail",
  category: "business_development",
  keywords: ["memory", "email writing", "client update", "writing style"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "50653345-ee5f-4d46-a692-a47d9d5a169f",
        "role": "user",
        "content": "example_chats.memory_mail_writing_styles.message_1",
        "created_at": 1781290935
    },
    {
        "id": "50653345-ee5f-4d46-a692-a47d9d5a169f-memory-response",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_response\",\"user_message_id\":\"50653345-ee5f-4d46-a692-a47d9d5a169f\",\"action\":\"included\",\"categories\":[{\"appId\":\"mail\",\"itemType\":\"writing_styles\",\"entryCount\":2}]}",
        "created_at": 1781290937
    },
    {
        "id": "0540b5f3-2d30-4340-910b-90adf59533ca",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_request\",\"user_message_id\":\"50653345-ee5f-4d46-a692-a47d9d5a169f\",\"request_id\":\"0540b5f3-2d30-4340-910b-90adf59533ca\",\"requested_keys\":[\"mail-writing_styles\"],\"categories\":[{\"appId\":\"mail\",\"itemType\":\"writing_styles\",\"entryCount\":0}]}",
        "created_at": 1781290937
    },
    {
        "id": "8574dc25-3cfb-4bf1-aaa8-4721e95148cc",
        "role": "assistant",
        "content": "example_chats.memory_mail_writing_styles.message_2",
        "created_at": 1781290957,
        "category": "general_knowledge",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 65,
    app_settings_memory_examples: ["mail.writing_styles"],
  },
};
