// frontend/packages/ui/src/demo_chats/data/example_chats/memory-books-to-read-list.ts
//
// Example chat: Memory Books To Read List
// Extracted from shared chat 6426169f-bdd8-4247-83ba-624aecfe815b
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryBooksToReadListChat: ExampleChat = {
  chat_id: "example-memory-books-to-read",
  slug: "memory-books-to-read-list",
  title: "example_chats.memory_books_to_read_list.title",
  summary: "example_chats.memory_books_to_read_list.summary",
  icon: "task",
  category: "general_knowledge",
  keywords: ["memory", "to-read list", "books", "reading plan"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "adf8af89-25d3-4f16-8175-86c45b4e8769",
        "role": "user",
        "content": "example_chats.memory_books_to_read_list.message_1",
        "created_at": 1781290495
    },
    {
        "id": "64372cad-97a6-42d2-be31-1608573a3c0c",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_request\",\"user_message_id\":\"adf8af89-25d3-4f16-8175-86c45b4e8769\",\"request_id\":\"64372cad-97a6-42d2-be31-1608573a3c0c\",\"requested_keys\":[\"books-to_read_list\"],\"categories\":[{\"appId\":\"books\",\"itemType\":\"to_read_list\",\"entryCount\":0}]}",
        "created_at": 1781290497
    },
    {
        "id": "adf8af89-25d3-4f16-8175-86c45b4e8769-memory-response",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_response\",\"user_message_id\":\"adf8af89-25d3-4f16-8175-86c45b4e8769\",\"action\":\"included\",\"categories\":[{\"appId\":\"books\",\"itemType\":\"to_read_list\",\"entryCount\":2}]}",
        "created_at": 1781290497
    },
    {
        "id": "9a9decf1-e816-4807-85f6-08ca1f4fbd0c",
        "role": "assistant",
        "content": "example_chats.memory_books_to_read_list.message_2",
        "created_at": 1781290519,
        "category": "general_knowledge",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 54,
    app_settings_memory_examples: ["books.to_read_list"],
  },
};
