// frontend/packages/ui/src/demo_chats/data/example_chats/memory-health-appointments.ts
//
// Example chat: Memory Health Appointments
// Extracted from shared chat 449c5445-f63d-402a-9119-6439cf7d8b8d
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryHealthAppointmentsChat: ExampleChat = {
  chat_id: "example-memory-health-appointments",
  slug: "memory-health-appointments",
  title: "example_chats.memory_health_appointments.title",
  summary: "example_chats.memory_health_appointments.summary",
  icon: "heart",
  category: "medical_health",
  keywords: ["memory", "health appointment", "checklist", "preparation"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "6cf628ac-7c67-41af-8775-551ae0e6615f",
        "role": "user",
        "content": "example_chats.memory_health_appointments.message_1",
        "created_at": 1781290826
    },
    {
        "id": "6cf628ac-7c67-41af-8775-551ae0e6615f-memory-response",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_response\",\"user_message_id\":\"6cf628ac-7c67-41af-8775-551ae0e6615f\",\"action\":\"included\",\"categories\":[{\"appId\":\"health\",\"itemType\":\"appointments\",\"entryCount\":2}]}",
        "created_at": 1781290828
    },
    {
        "id": "6284b8da-caf2-4cf5-b457-eedb71ab91a1",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_request\",\"user_message_id\":\"6cf628ac-7c67-41af-8775-551ae0e6615f\",\"request_id\":\"6284b8da-caf2-4cf5-b457-eedb71ab91a1\",\"requested_keys\":[\"health-appointments\"],\"categories\":[{\"appId\":\"health\",\"itemType\":\"appointments\",\"entryCount\":0}]}",
        "created_at": 1781290828
    },
    {
        "id": "ddc6f312-f7c3-4303-9f15-f076d51a6e67",
        "role": "assistant",
        "content": "example_chats.memory_health_appointments.message_2",
        "created_at": 1781290849,
        "category": "medical_health",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 61,
    app_settings_memory_examples: ["health.appointments"],
  },
};
