// frontend/packages/ui/src/demo_chats/data/example_chats/memory-travel-saved-stays.ts
//
// Example chat: Memory Travel Saved Stays
// Extracted from shared chat e989e102-4c50-4d4d-8424-92fbe6957944
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryTravelSavedStaysChat: ExampleChat = {
  chat_id: "example-memory-travel-saved-stays",
  slug: "memory-travel-saved-stays",
  title: "example_chats.memory_travel_saved_stays.title",
  summary: "example_chats.memory_travel_saved_stays.summary",
  icon: "home",
  category: "general_knowledge",
  keywords: ["memory", "travel stay", "accommodation", "booking"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "422a2877-35ff-4894-ac70-c9e9f3c53999",
        "role": "user",
        "content": "example_chats.memory_travel_saved_stays.message_1",
        "created_at": 1781291110
    },
    {
        "id": "115e2a7a-7b23-4a22-9480-59ae05098c48",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_request\",\"user_message_id\":\"422a2877-35ff-4894-ac70-c9e9f3c53999\",\"request_id\":\"115e2a7a-7b23-4a22-9480-59ae05098c48\",\"requested_keys\":[\"travel-saved_stays\"],\"categories\":[{\"appId\":\"travel\",\"itemType\":\"saved_stays\",\"entryCount\":0}]}",
        "created_at": 1781291111
    },
    {
        "id": "422a2877-35ff-4894-ac70-c9e9f3c53999-memory-response",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_response\",\"user_message_id\":\"422a2877-35ff-4894-ac70-c9e9f3c53999\",\"action\":\"included\",\"categories\":[{\"appId\":\"travel\",\"itemType\":\"saved_stays\",\"entryCount\":2}]}",
        "created_at": 1781291111
    },
    {
        "id": "5d1e9d50-e447-44f1-9a70-39464f990448",
        "role": "assistant",
        "content": "example_chats.memory_travel_saved_stays.message_2",
        "created_at": 1781291130,
        "category": "general_knowledge",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 69,
    app_settings_memory_examples: ["travel.saved_stays"],
  },
};
