// frontend/packages/ui/src/demo_chats/data/example_chats/memory-books-favorite-books.ts
//
// Example chat: Memory Books Favorite Books
// Extracted from shared chat 1cdf63a4-7c0d-445b-9346-aa32afac5faf
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryBooksFavoriteBooksChat: ExampleChat = {
  chat_id: "example-memory-books-favorite-books",
  slug: "memory-books-favorite-books",
  title: "example_chats.memory_books_favorite_books.title",
  summary: "example_chats.memory_books_favorite_books.summary",
  icon: "book",
  category: "general_knowledge",
  keywords: ["memory", "books", "recommendations", "reading"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "5dfac893-eb22-4773-8f21-83a246920905",
        "role": "user",
        "content": "example_chats.memory_books_favorite_books.message_1",
        "created_at": 1781279664
    },
    {
        "id": "5763c627-6574-4563-9297-394a69cee8c2",
        "role": "assistant",
        "content": "example_chats.memory_books_favorite_books.message_2",
        "created_at": 1781279687,
        "category": "general_knowledge",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 52,
    app_settings_memory_examples: ["books.favorite_books"],
  },
};
