// frontend/packages/ui/src/demo_chats/data/example_chats/memory-code-want-to-learn.ts
//
// Example chat: Memory Code Want To Learn
// Extracted from shared chat 08983a0c-c9e7-448f-835a-cc445bc9c925
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryCodeWantToLearnChat: ExampleChat = {
  chat_id: "example-memory-code-want-to",
  slug: "memory-code-want-to-learn",
  title: "example_chats.memory_code_want_to_learn.title",
  summary: "example_chats.memory_code_want_to_learn.summary",
  icon: "library",
  category: "software_development",
  keywords: ["memory", "code learning", "WebAssembly", "mini project"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "c81becbc-d377-4e1e-8d83-1c8a333a2f41",
        "role": "user",
        "content": "example_chats.memory_code_want_to_learn.message_1",
        "created_at": 1781279869
    },
    {
        "id": "a3e27509-b71a-463e-b0c4-8a5570a382b2",
        "role": "assistant",
        "content": "example_chats.memory_code_want_to_learn.message_2",
        "created_at": 1781279893,
        "category": "software_development",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 57,
    app_settings_memory_examples: ["code.want_to_learn"],
  },
};
