// frontend/packages/ui/src/demo_chats/data/example_chats/memory-code-preferred-tech.ts
//
// Example chat: Memory Code Preferred Tech
// Extracted from shared chat b18d6e05-9558-4264-9897-746d44e33e0c
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryCodePreferredTechChat: ExampleChat = {
  chat_id: "example-memory-code-preferred-tech",
  slug: "memory-code-preferred-tech",
  title: "example_chats.memory_code_preferred_tech.title",
  summary: "example_chats.memory_code_preferred_tech.summary",
  icon: "coding",
  category: "software_development",
  keywords: ["memory", "coding preferences", "SvelteKit", "developer tools"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "885b673d-884d-4783-b73e-df3a1adfc1f3",
        "role": "user",
        "content": "example_chats.memory_code_preferred_tech.message_1",
        "created_at": 1781279810
    },
    {
        "id": "f665efd0-ac35-4c54-91d3-bfe217185d0a",
        "role": "assistant",
        "content": "example_chats.memory_code_preferred_tech.message_2",
        "created_at": 1781279836,
        "category": "software_development",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 55,
    app_settings_memory_examples: ["code.preferred_tech"],
  },
};
