// frontend/packages/ui/src/demo_chats/data/example_chats/memory-travel-preferred-airlines.ts
//
// Example chat: Memory Travel Preferred Airlines
// Extracted from shared chat 12ebdf7f-6f7e-4296-955d-ef50c41f323a
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryTravelPreferredAirlinesChat: ExampleChat = {
  chat_id: "example-memory-travel-preferred-airlines",
  slug: "memory-travel-preferred-airlines",
  title: "example_chats.memory_travel_preferred_airlines.title",
  summary: "example_chats.memory_travel_preferred_airlines.summary",
  icon: "travel",
  category: "general_knowledge",
  keywords: ["memory", "preferred airline", "travel", "flights"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "7281bee2-adf0-4178-af62-3fb0104ee0f3",
        "role": "user",
        "content": "example_chats.memory_travel_preferred_airlines.message_1",
        "created_at": 1781291229
    },
    {
        "id": "7281bee2-adf0-4178-af62-3fb0104ee0f3-memory-response",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_response\",\"user_message_id\":\"7281bee2-adf0-4178-af62-3fb0104ee0f3\",\"action\":\"included\",\"categories\":[{\"appId\":\"travel\",\"itemType\":\"preferred_airlines\",\"entryCount\":2}]}",
        "created_at": 1781291230
    },
    {
        "id": "1ab9400c-792f-4984-92d3-113ba456db79",
        "role": "system",
        "content": "{\"type\":\"app_settings_memories_request\",\"user_message_id\":\"7281bee2-adf0-4178-af62-3fb0104ee0f3\",\"request_id\":\"1ab9400c-792f-4984-92d3-113ba456db79\",\"requested_keys\":[\"travel-preferred_airlines\"],\"categories\":[{\"appId\":\"travel\",\"itemType\":\"preferred_airlines\",\"entryCount\":0}]}",
        "created_at": 1781291230
    },
    {
        "id": "df1f48a3-7003-4349-bf05-c27e5a178955",
        "role": "assistant",
        "content": "example_chats.memory_travel_preferred_airlines.message_2",
        "created_at": 1781291250,
        "category": "general_knowledge",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 71,
    app_settings_memory_examples: ["travel.preferred_airlines"],
  },
};
