// frontend/packages/ui/src/demo_chats/data/example_chats/memory-events-saved-events.ts
//
// Example chat: Memory Events Saved Events
// Extracted from shared chat dad0de8c-80df-4b09-8568-bcd7ee8413b1
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryEventsSavedEventsChat: ExampleChat = {
  chat_id: "example-memory-events-saved-events",
  slug: "memory-events-saved-events",
  title: "example_chats.memory_events_saved_events.title",
  summary: "example_chats.memory_events_saved_events.summary",
  icon: "events",
  category: "general_knowledge",
  keywords: ["memory", "events", "checklist", "planning"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "597c994e-eb74-4474-a465-53e6add48637",
        "role": "user",
        "content": "example_chats.memory_events_saved_events.message_1",
        "created_at": 1781280012
    },
    {
        "id": "bc9530e9-17e6-41ea-a2bf-2614a7f04613",
        "role": "assistant",
        "content": "example_chats.memory_events_saved_events.message_2",
        "created_at": 1781280038,
        "category": "life_coach_psychology",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 60,
    app_settings_memory_examples: ["events.saved_events"],
  },
};
