// frontend/packages/ui/src/demo_chats/data/example_chats/memory-tv-watched-shows.ts
//
// Example chat: Memory Tv Watched Shows
// Extracted from shared chat e937ce9c-5267-49ea-85e4-071f798aa5ca
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryTvWatchedShowsChat: ExampleChat = {
  chat_id: "example-memory-tv-watched-shows",
  slug: "memory-tv-watched-shows",
  title: "example_chats.memory_tv_watched_shows.title",
  summary: "example_chats.memory_tv_watched_shows.summary",
  icon: "tv",
  category: "movies_tv",
  keywords: ["memory", "watched TV shows", "Severance", "series recommendations"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "e54287c0-54dc-4961-93f1-0caed8596ba7",
        "role": "user",
        "content": "example_chats.memory_tv_watched_shows.message_1",
        "created_at": 1781280553
    },
    {
        "id": "7cf4ba64-2134-4341-9a65-ac3ef207349e",
        "role": "assistant",
        "content": "example_chats.memory_tv_watched_shows.message_2",
        "created_at": 1781280577,
        "category": "movies_tv",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 75,
    app_settings_memory_examples: ["tv.watched_tv_shows"],
  },
};
