// frontend/packages/ui/src/demo_chats/data/example_chats/memory-web-read-later.ts
//
// Example chat: Memory Web Read Later
// Extracted from shared chat 29fc2eaf-0b80-4289-ba7c-a846e37a80c3
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const memoryWebReadLaterChat: ExampleChat = {
  chat_id: "example-memory-web-read-later",
  slug: "memory-web-read-later",
  title: "example_chats.memory_web_read_later.title",
  summary: "example_chats.memory_web_read_later.summary",
  icon: "task",
  category: "software_development",
  keywords: ["memory", "read later", "testing strategy", "engineering planning"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "7365e817-390f-4e70-a020-fa4eef5f637c",
        "role": "user",
        "content": "example_chats.memory_web_read_later.message_1",
        "created_at": 1781280720
    },
    {
        "id": "b1bdbb77-38e4-4974-ac51-4fff6ea5c6fd",
        "role": "assistant",
        "content": "example_chats.memory_web_read_later.message_2",
        "created_at": 1781280743,
        "category": "general_knowledge",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [],
  metadata: {
    featured: true,
    order: 79,
    app_settings_memory_examples: ["web.read_later"],
  },
};
