// frontend/packages/ui/src/demo_chats/data/example_chats/plumber-message-email-phone-privacy.ts
//
// Example chat: Write a plumber message with protected contact details
// Extracted from shared chat 5d90fb1c-2fa0-421b-96c4-5772c93e74fe
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const plumberMessageEmailPhonePrivacyChat: ExampleChat = {
  chat_id: "example-plumber-message-email-phone",
  slug: "plumber-message-email-phone-privacy",
  title: "example_chats.plumber_message_email_phone_privacy.title",
  summary: "example_chats.plumber_message_email_phone_privacy.summary",
  icon: "wrench",
  category: "maker_prototyping",
  keywords: [],
  follow_up_suggestions: ["example_chats.plumber_message_email_phone_privacy.follow_up_1", "example_chats.plumber_message_email_phone_privacy.follow_up_2", "example_chats.plumber_message_email_phone_privacy.follow_up_3", "example_chats.plumber_message_email_phone_privacy.follow_up_4", "example_chats.plumber_message_email_phone_privacy.follow_up_5", "example_chats.plumber_message_email_phone_privacy.follow_up_6"],
  
  messages: [
    {
        "id": "b3d03742-54e2-4a8f-96b4-85d37efc807f",
        "role": "user",
        "content": "example_chats.plumber_message_email_phone_privacy.message_1",
        "created_at": 1788871019,
        "pii_mappings": [
            {
                "placeholder": "[EMAIL_1_com]",
                "original": "lena.hoffmann@example.com",
                "type": "EMAIL"
            },
            {
                "placeholder": "[PHONE_1_147]",
                "original": "+1 202-555-0147",
                "type": "PHONE"
            }
        ]
    },
    {
        "id": "2ff95403-8a44-59b4-8aec-d53546370d00",
        "role": "assistant",
        "content": "example_chats.plumber_message_email_phone_privacy.message_2",
        "created_at": 1788871025,
        "category": "maker_prototyping",
        "model_name": "Gemini 3.5 Flash-Lite"
    }
],
  embeds: [
    {
        "embed_id": "aa8bee97-be75-43c8-b96c-779c4c36624f",
        "type": "mail",
        "content": "type: mail\napp_id: mail\nskill_id: email\nreceiver: Plumber\nsubject: Kitchen sink leak repair needed - available tomorrow afternoon\ncontent: \"Hello,\\n\\nMy kitchen sink has been leaking since yesterday, and I need to get it fixed as soon as possible. I am available tomorrow afternoon for a visit. \\n\\nPlease contact me at [EMAIL_1_com] or [PHONE_1_147] so we can arrange a time.\\n\\nBest regards,\\n[Your Name]\"\nfooter: \"\"\nembed_ref: kitchen-sink-leak-repair-needed-available-tomorr-aa8bee\nstatus: finished",
        "parent_embed_id": null,
        "embed_ids": null,
        "pii_mappings": [
            {
                "placeholder": "[EMAIL_1_com]",
                "original": "lena.hoffmann@example.com",
                "type": "EMAIL"
            },
            {
                "placeholder": "[PHONE_1_147]",
                "original": "+1 202-555-0147",
                "type": "PHONE"
            }
        ]
    }
],
  metadata: {
    featured: false,
    order: 125,
  },
};
