// frontend/packages/ui/src/demo_chats/data/example_chats/private-workspace-demo-video.ts
//
// Example chat: Private Workspace Demo Video
// Extracted from shared chat 0aa2bbf4-70fd-438c-a7d9-8bd9c9a784ed
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const privateWorkspaceDemoVideoChat: ExampleChat = {
  chat_id: "example-private-workspace-demo-video",
  slug: "private-workspace-demo-video",
  title: "example_chats.private_workspace_demo_video.title",
  summary: "example_chats.private_workspace_demo_video.summary",
  icon: "video",
  category: "marketing_sales",
  keywords: ["video generation", "product demo", "privacy dashboard", "abstract UI", "marketing video"],
  follow_up_suggestions: [],
  messages: [
    {
        id: "a9e5bfdd-2ff5-4182-9ea7-5c138896d161",
        role: "user",
        content: "example_chats.private_workspace_demo_video.message_1",
        created_at: 1780913744
    },
    {
        id: "7b52c580-b175-461d-a321-fdca28c0c07c",
        role: "assistant",
        content: "example_chats.private_workspace_demo_video.message_2",
        created_at: 1780913816,
        category: "design",
        model_name: "Gemini 3 Flash"
    }
],
  embeds: [
    {
        embed_id: "57274061-04d4-43a4-958f-fd56bc22f20a",
        type: "app_skill_use",
        content: "app_id: videos\nskill_id: generate\ntype: video\nstatus: finished\nprompt: \"A calm, high-end abstract UI animation. Soft glowing pulses of light, representing encrypted messages, flow gracefully from the left edge of the screen toward a central dashboard interface. The dashboard consists of minimalist geometric shapes, blurred glass layers, and soft shadows. The color palette is deep charcoal and slate blue with subtle cyan highlights. No text, no logos, no human figures. Cinematic lighting, smooth motion, 4k resolution.\"\nduration_seconds: 6\naspect_ratio: \"16:9\"\nresolution: 720p\nmodel: veo-3.1-generate-preview\nprovider: Google Gemini API\nfiles:\n  original:\n    s3_key: 8881f651-dcaf-4809-8f06-a8e8796f7486/20260608_101655_f6c94220_video_original.mp4\n    size_bytes: 1229012\n    format: mp4\n    mime_type: video/mp4\n    duration_seconds: 6\ns3_base_url: \"https://dev-openmates-chatfiles.nbg1.your-objectstorage.com\"\naes_key: 7Uv5HeLctkw5uOACyMfZ047LKbM/pEAKHnBKi80P3EU=\naes_nonce: LYLHz/WP62BrTKt9\nvault_wrapped_aes_key: \"vault:v1:mI2TXspP/7/j+OBPhYqlcjeQ+lrIpgA5n4mNjd2lALGtqlGSiqafwvnB+L5P2TTJdyePF3DfmaDG15doQ/J56d9VnLIzejOI\"\ngenerated_at: \"2026-06-08T10:16:54.815663+00:00\"\nwatermarking: SynthID\nprovenance:\n  ai_generated: true\n  labeling: metadata_only\n  visual_watermark: false\n  provider_watermarking: SynthID",
        parent_embed_id: null,
        embed_ids: null
    }
],
  metadata: {
    featured: true,
    order: 37,
    app_skill_examples: ["videos.generate"],
  },
};
