// frontend/packages/ui/src/demo_chats/data/example_chats/product-launch-synth-loop.ts
//
// Example chat: Product Launch Synth Loop
// Extracted from shared chat d56d35a4-8baa-4139-96e1-c508f324df22
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const productLaunchSynthLoopChat: ExampleChat = {
  chat_id: "example-product-launch-synth-loop",
  slug: "product-launch-synth-loop",
  title: "example_chats.product_launch_synth_loop.title",
  summary: "example_chats.product_launch_synth_loop.summary",
  icon: "music",
  category: "marketing_sales",
  keywords: ["music generation", "product launch", "synth loop", "instrumental teaser", "marketing audio"],
  follow_up_suggestions: [],
  messages: [
    {
        id: "f35daded-f6ab-4dd4-a14e-da1c882bd4a1",
        role: "user",
        content: "example_chats.product_launch_synth_loop.message_1",
        created_at: 1780913666
    },
    {
        id: "311d4f9c-f847-4823-b269-05816b2d7432",
        role: "assistant",
        content: "example_chats.product_launch_synth_loop.message_2",
        created_at: 1780913702,
        category: "general_knowledge",
        model_name: "Gemini 3 Flash"
    }
],
  embeds: [
    {
        embed_id: "65404c52-39dc-4793-9fc7-05c369b2a0af",
        type: "app_skill_use",
        content: "app_id: music\nskill_id: generate\ntype: music\nstatus: finished\nprompt: \"upbeat instrumental loop for a product launch teaser featuring warm synth bass, light percussion, and an optimistic mood, no vocals\"\nmode: loop\nlyrics: null\nstyle: \"optimistic, warm synth, light percussion, corporate teaser\"\nduration_seconds: 20\nmodel: lyria-3-pro-preview\nprovider: Google Vertex AI\nfiles:\n  original:\n    s3_key: 8881f651-dcaf-4809-8f06-a8e8796f7486/20260608_101502_8e3aa9d0_music_original.mp3\n    size_bytes: 576817\n    format: mp3\n    mime_type: audio/mpeg\n    duration_seconds: 20\ns3_base_url: \"https://dev-openmates-chatfiles.nbg1.your-objectstorage.com\"\naes_key: RGvPQWHvBOJb0wphXpuh5aO9TvWFXIibb5MF8x47xio=\naes_nonce: RkG/A20mYQ2trH9A\nvault_wrapped_aes_key: \"vault:v1:Xpd1ywIh2c5TcAKXpWx/vaBEshAwWGvEVSbRUp4/aIFfpblL3BRcM7IeZcuCfEVFs60O8j4TllrPhX2aie/+t5cO5UCgGMsy\"\ngenerated_at: \"2026-06-08T10:15:01.873368+00:00\"\nwatermarking: SynthID\nprovenance:\n  ai_generated: true\n  labeling: audio_container_metadata\n  visual_watermark: false\n  provider_watermarking: SynthID",
        parent_embed_id: null,
        embed_ids: null
    }
],
  metadata: {
    featured: true,
    order: 36,
    app_skill_examples: ["music.generate"],
  },
};
