// frontend/packages/ui/src/demo_chats/data/example_chats/python-squares-code-run.ts
//
// Example chat: Run a Python Squares Snippet
// Extracted from shared chat 46c88840-1a4e-41c7-96ad-d70065432913
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const pythonSquaresCodeRunChat: ExampleChat = {
  chat_id: "example-python-squares-code-run",
  slug: "python-squares-code-run",
  title: "example_chats.python_squares_code_run.title",
  summary: "example_chats.python_squares_code_run.summary",
  icon: "code",
  category: "software_development",
  keywords: ["Python", "code run", "CLI example", "program output", "developer tools"],
  follow_up_suggestions: [],
  messages: [
    {
        id: "4e36c85d-2578-4a7c-ad27-fe3f0a8aade4",
        role: "user",
        content: "example_chats.python_squares_code_run.message_1",
        created_at: 1780913145
    },
    {
        id: "17656537-17e4-464e-90f1-b0c3f75a8306",
        role: "assistant",
        content: "example_chats.python_squares_code_run.message_2",
        created_at: 1780913195,
        category: "software_development",
        model_name: "Gemini 3 Flash"
    }
],
  embeds: [
    {
        embed_id: "df9131ca-18fb-4f9b-9063-23e6abead1ff",
        type: "code",
        content: "type: code\napp_id: code\nskill_id: code\nlanguage: python\ncode: \"for n in range(1, 8):\\n    print(n, n*n, 'even' if n % 2 == 0 else 'odd')\\n\"\nfilename: square_parity.py\nembed_ref: square_parity.py-df9131\nstatus: finished\nline_count: 3",
        parent_embed_id: null,
        embed_ids: null
    },
    {
        embed_id: "a6cf69a2-a9cc-41d5-9317-826b02fbfa16",
        type: "code",
        content: "type: code\napp_id: code\nskill_id: code\nlanguage: text\ncode: \"1 1 odd\\n2 4 even\\n3 9 odd\\n4 16 even\\n5 25 odd\\n6 36 even\\n7 49 odd\\n\"\nfilename: null\nembed_ref: code-a6cf69\nstatus: finished\nline_count: 8",
        parent_embed_id: null,
        embed_ids: null
    },
    {
        embed_id: "5fc00e79-43bc-4343-b965-4452d79e8fb8",
        type: "app_skill_use",
        content: "app_id: code\nskill_id: run\nresults[1]{execution_id,status,error}:\n  null,requires_web_app_route,Code Run is started from the web app code fullscreen via /v1/code/run.\nresult_count: 1\nstatus: finished\nembed_ref: run-KZZ\nembed_id: 5fc00e79-43bc-4343-b965-4452d79e8fb8\ntarget_embed_id: python_snippet_1",
        parent_embed_id: null,
        embed_ids: null
    }
],
  metadata: {
    featured: true,
    order: 28,
    app_skill_examples: ["code.run"],
  },
};
