// frontend/packages/ui/src/demo_chats/data/example_chats/us-egg-prices-deep-research.ts
//
// Example chat: Why US Egg Prices Stayed High
// Extracted from shared chat ba728ecf-d42c-44c9-9928-d3655437f652
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const usEggPricesDeepResearchChat: ExampleChat = {
  chat_id: "example-us-egg-prices-deep",
  slug: "us-egg-prices-deep-research",
  title: "example_chats.us_egg_prices_deep_research.title",
  summary: "example_chats.us_egg_prices_deep_research.summary",
  icon: "search",
  category: "finance",
  keywords: ["egg prices", "US food inflation", "avian flu", "market concentration", "retailer margins", "Deep research", "focus mode"],
  follow_up_suggestions: [],
  messages: [
    {
        "id": "dfd8a5dc-b685-4854-8dbf-4b00c71d93cc",
        "role": "user",
        "content": "example_chats.us_egg_prices_deep_research.message_1",
        "created_at": 1781095179
    },
    {
        "id": "a2413624-df30-4176-9c00-5ea6fb96552d",
        "role": "assistant",
        "content": "example_chats.us_egg_prices_deep_research.message_2",
        "created_at": 1781095355,
        "category": "business_development",
        "model_name": "Gemini 3.1 Pro"
    }
],
  embeds: [
    {
        "embed_id": "070f626b-44ed-43d0-b159-e8a4f567b50f",
        "type": "focus-mode-activation",
        "content": "app_id: web\nskill_id: research\nstatus: finished\nfocus_id: web-research\nfocus_mode_name: Deep research",
        "parent_embed_id": null,
        "embed_ids": null
    }
],
  sub_chats: [
    {
        "chat_id": "example-us-egg-prices-deep-sub-chat-1",
        "title": "example_chats.us_egg_prices_deep_research.sub_chat_1_title",
        "summary": "example_chats.us_egg_prices_deep_research.sub_chat_1_summary",
        "icon": "search",
        "category": "finance",
        "follow_up_suggestions": [],
        "messages": [
            {
                "id": "adbfe974a8-fc7fde58-9615-4e20-943f-824589cbe36d",
                "role": "user",
                "content": "example_chats.us_egg_prices_deep_research.sub_chat_1_message_1",
                "created_at": 1781095196
            },
            {
                "id": "36d9ff59-640a-4727-9288-b9b166952d4e",
                "role": "assistant",
                "content": "Supply recovered slowly because the 2024-2025 HPAI losses hit laying hens, not just short-lived broilers. Repopulation requires cleaning houses, restoring biosecurity, sourcing pullets, and waiting roughly 19 to 20 weeks for hens to reach laying age, so retail relief lagged the headline decline in outbreaks.",
                "created_at": 1781095242,
                "category": "business_development",
                "model_name": "Gemini 3.1 Pro"
            }
        ],
        "embeds": [],
        "parent_id": "example-us-egg-prices-deep",
        "is_sub_chat": true,
        "budget_limit": null,
        "budget_spent": 0
    },
    {
        "chat_id": "example-us-egg-prices-deep-sub-chat-2",
        "title": "example_chats.us_egg_prices_deep_research.sub_chat_2_title",
        "summary": "example_chats.us_egg_prices_deep_research.sub_chat_2_summary",
        "icon": "search",
        "category": "finance",
        "follow_up_suggestions": [],
        "messages": [
            {
                "id": "e9038e115b-1326d3a4-a50c-4b08-8581-c0e1d142a6de",
                "role": "user",
                "content": "example_chats.us_egg_prices_deep_research.sub_chat_2_message_1",
                "created_at": 1781095196
            },
            {
                "id": "d956cf2b-796d-49dd-9745-66bc695490d5",
                "role": "assistant",
                "content": "The market-structure evidence supports a cautious conclusion: concentrated producers and retailers had room to hold prices above the immediate supply shock, but public evidence does not prove formal coordination. The strongest confirmed signal is margin expansion during a period when national supply losses were materially smaller than the retail price spike.",
                "created_at": 1781095269,
                "category": "business_development",
                "model_name": "Gemini 3.1 Pro"
            }
        ],
        "embeds": [],
        "parent_id": "example-us-egg-prices-deep",
        "is_sub_chat": true,
        "budget_limit": null,
        "budget_spent": 0
    },
    {
        "chat_id": "example-us-egg-prices-deep-sub-chat-3",
        "title": "example_chats.us_egg_prices_deep_research.sub_chat_3_title",
        "summary": "example_chats.us_egg_prices_deep_research.sub_chat_3_summary",
        "icon": "search",
        "category": "finance",
        "follow_up_suggestions": [],
        "messages": [
            {
                "id": "c8787e5a8d-98b8eb1e-f25c-422b-8e81-6fa14dfbe351",
                "role": "user",
                "content": "example_chats.us_egg_prices_deep_research.sub_chat_3_message_1",
                "created_at": 1781095196
            },
            {
                "id": "d6376b54-7082-491e-a69f-8eea677e94fd",
                "role": "assistant",
                "content": "Regulation raised the long-run price floor rather than explaining every short-run spike. Cage-free mandates increase capital, labor, and disease-risk costs, while the counterargument is that these costs should not automatically translate into the extreme retail markups seen during the flu shock.",
                "created_at": 1781095297,
                "category": "business_development",
                "model_name": "Gemini 3.1 Pro"
            }
        ],
        "embeds": [],
        "parent_id": "example-us-egg-prices-deep",
        "is_sub_chat": true,
        "budget_limit": null,
        "budget_spent": 0
    }
],
  metadata: {
    featured: true,
    order: 47,
    app_focus_mode_examples: ["web.research"],
    active_focus_id: "web-research",
  },
};
