// frontend/packages/ui/src/demo_chats/data/example_chats/vital-farms-sec-financials.ts
//
// Example chat: Vital Farms SEC Financials
// Extracted from shared chat 74b72f13-4df1-4409-83e7-672b4bd403ec
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const vitalFarmsSecFinancialsChat: ExampleChat = {
  chat_id: "example-vital-farms-sec-financials",
  slug: "vital-farms-sec-financials",
  title: "example_chats.vital_farms_sec_financials.title",
  summary: "example_chats.vital_farms_sec_financials.summary",
  icon: "business",
  category: "business_development",
  keywords: ["Vital Farms", "VITL", "SEC EDGAR", "company financials", "annual report", "10-K", "business research"],
  follow_up_suggestions: ["example_chats.vital_farms_sec_financials.follow_up_1", "example_chats.vital_farms_sec_financials.follow_up_2", "example_chats.vital_farms_sec_financials.follow_up_3", "example_chats.vital_farms_sec_financials.follow_up_4", "example_chats.vital_farms_sec_financials.follow_up_5", "example_chats.vital_farms_sec_financials.follow_up_6"],
  messages: [
    {
        "id": "87c21836-7ea6-4f5f-be36-5d7796106282",
        "role": "user",
        "content": "example_chats.vital_farms_sec_financials.message_1",
        "created_at": 1784476498
    },
    {
        "id": "d6cb138f-3b3b-50aa-b9ff-5c36805e758a",
        "role": "assistant",
        "content": "example_chats.vital_farms_sec_financials.message_2",
        "created_at": 1784476518,
        "user_message_id": "87c21836-7ea6-4f5f-be36-5d7796106282",
        "category": "finance",
        "model_name": "Gemini 3 Flash"
    }
],
  embeds: [
    {
        "embed_id": "94ccced8-6cf6-4f70-b798-b3eede1bfe4a",
        "type": "app_skill_use",
        "content": "app_id: business\nskill_id: company_financials\nresult_count: 1\nembed_ids: d4397677-413a-48e4-8bfb-56f14439690c\nstatus: finished\nembed_id: 94ccced8-6cf6-4f70-b798-b3eede1bfe4a\ncompanies[1]{identifier_type,query}:\n  ticker,VITL\ninclude_sources: true\nmetric_group: all\nperiod: latest_annual\nprovider: SEC EDGAR\nproviders: SEC EDGAR\nquery: VITL\npreview_results[1]{source_url}:\n  \"https://www.sec.gov/Archives/edgar/data/000119312526073423/\"",
        "parent_embed_id": null,
        "embed_ids": [
            "d4397677-413a-48e4-8bfb-56f14439690c"
        ]
    },
    {
        "embed_id": "d4397677-413a-48e4-8bfb-56f14439690c",
        "type": "company_financial_result",
        "content": "period_type: annual\nfiscal_year: 2025\nfiscal_quarter: FY\nperiod_start: 2024-12-30\nperiod_end: 2025-12-28\nfiled: 2026-02-26\nform: 10-K\ncurrency: USD\nrevenue: 759444000\ngross_profit: 285682000\noperating_income: 88373000\nnet_income: 66282000\noperating_cash_flow: 33715000\nsource_url: \"https://www.sec.gov/Archives/edgar/data/000119312526073423/\"\naccession_number: 0001193125-26-073423\nconfidence: high\nnotes: assets was not available in standardized SEC facts|liabilities was not available in standardized SEC facts|equity was not available in standardized SEC facts\ncompany: \"Vital Farms, Inc.\"\nticker: VITL\ncik: \"0001579733\"\ntype: company_financial_result\nparent_app_skill_type: app_skill_use\nembed_ref: company_financial_result-wxr\napp_id: business\nskill_id: company_financials",
        "parent_embed_id": "94ccced8-6cf6-4f70-b798-b3eede1bfe4a",
        "embed_ids": null
    }
],
  metadata: {
    featured: true,
    order: 115,
    app_skill_examples: ["business.company_financials"],
  },
};
