// frontend/packages/ui/src/demo_chats/data/example_chats/voice-note-transcription-action-item.ts
//
// Example chat: Transcribe a Short Voice Note
// Extracted from shared chat 1cee8c61-0330-49d8-a1f3-800fa7f2f4d7
// Generated by scripts/create-example-chat-from-share.mjs

import type { ExampleChat } from "../../types";

export const voiceNoteTranscriptionActionItemChat: ExampleChat = {
  chat_id: "example-voice-note-transcription-action",
  slug: "voice-note-transcription-action-item",
  title: "example_chats.voice_note_transcription_action_item.title",
  summary: "example_chats.voice_note_transcription_action_item.summary",
  icon: "audio",
  category: "general_knowledge",
  keywords: ["audio transcription", "voice note", "action items", "speech to text"],
  follow_up_suggestions: ["example_chats.voice_note_transcription_action_item.follow_up_1", "example_chats.voice_note_transcription_action_item.follow_up_2", "example_chats.voice_note_transcription_action_item.follow_up_3", "example_chats.voice_note_transcription_action_item.follow_up_4", "example_chats.voice_note_transcription_action_item.follow_up_5", "example_chats.voice_note_transcription_action_item.follow_up_6"],

  messages: [
    {
        "id": "621c90d7-2625-4979-8ffe-c0167afb5949",
        "role": "user",
        "content": "example_chats.voice_note_transcription_action_item.message_1",
        "created_at": 1791558631
    },
    {
        "id": "a98d6285-3e9e-5962-8cd7-84ab66709870",
        "role": "assistant",
        "content": "example_chats.voice_note_transcription_action_item.message_2",
        "created_at": 1791558632,
        "user_message_id": "621c90d7-2625-4979-8ffe-c0167afb5949",
        "category": "general_knowledge",
        "model_name": "Gemini 3.8 Flash"
    }
],
  embeds: [
    {
        "embed_id": "476941de-0520-440f-a232-66e7cfb8d7e0",
        "type": "audio-recording",
        "content": "app_id: audio\nskill_id: transcribe\ntype: audio-recording\nstatus: finished\nfilename: transcription-demo-voice-note.wav\nembed_ref: transcription-demo-voice-note-wav-ab2ed0-823c8695-2632-495a-9bff-9e66a805d114\nmime_type: audio/wav\npreviewAudioUrl: /store-examples/transcription-demo-voice-note.wav\ntranscript: Real-time transcription is working correctly in OpenMates.\ntranscript_original: Real-time transcription is working correctly in OpenMates.\ntranscript_corrected: Real-time transcription is working correctly in OpenMates.\nuse_corrected: true\ncorrection_model: gemini-3.5-flash\nmodel: voxtral-mini-2602\nwaveform:\n  version: 1\n  kind: rms-envelope\n  samples[128]: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,8,12,8,5,4,0,1,4,5,3,5,6,1,1,5,4,4,5,1,1,1,4,3,1,1,0,3,5,6,3,1,7,3,1,3,5,6,4,1,0,4,6,6,1,1,5,4,5,3,3,1,0,3,4,5,5,2,2,8,5,1,5,9,4,1,6,7,6,7,6,5,4,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n  duration_seconds: 5",
        "parent_embed_id": null,
        "embed_ids": null
    }
],
  metadata: {
    featured: true,
    order: 140,
  },
};
