import { getCurrentLanguage } from '../i18n/setup';

// Define interfaces for type safety
export interface MetaTagConfig {
    title: string;
    description: string;
    image: string;
    imageWidth: number;
    imageHeight: number;
    url: string;
    type: string;
    keywords: string[];
    author: string;
    locale: string;
    siteName: string;
    logo: string;
    logoWidth: number;
    logoHeight: number;
}

interface PageMetaTags {
    [key: string]: MetaTagConfig;
}

// Default meta values
export let defaultMeta: MetaTagConfig = {
    title: '',
    description: '',
    image: "/images/og-image.jpg",
    imageWidth: 1200,
    imageHeight: 630,
    url: "https://openmates.org",
    type: "website",
    keywords: [],
    author: "OpenMates Team",
    locale: "en_US",
    siteName: "OpenMates™",
    logo: "/images/logo.png",
    logoWidth: 436,
    logoHeight: 92,
};

// Page-specific meta tags
export let pageMeta: PageMetaTags = {
    // Add a default fallback structure
    for_all_of_us: { ...defaultMeta },
    for_developers: { ...defaultMeta },
    docs: { ...defaultMeta },
    docsApi: { ...defaultMeta },
    docsDesignGuidelines: { ...defaultMeta },
    docsDesignSystem: { ...defaultMeta },
    docsRoadmap: { ...defaultMeta },
    docsUserGuide: { ...defaultMeta },
    legalImprint: { ...defaultMeta },
    legalPrivacy: { ...defaultMeta },
    legalTerms: { ...defaultMeta },
    webapp: { ...defaultMeta },
};

/**
 * Pre-load all locale files using Vite's import.meta.glob
 * This allows Vite to statically analyze and bundle all locale files at build time,
 * which is required for proper code splitting and to avoid build-time resolution errors.
 * 
 * IMPORTANT: This function depends on JSON locale files being generated from YAML sources.
 * The JSON files are generated by the `build:translations` script, which runs automatically
 * in the `prebuild` step. This ensures the JSON files exist before the build process tries
 * to import them.
 * 
 * The JSON files are located in `src/i18n/locales/` and are generated from YAML sources
 * in `src/i18n/sources/` during the build process.
 */
// Use Vite's import.meta.glob to pre-bundle all locale files
// This allows Vite to statically analyze the imports at build time
const localeModules = import.meta.glob('../i18n/locales/*.json', { eager: false });

/**
 * Function to load metatags dynamically based on the current language
 */
export async function loadMetaTags(): Promise<void> {
    try {
        const currentLanguage = getCurrentLanguage();
        let metaData;
        
        // Try to load the current language's metadata using the pre-bundled modules
        // The path format matches what import.meta.glob creates: '../i18n/locales/en.json'
        const localePath = `../i18n/locales/${currentLanguage}.json`;
        const enLocalePath = `../i18n/locales/en.json`;
        
        // Try to load the current language's metadata
        // Note: These JSON files are generated from YAML sources during prebuild
        // JSON imports in Vite return { default: <json data> }, so we need to access .default
        try {
            const loader = localeModules[localePath];
            if (loader) {
                const module = await loader() as { default: any };
                metaData = module.default; // JSON imports return { default: <data> }
            } else {
                throw new Error(`Locale module not found for ${currentLanguage}`);
            }
        } catch (e) {
            console.warn(`Metadata for language ${currentLanguage} not found, falling back to English`);
            // Fallback to English if current language metadata is not available
            const enLoader = localeModules[enLocalePath];
            if (enLoader) {
                const module = await enLoader() as { default: any };
                metaData = module.default; // JSON imports return { default: <data> }
            } else {
                throw new Error('English locale module not found');
            }
        }
        
        // Check if metadata exists in the language file
        if (!metaData.metadata || !metaData.metadata.default) {
            console.warn(`Metadata structure missing in language ${currentLanguage}, falling back to English`);
            // Fallback to English metadata
            const enLoader = localeModules[enLocalePath];
            if (enLoader) {
                const module = await enLoader() as { default: any };
                metaData = module.default; // JSON imports return { default: <data> }
            } else {
                throw new Error('English locale module not found');
            }
            
            // If English also doesn't have the metadata structure, use hardcoded defaults
            if (!metaData.metadata || !metaData.metadata.default) {
                throw new Error('Metadata structure missing in English language file');
            }
        }

        // Update defaultMeta
        defaultMeta = {
            title: metaData.metadata.default.title?.text || "OpenMates",
            description: metaData.metadata.default.description?.text || "",
            image: "/images/og-image.jpg",
            imageWidth: 1200,
            imageHeight: 630,
            url: "https://openmates.org",
            type: "website",
            keywords: (metaData.metadata.default.keywords?.text || "").split(', ').filter(Boolean),
            author: "OpenMates Team",
            locale: `${currentLanguage}_${currentLanguage.toUpperCase()}`,
            siteName: "OpenMates™",
            logo: "/images/logo.png",
            logoWidth: 436,
            logoHeight: 92,
        };

        // Safe function to get nested properties with fallback
        const getMetaProperty = (path: string[], fallback: string = ""): string => {
            let obj = metaData.metadata;
            for (const key of path) {
                if (!obj || typeof obj !== 'object') return fallback;
                obj = obj[key];
            }
            return obj?.text || fallback;
        };

        // Update pageMeta with safe property access
        pageMeta = {
            for_all_of_us: {
                ...defaultMeta,
                title: getMetaProperty(['for_all_of_us', 'title'], defaultMeta.title),
            },
            for_developers: {
                ...defaultMeta,
                title: getMetaProperty(['for_developers', 'title'], defaultMeta.title),
                description: getMetaProperty(['for_developers', 'description'], defaultMeta.description),
            },
            docs: {
                ...defaultMeta,
                title: getMetaProperty(['docs', 'title'], defaultMeta.title),
                description: getMetaProperty(['docs', 'description'], defaultMeta.description),
                type: "article"
            },
            docsApi: {
                ...defaultMeta,
                title: getMetaProperty(['docs_api', 'title'], defaultMeta.title),
                description: getMetaProperty(['docs_api', 'description'], defaultMeta.description),
            },
            docsDesignGuidelines: {
                ...defaultMeta,
                title: getMetaProperty(['docs_design_guidelines', 'title'], defaultMeta.title),
                description: getMetaProperty(['docs_design_guidelines', 'description'], defaultMeta.description),
            },
            docsDesignSystem: {
                ...defaultMeta,
                title: getMetaProperty(['docs_design_system', 'title'], defaultMeta.title),
                description: getMetaProperty(['docs_design_system', 'description'], defaultMeta.description),
            },
            docsRoadmap: {
                ...defaultMeta,
                title: getMetaProperty(['docs_roadmap', 'title'], defaultMeta.title),
                description: getMetaProperty(['docs_roadmap', 'description'], defaultMeta.description),
            },
            docsUserGuide: {
                ...defaultMeta,
                title: getMetaProperty(['docs_user_guide', 'title'], defaultMeta.title),
                description: getMetaProperty(['docs_user_guide', 'description'], defaultMeta.description),
            },
            legalImprint: {
                ...defaultMeta,
                title: getMetaProperty(['legal_imprint', 'title'], defaultMeta.title),
                description: getMetaProperty(['legal_imprint', 'description'], defaultMeta.description),
            },
            legalPrivacy: {
                ...defaultMeta,
                title: getMetaProperty(['legal_privacy', 'title'], defaultMeta.title),
                description: getMetaProperty(['legal_privacy', 'description'], defaultMeta.description),
            },
            legalTerms: {
                ...defaultMeta,
                title: getMetaProperty(['legal_terms', 'title'], defaultMeta.title),
                description: getMetaProperty(['legal_terms', 'description'], defaultMeta.description),
            },
            webapp: {
                ...defaultMeta,
                title: getMetaProperty(['webapp', 'title'], defaultMeta.title),
                description: getMetaProperty(['webapp', 'description'], defaultMeta.description),
                type: "website"
            },
        };
    } catch (error) {
        console.error('Failed to load meta tags:', error);
        // Keep using default values if loading fails
    }
}

// Load meta tags dynamically
loadMetaTags();

// Helper function to get meta tags for a specific page
export function getMetaTags(page: string = 'home'): MetaTagConfig {
    // Ensure we always return a valid meta config even if pageMeta[page] is undefined
    return pageMeta[page] || defaultMeta;
}

// Helper function to generate dynamic meta tags (e.g., for blog posts or docs)
export function generateMetaTags(
    title: string,
    description: string,
    slug: string,
    type: string = 'article',
    keywords?: string[]
): MetaTagConfig {
    return {
        ...defaultMeta,
        title: `${title} | ${defaultMeta.siteName}`,
        description,
        url: `${defaultMeta.url}/${slug}`,
        type,
        keywords: keywords || defaultMeta.keywords
    };
}