// frontend/apps/web_app/src/routes/(seo)/tips/[slug]/+page.server.ts
//
// Server-side loader for Updates & Announcements newsletter landing pages.
// Each newsletter issue (generated by publish_newsletter.py) is backed by a
// DemoChat in ALL_NEWSLETTER_CHATS. The page body is crawlable (good for
// SEO + Gmail/Apple Mail previews that follow links before rendering), and
// human browsers are redirected to the SPA deep link on mount.

import { error } from '@sveltejs/kit';
import type { PageServerLoad } from './$types';
import { getNewsletterChatBySlug } from '@repo/ui';
import { resolveI18nKey as t } from '@repo/ui/src/demo_chats/resolveI18nServer';
import { getSiteOrigin } from '$lib/backendUrl';

export const load: PageServerLoad = async ({ params, setHeaders, url }) => {
	const { slug } = params;

	const chat = getNewsletterChatBySlug('tips', slug);
	if (!chat) {
		error(404, 'Tip not found');
	}

	const hostname = url.hostname;
	const isDevHost =
		hostname.includes('.dev.') ||
		hostname.startsWith('dev.') ||
		hostname.endsWith('.vercel.app') ||
		hostname === 'localhost' ||
		hostname === '127.0.0.1';

	setHeaders({
		'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=604800'
	});

	const siteOrigin = getSiteOrigin(url);
	const canonicalUrl = `${siteOrigin}/tips/${slug}`;

	const title = t(chat.title);
	const summary = t(chat.description);
	const messageBody = chat.messages[0] ? t(chat.messages[0].content) : '';

	const jsonLd = {
		'@context': 'https://schema.org',
		'@type': 'Article',
		headline: title,
		description: summary,
		keywords: chat.keywords.join(', '),
		author: { '@type': 'Organization', name: 'OpenMates', url: siteOrigin },
		publisher: { '@type': 'Organization', name: 'OpenMates', url: siteOrigin },
		mainEntityOfPage: { '@type': 'WebPage', '@id': canonicalUrl }
	};

	return {
		slug,
		title,
		summary,
		messageBody,
		keywords: chat.keywords,
		video: {
			mp4_url: chat.metadata.video_mp4_url ?? null,
			hls_url: chat.metadata.video_hls_url ?? null,
			thumbnail_url: chat.metadata.video_thumbnail_url ?? null
		},
		canonicalUrl,
		jsonLd: JSON.stringify(jsonLd),
		isDevHost,
		spaUrl: `${siteOrigin}/#chat-id=${encodeURIComponent(chat.chat_id)}`
	};
};
