# backend/shared/python_utils/image_safety/messages.py
#
# Tiered user-facing messages for image safety rejections.
#
# Architecture: docs/architecture/image-safety-pipeline.md §9
#
# Rules (hard):
# - Never reveal classifier details to the user
# - Never leak which signal fired
# - Messages are versioned here, not generated by the LLM
# - The LLM gets the prepared message + a do_not_retry flag

from typing import Any, Dict

# Tier-level messages. Keep these intentionally vague for CSAM, NCII, and
# adversarial bypass attempts — we do not want to give attackers feedback on
# what specifically tripped the classifier.
_VAGUE_MESSAGE = "This image couldn't be generated."
_PUBLIC_FIGURE_MESSAGE = (
    "I can't generate or edit images of public figures at the moment."
)
_MINOR_SAFE_MESSAGE = (
    "I can only apply background, lighting, or colorization edits to images "
    "containing minors."
)
_MODERATE_MESSAGE = (
    "This specific image or prompt couldn't be used. You can try a different "
    "subject or phrasing."
)

# Category → (tier, severity, message)
CATEGORY_MAP: Dict[str, Dict[str, str]] = {
    "S1_csam": {
        "tier": "critical",
        "severity": "critical",
        "message": _VAGUE_MESSAGE,
    },
    "S2_ncii": {
        "tier": "critical",
        "severity": "critical",
        "message": _VAGUE_MESSAGE,
    },
    "S3_sexual_other": {
        "tier": "severe",
        "severity": "severe",
        "message": _VAGUE_MESSAGE,
    },
    "S4_violent_recontextualization": {
        "tier": "severe",
        "severity": "severe",
        "message": _MODERATE_MESSAGE,
    },
    "S5_minor_restricted_edit": {
        "tier": "severe",
        "severity": "severe",
        "message": _MINOR_SAFE_MESSAGE,
    },
    "S6_public_figure_blocked": {
        "tier": "moderate",
        "severity": "moderate",
        "message": _PUBLIC_FIGURE_MESSAGE,
    },
    "S7_identity_replacement": {
        "tier": "severe",
        "severity": "severe",
        "message": _VAGUE_MESSAGE,
    },
    "S8_id_document": {
        "tier": "severe",
        "severity": "severe",
        "message": _VAGUE_MESSAGE,
    },
    "S9_hate_symbol": {
        "tier": "critical",
        "severity": "critical",
        "message": _VAGUE_MESSAGE,
    },
    "S10_self_harm": {
        "tier": "critical",
        "severity": "critical",
        "message": _VAGUE_MESSAGE,
    },
    "S11_weapon_instruction": {
        "tier": "severe",
        "severity": "severe",
        "message": _VAGUE_MESSAGE,
    },
    "S12_adversarial_bypass": {
        "tier": "adversarial",
        "severity": "adversarial",
        "message": _VAGUE_MESSAGE,
    },
    # Reasoner / infra failure categories — severe fail-closed
    "safeguard_error": {
        "tier": "severe",
        "severity": "severe",
        "message": _MODERATE_MESSAGE,
    },
    "safeguard_not_configured": {
        "tier": "severe",
        "severity": "severe",
        "message": _MODERATE_MESSAGE,
    },
    "safeguard_parse_error": {
        "tier": "severe",
        "severity": "severe",
        "message": _MODERATE_MESSAGE,
    },
    "sightengine_not_configured": {
        "tier": "severe",
        "severity": "severe",
        "message": _MODERATE_MESSAGE,
    },
    "unknown": {
        "tier": "moderate",
        "severity": "moderate",
        "message": _MODERATE_MESSAGE,
    },
}


def category_info(category: str) -> Dict[str, str]:
    """Return tier/severity/message for a category (with unknown-safe fallback)."""
    return CATEGORY_MAP.get(category, CATEGORY_MAP["unknown"])


def user_facing_message(category: str) -> str:
    """Return the user-visible message for a rejection category."""
    return category_info(category)["message"]


def build_rejection_payload(category: str) -> Dict[str, Any]:
    """
    Build the structured tool response returned to the LLM on rejection.

    The LLM relays `user_facing_message` to the user and MUST NOT retry in the
    same response — `do_not_retry: true` is enforced by the pipeline auto-reject
    cache keyed on assistant_response_id.
    """
    info = category_info(category)
    return {
        "error": "safety_rejection",
        "category": category or "unknown",
        "severity": info["severity"],
        "user_facing_message": info["message"],
        "instructions_to_llm": (
            "Do not retry this request. Do not attempt reformulations. Do not "
            "call images-generate again in this response. Relay the "
            "user_facing_message verbatim or paraphrase very closely. Do not "
            "speculate about what would be allowed."
        ),
        "do_not_retry": True,
    }
