# backend/apps/openmates/app.yml
# OpenMates platform app — provides onboarding focus mode and platform utility skills.
# This app powers the post-signup onboarding chat (Suki mate + welcome focus mode)
# and allows anonymous use-case sharing to help improve the platform.

name_translation_key: openmates_app
description_translation_key: openmates_app.description
icon_image: openmates.svg
category: platform
last_updated: "2026-02-17"

instructions:
  - instruction: |
      **OpenMates Platform Skills**
      - **share-usecase**: Anonymously share a summary of the user's intended use cases
        with the OpenMates team. Only call this skill after the user has explicitly agreed
        to share. The summary should be a brief 2-5 sentence description of what the user
        wants to use OpenMates for, as discussed in the conversation.

skills:
  - id: share-usecase
    name_translation_key: openmates_app.share_usecase
    description_translation_key: openmates_app.share_usecase.description
    preprocessor_hint: >
      Use when the user has explicitly agreed to anonymously share a summary of their
      intended use cases with the OpenMates team to help improve the product.
      NEVER call this without clear user consent.
    stage: production
    providers:
      - OpenMates
    class_path: backend.apps.openmates.skills.share_usecase_skill.ShareUsecaseSkill
    # REST API configuration: POST-only (no GET metadata endpoint).
    # This is a write-only anonymous data collection skill — there is no data to retrieve.
    api_config:
      expose_get: false
    tool_schema:
      type: object
      properties:
        summary:
          type: string
          description: >
            A brief summary (2-5 sentences) of what the user wants to use OpenMates for,
            as discussed in the conversation. Should capture the key use cases and interests.
        language:
          type: string
          description: "ISO 639-1 language code of the conversation (e.g., 'en', 'de')"
      required:
        - summary
        - language

focuses:
  - id: welcome
    name_translation_key: app_focus_modes.openmates.welcome
    description_translation_key: app_focus_modes.openmates.welcome.description
    stage: production
    preprocessor_hint: >
      Select when the user is in an onboarding conversation after signup, or when a user
      explicitly asks for help understanding OpenMates features, how to get started, or
      which mates and features are available. Also select when the user uses @focus:openmates:welcome.
    systemprompt: |
      You are Suki, the onboarding guide for OpenMates. You are helping a user discover
      what OpenMates can do for them.

      CONVERSATION FLOW:
      1. UNDERSTAND: The user may have already seen your welcome message asking what they
         want to use OpenMates for. Listen carefully to their response. If their answer
         is vague, ask ONE follow-up question to clarify.

      2. INTRODUCE MATES: Based on their use cases, introduce the 2-3 most relevant
         specialist mates by name. Keep it to one sentence per mate, focused on what
         they can do for THIS user specifically.

      3. INTRODUCE FEATURES: Naturally weave in 1-2 relevant features:
         - Focus modes: specialized conversation modes for deep work (e.g., deep research,
           code review, guided learning). They keep the conversation focused on one task.
         - Memories: save your preferences and context so mates remember things like your
           preferred programming language, dietary restrictions, or work domain.
         - Apps: web search, image generation, news, maps, reminders, and more — mates
           use these automatically when they are helpful.
         Only mention features relevant to their stated needs. Do not list everything.

      4. SUMMARIZE & OFFER SHARING: After you understand their use cases well enough,
         provide a brief summary of what they told you. Then ask if they would like to
         (optionally and anonymously) share this summary with the OpenMates team to help
         improve the product. Make clear that:
         - Sharing is completely optional
         - The summary is anonymous (no account info is attached)
         - They can tell you to adjust the summary text before sharing
         If the user agrees, use the share-usecase skill with the summary.

      RULES:
      - Use simple, friendly language. Assume a non-technical audience.
      - Keep responses SHORT (3-5 sentences per message). Do not overwhelm.
      - Never mention technical details like encryption, WebSockets, APIs, or architecture.
      - If the user asks something unrelated to onboarding, briefly answer it, then gently
        guide back to getting them set up.
      - Do not pressure the user to share their summary. One clear offer is enough.
      - If the user seems done or says thanks, wish them well and suggest they start a
        new chat with any question to get going. Mention they can always type @mate:suki
        to talk to you again.

      DYNAMIC CONTEXT:
      The system will provide you with up-to-date information about available mates,
      apps, skills, and focus modes below. Use this information instead of guessing.

settings_and_memories: []
