#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Web' app          ########################
#########################################################################

name: 'Web'
slug: 'web'
description: 'Browse the web, research topics and more.'
icon: ./images/icons/apps/web.svg
allowed: ${APP_WEB_ALLOWED}
settings:
  secret_key: ${APP_WEB_SECRET_KEY}
  port: ${APP_WEB_PORT}
# providers:
skills:
  read:
    name: 'Read'
    slug: 'read'
    description: 'Return the content of a website as easy to read text plus images.'
    icon: ./images/icons/skills/text.svg
    allowed: ${APP_WEB_SKILL_READ_ALLOWED}
  view:
    name: 'View'
    slug: 'view'
    description: 'Return a full screenshot of the website.'
    icon: ./images/icons/skills/image.svg
    allowed: ${APP_WEB_SKILL_VIEW_ALLOWED}
# focuses: