#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Web' app          ########################
#########################################################################

app:
  name: 'Web'
  slug: 'web'
  description: 'Browse the web, research topics and more.'
  icon: /images/icons/apps/web.svg
  allowed: True
  settings:
    secret_key: ${WEB_BROWSER_SECRET_KEY}
    port: ${WEB_BROWSER_PORT}