# backend/core/api/app/routes/auth_routes/auth_pair.py
# Magic Pair Login — cross-device authentication via QR code or short typed token.
#
# Architecture: docs/architecture/device-sessions.md (Device Authorization Methods § Magic Login Links)
# Security model: Zero-knowledge — server stores only AES-encrypted bundle; PIN never decrypted server-side.
#
# Full flow (two devices):
#   1. [Initiating device]  POST /pair/initiate   → gets 6-char token + URL
#   2. [Logged-in device]   GET  /pair/info/{tok} → sees who wants to pair (device info)
#   3. [Logged-in device]   POST /pair/authorize/{tok} → uploads AES-encrypted bundle + 6-digit PIN
#   4. [Initiating device]  GET  /pair/poll/{tok} → learns bundle is "ready"
#   5. [Initiating device]  POST /pair/complete/{tok} → sends PIN → gets encrypted bundle back
#   6. [Initiating device]  Client decrypts bundle with PIN → recovers lookup_hash
#   7. [Initiating device]  POST /auth/login with recovered lookup_hash → normal session
#
# Redis key TTLs (all scoped to pair: namespace, no overlap with existing keys):
#   pair:req:{token}      5 min   — request metadata + status
#   pair:bundle:{token}   2 min   — encrypted bundle (set by /authorize, consumed by /complete)
#   pair:attempts:{token} 2 min   — integer attempt counter for brute-force guard

from __future__ import annotations

import hashlib
import logging
import re
import secrets
import time
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, field_validator

from backend.core.api.app.models.user import User
from backend.core.api.app.routes.auth_routes.auth_dependencies import (
    get_cache_service,
    get_compliance_service,
    get_current_user,
    get_directus_service,
)
from backend.core.api.app.services.cache import CacheService
from backend.core.api.app.services.compliance import ComplianceService
from backend.core.api.app.services.directus import DirectusService
from backend.core.api.app.services.limiter import limiter
from backend.core.api.app.utils.device_fingerprint import (
    _extract_client_ip,
    derive_device_name,
    get_geo_data_from_ip,
    truncate_ip,
)

logger = logging.getLogger(__name__)
router = APIRouter()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Unambiguous uppercase alphabet — removes chars confused visually (0/O, 1/I, 5/S, 2/Z)
_PAIR_TOKEN_ALPHABET = "ABCDEFGHJKLMNPQRTUVWXY3468"
_PAIR_TOKEN_LENGTH = 6

_PAIR_REQUEST_TTL = 300    # 5 min — QR / URL validity window
_PAIR_BUNDLE_TTL = 120     # 2 min — encrypted bundle sits in Redis
_MAX_PIN_ATTEMPTS = 5      # Brute-force guard; exceeded → token destroyed

_REDIS_REQ_PREFIX = "pair:req:"
_REDIS_BUNDLE_PREFIX = "pair:bundle:"
_REDIS_ATTEMPTS_PREFIX = "pair:attempts:"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _generate_token() -> str:
    """Generate a cryptographically random 6-char pair token from unambiguous alphabet."""
    return "".join(secrets.choice(_PAIR_TOKEN_ALPHABET) for _ in range(_PAIR_TOKEN_LENGTH))


async def _cleanup_pair_keys(cache_service: CacheService, token: str) -> None:
    """Atomically delete all Redis keys for a pairing session."""
    await cache_service.delete(f"{_REDIS_REQ_PREFIX}{token}")
    await cache_service.delete(f"{_REDIS_BUNDLE_PREFIX}{token}")
    await cache_service.delete(f"{_REDIS_ATTEMPTS_PREFIX}{token}")


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------

class PairInitiateRequest(BaseModel):
    """Optional: human-readable device hint displayed on the authorizing device."""
    device_hint: Optional[str] = None


class PairInitiateResponse(BaseModel):
    token: str        # 6-char uppercase token
    expires_in: int   # Seconds until token expires


class PairAuthorizeRequest(BaseModel):
    """
    Sent by the logged-in (authorizing) device after the user approves the pairing.
    The bundle is AES-256-GCM encrypted client-side with a PIN-derived key.
    The server stores the opaque blob; it cannot decrypt it.
    """
    encrypted_bundle: str           # Base64(ciphertext) — AES-GCM
    iv: str                         # Base64 12-byte IV
    pin: str                        # 6-char alphanumeric PIN generated by client (shown to user, not stored in DB)
    authorizer_device_name: Optional[str] = None
    auto_logout_minutes: Optional[int] = None  # Session lifetime chosen by the authorizing device

    @field_validator("pin")
    @classmethod
    def validate_pin(cls, v: str) -> str:
        normalized = v.upper()
        if not re.fullmatch(r"[A-Z0-9]{6}", normalized):
            raise ValueError("pin must be exactly 6 alphanumeric characters")
        return normalized


class PairAuthorizeResponse(BaseModel):
    success: bool


class PairPollResponse(BaseModel):
    status: str                              # "waiting" | "ready" | "expired"
    authorizer_device_name: Optional[str] = None  # Only when status == "ready"


class PairCredentialsResponse(BaseModel):
    """Authenticated credentials payload used to build pair-login encrypted bundle."""
    lookup_hash: str
    user_email_salt: str
    hashed_email: str  # SHA256(email) — needed by /auth/login for user lookup
    encrypted_key: str
    salt: str


class PairCompleteRequest(BaseModel):
    pin: str  # 6-char alphanumeric PIN entered by user on the initiating device

    @field_validator("pin")
    @classmethod
    def validate_pin(cls, v: str) -> str:
        normalized = v.upper()
        if not re.fullmatch(r"[A-Z0-9]{6}", normalized):
            raise ValueError("pin must be exactly 6 alphanumeric characters")
        return normalized


class PairCompleteResponse(BaseModel):
    """
    Returns the encrypted bundle to the initiating device on success.
    Client decrypts with PIN → recovers {lookup_hash, user_email_salt, …} → calls /auth/login.
    Zero-knowledge: server never sees the decrypted contents.
    """
    success: bool
    encrypted_bundle: Optional[str] = None
    iv: Optional[str] = None
    auto_logout_minutes: Optional[int] = None  # Session lifetime set by the authorizing device
    authorizer_device_name: Optional[str] = None
    message: Optional[str] = None


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/pair/initiate", response_model=PairInitiateResponse)
@limiter.limit("10/hour")
async def pair_initiate(
    request: Request,
    body: PairInitiateRequest,
    cache_service: CacheService = Depends(get_cache_service),
) -> PairInitiateResponse:
    """
    Generate a new pairing token.  No authentication required.
    Rate-limited: 10 initiations per hour per IP to prevent token flooding.
    The returned token encodes information about the requesting device for display
    on the authorizing device (device name, truncated IP, geo).
    """
    token = _generate_token()

    # Collect device info from the initiating device
    client_ip = _extract_client_ip(request.headers, request.client.host if request.client else None)
    ip_truncated = truncate_ip(client_ip)
    user_agent = request.headers.get("user-agent", "")
    device_name = body.device_hint or derive_device_name(user_agent)
    geo = get_geo_data_from_ip(client_ip)
    country_code = geo.get("country_code") if isinstance(geo, dict) else None
    city = geo.get("city") if isinstance(geo, dict) else None

    payload = {
        "status": "waiting",
        "created_at": int(time.time()),
        "device_name": device_name,
        "ip_truncated": ip_truncated,
        "country_code": country_code,
        "city": city,
        "authorizer_device_name": None,
    }

    await cache_service.set(f"{_REDIS_REQ_PREFIX}{token}", payload, ttl=_PAIR_REQUEST_TTL)

    logger.info("Pair token generated")
    return PairInitiateResponse(
        token=token,
        expires_in=_PAIR_REQUEST_TTL,
    )


@router.get("/pair/info/{token}")
@limiter.limit("30/minute")
async def pair_info(
    request: Request,
    token: str,
    cache_service: CacheService = Depends(get_cache_service),
) -> dict:
    """
    Return initiating-device info for display on the authorizing device.
    Unauthenticated — the token itself is the access credential.
    """
    token = token.upper()
    data = await cache_service.get(f"{_REDIS_REQ_PREFIX}{token}")

    if not data:
        return {"valid": False, "reason": "expired_or_invalid"}
    if data.get("status") != "waiting":
        return {"valid": False, "reason": "already_authorized"}

    return {
        "valid": True,
        "device_name": data.get("device_name", "Unknown device"),
        "ip_truncated": data.get("ip_truncated"),
        "country_code": data.get("country_code"),
        "city": data.get("city"),
        "created_at": data.get("created_at"),
    }


@router.get("/pair/poll/{token}", response_model=PairPollResponse)
@limiter.limit("60/minute")
async def pair_poll(
    request: Request,
    token: str,
    cache_service: CacheService = Depends(get_cache_service),
) -> PairPollResponse:
    """
    Poll for pairing status.  Unauthenticated.
    Designed for 2-second interval polling from the initiating device.
    Returns status: waiting → ready → (client calls /complete) → token deleted.
    """
    token = token.upper()
    data = await cache_service.get(f"{_REDIS_REQ_PREFIX}{token}")

    if not data:
        return PairPollResponse(status="expired")

    status = data.get("status", "waiting")
    authorizer_name = data.get("authorizer_device_name") if status == "ready" else None
    return PairPollResponse(status=status, authorizer_device_name=authorizer_name)


@router.get("/pair/credentials", response_model=PairCredentialsResponse)
@limiter.limit("30/minute")
async def pair_credentials(
    request: Request,
    current_user: User = Depends(get_current_user),
    directus_service: DirectusService = Depends(get_directus_service),
) -> PairCredentialsResponse:
    """
    Return pair-login credentials for the authenticated authorizing device.

    lookup_hashes and user_email_salt come from the cached User object.
    encrypted_key and salt are stored in the encryption_keys collection (keyed by
    hashed_user_id = SHA256(user_uuid)) — NOT on the directus_users record — so we
    fetch them via get_encryption_key() rather than from current_user fields.
    """
    lookup_hashes = current_user.lookup_hashes or []
    lookup_hash = next(
        (value for value in lookup_hashes if isinstance(value, str) and value.strip()),
        None,
    )

    # hashed_email is not on the User model — read it from the cached user profile or Directus.
    # get_user_profile checks cache first (key: user_profile:{id}), then fetches from Directus.
    hashed_email: str | None = None
    profile_ok, profile_data, _ = await directus_service.get_user_profile(current_user.id)
    if profile_ok and profile_data:
        hashed_email = profile_data.get("hashed_email")
    if not hashed_email:
        # Fallback: fetch hashed_email directly from Directus (in case profile cache is stale)
        user_fields = await directus_service.get_user_fields_direct(current_user.id, ["hashed_email"])
        if user_fields:
            hashed_email = user_fields.get("hashed_email")

    if not lookup_hash or not current_user.user_email_salt or not hashed_email:
        logger.warning(
            "pair/credentials: missing lookup_hash, user_email_salt, or hashed_email for user %s",
            current_user.id[:8],
        )
        raise HTTPException(
            status_code=409,
            detail="Pair login credentials not available for current session",
        )

    # encrypted_key + salt live in the encryption_keys collection, not on directus_users.
    hashed_user_id = hashlib.sha256(current_user.id.encode()).hexdigest()
    encryption_key_data = await directus_service.get_encryption_key(hashed_user_id, "password")

    if not encryption_key_data:
        logger.warning(
            "pair/credentials: no password encryption key found for user %s",
            current_user.id[:8],
        )
        raise HTTPException(
            status_code=409,
            detail="Pair login credentials not available for current session",
        )

    encrypted_key = encryption_key_data.get("encrypted_key")
    salt = encryption_key_data.get("salt")

    if not encrypted_key or not salt:
        logger.warning(
            "pair/credentials: encryption key record incomplete for user %s",
            current_user.id[:8],
        )
        raise HTTPException(
            status_code=409,
            detail="Pair login credentials not available for current session",
        )

    return PairCredentialsResponse(
        lookup_hash=lookup_hash,
        user_email_salt=current_user.user_email_salt,
        hashed_email=hashed_email,
        encrypted_key=encrypted_key,
        salt=salt,
    )


@router.post("/pair/authorize/{token}", response_model=PairAuthorizeResponse)
@limiter.limit("20/hour")
async def pair_authorize(
    request: Request,
    token: str,
    body: PairAuthorizeRequest,
    current_user: User = Depends(get_current_user),
    cache_service: CacheService = Depends(get_cache_service),
    compliance_service: ComplianceService = Depends(get_compliance_service),
) -> PairAuthorizeResponse:
    """
    Upload the AES-encrypted bundle.  Requires authentication (logged-in device).
    The server stores the opaque ciphertext and the 6-digit PIN for /complete to verify.
    Security: server never decrypts the bundle — only the client with the correct PIN can.
    """
    token = token.upper()
    data = await cache_service.get(f"{_REDIS_REQ_PREFIX}{token}")

    if not data:
        raise HTTPException(status_code=404, detail="Pair token not found or expired")
    if data.get("status") != "waiting":
        raise HTTPException(status_code=409, detail="Token already authorized")

    # Store encrypted bundle
    bundle_payload = {
        "encrypted_bundle": body.encrypted_bundle,
        "iv": body.iv,
        "pin": body.pin,  # Stored for /complete PIN validation — never returned to clients
        "auto_logout_minutes": body.auto_logout_minutes,  # Forwarded to initiating device on /complete
    }
    await cache_service.set(f"{_REDIS_BUNDLE_PREFIX}{token}", bundle_payload, ttl=_PAIR_BUNDLE_TTL)

    # Update request status → "ready"
    authorizer_name = body.authorizer_device_name or "Unknown device"
    data["status"] = "ready"
    data["authorizer_device_name"] = authorizer_name
    await cache_service.set(f"{_REDIS_REQ_PREFIX}{token}", data, ttl=_PAIR_REQUEST_TTL)

    # Initialize attempt counter
    await cache_service.set(f"{_REDIS_ATTEMPTS_PREFIX}{token}", 0, ttl=_PAIR_BUNDLE_TTL)

    # Compliance log (no sensitive content — token prefix only for audit trail)
    compliance_service.log_auth_event_safe(
        event_type="pair_authorize",
        user_id=current_user.id,
        device_fingerprint=token[:3],
        location=data.get("country_code") or "unknown",
        status="success",
    )

    logger.info("Pair bundle uploaded by authenticated user")
    return PairAuthorizeResponse(success=True)


@router.delete("/pair/{token}")
@limiter.limit("20/hour")
async def pair_cancel(
    request: Request,
    token: str,
    current_user: User = Depends(get_current_user),
    cache_service: CacheService = Depends(get_cache_service),
) -> dict:
    """
    Cancel an authorized pairing and immediately clean up all Redis keys.
    Requires authentication — only the user who authorized the pairing can cancel it.
    Called when the authorizing device clicks Cancel after showing the PIN.
    """
    token = token.upper()
    data = await cache_service.get(f"{_REDIS_REQ_PREFIX}{token}")

    if not data:
        raise HTTPException(status_code=404, detail="Pair token not found or expired")

    await _cleanup_pair_keys(cache_service, token)
    logger.info("Pair token cancelled by authenticated user")
    return {"success": True}


@router.post("/pair/complete/{token}", response_model=PairCompleteResponse)
@limiter.limit("30/minute")
async def pair_complete(
    request: Request,
    token: str,
    body: PairCompleteRequest,
    cache_service: CacheService = Depends(get_cache_service),
) -> PairCompleteResponse:
    """
    Return the encrypted bundle after verifying the PIN and attempt count.
    Unauthenticated — the PIN and bundle are the mutual secret.

    Security model:
    - Server checks PIN (prevents trivially wrong input on initiating device side)
    - Client decrypts bundle locally using PIN as AES key material
    - If AES decryption fails (wrong PIN), client prompts user again; no need for a new /complete call
    - Max 5 attempts → token destroyed to prevent brute force
    - On success: all pair:* Redis keys are deleted (single-use guarantee)
    """
    token = token.upper()

    # Check attempt counter
    attempts_raw = await cache_service.get(f"{_REDIS_ATTEMPTS_PREFIX}{token}")
    if attempts_raw is None:
        return PairCompleteResponse(success=False, message="expired")

    # The cache.get returns parsed JSON — int stored as int, or might be string
    try:
        attempts = int(attempts_raw)
    except (TypeError, ValueError):
        attempts = 0

    if attempts >= _MAX_PIN_ATTEMPTS:
        await _cleanup_pair_keys(cache_service, token)
        logger.warning("Pair token destroyed: max PIN attempts exceeded")
        return PairCompleteResponse(success=False, message="too_many_attempts")

    # Increment attempt counter BEFORE returning bundle to prevent race-condition bypass
    await cache_service.set(
        f"{_REDIS_ATTEMPTS_PREFIX}{token}",
        attempts + 1,
        ttl=_PAIR_BUNDLE_TTL,
    )

    # Retrieve bundle
    bundle_data = await cache_service.get(f"{_REDIS_BUNDLE_PREFIX}{token}")
    if not bundle_data:
        return PairCompleteResponse(success=False, message="expired")

    # Validate PIN against stored value
    stored_pin = bundle_data.get("pin", "")
    if body.pin != stored_pin:
        remaining = _MAX_PIN_ATTEMPTS - (attempts + 1)
        if remaining <= 0:
            await _cleanup_pair_keys(cache_service, token)
            return PairCompleteResponse(success=False, message="too_many_attempts")
        return PairCompleteResponse(
            success=False,
            message=f"invalid_pin:{remaining}_attempts_left",
        )

    # PIN correct — return bundle and destroy all keys (single-use guarantee)
    encrypted_bundle = bundle_data["encrypted_bundle"]
    iv = bundle_data["iv"]
    auto_logout_minutes = bundle_data.get("auto_logout_minutes")
    # Retrieve authorizer device name from the request metadata
    req_data = await cache_service.get(f"{_REDIS_REQ_PREFIX}{token}")
    authorizer_device_name = req_data.get("authorizer_device_name") if req_data else None
    await _cleanup_pair_keys(cache_service, token)

    logger.info("Pair complete: encrypted bundle returned to initiating device")
    return PairCompleteResponse(
        success=True,
        encrypted_bundle=encrypted_bundle,
        iv=iv,
        auto_logout_minutes=auto_logout_minutes,
        authorizer_device_name=authorizer_device_name,
    )
