/**
 * Type definitions for generated documentation data
 * 
 * These types match the structure generated by scripts/process-docs.js
 */

/**
 * Individual documentation file
 */
export interface DocFile {
    /** Filename (e.g., "chats.md") */
    name: string;
    /** Human-readable title extracted from first heading */
    title: string;
    /** Relative path from docs root (e.g., "architecture/chats.md") */
    path: string;
    /** URL slug without .md extension (e.g., "architecture/chats") */
    slug: string;
    /** Processed HTML content for rendering */
    content: string;
    /** Original markdown content for copy functionality */
    originalMarkdown: string;
    /** Word count of the document */
    wordCount: number;
    /** Short description extracted from first paragraph (max 160 chars) for SEO */
    description: string;
}

/**
 * Lightweight documentation file entry used by navigation manifests.
 */
export interface DocManifestFile {
    /** Filename (e.g., "chats.md") */
    name: string;
    /** Human-readable title extracted from first heading */
    title: string;
    /** Relative path from docs root (e.g., "architecture/chats.md") */
    path: string;
    /** URL slug without .md extension (e.g., "architecture/chats") */
    slug: string;
    /** Word count of the document */
    wordCount: number;
    /** Short description extracted from first paragraph (max 160 chars) for SEO */
    description: string;
    /** Static JSON payload path for this page */
    pagePayload: string;
}

/**
 * Documentation folder with nested structure
 */
export interface DocFolder {
    /** Folder name (e.g., "architecture") */
    name: string;
    /** Human-readable title */
    title: string;
    /** Relative path from docs root */
    path: string;
    /** Files in this folder */
    files: DocFile[];
    /** Subfolders */
    folders: DocFolder[];
}

/**
 * Lightweight documentation folder for the navigation manifest.
 */
export interface DocManifestFolder {
    /** Folder name (e.g., "architecture") */
    name: string;
    /** Human-readable title */
    title: string;
    /** Relative path from docs root */
    path: string;
    /** Files in this folder */
    files: DocManifestFile[];
    /** Subfolders */
    folders: DocManifestFolder[];
}

/**
 * Root documentation structure
 */
export interface DocStructure {
    /** Top-level files in /docs */
    files: DocFile[];
    /** Top-level folders in /docs */
    folders: DocFolder[];
}

/**
 * Lightweight documentation structure for fast initial docs loading.
 */
export interface DocManifestStructure {
    /** Top-level files in /docs */
    files: DocManifestFile[];
    /** Top-level folders in /docs */
    folders: DocManifestFolder[];
}

/**
 * Search index entry
 */
export interface SearchIndexEntry {
    /** Document slug (used as unique ID) */
    id: string;
    /** Document title */
    title: string;
    /** Relative path */
    path: string;
    /** URL slug */
    slug: string;
    /** Plain text content for searching */
    content: string;
    /** Breadcrumb path (e.g., "Architecture > Chats") */
    breadcrumbs: string;
}

/**
 * Complete generated documentation data
 */
export interface DocsData {
    /** ISO timestamp when docs were generated */
    generated: string;
    /** Documentation structure tree */
    structure: DocStructure;
    /** Search index entries */
    searchIndex: SearchIndexEntry[];
}

/**
 * Lightweight docs manifest generated for route navigation.
 */
export interface DocsManifest {
    /** ISO timestamp when docs were generated */
    generated: string;
    /** Lightweight documentation structure tree */
    structure: DocManifestStructure;
}

/**
 * Static search payload loaded only when docs search is used.
 */
export interface DocsSearchData {
    /** ISO timestamp when docs were generated */
    generated: string;
    /** Search index entries */
    searchIndex: SearchIndexEntry[];
}
