# backend/shared/providers/google/gemini_music.py
#
# Google Lyria music generation provider for OpenMates.
# Keeps provider concerns isolated from app skills and uses Vertex AI by
# default so OpenMates can rely on Google Cloud's customer-data controls.
# The music skill encrypts and stores generated bytes separately.

import atexit
import base64
import json
import logging
import os
import tempfile
from dataclasses import dataclass
from typing import Optional

import httpx

from backend.core.api.app.utils.secrets_manager import SecretsManager

logger = logging.getLogger(__name__)

GOOGLE_VERTEX_SECRET_PATH = "kv/data/providers/google"
DEFAULT_VERTEX_LOCATION = "global"
LYRIA_3_VERTEX_LOCATION = "global"
LYRIA_3_PRO_PREVIEW = "lyria-3-pro-preview"
LYRIA_3_CLIP_PREVIEW = "lyria-3-clip-preview"
LYRIA_LEGACY_VERTEX = "lyria-002"
DEFAULT_LYRIA_MODEL = LYRIA_3_PRO_PREVIEW
VERTEX_SCOPE = "https://www.googleapis.com/auth/cloud-platform"

_vertex_initialized = False
_vertex_project_id: Optional[str] = None
_vertex_location: Optional[str] = None
_vertex_temp_credentials_file: Optional[str] = None


@dataclass(frozen=True)
class GeneratedMusic:
    """Normalized music generation response."""

    audio_bytes: bytes
    mime_type: str
    model: str
    duration_seconds: Optional[int]


def _cleanup_vertex_credentials() -> None:
    global _vertex_temp_credentials_file
    if _vertex_temp_credentials_file and os.path.exists(_vertex_temp_credentials_file):
        try:
            os.remove(_vertex_temp_credentials_file)
        except Exception:
            pass


atexit.register(_cleanup_vertex_credentials)


async def _init_vertex_credentials(secrets_manager: Optional[SecretsManager]) -> None:
    """Load Vertex AI service account config from Vault/env and initialize auth."""
    global _vertex_initialized, _vertex_project_id, _vertex_location, _vertex_temp_credentials_file

    if _vertex_initialized:
        return

    project_id = os.environ.get("GOOGLE_VERTEX_PROJECT_ID")
    location = os.environ.get("GOOGLE_VERTEX_LOCATION") or DEFAULT_VERTEX_LOCATION
    service_account_str = os.environ.get("GOOGLE_VERTEX_SERVICE_ACCOUNT_JSON")

    if secrets_manager:
        try:
            service_account_str = service_account_str or await secrets_manager.get_secret(
                secret_path=GOOGLE_VERTEX_SECRET_PATH,
                secret_key="service_account_json",
            )
            project_id = project_id or await secrets_manager.get_secret(
                secret_path=GOOGLE_VERTEX_SECRET_PATH,
                secret_key="project_id",
            )
            location = (
                os.environ.get("GOOGLE_VERTEX_LOCATION")
                or await secrets_manager.get_secret(
                    secret_path=GOOGLE_VERTEX_SECRET_PATH,
                    secret_key="location",
                )
                or DEFAULT_VERTEX_LOCATION
            )
        except Exception as exc:
            logger.error("Failed to load Google Vertex credentials: %s", exc, exc_info=True)

    if not project_id or not service_account_str:
        raise RuntimeError("Google Vertex AI project_id/service_account_json are not configured")

    with tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".json", encoding="utf-8") as fp:
        fp.write(service_account_str)
        _vertex_temp_credentials_file = fp.name

    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = _vertex_temp_credentials_file
    _vertex_project_id = project_id
    _vertex_location = location
    _vertex_initialized = True

    logger.info(
        "Initialized Google Vertex credentials for Lyria (project=%s, location=%s)",
        project_id,
        location,
    )


async def _get_vertex_access_token() -> str:
    """Get an OAuth access token for direct Vertex REST requests."""
    import google.auth
    import google.auth.transport.requests

    credentials, _ = google.auth.default(scopes=[VERTEX_SCOPE])
    credentials.refresh(google.auth.transport.requests.Request())
    if not credentials.token:
        raise RuntimeError("Google auth returned an empty access token")
    return credentials.token


def _vertex_predict_url(location: str, project_id: str, model_id: str) -> str:
    host = "aiplatform.googleapis.com" if location == "global" else f"{location}-aiplatform.googleapis.com"
    return (
        f"https://{host}/v1/projects/{project_id}/locations/{location}/"
        f"publishers/google/models/{model_id}:predict"
    )


def _vertex_interactions_url(project_id: str) -> str:
    return f"https://aiplatform.googleapis.com/v1beta1/projects/{project_id}/locations/{LYRIA_3_VERTEX_LOCATION}/interactions"


async def _generate_lyria_3_interaction(prompt: str, model_id: str) -> tuple[bytes, str]:
    """Call the documented Vertex interactions endpoint for Lyria 3 models."""
    if not _vertex_project_id:
        raise RuntimeError("Vertex project not initialized")

    token = await _get_vertex_access_token()
    async with httpx.AsyncClient(timeout=300) as client:
        response = await client.post(
            _vertex_interactions_url(_vertex_project_id),
            headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json; charset=utf-8"},
            json={
                "model": model_id,
                "input": [{"type": "text", "text": prompt}],
            },
        )
    response.raise_for_status()
    payload = response.json()
    outputs = payload.get("outputs") or []
    for output in outputs:
        if not isinstance(output, dict) or output.get("type") != "audio":
            continue
        data = output.get("data")
        if not data:
            continue
        return base64.b64decode(data), output.get("mime_type") or "audio/mpeg"
    raise RuntimeError(f"Lyria 3 interaction returned no audio output: {json.dumps(payload)[:300]}")


async def _generate_legacy_lyria_002(
    prompt: str,
    negative_prompt: Optional[str],
    sample_count: int,
    seed: Optional[int],
) -> tuple[bytes, str]:
    """Call the documented Vertex Lyria predict endpoint for lyria-002."""
    if not _vertex_project_id:
        raise RuntimeError("Vertex project not initialized")

    location = _vertex_location or "us-central1"
    url = _vertex_predict_url(location, _vertex_project_id, LYRIA_LEGACY_VERTEX)
    token = await _get_vertex_access_token()
    instance: dict[str, object] = {"prompt": prompt}
    if negative_prompt:
        instance["negative_prompt"] = negative_prompt
    if seed is not None:
        instance["seed"] = seed
    parameters = {} if seed is not None else {"sample_count": sample_count}

    async with httpx.AsyncClient(timeout=180) as client:
        response = await client.post(
            url,
            headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
            json={"instances": [instance], "parameters": parameters},
        )
    response.raise_for_status()
    payload = response.json()
    predictions = payload.get("predictions") or []
    if not predictions:
        raise RuntimeError(f"Lyria predict returned no predictions: {json.dumps(payload)[:300]}")
    first = predictions[0]
    audio_content = first.get("audioContent") if isinstance(first, dict) else None
    if not audio_content:
        raise RuntimeError("Lyria predict response did not contain audioContent")
    mime_type = first.get("mimeType", "audio/wav") if isinstance(first, dict) else "audio/wav"
    return base64.b64decode(audio_content), mime_type


async def generate_music_google_lyria(
    prompt: str,
    secrets_manager: SecretsManager,
    model_id: str = DEFAULT_LYRIA_MODEL,
    duration_seconds: Optional[int] = None,
    negative_prompt: Optional[str] = None,
    seed: Optional[int] = None,
    sample_count: int = 1,
) -> GeneratedMusic:
    """Generate music with Google's Lyria models via Vertex AI."""
    await _init_vertex_credentials(secrets_manager)
    normalized_model = model_id or DEFAULT_LYRIA_MODEL

    logger.info(
        "Generating music with Google Lyria via Vertex AI (model=%s, duration=%s): %s",
        normalized_model,
        duration_seconds,
        prompt[:80],
    )

    if normalized_model == LYRIA_LEGACY_VERTEX:
        audio_bytes, mime_type = await _generate_legacy_lyria_002(
            prompt=prompt,
            negative_prompt=negative_prompt,
            sample_count=sample_count,
            seed=seed,
        )
    else:
        prompt_parts = [prompt]
        if duration_seconds:
            prompt_parts.append(f"Target duration: {duration_seconds} seconds.")
        if negative_prompt:
            prompt_parts.append(f"Avoid: {negative_prompt}")
        audio_bytes, mime_type = await _generate_lyria_3_interaction("\n".join(prompt_parts), normalized_model)

    if not audio_bytes:
        raise RuntimeError("Lyria returned empty audio")

    return GeneratedMusic(
        audio_bytes=audio_bytes,
        mime_type=mime_type or "audio/wav",
        model=normalized_model,
        duration_seconds=duration_seconds,
    )
