name_translation_key: nutrition.text
description_translation_key: nutrition.description.text
icon_image: |
  nutrition.svg
category: personal
last_updated: '2025-11-12'
settings_and_memories:
  - id: |
      saved_recipes
    stage: planning
  - id: |
      meal_plan
    stage: planning
