name: |
  Nutrition
description: |
  Keep track of what you eat and drink, find tasty recipes and more.
icon_image: |
  nutrition.svg
category: personal
last_updated: '2025-11-12'
settings_and_memories:
  - id: |
      saved_recipes
    stage: planning
  - id: |
      meal_plan
    stage: planning
