name_translation_key: images.text
description_translation_key: images.description.text
icon_image: |
  image.svg
category: work
last_updated: '2025-11-12'
settings_and_memories:
  - id: |
      preffered_styles
    stage: planning
skills:
  - id: generate
    name_translation_key: images.generate.text
    description_translation_key: images.generate.description.text
    stage: planning
    class_path: |
      skills.image.GenerateSkill
    models:
      - google/imagen-4
      - openai/gpt-image-1
