name_translation_key: images
description_translation_key: images.description
icon_image: |
  image.svg
category: work
last_updated: "2026-01-17"
# All image skills rely on zero-knowledge (client-side) encryption or WebSocket-based
# crypto flows that cannot be executed via a stateless REST call. Hide the entire app
# from the public /docs so the API reference does not show unusable endpoints.
expose_in_api: false
settings_and_memories:
  # Preferred styles: Image styles and aesthetics the user prefers
  - id: preferred_styles
    name_translation_key: images.preferred_styles
    description_translation_key: images.preferred_styles.description
    type: list
    stage: production
    example_translation_keys:
      - "images.preferred_styles.example_1"
      - "images.preferred_styles.example_2"
      - "images.preferred_styles.example_3"
    schema:
      type: object
      properties:
        name:
          type: string
          description: Style name (e.g., Watercolor, Minimalist, Cyberpunk, Art Deco)
          is_title: true
        description:
          type: string
          description: Optional description of the style or when to use it
      required:
        - name
instructions:
  - instruction: |
      When you use the images-generate or images-generate_draft tool, the result will confirm the image is being generated. In your response, briefly acknowledge the request in a natural conversational way (e.g., "I'm generating that image for you now" or "Your image is being created"). Do NOT output any JSON, technical details, task IDs, embed IDs, or status codes. Keep it short and natural.
skills:
  - id: generate
    name_translation_key: images.generate
    description_translation_key: images.generate.description
    api_config:
      expose_get: false # Hidden from REST API docs — image generation requires WebSocket + browser crypto (zero-knowledge). Use the web app or CLI instead.
      expose_post: false # POST requires client-side encryption (WebSocket + browser crypto). Use the web app or CLI instead.
    preprocessor_hint: >
      Generate high-quality images from text prompts and/or reference images.
      Also use for: mockups, design concepts, visual mockup creation, logo mockups,
      product mockups, illustration requests, visual design, concept art, posters,
      banners, thumbnails, or any request that implies creating a visual output.
      Use output_filetype="svg" for logos, icons, illustrations, and any other
      vector graphics that need to be scalable or editable.
    stage: development
    class_path: |
      backend.apps.images.skills.generate_skill.GenerateSkill
    providers:
      - Google
      - Recraft
    full_model_reference: google/gemini-3-pro-image-preview
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: |
            REQUIRED: Array of image generation request objects for parallel processing (up to 5 requests).
            This parameter is MANDATORY - you MUST always provide a 'requests' array, even for a single image.
            Example for single image: {"requests": [{"prompt": "a cute cat"}]}
            Each object must contain 'prompt' (detailed description), and can include optional
            'aspect_ratio', 'output_filetype', and 'quality'.
          items:
            type: object
            properties:
              prompt:
                type: string
                description: Detailed description of the image to generate
              aspect_ratio:
                type: string
                description: Aspect ratio of the generated image
                enum: ["1:1", "16:9", "4:3", "3:2", "2:3", "9:16"]
                default: "1:1"
              output_filetype:
                type: string
                description: |
                  Output file format. Use "svg" to generate a scalable vector graphic (SVG) via
                  Recraft V4 — ideal for logos, icons, illustrations, and any graphic that needs
                  to be scalable, editable in design tools, or used at any size without quality loss.
                  Use "png" or "jpg" for photos, realistic scenes, and detailed raster images.
                  When a Recraft model is selected, Recraft V4 is used for raster output as well.
                enum: ["png", "jpg", "svg"]
                default: "png"
              quality:
                type: string
                description: |
                  Generation quality. Controls which model tier is used when Recraft is the provider.
                  For SVG output (output_filetype="svg"):
                    "default" uses Recraft V4 Vector (1MP, 80 credits — good for web/UI use).
                    "max" uses Recraft V4 Pro Vector (4MP, 300 credits — best for print, large-format,
                    or highly detailed vector illustrations).
                  For raster output (output_filetype="png"/"jpg") with a Recraft model selected:
                    "default" uses Recraft V4 (1024×1024, 40 credits — fast, cost-effective).
                    "max" uses Recraft V4 Pro (2048×2048, 250 credits — high-resolution, print-ready).
                  For other raster models (Google Gemini, FLUX), quality is ignored.
                enum: ["default", "max"]
                default: "default"
            required:
              - prompt
      required:
        - requests
  - id: view
    name_translation_key: images.view
    description_translation_key: images.view.description
    # Internal: invoked automatically by the backend when the user attaches an image.
    # Never shown in the app store or settings UI — users don't select this manually.
    internal: true
    preprocessor_hint: >
      Load an image into the conversation so the AI can see it. Use this skill
      when the user references an uploaded image embed and wants the AI to look
      at it, describe it, read text in it, identify objects, or answer any visual
      question about it. Only requires the embed_id — the server resolves all
      cryptographic and storage details automatically.
    stage: development
    class_path: |
      backend.apps.images.skills.view_skill.ViewSkill
    api_config:
      expose_get: false # Hidden — requires server-side embed lookup with Vault Transit decryption
      expose_post: false # Hidden — requires server-side context (user_vault_key_id). Not usable via stateless REST.
    tool_schema:
      type: object
      properties:
        embed_id:
          type: string
          description: "The embed_id of the image to load into the conversation."
      required:
        - embed_id
  - id: generate_draft
    name_translation_key: images.generate_draft
    description_translation_key: images.generate_draft.description
    api_config:
      expose_get: false # Hidden from REST API docs — image generation requires WebSocket + browser crypto (zero-knowledge). Use the web app or CLI instead.
      expose_post: false # POST requires client-side encryption (WebSocket + browser crypto). Use the web app or CLI instead.
    preprocessor_hint: >
      Quickly generate a draft/preview image from a text prompt.
      Also use for: quick mockups, rough design concepts, draft illustrations,
      sketches, quick visual previews, or any request for a fast/rough image.
    stage: development
    class_path: |
      backend.apps.images.skills.generate_skill.GenerateSkill
    providers:
      - BFL
    full_model_reference: bfl/flux-schnell
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: |
            REQUIRED: Array of image generation request objects for parallel processing (up to 5 requests).
            This parameter is MANDATORY - you MUST always provide a 'requests' array, even for a single image.
            Example for single image: {"requests": [{"prompt": "a cute cat"}]}
            Each object must contain 'prompt' (description of the image).
          items:
            type: object
            properties:
              prompt:
                type: string
                description: Description of the image to generate
            required:
              - prompt
      required:
        - requests
