name_translation_key: images
description_translation_key: images.description
icon_image: |
  image.svg
category: work
last_updated: "2026-01-17"
settings_and_memories:
  # Preferred styles: Image styles and aesthetics the user prefers
  - id: preferred_styles
    name_translation_key: images.preferred_styles
    description_translation_key: images.preferred_styles.description
    type: list
    stage: production
    example_translation_keys:
      - "images.preferred_styles.example_1.text"
      - "images.preferred_styles.example_2.text"
      - "images.preferred_styles.example_3.text"
    schema:
      type: object
      properties:
        name:
          type: string
          description: Style name (e.g., Watercolor, Minimalist, Cyberpunk, Art Deco)
          is_title: true
        description:
          type: string
          description: Optional description of the style or when to use it
      required:
        - name
instructions:
  - instruction: |
      When you use the images-generate or images-generate_draft tool, the result will confirm the image is being generated. In your response, briefly acknowledge the request in a natural conversational way (e.g., "I'm generating that image for you now" or "Your image is being created"). Do NOT output any JSON, technical details, task IDs, embed IDs, or status codes. Keep it short and natural.
skills:
  - id: generate
    name_translation_key: images.generate
    description_translation_key: images.generate.description
    preprocessor_hint: >
      Generate high-quality images from text prompts and/or reference images.
      Also use for: mockups, design concepts, visual mockup creation, logo mockups,
      product mockups, illustration requests, visual design, concept art, posters,
      banners, thumbnails, or any request that implies creating a visual output.
    stage: development
    class_path: |
      backend.apps.images.skills.generate_skill.GenerateSkill
    providers:
      - Google
    full_model_reference: google/gemini-3-pro-image-preview
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: |
            REQUIRED: Array of image generation request objects for parallel processing (up to 5 requests).
            This parameter is MANDATORY - you MUST always provide a 'requests' array, even for a single image.
            Example for single image: {"requests": [{"prompt": "a cute cat"}]}
            Each object must contain 'prompt' (detailed description), and can include optional 'aspect_ratio'.
          items:
            type: object
            properties:
              prompt:
                type: string
                description: Detailed description of the image to generate
              aspect_ratio:
                type: string
                description: Aspect ratio of the generated image
                enum: ["1:1", "16:9", "4:3", "3:2", "2:3", "9:16"]
                default: "1:1"
            required:
              - prompt
      required:
        - requests
  - id: generate_draft
    name_translation_key: images.generate_draft
    description_translation_key: images.generate_draft.description
    preprocessor_hint: >
      Quickly generate a draft/preview image from a text prompt.
      Also use for: quick mockups, rough design concepts, draft illustrations,
      sketches, quick visual previews, or any request for a fast/rough image.
    stage: development
    class_path: |
      backend.apps.images.skills.generate_skill.GenerateSkill
    providers:
      - BFL
    full_model_reference: bfl/flux-schnell
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: |
            REQUIRED: Array of image generation request objects for parallel processing (up to 5 requests).
            This parameter is MANDATORY - you MUST always provide a 'requests' array, even for a single image.
            Example for single image: {"requests": [{"prompt": "a cute cat"}]}
            Each object must contain 'prompt' (description of the image).
          items:
            type: object
            properties:
              prompt:
                type: string
                description: Description of the image to generate
            required:
              - prompt
      required:
        - requests
