name: |
  Images
description: |
  Generate images, modify and resize them and more.
icon_image: |
  image.svg
category: work
last_updated: '2025-11-12'
settings_and_memories:
  - id: |
      preffered_styles
    stage: planning
skills:
  - id: |
      generate
    name: |
      Generate
    description: |
      Generate an image based on a prompt and/or images.
    stage: planning
    class_path: |
      skills.image.GenerateSkill
    models:
      - google/imagen-4
      - openai/gpt-image-1
