name_translation_key: images.text
description_translation_key: images.description.text
icon_image: |
  image.svg
category: work
last_updated: '2026-01-17'
settings_and_memories:
  - id: preferred_styles
    name_translation_key: images.preferred_styles.text
    description_translation_key: images.preferred_styles.description.text
    type: list
    stage: development
skills:
  - id: generate
    name_translation_key: images.generate.text
    description_translation_key: images.generate.description.text
    stage: development
    class_path: |
      backend.apps.images.skills.generate_skill.GenerateSkill
    providers:
      - Google
    full_model_reference: google/gemini-3-pro-image-preview
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: |
            REQUIRED: Array of image generation request objects for parallel processing (up to 5 requests).
            This parameter is MANDATORY - you MUST always provide a 'requests' array, even for a single image.
            Example for single image: {"requests": [{"prompt": "a cute cat"}]}
            Each object must contain 'prompt' (detailed description), and can include optional 'aspect_ratio'.
          items:
            type: object
            properties:
              prompt:
                type: string
                description: Detailed description of the image to generate
              aspect_ratio:
                type: string
                description: Aspect ratio of the generated image
                enum: ["1:1", "16:9", "4:3", "3:2", "2:3", "9:16"]
                default: "1:1"
            required:
              - prompt
      required:
        - requests
  - id: generate_draft
    name_translation_key: images.generate_draft.text
    description_translation_key: images.generate_draft.description.text
    stage: development
    class_path: |
      backend.apps.images.skills.generate_skill.GenerateSkill
    providers:
      - BFL
    full_model_reference: bfl/flux-schnell
    tool_schema:
      type: object
      properties:
        requests:
          type: array
          description: |
            REQUIRED: Array of image generation request objects for parallel processing (up to 5 requests).
            This parameter is MANDATORY - you MUST always provide a 'requests' array, even for a single image.
            Example for single image: {"requests": [{"prompt": "a cute cat"}]}
            Each object must contain 'prompt' (description of the image).
          items:
            type: object
            properties:
              prompt:
                type: string
                description: Description of the image to generate
            required:
              - prompt
      required:
        - requests
