#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Finance' app          ####################
#########################################################################

app:
  name: 'Finance'
  slug: 'finance'
  description: 'Keep track of your finances and build a stable income.'
  active: True
  providers:
    - name: 'Akaunting'
      api_url: ${AKAUNTING_API_URL}
      username: ${AKAUNTING_USERNAME}
      password: ${AKAUNTING_PASSWORD}
      company_id: ${AKAUNTING_COMPANY_ID}