#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Finance' app          ####################
#########################################################################

name: 'Finance'
slug: 'finance'
description: 'Keep track of your finances and build a stable income.'
icon: /images/icons/apps/finance.svg
allowed: ${APP_FINANCE_ALLOWED}
providers:
  akaunting:
    name: 'Akaunting'
    slug: 'akaunting'
    description: 'Akaunting is an open-source accounting software that runs in the web browser.'
    icon: /images/icons/providers/akaunting.svg
    allowed: ${APP_FINANCE_PROVIDER_AKAUNTING_ALLOWED}
    install_server: ${APP_FINANCE_PROVIDER_AKAUNTING_INSTALL_SERVER}
    api_url: ${APP_FINANCE_PROVIDER_AKAUNTING_API_URL}