pricingTiers:
  - credits: 1000
    price:
      eur: 1
      usd: 2
      jpy: 200
    label: "1.000 credits"
  
  - credits: 10000
    price:
      eur: 10
      usd: 11
      jpy: 2000
    label: "10.000 credits"
  
  - credits: 21000
    price:
      eur: 20
      usd: 22
      jpy: 4000
    label: "21.000 credits"
  
  - credits: 54000
    price:
      eur: 50
      usd: 55
      jpy: 9000
    label: "54.000 credits"
  
  - credits: 110000
    price:
      eur: 100
      usd: 110
      jpy: 18000
    label: "110.000 credits"

aiModelCosts:
  - model: "claude 3.7 sonnet"
    costs:
      text: 
        credits: 1
        per: 50
        unit: "tokens"
      image:
        credits: 15
        per: 1
        unit: "image"
  
  - model: "gemini 2.0 flash"
    costs:
      text:
        credits: 1
        per: 1000
        unit: "tokens"
      image:
        credits: 1
        per: 1
        unit: "image"
