#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Audio' app          ######################
#########################################################################

name: 'Audio'
slug: 'audio'
description: 'Generate, modify and transcribe audio and more.'
icon: /images/icons/apps/audio.svg
allowed: True
providers:
  assemblyai:
    name: 'AssemblyAI'
    allowed: True
    api_key: ${ASSEMBLYAI_API_KEY}
  openai:
    name: 'OpenAI'
    allowed: True
    api_key: ${OPENAI_API_KEY}
  elevenlabs:
    name: 'ElevenLabs'
    allowed: True
    api_key: ${ELEVENLABS_API_KEY}