#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Audio' app          ######################
#########################################################################

name: 'Audio'
slug: 'audio'
description: |
  Generate, modify and transcribe audio and more.
icon: /images/icons/apps/audio.svg
allowed: ${APP_AUDIO_ALLOWED}
providers:
  assemblyai:
    name: 'AssemblyAI'
    slug: 'assemblyai'
    description: |
      AssemblyAI offers powerful AI transcription and speech-to-text services.
    icon: /images/icons/providers/assemblyai.svg
    allowed: ${APP_AUDIO_PROVIDER_ASSEMBLYAI_ALLOWED}
    api_key: ${APP_AUDIO_PROVIDER_ASSEMBLYAI_API_KEY}
  openai:
    name: 'OpenAI'
    slug: 'openai'
    description: |
      OpenAI offers powerful AI transcription and speech-to-text services.
    icon: /images/icons/providers/openai.svg
    allowed: ${APP_AUDIO_PROVIDER_OPENAI_ALLOWED}
    api_key: ${APP_AUDIO_PROVIDER_OPENAI_API_KEY}
  elevenlabs:
    name: 'ElevenLabs'
    slug: 'elevenlabs'
    description: |
      ElevenLabs offers powerful AI text-to-speech services.
    icon: /images/icons/providers/elevenlabs.svg
    allowed: ${APP_AUDIO_PROVIDER_ELEVENLABS_ALLOWED}
    api_key: ${APP_AUDIO_PROVIDER_ELEVENLABS_API_KEY}
skills:
  generate_speech:
    name: 'Generate speech'
    slug: 'generate_speech'
    description: |
      Transform text into spoken audio.
    icon: /images/icons/skills/generate_speech.svg
    allowed: ${APP_AUDIO_SKILL_GENERATE_SPEECH_ALLOWED}
    default_provider_slug: ${APP_AUDIO_SKILL_GENERATE_SPEECH_DEFAULT_PROVIDER_SLUG}
  generate_transcript:
    name: 'Generate transcript'
    slug: 'generate_transcript'
    description: |
      Transform spoken audio to text.
    icon: /images/icons/skills/generate_transcript.svg
    allowed: ${APP_AUDIO_SKILL_GENERATE_TRANSCRIPT_ALLOWED}
    default_provider_slug: ${APP_AUDIO_SKILL_GENERATE_TRANSCRIPT_DEFAULT_PROVIDER_SLUG}
# focuses: