---
# roles/apps/tasks/main.yml

# Include all applications defined in the applications map
- name: Include application roles
  include_role:
    name: "{{ item.key }}"
  vars:
    app_subdomain: "{{ item.value.subdomain }}"
    app_port: "{{ item.value.port }}"
  loop: "{{ applications | dict2items }}"