#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
#####################          'Code' app          ######################
#########################################################################

name: 'Code'
slug: 'code'
description: 'Write, test, improve and execute code.'
icon: /images/icons/apps/code.svg
allowed: ${APP_CODE_ALLOWED}
# providers:
# skills:
focuses:
  plan:
    name: 'Plan'
    slug: 'plan'
    description: |
      Asks you multiple rounds of questions,
      to make a clear plan with your coding requirements.
    icon: /images/icons/focuses/plan.svg
    allowed: ${APP_CODE_FOCUS_PLAN_ALLOWED}
    prompt: /api/configs/apps/code/prompts/plan.md
