#!/usr/bin/env python3
"""Validate, promote, and audit web-rendered Apple UI contract fixtures.

Contracts are generated by Playwright from browser-rendered DOM/computed style
and promoted intentionally before Apple UI tests consume them. The first surface
is `message-input`, where structural/testability drift fails and visual drift is
reported as warning metadata.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = REPO_ROOT / "apple" / "OpenMatesUITests" / "Fixtures" / "WebUIContracts"
MESSAGE_INPUT_FIXTURE = FIXTURE_DIR / "message-input.json"
EMBEDS_FIXTURE = FIXTURE_DIR / "embeds.json"

REQUIRED_MESSAGE_INPUT_STATES = {
    "default",
    "focused",
    "image-pending-embed",
    "file-pending-embed",
    "recording-overlay",
}
REQUIRED_MESSAGE_INPUT_IDENTIFIERS = {
    "message-editor",
    "action-buttons",
    "attach-files-button",
    "take-photo-button",
    "record-audio-button",
    "record-overlay",
    "release-text",
    "timer-pill",
    "cancel-hint",
    "mic-button",
    "embed-full-width-wrapper",
    "pending-composer-embed",
    "pending-composer-embed-remove",
}
REQUIRED_EMBED_SHOWCASE_APPS = {
    "audio",
    "code",
    "docs",
    "electronics",
    "events",
    "health",
    "home",
    "images",
    "mail",
    "maps",
    "math",
    "music",
    "news",
    "nutrition",
    "pdf",
    "reminder",
    "sheets",
    "shopping",
    "social_media",
    "travel",
    "videos",
    "weather",
    "web",
}
ALLOWED_SEVERITIES = {"fail", "warn"}
PRIVATE_VALUE_PATTERNS = [
    re.compile(r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}", re.IGNORECASE),
    re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"),
    re.compile(r"openmates_test_account", re.IGNORECASE),
    re.compile(r"chat-id=", re.IGNORECASE),
]


class ContractError(Exception):
    """Raised for contract validation or audit failures."""


def load_contract(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ContractError(f"contract file not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ContractError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ContractError("contract root must be an object")
    return data


def walk_values(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        values: list[str] = []
        for item in value:
            values.extend(walk_values(item))
        return values
    if isinstance(value, dict):
        values = []
        for item in value.values():
            values.extend(walk_values(item))
        return values
    return []


def validate_contract(path: Path, *, surface: str | None = None) -> list[str]:
    contract = load_contract(path)
    errors: list[str] = []

    if contract.get("schemaVersion") != 1:
        errors.append("schemaVersion must be 1")
    if not isinstance(contract.get("surface"), str):
        errors.append("surface must be a string")
    if surface and contract.get("surface") != surface:
        errors.append(f"surface must be {surface!r}")
    if not isinstance(contract.get("generatedAt"), str):
        errors.append("generatedAt must be a string")
    viewport = contract.get("viewport")
    if not isinstance(viewport, dict) or not isinstance(viewport.get("width"), int) or not isinstance(viewport.get("height"), int):
        errors.append("viewport.width and viewport.height must be integers")

    states = contract.get("states")
    if not isinstance(states, list) or not states:
        errors.append("states must be a non-empty array")
        states = []

    state_ids: set[str] = set()
    for state in states:
        if not isinstance(state, dict):
            errors.append("state entries must be objects")
            continue
        state_id = state.get("id")
        if not isinstance(state_id, str) or not state_id:
            errors.append("state.id must be a non-empty string")
        else:
            state_ids.add(state_id)
        elements = state.get("elements")
        if not isinstance(elements, list) or not elements:
            errors.append(f"state {state_id or '<unknown>'} must contain elements")
            continue
        for element in elements:
            if not isinstance(element, dict):
                errors.append(f"state {state_id} has a non-object element")
                continue
            for required_field in ("semanticId", "testId", "severity", "structure", "computedStyle"):
                if required_field not in element:
                    errors.append(f"state {state_id} element missing {required_field}")
            if element.get("severity") not in ALLOWED_SEVERITIES:
                errors.append(f"state {state_id} has invalid severity {element.get('severity')!r}")
            if element.get("required", True) and element.get("exists") is not True:
                errors.append(f"state {state_id} required element {element.get('testId')} does not exist")

    if contract.get("surface") == "message-input":
        missing_states = REQUIRED_MESSAGE_INPUT_STATES - state_ids
        if missing_states:
            errors.append(f"missing message-input states: {', '.join(sorted(missing_states))}")

    for text in walk_values(contract):
        for pattern in PRIVATE_VALUE_PATTERNS:
            if pattern.search(text):
                errors.append(f"contract contains private or volatile value matching {pattern.pattern!r}")

    return errors


def _read_repo_file(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def _extract_ts_object_keys(source: str, const_name: str) -> set[str]:
    match = re.search(
        rf"export const {re.escape(const_name)}:[^=]+=\s*{{(?P<body>.*?)^}};",
        source,
        flags=re.DOTALL | re.MULTILINE,
    )
    if not match:
        return set()
    return set(re.findall(r'^[ \t]*"([^"]+)"[ \t]*:', match.group("body"), flags=re.MULTILINE))


def _extract_showcase_apps(source: str) -> set[str]:
    match = re.search(r"const ALL_APPS = \[(?P<body>.*?)\];", source, flags=re.DOTALL)
    if not match:
        return set()
    return set(re.findall(r"'([^']+)'", match.group("body")))


def _extract_swift_enum_raw_values(source: str, enum_name: str) -> set[str]:
    match = re.search(rf"enum {re.escape(enum_name)}[^{{]*{{(?P<body>.*?)^}}", source, flags=re.DOTALL | re.MULTILINE)
    if not match:
        return set()
    values: set[str] = set()
    for line in match.group("body").splitlines():
        stripped = line.strip()
        if not stripped.startswith("case "):
            continue
        if "=" in stripped:
            raw_match = re.search(r'=\s*"([^"]+)"', stripped)
            if raw_match:
                values.add(raw_match.group(1))
        else:
            for name in stripped.removeprefix("case ").split(","):
                name = name.strip()
                if not name:
                    continue
                case_name = name.split()[0]
                if case_name:
                    values.add(case_name)
    return values


def _extract_swift_enum_cases(source: str, enum_name: str) -> set[str]:
    match = re.search(rf"enum {re.escape(enum_name)}[^{{]*{{(?P<body>.*?)^}}", source, flags=re.DOTALL | re.MULTILINE)
    if not match:
        return set()
    cases: set[str] = set()
    for line in match.group("body").splitlines():
        stripped = line.strip()
        if not stripped.startswith("case "):
            continue
        for name in stripped.removeprefix("case ").split(","):
            case_name = name.strip().split("=")[0].strip().split()[0]
            if case_name:
                cases.add(case_name)
    return cases


def _extract_apple_fixture_skill_ids(source: str) -> set[str]:
    return set(re.findall(r"return skill\(id:\s*\"([^\"]+)\"", source))


def audit_embeds() -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []

    registry_source = _read_repo_file("frontend/packages/ui/src/data/embedRegistry.generated.ts")
    showcase_source = _read_repo_file("frontend/apps/web_app/src/routes/dev/preview/embeds/[app]/+page.svelte")
    embed_models_source = _read_repo_file("apple/OpenMates/Sources/Core/Models/EmbedModels.swift")
    fixtures_source = _read_repo_file("apple/OpenMates/Sources/DevPreview/DevEmbedPreviewFixtures.swift")
    content_view_source = _read_repo_file("apple/OpenMates/Sources/Features/Embeds/Views/EmbedContentView.swift")

    preview_keys = _extract_ts_object_keys(registry_source, "EMBED_PREVIEW_COMPONENTS")
    fullscreen_keys = _extract_ts_object_keys(registry_source, "EMBED_FULLSCREEN_COMPONENTS")
    registry_keys = preview_keys | fullscreen_keys
    apple_types = _extract_swift_enum_raw_values(embed_models_source, "EmbedType")
    showcase_apps = _extract_showcase_apps(showcase_source)
    apple_apps = _extract_swift_enum_raw_values(fixtures_source, "DevEmbedPreviewApp")
    apple_fixture_skill_ids = _extract_apple_fixture_skill_ids(fixtures_source)

    if not registry_keys:
        errors.append("could not extract web embed registry keys")
    if not showcase_apps:
        errors.append("could not extract web embed showcase ALL_APPS")
    if not apple_types:
        errors.append("could not extract Apple EmbedType cases")
    if not apple_apps:
        errors.append("could not extract Apple DevEmbedPreviewApp cases")

    missing_showcase_apps = REQUIRED_EMBED_SHOWCASE_APPS - showcase_apps
    extra_missing_from_apple_gallery = REQUIRED_EMBED_SHOWCASE_APPS - apple_apps
    missing_apple_types = registry_keys - apple_types

    if missing_showcase_apps:
        errors.append(f"web embed showcase missing apps: {', '.join(sorted(missing_showcase_apps))}")
    if extra_missing_from_apple_gallery:
        errors.append(f"Apple embed preview gallery missing apps: {', '.join(sorted(extra_missing_from_apple_gallery))}")
    if missing_apple_types:
        errors.append(f"Apple EmbedType missing registry keys: {', '.join(sorted(missing_apple_types))}")

    for app in sorted(REQUIRED_EMBED_SHOWCASE_APPS):
        if f"case .{_swift_case_name_for_app(app)}" not in fixtures_source:
            errors.append(f"Apple DevEmbedPreviewFixtures.skills missing switch coverage for app: {app}")

    for registry_key in sorted(registry_keys):
        fixture_hint = registry_key.replace("app:", "").replace(":", "-").replace("_", "-")
        if fixture_hint not in apple_fixture_skill_ids and registry_key not in content_view_source:
            warnings.append(f"no direct Apple debug fixture id found for registry key: {registry_key}")

    forbidden_controls = ["Form {", "List {", "NavigationLink {", ".navigationTitle(", ".toolbar {"]
    embed_source_root = REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Features" / "Embeds"
    parity_paths = [
        path
        for path in embed_source_root.rglob("*.swift")
        if path.name != "ShareEmbedView.swift"
    ]
    embed_source = "\n".join(path.read_text(encoding="utf-8") for path in parity_paths)
    for forbidden in forbidden_controls:
        if forbidden in embed_source:
            errors.append(f"forbidden native product control in embed source: {forbidden}")

    warnings.append("visual/style contract checks are agent-reviewed for embeds until specific surfaces are promoted")
    return errors, warnings


def _swift_case_name_for_app(app_id: str) -> str:
    if "_" not in app_id:
        return app_id
    head, *tail = app_id.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in tail)


def promote_contract(source: Path, destination: Path) -> None:
    errors = validate_contract(source)
    if errors:
        raise ContractError("cannot promote invalid contract:\n" + "\n".join(f"- {error}" for error in errors))
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)


def swift_files_for_message_input() -> list[Path]:
    return [
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Features" / "Chat" / "Views" / "ChatView.swift",
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Features" / "Chat" / "Views" / "InlinePreviewView.swift",
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Features" / "Chat" / "Views" / "VoiceRecordingView.swift",
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Shared" / "Components" / "OMDesignPrimitives.swift",
    ]


def audit_message_input() -> tuple[list[str], list[str]]:
    errors = validate_contract(MESSAGE_INPUT_FIXTURE, surface="message-input")
    warnings: list[str] = []
    source = "\n".join(path.read_text(encoding="utf-8") for path in swift_files_for_message_input())

    for identifier in sorted(REQUIRED_MESSAGE_INPUT_IDENTIFIERS):
        if f'"{identifier}"' not in source:
            errors.append(f"missing Apple accessibility identifier: {identifier}")

    forbidden_controls = ["Form {", "List {", "NavigationLink {", ".navigationTitle(", ".toolbar {"]
    for forbidden in forbidden_controls:
        if forbidden in source:
            errors.append(f"forbidden native product control in message input source: {forbidden}")

    warnings.append("visual/style contract checks are warning-only for message-input until promoted")
    return errors, warnings


def audit_surface(surface: str) -> tuple[list[str], list[str]]:
    if surface == "message-input":
        return audit_message_input()
    if surface == "embeds":
        return audit_embeds()
    raise ContractError(f"unsupported audit surface: {surface}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate")
    validate_parser.add_argument("path", type=Path)
    validate_parser.add_argument("--surface")

    promote_parser = subparsers.add_parser("promote")
    promote_parser.add_argument("source", type=Path)
    promote_parser.add_argument("--destination", type=Path, default=MESSAGE_INPUT_FIXTURE)

    audit_parser = subparsers.add_parser("audit")
    audit_parser.add_argument("--surface", required=True, choices=["message-input", "embeds"])

    args = parser.parse_args()
    try:
        if args.command == "validate":
            errors = validate_contract(args.path, surface=args.surface)
            if errors:
                for error in errors:
                    print(f"ERROR: {error}", file=sys.stderr)
                return 1
            print(f"PASS {args.path}")
            return 0

        if args.command == "promote":
            promote_contract(args.source, args.destination)
            print(f"PROMOTED {args.source} -> {args.destination}")
            return 0

        if args.command == "audit":
            errors, warnings = audit_surface(args.surface)
            for warning in warnings:
                print(f"WARNING: {warning}")
            if errors:
                for error in errors:
                    print(f"ERROR: {error}", file=sys.stderr)
                return 1
            print(f"PASS {args.surface} audit")
            return 0
    except ContractError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
