#!/usr/bin/env python3
"""Validate, promote, and audit web-rendered Apple UI contract fixtures.

Contracts are generated by Playwright from browser-rendered DOM/computed style
and promoted intentionally before Apple UI tests consume them. Structural and
testability drift fails while visual drift is reported as warning metadata until
individual values are promoted to failure gates.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = REPO_ROOT / "apple" / "OpenMatesUITests" / "Fixtures" / "WebUIContracts"
MESSAGE_INPUT_FIXTURE = FIXTURE_DIR / "message-input.json"
EMBEDS_FIXTURE = FIXTURE_DIR / "embeds.json"
SETTINGS_FIXTURE = FIXTURE_DIR / "settings.json"

REQUIRED_MESSAGE_INPUT_STATES = {
    "default",
    "focused",
    "image-pending-embed",
    "file-pending-embed",
    "recording-overlay",
}
REQUIRED_MESSAGE_INPUT_IDENTIFIERS = {
    "message-editor",
    "action-buttons",
    "composer-attachment-toggle",
    "composer-attachment-menu",
    "record-audio-button",
    "record-overlay",
    "release-text",
    "record-shortcuts",
    "record-controls",
    "record-action-buttons",
    "record-cancel-button",
    "record-finish-button",
    "timer-pill",
    "embed-full-width-wrapper",
    "pending-composer-embed",
    "pending-composer-embed-remove",
}
REQUIRED_SETTINGS_STATES = {
    "authenticated-root-expanded",
    "authenticated-root-collapsed",
    "account-destination-header",
}
REQUIRED_SETTINGS_TEST_IDS_BY_STATE = {
    "authenticated-root-expanded": {
        "settings-menu",
        "settings-banner-shell",
        "icon-button-close",
        "credits-row",
        "incognito-toggle-wrapper",
        "learning-mode-toggle-wrapper",
    },
    "authenticated-root-collapsed": {
        "settings-menu",
        "settings-banner-shell",
        "icon-button-close",
        "credits-row",
        "incognito-toggle-wrapper",
        "learning-mode-toggle-wrapper",
    },
    "account-destination-header": {
        "settings-menu",
        "settings-banner-shell",
        "icon-button-close",
    },
}
SETTINGS_VIEWPORT = {"width": 390, "height": 844}
REQUIRED_EMBED_SHOWCASE_APPS = {
    "audio",
    "code",
    "docs",
    "electronics",
    "events",
    "finance",
    "health",
    "home",
    "images",
    "mail",
    "maps",
    "math",
    "music",
    "news",
    "nutrition",
    "pdf",
    "reminder",
    "sheets",
    "shopping",
    "social_media",
    "tasks",
    "travel",
    "videos",
    "weather",
    "web",
    "workflows",
}
REQUIRED_EMBED_REGISTRY_DIMENSIONS = {
    "iphone-light-ltr",
}
REQUIRED_APP_SPECIFIC_EMBED_IDENTIFIERS = {
    "models3d-generate-fullscreen",
    "models3d-generate-preview",
    "models3d-result-card",
    "models3d-result-fullscreen",
    "models3d-search-fullscreen",
    "models3d-search-preview",
    "task-create-embed-preview",
    "task-embed-card",
    "task-embed-fullscreen",
    "task-parent-fullscreen",
    "task-search-embed-preview",
    "workflow-create-embed-preview",
    "workflow-embed-card",
    "workflow-embed-fullscreen",
    "workflow-parent-fullscreen",
    "workflow-search-embed-preview",
}
EMBED_REGISTRY_FIXTURE_ALIASES = {
    "app:calendar:get-events": {"calendar-get-events"},
    "app:calendar:create-event": {"calendar-create-event"},
    "app:calendar:update-event": {"calendar-update-event"},
    "app:calendar:delete-event": {"calendar-delete-event"},
    # Same native renderer/fixture as the standard image generation card.
    "app:images:generate_draft": {"images-generate"},
    # Native fixture IDs intentionally use shorter display-route names than the
    # generated app-skill registry keys.
    "app:travel:search_connections": {"travel-search"},
    "app:travel:search_stays": {"travel-stays"},
    "app:travel:get_flight": {"travel-get-flight"},
    # Child embed renderers are covered through standalone and grouped fixtures.
    "image": {"images-upload"},
    "images-image-result": {"images-result", "images-search"},
    "maps-place": {"maps-search"},
    "app:workflows:create-or-modify": {"workflows-create"},
    "business-company-financial-result": {"business-financial-result", "business-company-financials"},
    "design-icon-result": {"design-icon-result", "design-search-icons"},
    "models3d-model-result": {"models3d-model-result", "models3d-search"},
    "tasks-task": {"tasks-task", "tasks-create", "tasks-search"},
    "workflows-workflow": {"workflows-workflow", "workflows-create", "workflows-search"},
}
EMBED_REGISTRY_RENDERER_ONLY_KEYS = {
    # Focus-mode activation is a direct message embed, not an app showcase route.
    "focus-mode-activation",
}
ALLOWED_SEVERITIES = {"fail", "warn"}
PRIVATE_VALUE_PATTERNS = [
    re.compile(r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}", re.IGNORECASE),
    re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"),
    re.compile(r"openmates_test_account", re.IGNORECASE),
    re.compile(r"chat-id=", re.IGNORECASE),
]


class ContractError(Exception):
    """Raised for contract validation or audit failures."""


def load_contract(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ContractError(f"contract file not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ContractError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ContractError("contract root must be an object")
    return data


def walk_values(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        values: list[str] = []
        for item in value:
            values.extend(walk_values(item))
        return values
    if isinstance(value, dict):
        values = []
        for item in value.values():
            values.extend(walk_values(item))
        return values
    return []


def validate_contract(path: Path, *, surface: str | None = None) -> list[str]:
    contract = load_contract(path)
    errors: list[str] = []

    if contract.get("schemaVersion") != 1:
        errors.append("schemaVersion must be 1")
    if not isinstance(contract.get("surface"), str):
        errors.append("surface must be a string")
    if surface and contract.get("surface") != surface:
        errors.append(f"surface must be {surface!r}")
    if not isinstance(contract.get("generatedAt"), str) and contract.get("surface") != "embeds":
        errors.append("generatedAt must be a string")
    viewport = contract.get("viewport")
    if contract.get("surface") != "embeds" and (
        not isinstance(viewport, dict) or not isinstance(viewport.get("width"), int) or not isinstance(viewport.get("height"), int)
    ):
        errors.append("viewport.width and viewport.height must be integers")

    if contract.get("surface") == "embeds":
        return errors + validate_embeds_contract(contract)

    states = contract.get("states")
    if not isinstance(states, list) or not states:
        errors.append("states must be a non-empty array")
        states = []

    state_ids: set[str] = set()
    test_ids_by_state: dict[str, set[str]] = {}
    for state in states:
        if not isinstance(state, dict):
            errors.append("state entries must be objects")
            continue
        state_id = state.get("id")
        if not isinstance(state_id, str) or not state_id:
            errors.append("state.id must be a non-empty string")
        else:
            state_ids.add(state_id)
            test_ids_by_state[state_id] = set()
        elements = state.get("elements")
        if not isinstance(elements, list) or not elements:
            errors.append(f"state {state_id or '<unknown>'} must contain elements")
            continue
        for element in elements:
            if not isinstance(element, dict):
                errors.append(f"state {state_id} has a non-object element")
                continue
            for required_field in ("semanticId", "testId", "severity", "structure", "computedStyle"):
                if required_field not in element:
                    errors.append(f"state {state_id} element missing {required_field}")
            if element.get("severity") not in ALLOWED_SEVERITIES:
                errors.append(f"state {state_id} has invalid severity {element.get('severity')!r}")
            if element.get("required", True) and element.get("exists") is not True:
                errors.append(f"state {state_id} required element {element.get('testId')} does not exist")
            if (
                isinstance(state_id, str)
                and state_id in test_ids_by_state
                and isinstance(element.get("testId"), str)
            ):
                test_ids_by_state[state_id].add(element["testId"])

    if contract.get("surface") == "message-input":
        missing_states = REQUIRED_MESSAGE_INPUT_STATES - state_ids
        if missing_states:
            errors.append(f"missing message-input states: {', '.join(sorted(missing_states))}")

    if contract.get("surface") == "settings":
        missing_states = REQUIRED_SETTINGS_STATES - state_ids
        if missing_states:
            errors.append(f"missing settings states: {', '.join(sorted(missing_states))}")
        for state_id, required_test_ids in REQUIRED_SETTINGS_TEST_IDS_BY_STATE.items():
            missing_test_ids = required_test_ids - test_ids_by_state.get(state_id, set())
            if missing_test_ids:
                errors.append(f"state {state_id} missing settings test IDs: {', '.join(sorted(missing_test_ids))}")
        if viewport != SETTINGS_VIEWPORT:
            errors.append("settings viewport must be 390x844")

    for value in walk_values(contract):
        for pattern in PRIVATE_VALUE_PATTERNS:
            if pattern.search(value):
                errors.append(f"contract contains private or volatile value matching {pattern.pattern!r}")
                break

    return errors


def validate_embeds_contract(contract: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    dimension = contract.get("dimension")
    if not isinstance(dimension, dict) or not isinstance(dimension.get("id"), str):
        errors.append("embeds contract requires dimension.id")

    apps = contract.get("apps")
    if not isinstance(apps, list) or not apps:
        errors.append("embeds contract requires a non-empty apps array")
        apps = []
    app_ids = {app.get("appId") for app in apps if isinstance(app, dict) and isinstance(app.get("appId"), str)}
    missing_apps = REQUIRED_EMBED_SHOWCASE_APPS - app_ids
    if missing_apps:
        errors.append(f"embeds contract missing apps: {', '.join(sorted(missing_apps))}")

    surfaces = contract.get("surfaces")
    if not isinstance(surfaces, list) or not surfaces:
        errors.append("embeds contract requires a non-empty surfaces array")
        surfaces = []
    for surface_entry in surfaces:
        if not isinstance(surface_entry, dict):
            errors.append("embeds contract surface entries must be objects")
            continue
        key = surface_entry.get("key")
        if not isinstance(key, str) or not key:
            errors.append("embeds contract surface entry missing key")
        if surface_entry.get("appId") not in app_ids:
            errors.append(f"embeds contract surface {key or '<unknown>'} references unknown appId")
        sources = surface_entry.get("sources")
        if not isinstance(sources, dict) or sources.get("preview") is not True or sources.get("fullscreen") is not True:
            errors.append(f"embeds contract surface {key or '<unknown>'} must include preview and fullscreen sources")
        previews = surface_entry.get("previews")
        if not isinstance(previews, list) or not previews:
            errors.append(f"embeds contract surface {key or '<unknown>'} must include preview captures")
        fullscreen = surface_entry.get("fullscreen")
        if not isinstance(fullscreen, dict):
            errors.append(f"embeds contract surface {key or '<unknown>'} must include fullscreen capture")
        # Legacy per-app surfaces remain useful DOM contracts, but requiring
        # separate section/fullscreen PNGs duplicates the exhaustive registry
        # captures below. Keep the complete DOM inventory without hundreds of
        # redundant screenshots.

    registry_surfaces = contract.get("registrySurfaces")
    if not isinstance(registry_surfaces, list):
        errors.append("embeds contract requires registrySurfaces array")
        registry_surfaces = []

    if isinstance(dimension, dict) and dimension.get("id") in REQUIRED_EMBED_REGISTRY_DIMENSIONS:
        registry_source = _read_repo_file("frontend/packages/ui/src/data/embedRegistry.generated.ts")
        preview_keys = _extract_ts_object_keys(registry_source, "EMBED_PREVIEW_COMPONENTS")
        fullscreen_keys = _extract_ts_object_keys(registry_source, "EMBED_FULLSCREEN_COMPONENTS")
        expected = {(key, "preview") for key in preview_keys} | {
            (key, "fullscreen") for key in fullscreen_keys
        }
        actual: set[tuple[str, str]] = set()
        for entry in registry_surfaces:
            if not isinstance(entry, dict):
                errors.append("embeds contract registry surface entries must be objects")
                continue
            key, surface = entry.get("registryKey"), entry.get("surface")
            if not isinstance(key, str) or surface not in {"preview", "fullscreen"}:
                errors.append("embeds contract registry surface has invalid key or surface")
                continue
            identity = (key, surface)
            if identity in actual:
                errors.append(f"embeds contract has duplicate registry surface: {key}:{surface}")
            actual.add(identity)
            if entry.get("exists") is not True or entry.get("renderError") is True:
                errors.append(f"embeds contract registry surface did not render: {key}:{surface}")
            if not isinstance(entry.get("capture"), dict):
                errors.append(f"embeds contract registry surface missing rendered capture: {key}:{surface}")
            screenshot = entry.get("screenshotPath")
            if not isinstance(screenshot, str) or not screenshot.strip():
                errors.append(f"embeds contract registry surface missing screenshot: {key}:{surface}")
            elif screenshot.startswith(("/", "~")) or re.match(r"^[A-Za-z]:[/\\]", screenshot):
                errors.append(f"embeds contract registry screenshot must be relative: {key}:{surface}")

        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        if missing:
            errors.append(
                f"embeds contract missing {len(missing)} registry surfaces: "
                + ", ".join(f"{key}:{surface}" for key, surface in missing[:8])
            )
        if extra:
            errors.append(
                f"embeds contract has {len(extra)} unknown registry surfaces: "
                + ", ".join(f"{key}:{surface}" for key, surface in extra[:8])
            )

    for value in walk_values(contract):
        for pattern in PRIVATE_VALUE_PATTERNS:
            if pattern.search(value):
                errors.append(f"contract contains private or volatile value matching {pattern.pattern!r}")
                break

    return errors


def _read_repo_file(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def _extract_ts_object_keys(source: str, const_name: str) -> set[str]:
    match = re.search(
        rf"export const {re.escape(const_name)}:[^=]+=\s*{{(?P<body>.*?)^}};",
        source,
        flags=re.DOTALL | re.MULTILINE,
    )
    if not match:
        return set()
    return set(re.findall(r'^[ \t]*"([^"]+)"[ \t]*:', match.group("body"), flags=re.MULTILINE))


def _extract_showcase_apps(source: str) -> set[str]:
    match = re.search(r"export const EMBED_APP_SLUGS = \[(?P<body>.*?)\] as const;", source, flags=re.DOTALL)
    if not match:
        return set()
    return set(re.findall(r"'([^']+)'", match.group("body")))


def _extract_swift_enum_raw_values(source: str, enum_name: str) -> set[str]:
    match = re.search(rf"enum {re.escape(enum_name)}[^{{]*{{(?P<body>.*?)^}}", source, flags=re.DOTALL | re.MULTILINE)
    if not match:
        return set()
    values: set[str] = set()
    for line in match.group("body").splitlines():
        stripped = line.strip()
        if not stripped.startswith("case "):
            continue
        if "=" in stripped:
            raw_match = re.search(r'=\s*"([^"]+)"', stripped)
            if raw_match:
                values.add(raw_match.group(1))
        else:
            for name in stripped.removeprefix("case ").split(","):
                name = name.strip()
                if not name:
                    continue
                case_name = name.split()[0]
                if case_name:
                    values.add(case_name)
    return values


def _extract_swift_enum_cases(source: str, enum_name: str) -> set[str]:
    match = re.search(rf"enum {re.escape(enum_name)}[^{{]*{{(?P<body>.*?)^}}", source, flags=re.DOTALL | re.MULTILINE)
    if not match:
        return set()
    cases: set[str] = set()
    for line in match.group("body").splitlines():
        stripped = line.strip()
        if not stripped.startswith("case "):
            continue
        for name in stripped.removeprefix("case ").split(","):
            case_name = name.strip().split("=")[0].strip().split()[0]
            if case_name:
                cases.add(case_name)
    return cases


def _extract_swift_enum_raw_value_to_case(source: str, enum_name: str) -> dict[str, str]:
    match = re.search(rf"enum {re.escape(enum_name)}[^{{]*{{(?P<body>.*?)^}}", source, flags=re.DOTALL | re.MULTILINE)
    if not match:
        return {}
    raw_to_case: dict[str, str] = {}
    for line in match.group("body").splitlines():
        stripped = line.strip()
        if not stripped.startswith("case "):
            continue
        for entry in stripped.removeprefix("case ").split(","):
            entry = entry.strip()
            if not entry or entry.startswith("."):
                continue
            case_name = entry.split("=")[0].strip().split()[0]
            if not case_name:
                continue
            raw_match = re.search(r'=\s*"([^"]+)"', entry)
            raw_to_case[raw_match.group(1) if raw_match else case_name] = case_name
    return raw_to_case


def _extract_apple_fixture_skill_ids(source: str) -> set[str]:
    direct = re.findall(r"\bskill\(id:\s*\"([^\"]+)\"", source)
    helper_calls = re.findall(r"calendarAction\(id:\s*\"([^\"]+)\"", source)
    return set(direct + helper_calls)


def _swift_mask(source: str) -> str:
    """Mask comments/strings without changing positions for balanced Swift blocks."""
    return re.sub(
        r'//[^\n]*|/\*.*?\*/|""".*?"""|"(?:\\.|[^"\\])*"',
        lambda match: re.sub(r"[^\n]", " ", match.group()), source, flags=re.DOTALL,
    )


def _swift_without_comments(source: str) -> str:
    return re.sub(
        r'""".*?"""|"(?:\\.|[^"\\])*"|//[^\n]*|/\*.*?\*/',
        lambda match: re.sub(r"[^\n]", " ", match.group()) if match.group().startswith(("//", "/*")) else match.group(),
        source, flags=re.DOTALL,
    )


def _swift_block(source: str, anchor: str) -> str:
    match = re.search(anchor, source)
    if not match:
        return ""
    mask = _swift_mask(source)
    start = mask.find("{", match.end())
    if start < 0:
        return ""
    depth = 1
    for end in range(start + 1, len(mask)):
        depth += (mask[end] == "{") - (mask[end] == "}")
        if depth == 0:
            return source[start + 1:end]
    return ""


def _swift_cases(body: str) -> dict[str, str]:
    mask = _swift_mask(body)
    starts = []
    for match in re.finditer(r"^\s*(case\s+[^:]+:|default:)", body, re.MULTILINE):
        prefix = mask[:match.start()]
        if prefix.count("{") == prefix.count("}"):
            starts.append(match)
    result = {}
    for index, match in enumerate(starts):
        end = starts[index + 1].start() if index + 1 < len(starts) else len(body)
        names = re.findall(r"\.([A-Za-z][A-Za-z0-9_]*)", match.group()) or ["default"]
        for name in names:
            result[name] = body[match.end():end]
    return result


def _fixture_registry_types(source: str, raw_to_case: dict[str, str]) -> set[str]:
    # Literal records and typed helper calls both create real gallery fixtures;
    # their IDs need not be the registry key's spelling.
    source = _swift_without_comments(source)
    literals = set(re.findall(r'\btype:\s*"([^"]+)"', source))
    cases = set(re.findall(r"\b(?:type|childType):\s*(?:EmbedType)?\.([A-Za-z][A-Za-z0-9_]*)", source))
    return literals | {raw for raw, case in raw_to_case.items() if case in cases}


SHARED_APP_SKILL_PARENTS = {
    "app:design:search_icons", "app:mail:search", "app:maps:search",
    "app:social_media:get-posts", "app:social_media:search",
}


def _predicate_registry_keys(source: str, owner: str, method: str) -> set[str]:
    """Resolve positive type predicates used by the renderer entry view.

    Only explicit true comparisons and whole contains expressions count. A type
    mentioned in a false branch, comment, or unrelated helper is not coverage.
    Unsupported predicate forms fail closed through the missing-route check.
    """
    owner_body = _swift_block(_swift_without_comments(source), rf"\b(?:enum|struct|class)\s+{re.escape(owner)}\b[^{{]*")
    predicate = _swift_block(owner_body, rf"\bfunc\s+{re.escape(method)}\([^{{]*\)\s*->\s*Bool\s*")
    keys = set(re.findall(r'if\s+embed\.type\s*==\s*"([^"]+)"\s*\{\s*return\s+true\s*\}', predicate))
    contains = re.fullmatch(r'\s*(?:return\s+)?\[(?P<keys>[^\]]+)\]\.contains\(embed\.type\)\s*', predicate)
    if contains:
        keys.update(re.findall(r'"([^"]+)"', contains.group("keys")))
    comparison = re.fullmatch(r'\s*(?:return\s+)?embed\.type\s*==\s*"([^"]+)"\s*', predicate)
    if comparison:
        keys.add(comparison.group(1))
    return keys


def _native_embed_dispatch(
    keys: set[str], raw_to_case: dict[str, str], content: str, parent: str,
    predicate_sources: str = "",
) -> tuple[list[str], list[str]]:
    """Check actual entry routes in both modes, not merely enum/fixture names.

    This is a source-structure gate. Shared search parents are review warnings;
    no visual or functional equivalence is inferred from an accepted route.
    """
    errors: list[str] = []
    warnings: list[str] = []
    content = _swift_without_comments(content)
    parent = _swift_without_comments(parent)
    parent_entry = _swift_block(content, r"if\s+(?:shouldUseCompositeRenderer|embed\.isAppSkillUse)\s*")
    composite_gate = _swift_block(content, r"var\s+shouldUseCompositeRenderer\s*:[^{{]+")
    has_parent_entry = (
        "AppSkillUseRenderer(" in _swift_mask(parent_entry)
        and bool(re.search(r"\bmode:\s*mode\b", _swift_mask(parent_entry)))
        and ("embed.isAppSkillUse" in composite_gate or "if embed.isAppSkillUse" in content)
    )
    direct = _swift_cases(_swift_block(content, r"switch\s+embedType\s*"))
    predicate_routes: dict[str, str] = {}
    entry_body = _swift_block(content, r"var\s+body\s*:\s*some\s+View\s*")
    for match in re.finditer(r"\bif\s+(\w+)\.(\w+)\(embed\)\s*\{", entry_body):
        owner, method = match.groups()
        branch = _swift_block(entry_body[match.start():], r"if\s+\w+\.\w+\(embed\)\s*")
        for key in _predicate_registry_keys(predicate_sources, owner, method):
            predicate_routes.setdefault(key, branch)
    # Tuple case labels contain strings rather than .enum names. Extract them
    # independently from the specializedKind function's explicit return cases.
    kind_source = _swift_block(parent, r"func\s+specializedKind\([^{{\n]*")
    specialized_keys = {
        f"app:{app}:{skill}": kind
        for labels, kind in re.findall(r"case\s+(.*?):\s*return\s+\.([A-Za-z][A-Za-z0-9_]*)", kind_source, re.DOTALL)
        for app, skill in re.findall(r'\("([^"]+)",\s*"([^"]+)"\)', labels)
    }
    for mode in ("preview", "fullscreen"):
        body = _swift_block(parent, rf"private\s+var\s+{mode}\s*:[^{{]+")
        routes: dict[str, str] = {}
        for match in re.finditer(r"\b(?:if|else if)\s+([^{}]+)\{", body):
            prefix = _swift_mask(body[:match.start()])
            if prefix.count("{") != prefix.count("}"):
                continue
            condition = match.group(1)
            branch = _swift_block(body[match.start():], r"\bif\s+[^{}]+")
            # Named boolean predicates are defined beside the dispatch chain.
            if re.fullmatch(r"is\w+", condition.strip()):
                condition = _swift_block(parent, rf"var\s+{condition.strip()}\s*:\s*Bool\s*")
            apps = re.findall(r'appId\s*==\s*"([^"]+)"', condition)
            skills = re.findall(r'skillId\s*==\s*"([^"]+)"', condition)
            skills += re.findall(r'"([^"]+)"', condition.split("&&", 1)[-1]) if ".contains(skillId)" in condition else []
            for app in apps:
                for skill in skills:
                    routes[f"app:{app}:{skill}"] = branch
        special_function = _swift_block(parent, rf"func\s+specialized{mode.title()}\([^{{\n]*")
        special_bodies = _swift_cases(_swift_block(special_function, r"switch\s+kind\s*"))
        if "Self.specializedKind(" in body and f"specialized{mode.title()}(specialized)" in body:
            for key, kind in specialized_keys.items():
                routes[key] = special_bodies.get(kind, "")
        fallback = ""
        for match in re.finditer(r"\belse\s*\{", body):
            prefix = _swift_mask(body[:match.start()])
            if prefix.count("{") == prefix.count("}"):
                fallback = _swift_block(body[match.start():], r"else\s*")
        fallback_code = _swift_mask(fallback)
        shared_exists = ("textSearchPreview" in fallback_code if mode == "preview" else "SearchResultFullscreenRow(" in fallback_code)
        for key in sorted(keys):
            case = raw_to_case.get(key)
            if not case:
                continue  # enum absence has its own precise error
            if key in predicate_routes:
                branch = predicate_routes[key]
                has_mode = bool(re.search(r"\bmode:\s*mode\b", _swift_mask(branch)))
            elif key.startswith("app:"):
                if not has_parent_entry:
                    errors.append(f"missing Apple app-skill entry route ({mode}): {key}")
                    continue
                branch = routes.get(key, "")
                if key not in routes and key in SHARED_APP_SKILL_PARENTS and shared_exists and "GenericEmbedRenderer" not in fallback_code:
                    warnings.append(f"shared AppSkillUseRenderer parent ({mode}): {key}; review visual/behavior parity")
                    continue
                if key not in routes and "GenericEmbedRenderer" in fallback_code:
                    branch = fallback
                has_mode = bool(re.search(rf"\bmode:\s*\.{mode}\b", _swift_mask(branch)))
            else:
                branch = direct.get(case, direct.get("default", ""))
                has_mode = bool(re.search(r"\bmode:\s*mode\b", _swift_mask(branch)))
            branch_code = _swift_mask(branch)
            if "GenericEmbedRenderer" in branch_code:
                errors.append(f"known Apple embed uses generic fallback ({mode}): {key}")
            elif not branch or not has_mode or not re.search(r"\b\w*(?:Renderer|SkillCard)\s*\(", branch_code):
                errors.append(f"missing concrete Apple embed route ({mode}): {key}")
    return errors, warnings


def _extract_generic_embed_cases(source: str) -> set[str]:
    cases: set[str] = set()
    for match in re.finditer(
        r"case\s+(?P<cases>[^:]+):(?P<body>.*?)(?=\n\s*(?:case\s+|default:)|\Z)",
        source,
        flags=re.DOTALL,
    ):
        if "GenericEmbedRenderer" not in match.group("body"):
            continue
        cases.update(re.findall(r"\.([A-Za-z][A-Za-z0-9_]*)", match.group("cases")))
    return cases


def _has_apple_embed_registry_coverage(
    registry_key: str,
    *,
    apple_fixture_skill_ids: set[str],
    embed_type_cases_by_raw_value: dict[str, str],
    content_view_source: str,
) -> bool:
    fixture_hint = registry_key.replace("app:", "").replace(":", "-").replace("_", "-")
    fixture_ids = {fixture_hint} | EMBED_REGISTRY_FIXTURE_ALIASES.get(registry_key, set())
    if fixture_ids & apple_fixture_skill_ids:
        return True

    case_name = embed_type_cases_by_raw_value.get(registry_key)
    if registry_key in EMBED_REGISTRY_RENDERER_ONLY_KEYS and case_name and f".{case_name}" in content_view_source:
        return True

    return False


def _embed_registry_source(web_root: Path) -> str:
    registry = web_root / "frontend/packages/ui/src/data/embedRegistry.generated.ts"
    if registry.exists():
        return registry.read_text(encoding="utf-8")
    # Read YAML through the web package's existing dependency. Never import/run
    # the generator, which writes shared source; mirror its active component-map
    # rules (including virtual definitions and composite child registration).
    node = shutil.which("node")
    if not node:
        raise ContractError("missing generated embed registry and Node.js needed to read canonical YAML")
    reader = r'''
const fs = require('fs'), path = require('path');
const root = process.argv[1];
const yaml = require(require.resolve('yaml', {paths: [path.join(root, 'frontend/packages/ui')]}));
const defs = [];
for (const app of fs.readdirSync(path.join(root, 'backend/apps')).sort()) {
  const p = path.join(root, 'backend/apps', app, 'app.yml');
  if (!fs.existsSync(p)) continue;
  for (const d of yaml.parse(fs.readFileSync(p, 'utf8'))?.embed_types || [])
    if (d.default_enabled !== false) defs.push({...d, app_id: app});
}
for (const d of yaml.parse(fs.readFileSync(path.join(root, 'shared/config/embed_types.yml'), 'utf8'))?.embed_types || [])
  if (d.default_enabled !== false) defs.push(d);
process.stdout.write(JSON.stringify(defs));
'''
    try:
        result = subprocess.run([node, "-e", reader, str(web_root)], capture_output=True, text=True, timeout=30, check=True)
        definitions = json.loads(result.stdout)
    except (subprocess.SubprocessError, json.JSONDecodeError) as exc:
        raise ContractError(f"cannot read canonical embed YAML using the existing web YAML dependency: {exc}") from exc
    maps: dict[str, dict[str, str]] = {"EMBED_PREVIEW_COMPONENTS": {}, "EMBED_FULLSCREEN_COMPONENTS": {}}
    for definition in definitions:
        if definition.get("category") == "app-skill-use" and definition.get("app_id") and definition.get("skill_id"):
            key = f"app:{definition['app_id']}:{definition['skill_id']}"
        elif definition.get("category") == "direct" and definition.get("frontend_type"):
            key = definition["frontend_type"]
        else:
            continue
        for mode, const in (("preview", "EMBED_PREVIEW_COMPONENTS"), ("fullscreen", "EMBED_FULLSCREEN_COMPONENTS")):
            component = definition.get(f"{mode}_component")
            if component and (mode != "fullscreen" or component != "null"):
                maps[const][key] = component
            child_component = definition.get(f"child_{mode}_component")
            if definition.get("has_children") and definition.get("child_frontend_type") and child_component:
                maps[const][definition["child_frontend_type"]] = child_component
    return "\n".join(
        f"export const {name}: Record<string, string> = {{\n"
        + "\n".join(f"  {json.dumps(key)}: {json.dumps(value)}," for key, value in sorted(values.items())) + "\n};"
        for name, values in maps.items()
    )


def audit_embeds(*, web_root: Path | None = None, native_root: Path | None = None) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []

    web_root = web_root or REPO_ROOT
    native_root = native_root or REPO_ROOT
    registry_source = _embed_registry_source(web_root)
    showcase_source = (web_root / "frontend/apps/web_app/src/routes/dev/preview/embeds/[app=embedApp]/+page.svelte").read_text()
    showcase_apps_source = (web_root / "frontend/apps/web_app/src/lib/devPreviewEmbedApps.ts").read_text()
    embed_models_source = (native_root / "apple/OpenMates/Sources/Core/Models/EmbedModels.swift").read_text()
    preview_root = native_root / "apple/OpenMates/Sources/DevPreview"
    fixture_paths = sorted(set(preview_root.glob("Dev*EmbedFixtures.swift")) | {preview_root / "DevEmbedPreviewFixtures.swift"})
    fixtures_source = "\n".join(path.read_text() for path in fixture_paths)
    content_view_source = (native_root / "apple/OpenMates/Sources/Features/Embeds/Views/EmbedContentView.swift").read_text()
    parent_source = (native_root / "apple/OpenMates/Sources/Features/Embeds/Renderers/AppSkillUseRenderer.swift").read_text()
    embed_source_root = native_root / "apple" / "OpenMates" / "Sources" / "Features" / "Embeds"
    predicate_sources = "\n".join(path.read_text() for path in sorted(embed_source_root.rglob("*.swift")))

    preview_keys = _extract_ts_object_keys(registry_source, "EMBED_PREVIEW_COMPONENTS")
    fullscreen_keys = _extract_ts_object_keys(registry_source, "EMBED_FULLSCREEN_COMPONENTS")
    registry_keys = preview_keys | fullscreen_keys
    apple_types = _extract_swift_enum_raw_values(embed_models_source, "EmbedType")
    apple_type_cases_by_raw_value = _extract_swift_enum_raw_value_to_case(embed_models_source, "EmbedType")
    showcase_apps = _extract_showcase_apps(showcase_apps_source)
    apple_apps = _extract_swift_enum_raw_values(fixtures_source, "DevEmbedPreviewApp")
    apple_fixture_skill_ids = _extract_apple_fixture_skill_ids(fixtures_source)
    fixture_registry_types = _fixture_registry_types(fixtures_source, apple_type_cases_by_raw_value)
    generic_embed_cases = _extract_generic_embed_cases(content_view_source)

    if not registry_keys:
        errors.append("could not extract web embed registry keys")
    if not showcase_apps:
        errors.append("could not extract web embed showcase EMBED_APP_SLUGS")
    if "EMBED_APP_SLUGS" not in showcase_source:
        errors.append("web embed showcase does not use EMBED_APP_SLUGS")
    if not apple_types:
        errors.append("could not extract Apple EmbedType cases")
    if not apple_apps:
        errors.append("could not extract Apple DevEmbedPreviewApp cases")

    missing_showcase_apps = REQUIRED_EMBED_SHOWCASE_APPS - showcase_apps
    extra_missing_from_apple_gallery = REQUIRED_EMBED_SHOWCASE_APPS - apple_apps
    missing_apple_types = registry_keys - apple_types
    missing_preview_components = fullscreen_keys - preview_keys
    missing_fullscreen_components = preview_keys - fullscreen_keys

    if missing_showcase_apps:
        errors.append(f"web embed showcase missing apps: {', '.join(sorted(missing_showcase_apps))}")
    if extra_missing_from_apple_gallery:
        errors.append(f"Apple embed preview gallery missing apps: {', '.join(sorted(extra_missing_from_apple_gallery))}")
    if missing_apple_types:
        errors.append(f"Apple EmbedType missing registry keys: {', '.join(sorted(missing_apple_types))}")
    if missing_preview_components:
        errors.append(
            "web embed registry keys missing preview components: "
            + ", ".join(sorted(missing_preview_components))
        )
    if missing_fullscreen_components:
        errors.append(
            "web embed registry keys missing fullscreen components: "
            + ", ".join(sorted(missing_fullscreen_components))
        )

    generic_registry_keys = sorted(
        key
        for key in registry_keys
        if apple_type_cases_by_raw_value.get(key) in generic_embed_cases
    )
    if generic_registry_keys:
        errors.append(
            "known Apple embed types use GenericEmbedRenderer: "
            + ", ".join(generic_registry_keys)
        )

    for app in sorted(REQUIRED_EMBED_SHOWCASE_APPS):
        if f"case .{_swift_case_name_for_app(app)}" not in fixtures_source:
            errors.append(f"Apple DevEmbedPreviewFixtures.skills missing switch coverage for app: {app}")

    for registry_key in sorted(registry_keys):
        if registry_key not in fixture_registry_types and not _has_apple_embed_registry_coverage(
            registry_key,
            apple_fixture_skill_ids=apple_fixture_skill_ids,
            embed_type_cases_by_raw_value=apple_type_cases_by_raw_value,
            content_view_source=content_view_source,
        ):
            errors.append(f"missing Apple debug fixture for registry key: {registry_key}")

    route_errors, route_warnings = _native_embed_dispatch(registry_keys, apple_type_cases_by_raw_value, content_view_source, parent_source, predicate_sources)
    errors.extend(route_errors)
    warnings.extend(route_warnings)
    warnings.append(f"structural registry coverage: {len(preview_keys)} web previews, {len(fullscreen_keys)} web fullscreens; visual/functional parity is not established")

    forbidden_controls = ["Form {", "List {", "NavigationLink {", ".navigationTitle(", ".toolbar {"]
    parity_paths = [
        path
        for path in embed_source_root.rglob("*.swift")
        if path.name != "ShareEmbedView.swift"
    ]
    embed_source = "\n".join(path.read_text(encoding="utf-8") for path in parity_paths)
    for forbidden in forbidden_controls:
        if forbidden in embed_source:
            errors.append(f"forbidden native product control in embed source: {forbidden}")

    missing_specific_identifiers = sorted(
        identifier for identifier in REQUIRED_APP_SPECIFIC_EMBED_IDENTIFIERS if f'"{identifier}"' not in embed_source
    )
    if missing_specific_identifiers:
        errors.append(
            "Apple embed source missing app-specific preview/fullscreen identifiers: "
            + ", ".join(missing_specific_identifiers)
        )

    warnings.append("visual/style contract checks are agent-reviewed for embeds until specific surfaces are promoted")
    return errors, warnings


def _swift_case_name_for_app(app_id: str) -> str:
    if "_" not in app_id:
        return app_id
    head, *tail = app_id.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in tail)


def promote_contract(source: Path, destination: Path | None) -> None:
    errors = validate_contract(source)
    if errors:
        raise ContractError("cannot promote invalid contract:\n" + "\n".join(f"- {error}" for error in errors))
    if destination is None:
        surface = load_contract(source).get("surface")
        if surface == "embeds":
            destination = EMBEDS_FIXTURE
        elif surface == "settings":
            destination = SETTINGS_FIXTURE
        else:
            destination = MESSAGE_INPUT_FIXTURE
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)


def swift_files_for_message_input() -> list[Path]:
    return [
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Features" / "Chat" / "Views" / "ChatView.swift",
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Features" / "Chat" / "Views" / "InlinePreviewView.swift",
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Features" / "Chat" / "Views" / "VoiceRecordingView.swift",
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Shared" / "Composer" / "ComposerAttachmentActionRow.swift",
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Shared" / "Components" / "MessageComposerView.swift",
        REPO_ROOT / "apple" / "OpenMates" / "Sources" / "Shared" / "Components" / "OMDesignPrimitives.swift",
    ]


def missing_attachment_icons(source: str, available_icons: set[str]) -> set[str]:
    return set(re.findall(r'\b(?:Icon|item)\("([^"]+)"', source)) - available_icons


def audit_message_input() -> tuple[list[str], list[str]]:
    errors = validate_contract(MESSAGE_INPUT_FIXTURE, surface="message-input")
    warnings: list[str] = []
    source = "\n".join(path.read_text(encoding="utf-8") for path in swift_files_for_message_input())

    for identifier in sorted(REQUIRED_MESSAGE_INPUT_IDENTIFIERS):
        if f'"{identifier}"' not in source:
            errors.append(f"missing Apple accessibility identifier: {identifier}")

    attachment_row = (REPO_ROOT / "apple/OpenMates/Sources/Shared/Composer/ComposerAttachmentActionRow.swift").read_text(encoding="utf-8")
    icon_sources = REPO_ROOT / "frontend/packages/ui/static/icons"
    available_icons = {path.stem for path in icon_sources.glob("*.svg")}
    for icon in sorted(missing_attachment_icons(attachment_row, available_icons)):
        errors.append(f"missing Apple attachment icon source: {icon}.svg")
    for action in ("drawing", "location", "camera", "files"):
        if not re.search(rf'item\([^,\n]+,\s*[^,\n]+,\s*"{action}"', attachment_row):
            errors.append(f"missing Apple attachment menu action: {action}")

    forbidden_controls = ["Form {", "List {", "NavigationLink {", ".navigationTitle(", ".toolbar {"]
    for forbidden in forbidden_controls:
        if forbidden in source:
            errors.append(f"forbidden native product control in message input source: {forbidden}")

    warnings.append("visual/style contract checks are warning-only for message-input until promoted")
    return errors, warnings


def audit_settings() -> tuple[list[str], list[str]]:
    errors = validate_contract(SETTINGS_FIXTURE, surface="settings")
    warnings = ["visual/style contract checks are warning-only for settings until promoted"]
    return errors, warnings


def audit_surface(surface: str) -> tuple[list[str], list[str]]:
    if surface == "message-input":
        return audit_message_input()
    if surface == "embeds":
        return audit_embeds()
    if surface == "settings":
        return audit_settings()
    raise ContractError(f"unsupported audit surface: {surface}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate")
    validate_parser.add_argument("path", type=Path)
    validate_parser.add_argument("--surface")

    promote_parser = subparsers.add_parser("promote")
    promote_parser.add_argument("source", type=Path)
    promote_parser.add_argument("--destination", type=Path)

    audit_parser = subparsers.add_parser("audit")
    audit_parser.add_argument("--surface", required=True, choices=["message-input", "embeds", "settings"])
    audit_parser.add_argument("--web-root", type=Path, help="Embed audit web source root; defaults to this checkout")
    audit_parser.add_argument("--native-root", type=Path, help="Embed audit Apple source root; defaults to this checkout")

    args = parser.parse_args()
    try:
        if args.command == "validate":
            errors = validate_contract(args.path, surface=args.surface)
            if errors:
                for error in errors:
                    print(f"ERROR: {error}", file=sys.stderr)
                return 1
            print(f"PASS {args.path}")
            return 0

        if args.command == "promote":
            promote_contract(args.source, args.destination)
            print(f"PROMOTED {args.source} -> {args.destination}")
            return 0

        if args.command == "audit":
            if args.surface != "embeds" and (args.web_root or args.native_root):
                raise ContractError("--web-root/--native-root apply only to the embeds audit")
            errors, warnings = (audit_embeds(web_root=args.web_root, native_root=args.native_root)
                                if args.surface == "embeds" else audit_surface(args.surface))
            for warning in warnings:
                print(f"WARNING: {warning}")
            if errors:
                for error in errors:
                    print(f"ERROR: {error}", file=sys.stderr)
                return 1
            print(f"PASS {args.surface} audit")
            return 0
    except ContractError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
