#!/usr/bin/env python3
"""
scripts/merge_storage_audits.py

Aggregate per-test storage snapshots produced by the cookie-audit Playwright
fixture (frontend/apps/web_app/tests/helpers/cookie-audit.ts) into the
single canonical compliance file:
    docs/architecture/compliance/cookies.yml

How it works:
  1. Read every JSON file under test-results/storage-audits/.
  2. Read existing cookies.yml (if any) to preserve human-maintained fields:
     `purpose`, `consent_exempt`, `exemption_basis`, `notes`.
  3. Deduplicate observations:
     - Cookies are keyed by (name, domain, path).
     - localStorage / sessionStorage are keyed by (key).
     - IndexedDB databases are keyed by name.
  4. Track first_observed / last_observed dates and up to 5 example specs.
  5. Rewrite cookies.yml with the merged result, preserving the file header
     comment.
  6. Print a stderr summary of additions / removals so CI can surface drift.

Run from repo root after a Playwright full-suite run:
    python3 scripts/merge_storage_audits.py
"""
from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("merge_storage_audits.py requires PyYAML — install via `pip install pyyaml`", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT_DIR = ROOT / "test-results" / "storage-audits"
COOKIES_YAML = ROOT / "docs" / "architecture" / "compliance" / "cookies.yml"

HUMAN_FIELDS = ("purpose", "consent_exempt", "exemption_basis", "notes")
MAX_EXAMPLE_SPECS = 5

# Header comment block — preserved verbatim across regenerations.
HEADER = """# Cookie & Browser Storage Inventory (runtime evidence)
#
# Empirical record of every cookie, localStorage key, sessionStorage key, and
# IndexedDB database that the OpenMates web app sets during the full E2E test
# suite. Used by the twice-weekly legal & compliance scan to verify the
# "essential-only, no consent banner required" claim from
# docs/architecture/compliance/acknowledgments.yml against actual runtime
# behavior.
#
# Sources of truth:
#   - `observed: ...` blocks are AUTO-GENERATED by scripts/merge_storage_audits.py
#     after a full Playwright run. Do not hand-edit them - they will be
#     overwritten on the next run.
#   - `purpose`, `consent_exempt`, `exemption_basis`, `notes` are
#     HUMAN-MAINTAINED and preserved across regenerations. Fill them in once
#     per entry; the merger never clobbers them.
#
# Anonymization (see frontend/apps/web_app/tests/helpers/cookie-audit.ts):
#   - Sensitive keys (token / refresh / secret / key / auth / session / csrf /
#     jwt / otp / password / stripe) -> example_value: "<redacted>" (length only)
#   - All other values -> first 4 chars + ellipsis + length
#
# Compliance gate:
#   Every entry MUST have `consent_exempt: true` with an `exemption_basis` that
#   maps to "strictly necessary for the service explicitly requested by the
#   user" under ePrivacy Art. 5(3) and TTDSG 25 (German DDG). Anything that
#   does not meet this bar means a cookie banner is legally required.
#
# Read by: scripts/_legal_compliance_helper.py (Mon + Thu cron)
# Updated by: scripts/run_tests.py after `--suite playwright` runs
# Related: docs/architecture/compliance/acknowledgments.yml (cookies entry)

"""


def _today() -> str:
    return date.today().isoformat()


def _load_existing() -> dict[str, list[dict]]:
    """Load existing cookies.yml; return empty structure on missing/invalid."""
    empty = {"cookies": [], "local_storage": [], "session_storage": [], "indexed_db": []}
    if not COOKIES_YAML.is_file():
        return empty
    try:
        data = yaml.safe_load(COOKIES_YAML.read_text()) or {}
    except yaml.YAMLError as e:
        print(f"warning: existing cookies.yml is invalid YAML ({e}); regenerating from scratch", file=sys.stderr)
        return empty
    for key in empty:
        if not isinstance(data.get(key), list):
            data[key] = []
    return data


def _index_existing(items: list[dict], key_fn) -> dict[Any, dict]:
    out: dict[Any, dict] = {}
    for item in items:
        try:
            out[key_fn(item)] = item
        except (KeyError, TypeError):
            continue
    return out


def _preserve_human_fields(existing: dict | None, fresh: dict) -> dict:
    """Copy human-maintained fields from `existing` into `fresh` if present."""
    if not existing:
        # Default new entries to empty human fields so admins can fill them in.
        for f in HUMAN_FIELDS:
            fresh.setdefault(f, None)
        return fresh
    for f in HUMAN_FIELDS:
        if f in existing and existing[f] is not None:
            fresh[f] = existing[f]
        else:
            fresh.setdefault(f, None)
    return fresh


def _merge_observation(
    fresh: dict,
    existing_idx: dict,
    key: Any,
    spec: str,
    today: str,
) -> None:
    """Mutate `fresh` to track first/last observed + spec list, preserving history from existing."""
    prior = existing_idx.get(key)
    fresh["first_observed"] = (prior or {}).get("first_observed", today) if prior else today
    fresh["last_observed"] = today
    seen = list((prior or {}).get("seen_in_specs", []))
    if spec and spec not in seen:
        seen.append(spec)
    fresh["seen_in_specs"] = seen[:MAX_EXAMPLE_SPECS]


def _collect_snapshots() -> list[dict]:
    if not SNAPSHOT_DIR.is_dir():
        return []
    out = []
    for fp in sorted(SNAPSHOT_DIR.glob("*.json")):
        try:
            out.append(json.loads(fp.read_text()))
        except json.JSONDecodeError as e:
            print(f"warning: skipping invalid snapshot {fp.name}: {e}", file=sys.stderr)
    return out


def merge() -> dict[str, Any]:
    snapshots = _collect_snapshots()
    existing = _load_existing()
    today = _today()

    cookie_idx = _index_existing(existing["cookies"], lambda c: (c["name"], c.get("domain", ""), c.get("path", "/")))
    ls_idx = _index_existing(existing["local_storage"], lambda c: c["key"])
    ss_idx = _index_existing(existing["session_storage"], lambda c: c["key"])
    idb_idx = _index_existing(existing["indexed_db"], lambda c: c["name"])

    cookies: dict[Any, dict] = {}
    locals_: dict[str, dict] = {}
    sessions_: dict[str, dict] = {}
    idbs: dict[str, dict] = {}

    for snap in snapshots:
        spec = snap.get("spec") or "unknown"
        for c in snap.get("cookies") or []:
            key = (c["name"], c.get("domain", ""), c.get("path", "/"))
            entry = cookies.get(key) or {
                "name": c["name"],
                "domain": c.get("domain", ""),
                "path": c.get("path", "/"),
                "http_only": c.get("http_only", False),
                "secure": c.get("secure", False),
                "same_site": c.get("same_site", "Lax"),
                "example_value": c.get("example_value", ""),
                "value_length": c.get("value_length", 0),
            }
            _merge_observation(entry, cookie_idx, key, spec, today)
            _preserve_human_fields(cookie_idx.get(key), entry)
            cookies[key] = entry

        for e in snap.get("local_storage") or []:
            key = e["key"]
            entry = locals_.get(key) or {
                "key": key,
                "example_value": e.get("example_value", ""),
                "value_length": e.get("value_length", 0),
            }
            _merge_observation(entry, ls_idx, key, spec, today)
            _preserve_human_fields(ls_idx.get(key), entry)
            locals_[key] = entry

        for e in snap.get("session_storage") or []:
            key = e["key"]
            entry = sessions_.get(key) or {
                "key": key,
                "example_value": e.get("example_value", ""),
                "value_length": e.get("value_length", 0),
            }
            _merge_observation(entry, ss_idx, key, spec, today)
            _preserve_human_fields(ss_idx.get(key), entry)
            sessions_[key] = entry

        for db in snap.get("indexed_db") or []:
            entry = idbs.get(db) or {"name": db}
            _merge_observation(entry, idb_idx, db, spec, today)
            _preserve_human_fields(idb_idx.get(db), entry)
            idbs[db] = entry

    merged = {
        "cookies": sorted(cookies.values(), key=lambda c: (c["name"], c["domain"])),
        "local_storage": sorted(locals_.values(), key=lambda c: c["key"]),
        "session_storage": sorted(sessions_.values(), key=lambda c: c["key"]),
        "indexed_db": sorted(idbs.values(), key=lambda c: c["name"]),
    }

    # Drift summary
    prior_keys = {
        "cookies": set(cookie_idx.keys()),
        "local_storage": set(ls_idx.keys()),
        "session_storage": set(ss_idx.keys()),
        "indexed_db": set(idb_idx.keys()),
    }
    new_keys = {
        "cookies": set(cookies.keys()),
        "local_storage": set(locals_.keys()),
        "session_storage": set(sessions_.keys()),
        "indexed_db": set(idbs.keys()),
    }
    print(f"merge_storage_audits: read {len(snapshots)} snapshot(s)", file=sys.stderr)
    for section in ("cookies", "local_storage", "session_storage", "indexed_db"):
        added = new_keys[section] - prior_keys[section]
        removed = prior_keys[section] - new_keys[section]
        if added or removed:
            print(
                f"  {section}: {len(new_keys[section])} total (+{len(added)} new, -{len(removed)} gone)",
                file=sys.stderr,
            )
            for k in sorted(map(str, added)):
                print(f"    + {k}", file=sys.stderr)
            for k in sorted(map(str, removed)):
                print(f"    - {k}", file=sys.stderr)
        else:
            print(f"  {section}: {len(new_keys[section])} total (no change)", file=sys.stderr)

    return merged


def write(merged: dict[str, Any]) -> None:
    body = yaml.safe_dump(merged, sort_keys=False, allow_unicode=True, width=100)
    COOKIES_YAML.parent.mkdir(parents=True, exist_ok=True)
    COOKIES_YAML.write_text(HEADER + body)
    print(f"merge_storage_audits: wrote {COOKIES_YAML.relative_to(ROOT)}", file=sys.stderr)


def main() -> int:
    merged = merge()
    if not any(merged.values()):
        print("merge_storage_audits: no observations found — leaving cookies.yml untouched", file=sys.stderr)
        return 0
    write(merged)
    return 0


if __name__ == "__main__":
    sys.exit(main())
