// frontend/packages/ui/src/utils/modelDisplayName.ts
//
// Utility to convert model IDs to human-readable display names for users.
// Used in "generated by {model}" text under assistant messages.
//
// The backend sends human-readable names from provider YAML files (e.g., "Gemini 3 Pro").
// This utility provides a fallback lookup from frontend metadata if the backend
// sends a model ID instead of a name.

import { modelsMetadata, type AIModelMetadata } from "../data/modelsMetadata";

// Build a lookup map from model metadata for fallback names
let modelsById: Record<string, AIModelMetadata> | null = null;

/**
 * Lazily initialize the models lookup map.
 * This avoids computing the map unless actually needed.
 */
function getModelsById(): Record<string, AIModelMetadata> {
  if (!modelsById) {
    modelsById = modelsMetadata.reduce(
      (acc, model) => {
        acc[model.id] = model;
        return acc;
      },
      {} as Record<string, AIModelMetadata>,
    );
  }
  return modelsById;
}

/**
 * Convert a model name or ID to a user-friendly display name.
 *
 * The backend normally sends human-readable names from provider YAML files.
 * This function provides a fallback lookup if a model ID is passed instead.
 *
 * @param modelNameOrId - Either a model ID (e.g., "gemini-3-pro-preview") or
 *                        a human-readable name (e.g., "Gemini 3 Pro")
 * @returns Display name for the user
 *
 * @example
 * getModelDisplayName("Gemini 3 Pro")               // "Gemini 3 Pro" (passthrough)
 * getModelDisplayName("gemini-3-pro-preview")       // "Gemini 3 Pro" (from metadata)
 * getModelDisplayName("Claude Sonnet 4.5")          // "Claude Sonnet 4.5" (passthrough)
 */
export function getModelDisplayName(modelNameOrId: string): string {
  // Try to get name from model metadata (if input looks like a model ID)
  const models = getModelsById();
  const model = models[modelNameOrId];
  if (model?.name) {
    return model.name;
  }

  // Return input as-is (already a human-readable name or unknown model)
  return modelNameOrId;
}
