#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
######################          Apps          ###########################
#########################################################################

# Apps used by OpenMates

apps:

  # 'AI' app
  # Use generative AI to answer questions, brainstorm ideas and more.
  ai:
    active: True
    providers:
      openai:
        api_key: ${OPENAI_API_KEY}
      anthropic:
        api_key: ${ANTHROPIC_API_KEY}

  # 'Messages' app
  # Send messages, create threads and more.
  messages:
    active: True
    providers:
      discord:
        active: True
        bots:
          burton:
            client_id: ${AI_MATE_BURTON_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_BURTON_DISCORD_OAUTH_URL}
            token: ${AI_MATE_BURTON_DISCORD_TOKEN}
          sophia:
            client_id: ${AI_MATE_SOPHIA_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_SOPHIA_DISCORD_OAUTH_URL}
            token: ${AI_MATE_SOPHIA_DISCORD_TOKEN}
          mark:
            client_id: ${AI_MATE_MARK_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_MARK_DISCORD_OAUTH_URL}
            token: ${AI_MATE_MARK_DISCORD_TOKEN}
          elton:
            client_id: ${AI_MATE_ELTON_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_ELTON_DISCORD_OAUTH_URL}
            token: ${AI_MATE_ELTON_DISCORD_TOKEN}
          finn:
            client_id: ${AI_MATE_FINN_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_FINN_DISCORD_OAUTH_URL}
            token: ${AI_MATE_FINN_DISCORD_TOKEN}
          grace:
            client_id: ${AI_MATE_GRACE_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_GRACE_DISCORD_OAUTH_URL}
            token: ${AI_MATE_GRACE_DISCORD_TOKEN}
          leon:
            client_id: ${AI_MATE_LEON_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_LEON_DISCORD_OAUTH_URL}
            token: ${AI_MATE_LEON_DISCORD_TOKEN}
          priscilla:
            client_id: ${AI_MATE_PRISCILLA_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_PRISCILLA_DISCORD_OAUTH_URL}
            token: ${AI_MATE_PRISCILLA_DISCORD_TOKEN}
          selma:
            client_id: ${AI_MATE_SELMA_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_SELMA_DISCORD_OAUTH_URL}
            token: ${AI_MATE_SELMA_DISCORD_TOKEN}
          makani:
            client_id: ${AI_MATE_MAKANI_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_MAKANI_DISCORD_OAUTH_URL}
            token: ${AI_MATE_MAKANI_DISCORD_TOKEN}
          monika:
            client_id: ${AI_MATE_MONIKA_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_MONIKA_DISCORD_OAUTH_URL}
            token: ${AI_MATE_MONIKA_DISCORD_TOKEN}
          melvin:
            client_id: ${AI_MATE_MELVIN_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_MELVIN_DISCORD_OAUTH_URL}
            token: ${AI_MATE_MELVIN_DISCORD_TOKEN}
          lisa:
            client_id: ${AI_MATE_LISA_DISCORD_CLIENT_ID}
            oauth_url: ${AI_MATE_LISA_DISCORD_OAUTH_URL}
            token: ${AI_MATE_LISA_DISCORD_TOKEN}
      slack:
        active: True
        bots:
          sophia:
            token: ${AI_MATE_SOPHIA_SLACK_TOKEN}
          mark:
            token: ${AI_MATE_MARK_SLACK_TOKEN}
          elton:
            token: ${AI_MATE_ELTON_SLACK_TOKEN}
          finn:
            token: ${AI_MATE_FINN_SLACK_TOKEN}
          grace:
            token: ${AI_MATE_GRACE_SLACK_TOKEN}
          leon:
            token: ${AI_MATE_LEON_SLACK_TOKEN}
          priscilla:
            token: ${AI_MATE_PRISCILLA_SLACK_TOKEN}
          selma:
            token: ${AI_MATE_SELMA_SLACK_TOKEN}
          makani:
            token: ${AI_MATE_MAKANI_SLACK_TOKEN}
          monika:
            token: ${AI_MATE_MONIKA_SLACK_TOKEN}
          melvin:
            token: ${AI_MATE_MELVIN_SLACK_TOKEN}
          lisa:
            token: ${AI_MATE_LISA_SLACK_TOKEN}

  # 'Web' app
  # Browse the web, research topics and more.
  web:
    active: True
    settings:
      secret_key: ${WEB_BROWSER_SECRET_KEY}
      port: ${WEB_BROWSER_PORT}

  # 'Audio' app
  # Generate, modify and transcribe audio and more.
  audio:
    active: True
    providers:
      - name: 'AssemblyAI'
        api_key: ${ASSEMBLYAI_API_KEY}
      - name: 'OpenAI'
        api_key: ${OPENAI_API_KEY}
      - name: 'ElevenLabs'
        api_key: ${ELEVENLABS_API_KEY}

  # 'Finance' app
  # Keep track of your finances and build a stable income.
  finance:
    active: True
    providers:
      - name: 'Akaunting'
        api_url: ${AKAUNTING_API_URL}
        username: ${AKAUNTING_USERNAME}
        password: ${AKAUNTING_PASSWORD}
        company_id: ${AKAUNTING_COMPANY_ID}