#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
######################          Apps          ###########################
#########################################################################

# Apps used by OpenMates

# 'AI' app
# Use generative AI to answer questions, brainstorm ideas and more.
ai: /api/configs/apps/ai/app.yml

# 'Audio' app
# Generate, modify and transcribe audio and more.
audio: /api/configs/apps/audio/app.yml

# 'Design' app
# Design interfaces, get feedback and more.
design: /api/configs/apps/design/app.yml

# 'Finance' app
# Keep track of your finances and build a stable income.
finance: /api/configs/apps/finance/app.yml

# 'Home' app
# Control your smart home, organize daily tasks and more.
home: /api/configs/apps/home/app.yml

# 'Messages' app
# Send messages, create threads and more.
messages: /api/configs/apps/messages/app.yml

# 'Web' app
# Browse the web, research topics and more.
web: /api/configs/apps/web/app.yml