#  _____________________________________________________________________
# |                                                                     |
# |         ____                  __  __        _                       |
# |        / __ \                |  \/   |     | |                      |
# |       | |  | |_ __   ___ _ __| \  /  | __ _| |_ ___  ___            |
# |       | |  | | '_ \ / _ \ '_ \ |\/ | |/ _` | __/ _ \/ __|           |
# |       | |__| | |_) |  __/ | | | |  | | (_| | ||  __/\__ \           |
# |        \____/| .__/ \___|_| |_|_|  |_|\__,_|\__\___||___/           |
# |              | |                                                    |
# |              |_|                                                    |
# |                                                                     |
# |_____________________________________________________________________|
#                       Your AI team mates.

#########################################################################
####################          'Maps' app          ####################
#########################################################################

name: 'Maps'
slug: 'maps'
description: |
  Find restaurants, bars and so much more - nearby and around the world.
icon: /images/icons/apps/maps.svg
allowed: ${APP_MAPS_ALLOWED}
providers:
  google_maps:
    name: 'Google Maps'
    slug: 'google_maps'
    description: |
      Google Maps is a platform for finding places and their ratings, opening hours, and more.
    icon: /images/icons/providers/google_maps.svg
    allowed: ${APP_MAPS_PROVIDER_GOOGLE_MAPS_ALLOWED}
skills:
  search:
    name: 'Search'
    slug: 'search'
    description: |
      Search for places.
    icon: /images/icons/skills/search.svg
    allowed: ${APP_MAPS_SKILL_SEARCH_PLACES_ALLOWED}
# focuses: