# backend/apps/ai/daily_inspiration/schemas.py
# Pydantic models for the Daily Inspiration feature.
#
# Architecture:
# - DailyInspirationVideo: enriched video metadata returned after Brave search + YouTube enrichment
# - DailyInspiration: a single generated inspiration with its associated video
# - DailyInspirationBatch: a group of 1-3 inspirations generated in one job run
#
# Privacy:
# - These are intermediate server-side schemas used during generation and delivery.
# - No user PII is stored in these schemas.
# - The content is encrypted with the user's vault key before being sent to the client.

from typing import Optional
from pydantic import BaseModel, Field


class DailyInspirationVideo(BaseModel):
    """
    Enriched video metadata selected for a Daily Inspiration banner.

    Sourced from Brave video search + optional YouTube Data API enrichment.
    Only YouTube videos are selected (youtube_id must be set).
    """

    youtube_id: str = Field(..., description="YouTube video ID (e.g., 'dQw4w9WgXcQ')")
    title: str = Field(..., description="Video title")
    thumbnail_url: str = Field(..., description="URL of the video thumbnail (YouTube or Brave-provided)")
    channel_name: Optional[str] = Field(None, description="YouTube channel / uploader name")
    view_count: Optional[int] = Field(None, description="View count from YouTube Data API")
    duration_seconds: Optional[int] = Field(None, description="Video duration in seconds")
    published_at: Optional[str] = Field(None, description="ISO 8601 publication date string")


class DailyInspiration(BaseModel):
    """
    A single Daily Inspiration item.

    Generated by an LLM call that combines the user's topic suggestions with
    a curated video, producing a short English phrase and the selected video metadata.

    The `content_type` field is included for future extensibility (articles, facts,
    podcasts, challenges, etc.) but only 'video' is generated currently.
    """

    inspiration_id: str = Field(..., description="UUID for this inspiration (used for view tracking)")
    phrase: str = Field(
        ...,
        description=(
            "Short, fascinating English phrase (6-12 words) that sparks curiosity. "
            "Examples: 'Why do cats always land on their feet?', "
            "'The mathematics behind a perfectly stacked Jenga tower'"
        ),
    )
    category: str = Field(
        ...,
        description="Chat category that best matches this inspiration (e.g., 'science', 'history')",
    )
    content_type: str = Field(
        default="video",
        description=(
            "Type of companion content. Currently always 'video'. "
            "Future values: 'article', 'fact', 'challenge', 'project', 'podcast'."
        ),
    )
    video: Optional[DailyInspirationVideo] = Field(
        None,
        description="Enriched video metadata. Required when content_type='video'.",
    )
    generated_at: int = Field(..., description="Unix timestamp when this inspiration was generated")
