// Data convenience extensions for hex string conversion and base64url encoding.
// Used throughout the crypto and passkey flows.

import Foundation
import SwiftUI

extension Data {
    init(hexString: String) {
        let hex = hexString.replacingOccurrences(of: " ", with: "")
        var data = Data(capacity: hex.count / 2)
        var index = hex.startIndex
        while index < hex.endIndex {
            let nextIndex = hex.index(index, offsetBy: 2)
            if let byte = UInt8(hex[index..<nextIndex], radix: 16) {
                data.append(byte)
            }
            index = nextIndex
        }
        self = data
    }

    func hexString() -> String {
        map { String(format: "%02x", $0) }.joined()
    }

    init?(base64URLEncoded string: String) {
        var base64 = string
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")

        let remainder = base64.count % 4
        if remainder > 0 {
            base64.append(String(repeating: "=", count: 4 - remainder))
        }

        self.init(base64Encoded: base64)
    }

    func base64URLEncodedString() -> String {
        base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }
}

extension Color {
    init(hex: UInt32) {
        let r = Double((hex >> 16) & 0xFF) / 255.0
        let g = Double((hex >> 8) & 0xFF) / 255.0
        let b = Double(hex & 0xFF) / 255.0
        self.init(red: r, green: g, blue: b)
    }
}

extension LinearGradient {
    /// Dark incognito gradient — matches ChatHeader.svelte's fixed incognito state:
    /// `linear-gradient(135deg, #1a1a2e 0%, #2d2d44 50%, #1e1e35 100%)`
    static let incognito = LinearGradient(
        colors: [Color(hex: 0x1A1A2E), Color(hex: 0x2D2D44), Color(hex: 0x1E1E35)],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )

    /// Official OpenMates brand — openmates_official category from categoryUtils.ts
    /// Uses the primary gradient (#4867cd / #5a85eb) matching --color-primary-start / --color-primary-end
    /// from theme.generated.css and LinearGradient.primary in GradientTokens.generated.swift.
    static let openMatesOfficial = LinearGradient(
        colors: [Color(hex: 0x4867CD), Color(hex: 0x5A85EB)],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )

    // openmates and chat app categories use the primary gradient.
    // Not generated by build-tokens.js because they use start_ref/end_ref in gradients.yml.
    static let appOpenmates = LinearGradient(
        colors: [Color(hex: 0x4867CD), Color(hex: 0x5A85EB)],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )
    static let appChat = LinearGradient(
        colors: [Color(hex: 0x4867CD), Color(hex: 0x5A85EB)],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )
}

// MARK: - Category → gradient / icon / orb-color mapping
// Maps web category strings (from categoryUtils.ts CATEGORY_GRADIENTS and
// CATEGORY_FALLBACK_ICONS) to iOS LinearGradients, icon asset names, and
// orb highlight colors. Used by InspirationCard and any future category UI.

enum CategoryMapping {
    static func isKnownCategory(_ category: String) -> Bool {
        switch category {
        case "software_development",
             "business_development",
             "medical_health",
             "legal_law",
             "openmates_official",
             "maker_prototyping",
             "marketing_sales",
             "finance",
             "design",
             "electrical_engineering",
             "movies_tv",
             "history",
             "science",
             "life_coach_psychology",
             "cooking_food",
             "activism",
             "general_knowledge",
             "onboarding_support":
            return true
        default:
            return false
        }
    }

    /// Gradient for a category — matches getCategoryGradientColors() in categoryUtils.ts.
    /// Falls back to the primary OM gradient for unknown categories.
    static func gradient(for category: String) -> LinearGradient {
        switch category {
        case "software_development":    return .omGradient(start: Color(hex: 0x155D91), end: Color(hex: 0x42ABF4))
        case "business_development":    return .omGradient(start: Color(hex: 0x004040), end: Color(hex: 0x008080))
        case "medical_health":          return .omGradient(start: Color(hex: 0xFD50A0), end: Color(hex: 0xF42C2D))
        case "legal_law":               return .omGradient(start: Color(hex: 0x239CFF), end: Color(hex: 0x005BA5))
        case "openmates_official":      return .omGradient(start: Color(hex: 0x6366F1), end: Color(hex: 0x4F46E5))
        case "maker_prototyping":       return .omGradient(start: Color(hex: 0xEA7600), end: Color(hex: 0xFBAB59))
        case "marketing_sales":         return .omGradient(start: Color(hex: 0xFF8C00), end: Color(hex: 0xF4B400))
        case "finance":                 return .omGradient(start: Color(hex: 0x119106), end: Color(hex: 0x15780D))
        case "design":                  return .omGradient(start: Color(hex: 0x101010), end: Color(hex: 0x2E2E2E))
        case "electrical_engineering":  return .omGradient(start: Color(hex: 0x233888), end: Color(hex: 0x2E4EC8))
        case "movies_tv":              return .omGradient(start: Color(hex: 0x00C2C5), end: Color(hex: 0x3170DC))
        case "history":                return .omGradient(start: Color(hex: 0x4989F2), end: Color(hex: 0x2F44BF))
        case "science":                return .omGradient(start: Color(hex: 0xCE5B06), end: Color(hex: 0x8F220E))
        case "life_coach_psychology":   return .omGradient(start: Color(hex: 0xFDB250), end: Color(hex: 0xF42C2D))
        case "cooking_food":           return .omGradient(start: Color(hex: 0xFD8450), end: Color(hex: 0xF42C2D))
        case "activism":               return .omGradient(start: Color(hex: 0xF53D00), end: Color(hex: 0xF56200))
        case "general_knowledge":      return .omGradient(start: Color(hex: 0xDE1E66), end: Color(hex: 0xFF763B))
        case "onboarding_support":     return .omGradient(start: Color(hex: 0x6364FF), end: Color(hex: 0x9B6DFF))
        default:                       return .primary
        }
    }

    /// Icon asset name for a category — matches CATEGORY_FALLBACK_ICONS in categoryUtils.ts.
    /// Maps to icons available in Icons.xcassets (SVG assets from the web app).
    static func iconName(for category: String) -> String {
        switch category {
        case "software_development":    return "coding"
        case "business_development":    return "business"
        case "medical_health":          return "heart"
        case "legal_law":               return "legal"
        case "openmates_official":      return "ai"
        case "maker_prototyping":       return "3dmodels"
        case "marketing_sales":         return "slides"
        case "finance":                 return "money"
        case "design":                  return "design"
        case "electrical_engineering":  return "pcbdesign"
        case "movies_tv":              return "tv"
        case "history":                return "time"
        case "science":                return "question"
        case "life_coach_psychology":   return "lifecoaching"
        case "cooking_food":           return "nutrition"
        case "activism":               return "activism"
        case "general_knowledge":      return "web"
        case "onboarding_support":     return "ai"
        default:                       return "ai"
        }
    }

    /// Lucide icon name for category-driven web surfaces.
    /// Matches CATEGORY_FALLBACK_ICONS in categoryUtils.ts.
    static func lucideIconName(for category: String) -> String {
        switch category {
        case "software_development":    return "code"
        case "business_development":    return "briefcase"
        case "medical_health":          return "heart"
        case "legal_law":               return "gavel"
        case "openmates_official":      return "shield-check"
        case "maker_prototyping":       return "wrench"
        case "marketing_sales":         return "megaphone"
        case "finance":                 return "dollar-sign"
        case "design":                  return "palette"
        case "electrical_engineering":  return "zap"
        case "movies_tv":              return "tv"
        case "history":                return "clock"
        case "science":                return "microscope"
        case "life_coach_psychology":   return "users"
        case "cooking_food":           return "utensils"
        case "activism":               return "trending-up"
        case "general_knowledge":      return "help-circle"
        case "onboarding_support":     return "compass"
        default:                       return "help-circle"
        }
    }

    /// Orb highlight color for a category — uses the brighter gradient stop.
    static func orbColor(for category: String) -> Color {
        switch category {
        case "software_development":    return Color(hex: 0x42ABF4)
        case "business_development":    return Color(hex: 0x008080)
        case "medical_health":          return Color(hex: 0xF42C2D)
        case "legal_law":               return Color(hex: 0x005BA5)
        case "openmates_official":      return Color(hex: 0x4F46E5)
        case "maker_prototyping":       return Color(hex: 0xFBAB59)
        case "marketing_sales":         return Color(hex: 0xF4B400)
        case "finance":                 return Color(hex: 0x15780D)
        case "design":                  return Color(hex: 0x2E2E2E)
        case "electrical_engineering":  return Color(hex: 0x2E4EC8)
        case "movies_tv":              return Color(hex: 0x3170DC)
        case "history":                return Color(hex: 0x2F44BF)
        case "science":                return Color(hex: 0x8F220E)
        case "life_coach_psychology":   return Color(hex: 0xF42C2D)
        case "cooking_food":           return Color(hex: 0xF42C2D)
        case "activism":               return Color(hex: 0xF56200)
        case "general_knowledge":      return Color(hex: 0xFF763B)
        case "onboarding_support":     return Color(hex: 0x9B6DFF)
        default:                       return Color(hex: 0xA0BEFF)
        }
    }
}
