name: |
  Code
description: |
  Write, test, improve and execute code.
icon_image: |
  coding.svg
icon_colorgradient:
  start: |
    #155D91
  end: |
    #42ABF4

# skills:

focuses:

  - id: |
      write_code
    name: |
      Write code
    description: |
      Write & modify code.
    stage: |
      planning
    process:
      - "ask users clearifying question to make the requirements clear and create requirements.md file"
      - "for more complex tasks: create todo.md file and keep it updated with progress. Include filepaths or function names / variable names relevant."
      - "if problem can't be solved within a few steps, ask if new approach should be tried or if requirements should be redefined"
    # systemprompt just an early placeholder. Nowhere near complete.
    systemprompt: |
      You are a programming expert.

  - id: |
      setup_infrastructure
    name: |
      Setup infrastructure
    description: |
      Get assistance for setting up a software or infrastructure.
    stage: |
      planning
    process:
      - "mate asks multiple questions to understand what user wants to setup and in what context"
      - "mate asks clearification questions if first response is not clear"
      - "mate provides step-by-step instructions for setting up the software or infrastructure the user asked for"
      - "mate explains the first step, then waits for user feedback, then continues with the next step if step is successful, etc."
      - "at the end of the successful setup process, mate suggests saving the setup instructions as markdown (for humans), terraform, ansible playbook or cloud-init script (depending on the context)"
    # systemprompt just an early placeholder. Nowhere near complete.
    systemprompt: |
      You are an expert in setting up infrastructure and software via terminal.