name_translation_key: code
description_translation_key: code.description
icon_image: |
  coding.svg
category: work
last_updated: "2025-11-12"
settings_and_memories:
  # Preferred technologies: Languages, frameworks, tools the user prefers
  - id: preferred_tech
    name_translation_key: code.preferred_tech
    description_translation_key: code.preferred_tech.description
    type: list
    stage: production
    example_translation_keys:
      - "code.preferred_tech.example_1"
      - "code.preferred_tech.example_2"
      - "code.preferred_tech.example_3"
    schema:
      type: object
      properties:
        name:
          type: string
          description: Technology name (e.g., Python, React, Docker)
          is_title: true
        proficiency:
          type: string
          description: Your proficiency level
          enum: ["beginner", "intermediate", "advanced", "expert"]
          is_subtitle: true
      required:
        - name
  # Projects: All projects with status to indicate current state
  - id: projects
    name_translation_key: code.projects
    description_translation_key: code.projects.description
    type: list
    stage: production
    example_translation_keys:
      - "code.projects.example_1"
      - "code.projects.example_2"
      - "code.projects.example_3"
    schema:
      type: object
      properties:
        name:
          type: string
          description: Project name
          is_title: true
        status:
          type: string
          description: Project status
          enum: ["active", "planned", "completed"]
          is_subtitle: true
        description:
          type: string
          description: Brief description of the project
        git_repo_url:
          type: string
          description: Git repository URL (e.g., https://github.com/user/repo)
      required:
        - name
  # Technologies to learn: Things the user wants to learn
  - id: want_to_learn
    name_translation_key: code.want_to_learn
    description_translation_key: code.want_to_learn.description
    type: list
    stage: production
    example_translation_keys:
      - "code.want_to_learn.example_1"
      - "code.want_to_learn.example_2"
      - "code.want_to_learn.example_3"
    schema:
      type: object
      properties:
        name:
          type: string
          description: Technology or skill you want to learn
          is_title: true
      required:
        - name

# IMPORTANT lerning:
# if we let ai code for too long extensive code changes and then start to test it, it becomes a huge broken mess. instead we need to find other ways. Maybe by reminding llm to break tasks down into smaller steps (that also allows for placebolder code), and build it up so that we can test individual steps better if they work and if so we continue to the next step.

#**Development approach:**
#- Break large tasks into smaller, testable increments instead of letting AI implement extensive changes all at once
#- Use placeholder-driven architecture - stub out structure first, then fill in components one by one
#- Validate each step before moving to the next (compile, test, verify functionality)
#- Treat AI as pair programming partner requiring frequent check-ins rather than autonomous contractor

#**Chat specific files**
#- todo.md -> to manage all

#**Project awareness files:**
#- Keep existing `todo.md`, `architecture.md`, and project structure
#- Add automated file generation that extracts real project state (dependencies, linter warnings, test coverage)
#- Use `changelog_since_commit.md` for current session changes, reset on each git commit
#- Maintain `recent_commits.md` showing last N commits for historical context

#**Context management:**
#- Start each session by having AI review and summarize key project files
#- Explicitly reference documentation files when requesting changes
#- Use git hooks or scripts to automatically sync documentation with commits
#- Focus on objective, automatically-generated project state rather than manually maintained status files

#**Testing integration:**
#- Write tests before or alongside implementation
#- Have AI explain how each component would be tested
#- Catch issues early when they're easier to trace and fix​​​​​​​​​​​​​​​​

#- also keep in mind when building a vscode extension that vscode extensions can also access terminal window names and write to them but not see the content of existing terminal windows.

# Step 1 - Planning: User writes down a plan of requirements of what they want and what they think how things should work
# Step 2 - Refinement: User tells ai the plan, ai checks for files in the existing project to better understand the project in the context of the requirements and then has a conversation to clarify the requirements / update them and creates a todo list or in case of larger projects / changes multiple files with todos which should result in testabable units / changes to the project. Ideally this is split up in a way that multiple ais can work on the tasks without creating colliding code changes.
# Step 3 - Coding & Feedback loop: the ai starts to update the code / implement the changes for the tasks block. Ideally multiple ais can work on the various tasks blocks without colliding with each other. Ideally the ais dont need further feedback because they have asked all relevant details in the planning & refinement stages. But when conflicts / unclear situations do occur, they ask the user for input and then continue the work based on the input.
# Step 4 - Testing: the ai is generating tests or test instructions and either runs them by itself or asks the user to
# Step 5 - Documentation: once the ai has completed the tasks or block of tasks, it updates the todo markdown file, updates the changelog file and creates or updates documentation files.
# Interruption: if the chat is getting too long, the ai is updating the todo's and changelog and starts a fresh chat

# skills:
# add issue as markdown file, for llm to better process
# with structure:
# ## Summary
# Brief description of the issue

# ## Steps to Reproduce
# 1. First step
# 2. Second step
# 3. Third step

# ## Expected Behavior
# What should happen

# ## Actual Behavior
# What actually happens

# ## Environment
# - OS:
# - Browser/Version:
# - Project Version:

# ## Additional Context
# Screenshots, logs, or other relevant information
embeds:
  - id: |
      code_embed
    description_embed: |
      Embedded code preview, with colored formatting of code based on language.
  - id: |
      hydra_embed
    description_embed: |
      Embedded rendered preview of hydra live visuals, but not playing by default.
    description_fullscreen: |
      Code on the left, rendered preview (auto playing) on the right.
skills:
  - id: get_docs
    name_translation_key: code.get_docs
    description_translation_key: code.get_docs.description
    preprocessor_hint: >
      Get latest documentation for programming libraries, frameworks, APIs, SDKs.
      Use for ANY programming-related query about a specific library or framework.
    stage: production
    class_path: |
      backend.apps.code.skills.get_docs_skill.GetDocsSkill
    providers:
      - Context7
    tool_schema:
      type: object
      properties:
        library:
          type: string
          description: |
            Library name to search for (e.g., "Svelte 5", "React", "FastAPI", "Miro API", etc.).
        question:
          type: string
          description: |
            Natural language question about the documentation needed
            (e.g., "How to use useState hook?", "How to setup routing?").
      required:
        - library
        - question
  - id: clean_repo
    name_translation_key: code.clean_repo
    description_translation_key: code.clean_repo.description
    stage: planning
  - id: get_issues
    name_translation_key: code.get_issues
    description_translation_key: code.get_issues.description
    stage: planning
  - id: add_issue
    name_translation_key: code.add_issue
    description_translation_key: code.add_issue.description
    stage: planning
  - id: remove_secrets
    name_translation_key: code.remove_secrets
    description_translation_key: code.remove_secrets.description
    stage: planning
  - id: get_project_overview
    name_translation_key: code.get_project_overview
    description_translation_key: code.get_project_overview.description
    stage: planning
focuses:
  - id: test_git_repo
    name_translation_key: focus_modes.code_test_git_repo.text
    description_translation_key: focus_modes.code_test_git_repo.description
    stage: planning
    name_translation_key: focus_modes.code_test_git_repo.text
    description_translation_key: focus_modes.code_test_git_repo.description
    stage: planning
    name_translation_key: focus_modes.code_test_git_repo.text
    description_translation_key: focus_modes.code_test_git_repo.description
    stage: planning
      You are a programming expert.
  - id: analyze_logs
    name_translation_key: focus_modes.code_analyze_logs.text
    description_translation_key: focus_modes.code_analyze_logs.description
    stage: planning
    name_translation_key: focus_modes.code_analyze_logs.text
    description_translation_key: focus_modes.code_analyze_logs.description
    stage: planning
    name_translation_key: focus_modes.code_analyze_logs.text
    description_translation_key: focus_modes.code_analyze_logs.description
    stage: planning
    name_translation_key: focus_modes.code_analyze_logs.text
    description_translation_key: focus_modes.code_analyze_logs.description
    stage: planning
  - id: research_solutions
    name_translation_key: focus_modes.code_research_solutions.text
    description_translation_key: focus_modes.code_research_solutions.description
    stage: planning
  - id: code_walkthrough
    name_translation_key: focus_modes.code_code_walkthrough.text
    description_translation_key: focus_modes.code_code_walkthrough.description
    stage: planning
  - id: setup_infrastructure
    name_translation_key: focus_modes.code_setup_infrastructure.text
    description_translation_key: focus_modes.code_setup_infrastructure.description
    stage: planning
      You are an expert in setting up infrastructure and software via terminal.
  - id: refactor_code
    name_translation_key: focus_modes.code_refactor_code.text
    description_translation_key: focus_modes.code_refactor_code.description
    stage: planning
