import type { NewsroomSurfaceData } from './types';

const en: NewsroomSurfaceData = {
  brand: 'OpenMates',
  newsLabel: 'Newsroom',
  blogLabel: 'Blog',
  openAppLabel: 'Open web app',
  tryItLabel: 'Try it out',
  searchLabel: 'Search',
  latestNewsLabel: 'Latest news',
  latestBlogLabel: 'Latest blog posts',
  socialLabel: 'Social media',
  coverageLabel: 'Press coverage',
  morePostsLabel: 'More posts',
  relatedLabel: 'More from OpenMates',
  pressKitLabel: 'Download press kit',
  pressInquiryLabel: 'Press inquiries',
  subscribeLabel: 'Subscribe to news',
  followLabel: 'Follow us',
  heroNews: {
    eyebrow: 'Release',
    title: 'Introducing: Workflow Automation',
    meta: 'September 28, 2026',
    actionLabel: 'Read the release',
  },
  heroBlog: {
    eyebrow: 'Blog post',
    kicker: 'Featured',
    title: 'Don’t fly blind: Better guardrails for agentic coding',
    meta: '10 min read',
    actionLabel: 'Read the blog post',
  },
  newsItems: [
    {
      id: 'health-app-redesigned',
      kind: 'update',
      eyebrow: 'Update',
      title: 'The Health app, redesigned',
      excerpt: 'A clearer way to find and understand useful health information.',
      publishedLabel: '2 hours ago',
      mediaShape: 'landscape',
    },
    {
      id: 'new-code-skills',
      kind: 'update',
      eyebrow: 'Update',
      title: 'New skills for the Code app',
      excerpt: 'More capable coding support for daily work and learning.',
      publishedLabel: '2 days ago',
      mediaShape: 'landscape',
    },
    {
      id: 'events-redesign',
      kind: 'update',
      eyebrow: 'Update',
      title: 'Redesigning the Events app',
      excerpt: 'Plan, discover, and revisit events with a calmer interface.',
      publishedLabel: '3 days ago',
      mediaShape: 'landscape',
    },
    {
      id: 'introducing-teams',
      kind: 'release',
      eyebrow: 'Release',
      title: 'Introducing: Teams',
      excerpt: 'Shared workspaces for people working toward the same goal.',
      publishedLabel: 'September 12, 2026',
      mediaShape: 'landscape',
    },
    {
      id: 'introducing-projects',
      kind: 'release',
      eyebrow: 'Release',
      title: 'Introducing: Projects',
      excerpt: 'Keep related conversations, files, and instructions together.',
      publishedLabel: 'September 8, 2026',
      mediaShape: 'landscape',
    },
  ],
  blogItems: [
    {
      id: 'workflow-best-practices',
      kind: 'blog',
      eyebrow: 'Blog post',
      title: 'Best practices for the new Workflow feature',
      excerpt: 'Build dependable automations that remain easy to understand.',
      publishedLabel: 'Today',
      readTime: '4 min read',
      author: 'OpenMates',
      mediaShape: 'landscape',
    },
    {
      id: 'code-app-ideas',
      kind: 'blog',
      eyebrow: 'Blog post',
      title: 'Things you can do with the Code app',
      excerpt: 'Practical ways to use a coding mate beyond generating snippets.',
      publishedLabel: '2 days ago',
      readTime: '5 min read',
      author: 'Marco',
      mediaShape: 'landscape',
    },
    {
      id: 'web-search-for-ai',
      kind: 'blog',
      eyebrow: 'Blog post',
      title: 'Why web search isn’t enough for AI',
      excerpt: 'How sources, context, and careful retrieval make answers more useful.',
      publishedLabel: '3 days ago',
      readTime: '3 min read',
      author: 'Marco',
      mediaShape: 'landscape',
    },
    {
      id: 'teams-comparison',
      kind: 'blog',
      eyebrow: 'Blog post',
      title: 'How Teams in OpenMates compares to other tools',
      excerpt: 'A practical look at collaboration, privacy, and flexibility.',
      publishedLabel: 'September 12, 2026',
      readTime: '5 min read',
      author: 'OpenMates',
      mediaShape: 'landscape',
    },
    {
      id: 'organize-projects',
      kind: 'blog',
      eyebrow: 'Blog post',
      title: 'How to organize and build projects',
      excerpt: 'A simple structure for turning scattered work into a useful project.',
      publishedLabel: 'September 8, 2026',
      readTime: '3 min read',
      author: 'OpenMates',
      mediaShape: 'landscape',
    },
  ],
  socialItems: [
    {
      id: 'workflow-social',
      kind: 'social',
      eyebrow: 'OpenMates',
      title: 'What if you didn’t have to constantly search for new appointments?',
      excerpt: 'A short look at how recurring searches can become a calm, useful workflow.',
      publishedLabel: '10 minutes ago',
      author: 'OpenMates',
      socialLinks: [
        {
          platform: 'bluesky',
          label: 'Open this post on Bluesky',
          href: 'https://bsky.app/profile/did:plc:bgflwrmldvtkddskwp6tynt4/post/3mvl6lyi6oy2w',
        },
        {
          platform: 'instagram',
          label: 'Open this post on Instagram',
          href: 'https://www.instagram.com/reel/DdURL81mGUs/',
        },
        {
          platform: 'mastodon',
          label: 'Open this post on Mastodon',
          href: 'https://mastodon.social/@OpenMates/117276281024759413',
        },
      ],
      mediaShape: 'portrait',
    },
    {
      id: 'projects-social',
      kind: 'social',
      eyebrow: 'OpenMates',
      title: 'Bring conversations and source material into one project.',
      excerpt: 'A quick walkthrough of the new Projects workspace.',
      publishedLabel: 'Yesterday',
      author: 'OpenMates',
      socialLinks: [
        {
          platform: 'bluesky',
          label: 'Open this post on Bluesky',
          href: 'https://bsky.app/profile/openmates.bsky.social/post/3projects',
        },
        {
          platform: 'instagram',
          label: 'Open this post on Instagram',
          href: 'https://www.instagram.com/openmates_official/p/projects-social/',
        },
      ],
      mediaShape: 'portrait',
    },
    {
      id: 'privacy-social',
      kind: 'social',
      eyebrow: 'OpenMates',
      title: 'What privacy by design means in everyday AI work.',
      excerpt: 'The choices we make when handling personal context and files.',
      publishedLabel: 'September 16, 2026',
      author: 'OpenMates',
      socialLinks: [
        {
          platform: 'bluesky',
          label: 'Open this post on Bluesky',
          href: 'https://bsky.app/profile/openmates.bsky.social/post/3privacy',
        },
        {
          platform: 'mastodon',
          label: 'Open this post on Mastodon',
          href: 'https://mastodon.social/@OpenMates/456',
        },
      ],
      mediaShape: 'portrait',
    },
  ],
  coverageItems: [
    {
      id: 'zdf-privacy-coverage',
      kind: 'coverage',
      eyebrow: 'ZDF Magazin · Germany',
      title: 'A privacy-focused alternative for everyday AI tasks',
      excerpt: 'External article — opens at the publisher’s website.',
      publishedLabel: 'December 28, 2025',
      language: 'German',
      mediaShape: 'landscape',
    },
  ],
  releaseArticle: {
    byline: 'OpenMates newsroom · Berlin, Germany',
    publishedLabel: 'September 28, 2026',
    intro: 'Workflow Automation helps people turn recurring searches and everyday tasks into understandable, reusable workflows.',
    paragraphs: [
      'A workflow can watch for new apartments, find suitable events, or help a team keep a project moving. Each step remains visible, so people can understand what happens and change it when their needs evolve.',
      'The release is available in the web app and is designed to work across the OpenMates ecosystem. Developers can connect the same workflows through the CLI and SDK.',
      'This page is a visual fixture. Final release copy, media, claims, and download files will come from the approved marketing source.',
    ],
    promptTitle: 'Example workflow',
    promptBody: 'Every Friday, find accessible technology events in Berlin for the following week and prepare a short digest with registration links.',
  },
  blogArticle: {
    byline: 'Written by Marco · Creator of OpenMates',
    publishedLabel: 'September 18, 2026 · 10 min read',
    intro: 'Agentic coding becomes useful when its actions are visible, bounded, and easy to review.',
    paragraphs: [
      'Good guardrails start with a clear task boundary. The coding agent should know which files it owns, what evidence matters, and which changes require a human decision.',
      'Small feedback loops make the work easier to trust. Preview the component before integrating it, verify the smallest meaningful behavior, and only broaden checks when a concrete risk justifies it.',
      'A useful workflow also preserves context. Decisions, sources, and test results should remain connected to the work without turning the interface into an audit dashboard.',
    ],
    promptTitle: 'Example instruction',
    promptBody: 'Implement the approved component in its isolated workspace. Show a focused preview before connecting it to live data, and stop for visual confirmation.',
  },
};

const de: NewsroomSurfaceData = {
  ...en,
  newsLabel: 'Newsroom',
  blogLabel: 'Blog',
  openAppLabel: 'Web-App öffnen',
  tryItLabel: 'Ausprobieren',
  searchLabel: 'Suchen',
  latestNewsLabel: 'Neueste Meldungen',
  latestBlogLabel: 'Neueste Blogbeiträge',
  socialLabel: 'Social Media',
  coverageLabel: 'Pressestimmen',
  morePostsLabel: 'Weitere Beiträge',
  relatedLabel: 'Mehr von OpenMates',
  pressKitLabel: 'Pressemappe herunterladen',
  pressInquiryLabel: 'Presseanfragen',
  subscribeLabel: 'News abonnieren',
  followLabel: 'Folge uns',
  heroNews: {
    eyebrow: 'Release',
    title: 'Neu: Workflow-Automatisierung',
    meta: '28. September 2026',
    actionLabel: 'Release lesen',
  },
  heroBlog: {
    eyebrow: 'Blogbeitrag',
    kicker: 'Empfohlen',
    title: 'Nicht blind fliegen: Bessere Leitplanken für Coding-Agenten',
    meta: '10 Min. Lesezeit',
    actionLabel: 'Blogbeitrag lesen',
  },
  releaseArticle: {
    ...en.releaseArticle,
    byline: 'OpenMates Newsroom · Berlin',
    publishedLabel: '28. September 2026',
    intro: 'Workflow-Automatisierung macht wiederkehrende Suchen und alltägliche Aufgaben verständlich und wiederverwendbar.',
  },
  blogArticle: {
    ...en.blogArticle,
    byline: 'Von Marco · Gründer von OpenMates',
    publishedLabel: '18. September 2026 · 10 Min. Lesezeit',
    intro: 'Coding-Agenten werden nützlich, wenn ihre Aktionen sichtbar, begrenzt und leicht überprüfbar sind.',
  },
};

export const newsroomFixtures = { en, de } as const;
