name_translation_key: fitness.text
description_translation_key: fitness.description.text
icon_image: |
  fitness.svg
category: personal
last_updated: '2025-11-12'
skills:
  - id: search_locations_and_courses
    name_translation_key: fitness.search_locations_and_courses.text
    description_translation_key: fitness.search_locations_and_courses.description.text
    stage: planning
    class_path: |
      skills.search_locations_and_courses.SearchLocationsAndCoursesSkill
    providers:
      - Urban Sports Club
