name: |
  Fitness
description: |
  Stay fit, keep moving, stay healthy.
icon_image: |
  fitness.svg
category: personal
last_updated: '2025-11-12'
skills:
  - id: |
      search_locations_and_courses
    name: |
      Search locations and courses
    description: |
      Searches for fitness locations and courses based on your requirements.
    stage: planning
    class_path: |
      skills.search_locations_and_courses.SearchLocationsAndCoursesSkill
    providers:
      - Urban Sports Club
