"""
Dev-only Playwright test recording browser API.

Reads manifests generated by scripts/run_tests.py from the host-mounted
test-results directory and signs private S3 recording assets for the /tests UI.
The route is intentionally disabled in production because recordings can contain
test account screens, emails, and payment provider sandbox UI.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, HTTPException, Request

from backend.core.api.app.services.limiter import limiter
from backend.core.api.app.services.s3.config import get_bucket_name

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/v1/test-recordings",
    tags=["Test Recordings"],
)

TEST_RECORDINGS_PATHS = [
    Path("/app/test-results/recordings/latest"),
    Path("/home/superdev/projects/OpenMates/test-results/recordings/latest"),
]
PRESIGNED_URL_TTL_SECONDS = 6 * 60 * 60


def _ensure_dev_only() -> None:
    if os.getenv("SERVER_ENVIRONMENT", "development").lower() == "production":
        raise HTTPException(status_code=404, detail="Not found")


def _find_recordings_dir() -> Optional[Path]:
    for path in TEST_RECORDINGS_PATHS:
        if path.exists():
            return path
    return None


def _read_json_file(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Recording not found")
    except json.JSONDecodeError as exc:
        logger.error("Invalid test recording JSON at %s: %s", path, exc)
        raise HTTPException(status_code=500, detail="Invalid recording metadata")


def _get_s3_service(request: Request):
    if not hasattr(request.app.state, "s3_service"):
        raise HTTPException(status_code=503, detail="S3 service unavailable")
    return request.app.state.s3_service


def _sign_asset_key(request: Request, key: Optional[str]) -> Optional[str]:
    if not key:
        return None
    if key.startswith("/") or ".." in key or "://" in key:
        raise HTTPException(status_code=400, detail="Invalid recording asset key")
    s3_service = _get_s3_service(request)
    bucket_name = get_bucket_name("test_recordings", os.getenv("SERVER_ENVIRONMENT", "development"))
    return s3_service.generate_presigned_url(bucket_name, key, expiration=PRESIGNED_URL_TTL_SECONDS)


def _add_signed_asset_urls(request: Request, item: dict[str, Any]) -> dict[str, Any]:
    assets = item.get("assets") or {}
    signed_assets = dict(assets)
    for key_name in ("video_key", "thumbnail_key", "report_key"):
        signed_assets[key_name.replace("_key", "_url")] = _sign_asset_key(
            request, assets.get(key_name)
        )
    if assets.get("screenshot_keys"):
        signed_assets["screenshot_urls"] = [
            _sign_asset_key(request, key) for key in assets.get("screenshot_keys", [])
        ]
    item["assets"] = signed_assets

    for step in item.get("steps", []):
        if isinstance(step, dict) and step.get("screenshot_key"):
            step["screenshot_url"] = _sign_asset_key(request, step.get("screenshot_key"))
    return item


@router.get("", dependencies=[])
@limiter.limit("30/minute")
async def list_test_recordings(request: Request) -> dict[str, Any]:
    """List latest Playwright test recordings for the /tests page."""
    _ensure_dev_only()
    recordings_dir = _find_recordings_dir()
    if not recordings_dir:
        return {"run_id": None, "git_sha": None, "git_branch": None, "tests": []}

    index = _read_json_file(recordings_dir / "index.json")
    tests = []
    for item in index.get("tests", []):
        if isinstance(item, dict):
            tests.append(_add_signed_asset_urls(request, dict(item)))
    index["tests"] = tests
    return index


@router.get("/{slug}", dependencies=[])
@limiter.limit("60/minute")
async def get_test_recording(slug: str, request: Request) -> dict[str, Any]:
    """Return one latest Playwright test recording manifest."""
    _ensure_dev_only()
    if not slug or "/" in slug or ".." in slug:
        raise HTTPException(status_code=400, detail="Invalid recording slug")

    recordings_dir = _find_recordings_dir()
    if not recordings_dir:
        raise HTTPException(status_code=404, detail="No test recordings available")

    manifest = _read_json_file(recordings_dir / slug / "manifest.json")
    return _add_signed_asset_urls(request, manifest)
